import type { Checklist } from './types';

export const checklistTemplates: Checklist[] = [
  // Events
  {
    id: 'evt-wd-haldi',
    title: 'Wedding - Haldi Ceremony',
    category: 'Events',
    type: 'Wedding - Haldi',
    tasks: [
      { id: '1', text: 'Book venue & confirm details', completed: true, subtasks: [
        { id: '1-1', text: 'Finalize guest count', completed: true },
        { id: '1-2', text: 'Confirm date and time', completed: true },
        { id: '1-3', text: 'Check power backup and facilities', completed: true },
      ] },
      { id: '2', text: 'Arrange ceremony essentials', completed: true, subtasks: [
        { id: '2-1', text: 'Order turmeric and sandalwood paste', completed: true },
        { id: '2-2', text: 'Get floral assortments (marigolds)', completed: true },
        { id: '2-3', text: 'Arrange sacred grass and other ritual items', completed: true },
      ] },
      { id: '3', text: 'Hire vendors', completed: true, subtasks: [
        { id: '3-1', text: 'Book photographer and videographer', completed: true },
        { id: '3-2', text: 'Hire caterer and finalize menu', completed: true },
        { id: '3-3', text: 'Book priest/pandit', completed: true },
      ] },
      { id: '4', text: 'Plan decor and setup', completed: false },
      { id: '5', text: 'Organize entertainment', completed: false, subtasks: [
        { id: '5-1', text: 'Create music playlist', completed: false },
        { id: '5-2', text: 'Book live traditional musicians', completed: false },
        { id: '5-3', text: 'Test sound system', completed: false },
      ] },
      { id: '6', text: 'Manage guest list and invitations', completed: true },
      { id: '7', text: 'Coordinate outfits', completed: false },
      { id: '8', text: 'Arrange for guest favors or return gifts', completed: false },
    ],
  },
  {
    id: 'evt-wd-mehndi',
    title: 'Wedding - Mehndi Night',
    category: 'Events',
    type: 'Wedding - Mehndi',
    tasks: [
      { id: '1', text: 'Book professional mehndi artist(s)', completed: true },
      { id: '2', text: 'Arrange comfortable seating for guests', completed: true },
      { id: '3', text: 'Decorate venue with colorful drapes, lights, and flowers', completed: false },
      { id: '4', text: 'Entertainment planning', completed: false, subtasks: [
        { id: '4-1', text: 'Create a lively music playlist', completed: false },
        { id: '4-2', text: 'Hire a DJ or dhol players', completed: false },
        { id: '4-3', text: 'Plan and schedule dance performances', completed: false },
      ] },
      { id: '5', text: 'Finalize menu with caterer, including drinks and desserts', completed: false },
      { id: '6', text: 'Ensure ample supply of quality mehndi cones and essentials', completed: false },
      { id: '7', text: 'Book photographer/videographer to capture candid moments', completed: false },
      { id: '8', text: 'Prepare and pack gift bags/favors for guests', completed: false },
      { id: '9', text: 'Set up a photo booth with fun props', completed: false },
    ],
  },
   {
    id: 'evt-wd-sangeet',
    title: 'Wedding - Sangeet',
    category: 'Events',
    type: 'Wedding - Sangeet',
    tasks: [
        { id: '1', text: 'Book entertainment and host', completed: true, subtasks: [
          { id: '1-1', text: 'Finalize DJ or live band', completed: true },
          { id: '1-2', text: 'Book an emcee for the evening', completed: true },
        ] },
        { id: '2', text: 'Venue and stage setup', completed: true, subtasks: [
          { id: '2-1', text: 'Set up stage, backdrop, and lighting', completed: true },
          { id: '2-2', text: 'Ensure sound system is tested and working', completed: true },
          { id: '2-3', text: 'Check dance floor size and condition', completed: true },
        ] },
        { id: '3', text: 'Coordinate performances', completed: true, subtasks: [
          { id: '3-1', text: 'Create and share rehearsal schedule', completed: true },
          { id: '3-2', text: 'Appoint a performance coordinator', completed: true },
          { id: '3-3', text: 'Prepare final list of performances', completed: true },
        ] },
        { id: '4', text: 'Finalize dinner and cocktail menu with caterer', completed: false },
        { id: '5', text: 'Plan guest seating arrangements and table assignments', completed: false },
        { id: '6', text: 'Brief photographer/videographer on key moments to capture', completed: false },
        { id: '7', text: 'Arrange for a backup generator in case of power failure', completed: false },
        { id: '8', text: 'Prepare a thank-you speech', completed: false },
    ],
  },
  {
    id: 'evt-prod-launch',
    title: 'Product Launch Event',
    category: 'Events',
    type: 'Product Launch',
    tasks: [
      { id: '1', text: 'Secure venue and necessary permits', completed: true },
      { id: '2', text: 'Design and print branding materials', completed: true },
      { id: '3', text: 'Prepare product demonstration', completed: false, subtasks: [
        { id: '3-1', text: 'Finalize demo script', completed: false },
        { id: '3-2', text: 'Test all hardware and software', completed: false },
        { id: '3-3', text: 'Have a backup demo ready', completed: false },
      ] },
      { id: '4', text: 'Arrange catering, including snacks and beverages', completed: false },
      { id: '5', text: 'Manage guest list and track RSVPs online', completed: false },
      { id: '6', text: 'Media and PR', completed: false, subtasks: [
        { id: '6-1', text: 'Send out press releases', completed: false },
        { id: '6-2', text: 'Prepare press kits', completed: false },
        { id: '6-3', text: 'Schedule interviews with key personnel', completed: false },
      ] },
      { id: '7', text: 'Hire a professional photographer and videographer', completed: false },
      { id: '8', text: 'Conduct a thorough AV system and microphone check', completed: false },
      { id: '9', text: 'Prepare product samples for attendees', completed: false },
      { id: '10', text: 'Plan event agenda, including speaker timings and Q&A session', completed: false },
    ],
  },
  {
    id: 'evt-startup-launch',
    title: 'Startup Launch Party',
    category: 'Events',
    type: 'Startup Launch',
    tasks: [
      { id: '1', text: 'Define launch goals and budget', completed: true },
      { id: '2', text: 'Create a target guest list (investors, press, partners, users)', completed: true },
      { id: '3', text: 'Select and book a unique venue that reflects brand identity', completed: false },
      { id: '4', text: 'Design and send out digital invitations with RSVP tracking', completed: false },
      { id: '5', text: 'Plan a short, engaging presentation or product demo', completed: false },
      { id: '6', text: 'Arrange for catering with trendy food and drink options', completed: false },
      { id: '7', text: 'Set up networking zones or icebreaker activities', completed: false },
      { id: '8', text: 'Prepare branded swag/goodie bags for guests', completed: false },
      { id: '9', text: 'Hire a photographer/videographer to capture the event', completed: false },
      { id: '10', text: 'Set up a social media wall with a unique event hashtag', completed: false },
      { id: '11', text: 'Coordinate with speakers and test AV equipment', completed: false },
      { id: '12', text: 'Follow up with attendees with a thank-you note and press kit', completed: false },
    ],
  },
  // Hospitality
  {
    id: 'hosp-hk-daily',
    title: 'Hotel Daily Housekeeping',
    category: 'Hospitality',
    type: 'Hotel Daily Housekeeping',
    tasks: [
      { id: '1', text: 'Clean and sanitize guest room', completed: true, requiresPhoto: true, subtasks: [
        { id: '1-1', text: 'Make the bed with fresh linens', completed: true },
        { id: '1-2', text: 'Clean bathroom (toilet, shower, sink, mirror)', completed: true },
        { id: '1-3', text: 'Dust all surfaces', completed: true },
      ] },
      { id: '2', text: 'Restock amenities', completed: true, requiresPhoto: true, subtasks: [
        { id: '2-1', text: 'Replenish towels', completed: true },
        { id: '2-2', text: 'Restock toiletries (shampoo, soap, etc.)', completed: true },
        { id: '2-3', text: 'Refill tea, coffee, and water supplies', completed: true },
      ] },
      { id: '3', text: 'Vacuum carpets and mop hard floors', completed: true },
      { id: '4', text: 'Check and restock minibar, recording any consumption', completed: false },
      { id: '5', text: 'Inspect all room electronics (TV, AC, lights, chargers)', completed: false },
      { id: '6', text: 'Report any maintenance issues or damages immediately', completed: false },
      { id: '7', text: 'Empty all trash bins and replace liners', completed: false },
      { id: '8', text: 'Update room status in the housekeeping management system', completed: false },
      { id: '9', text: 'Check for and collect any guest laundry requests', completed: false },
      { id: '10', text: 'Perform a final room inspection against the checklist', completed: false },
    ],
  },
  {
    id: 'hosp-res-open',
    title: 'Restaurant Daily Opening',
    category: 'Hospitality',
    type: 'Restaurant Daily Opening',
    tasks: [
      { id: '1', text: 'Wipe and set tables & chairs per floor plan', completed: true },
      { id: '2', text: 'Deep clean and sanitize all kitchen surfaces and equipment', completed: true, requiresPhoto: true },
      { id: '3', text: 'Receive and stock raw materials, checking for quality', completed: false },
      { id: '4', text: 'Check temperatures of all refrigerators and freezers', completed: false },
      { id: '5', text: 'Polish and arrange all tableware, glassware, and cutlery', completed: false },
      { id: '6', text: 'Switch on all lights, air conditioning, and music systems', completed: false },
      { id: '7', text: 'Conduct daily staff briefing on specials and reservations', completed: false },
      { id: '8', text: 'Check and clean restrooms, restocking supplies', completed: false },
      { id: '9', a: '9', text: 'Ensure point-of-sale systems are online and functional', completed: false },
      { id: '10', text: 'Review reservation list and plan for large parties', completed: false },
    ],
  },
  {
    id: 'hosp-res-close',
    title: 'Restaurant Daily Closing',
    category: 'Hospitality',
    type: 'Restaurant Daily Closing',
    tasks: [
      { id: '1', text: 'Clean and sanitize all kitchen stations, grills, and surfaces', completed: true, requiresPhoto: true },
      { id: '2', text: 'Switch off all cooking equipment, ovens, and exhaust fans', completed: false },
      { id: '3', text: 'Dispose of all trash and food waste properly', completed: false },
      { id: '4', text: 'Securely lock all food and beverage storage areas', completed: false },
      { id: '5', text: 'Sweep and mop all kitchen and dining area floors', completed: false },
      { id: '6', text: 'Run end-of-day sales reports and reconcile cash drawer', completed: false },
      { id: '7', text: 'Ensure all staff have completed and signed their closing checklists', completed: false },
      { id: '8', text: 'Turn off dining room lights, music, and climate control', completed: false },
      { id: '9', text: 'Set security alarm and lock all entrance doors', completed: false },
      { id: '10', text: 'Properly store any leftover prepared food', completed: false },
    ],
  },
  // Training (Example)
  {
    id: 'train-onboard-hotel',
    title: 'New Hotel Staff Onboarding',
    category: 'Training',
    type: 'New Hotel Staff Onboarding',
    tasks: [
      { id: '1', text: 'Company orientation: mission, vision, and values', completed: true },
      { id: '2', text: 'Complete mandatory fire safety and emergency procedure drill', completed: true },
      { id: '3', text: 'Training module on guest interaction and service standards', completed: false },
      { id: '4', text: 'Hands-on demonstration of room cleaning SOPs', completed: false },
      { id: '5', text: 'Shadow a senior staff member in the assigned role for one full shift', completed: false },
      { id: '6', text: 'Issue uniform and review grooming and presentation standards', completed: false },
      { id: '7', text: 'Complete and review performance on the 30-day evaluation checklist', completed: false },
      { id: '8', text: 'Introduction to hotel software (PMS, POS)', completed: false },
      { id: '9', text: 'Review of HR policies and employee handbook', completed: false },
      { id: '10', text: 'Set up employee ID, email, and system access', completed: false },
    ],
  },
    // Sustainability (Example)
  {
    id: 'sustain-energy-hotel',
    title: 'Hotel Energy Efficiency',
    category: 'Sustainability',
    type: 'Hotel Energy Efficiency',
    tasks: [
      { id: '1', text: 'Audit and ensure lights are switched off in all unused areas', completed: true, requiresPhoto: true },
      { id: '2', text: 'Verify AC thermostats are set to the optimal temperature (e.g., 24°C)', completed: false },
      { id: '3', text: 'Ensure laundry is run only with full, optimized loads', completed: false },
      { id: '4', text: 'Monthly check for replacement of any non-LED bulbs', completed: false },
      { id: '5', text: 'Record and review monthly energy usage from utility bills', completed: false },
      { id: '6', text: 'Inspect window and door seals for any air leaks', completed: false },
      { id: '7', text: 'Promote "green" program to guests for reusing towels and linens', completed: false },
      { id: '8', text: 'Schedule regular maintenance for HVAC systems', completed: false },
    ],
  },
];
