import type { Checklist } from './types';

export const checklistTemplates: Checklist[] = [
  // Events
  {
    id: 'evt-wd-haldi',
    title: 'Wedding - Haldi Ceremony',
    category: 'Events',
    type: 'Wedding - Haldi',
    tasks: [
      { id: '1', text: 'Book venue & confirm details', completed: true, subtasks: [
        { id: '1-1', text: 'Finalize guest count', completed: true },
        { id: '1-2', text: 'Confirm date and time', completed: true },
        { id: '1-3', text: 'Check power backup and facilities', completed: true },
      ] },
      { id: '2', text: 'Arrange ceremony essentials', completed: true, subtasks: [
        { id: '2-1', text: 'Order turmeric and sandalwood paste', completed: true },
        { id: '2-2', text: 'Get floral assortments (marigolds)', completed: true },
        { id: '2-3', text: 'Arrange sacred grass and other ritual items', completed: true },
      ] },
      { id: '3', text: 'Hire vendors', completed: true, subtasks: [
        { id: '3-1', text: 'Book photographer and videographer', completed: true },
        { id: '3-2', text: 'Hire caterer and finalize menu', completed: true },
        { id: '3-3', text: 'Book priest/pandit', completed: true },
      ] },
      { id: '4', text: 'Plan decor and setup', completed: false, subtasks: [
        { id: '4-1', text: 'Choose a color theme (traditionally yellow)', completed: false },
        { id: '4-2', text: 'Set up backdrop with marigold strings', completed: false },
        { id: '4-3', text: 'Arrange low seating for the ceremony', completed: false },
        { id: '4-4', text: 'Plan for floral rangoli or entrance decor', completed: false },
      ] },
      { id: '5', text: 'Organize entertainment', completed: false, subtasks: [
        { id: '5-1', text: 'Create music playlist with traditional Haldi songs', completed: false },
        { id: '5-2', text: 'Book live traditional musicians (e.g., Dholki players)', completed: false },
        { id: '5-3', text: 'Test sound system and speakers', completed: false },
      ] },
      { id: '6', text: 'Manage guest list and invitations', completed: true },
      { id: '7', text: 'Coordinate outfits', completed: false, subtasks: [
        { id: '7-1', text: 'Finalize Haldi outfit for the bride', completed: false },
        { id: '7-2', text: 'Finalize Haldi outfit for the groom', completed: false },
        { id: '7-3', text: 'Decide on a dress code for immediate family', completed: false },
      ] },
      { id: '8', text: 'Arrange for guest favors or return gifts', completed: false, subtasks: [
        { id: '8-1', text: 'Choose favors (e.g., bangles, bindis, sweets)', completed: false },
        { id: '8-2', text: 'Order and package the favors', completed: false },
      ] },
    ],
  },
  {
    id: 'evt-wd-mehndi',
    title: 'Wedding - Mehndi Night',
    category: 'Events',
    type: 'Wedding - Mehndi',
    tasks: [
      { id: '1', text: 'Book professional mehndi artist(s)', completed: true, subtasks: [
        { id: '1-1', text: 'Finalize artist for the bride', completed: true },
        { id: '1-2', text: 'Arrange artists for guests', completed: false },
        { id: '1-3', text: 'Confirm designs and pricing', completed: true },
      ] },
      { id: '2', text: 'Arrange comfortable seating for guests', completed: true, subtasks: [
        { id: '2-1', text: 'Arrange low seating with bolsters for mehndi application', completed: true },
        { id: '2-2', text: 'Set up general seating for other guests', completed: false },
      ] },
      { id: '3', text: 'Decorate venue with colorful elements', completed: false, subtasks: [
        { id: '3-1', text: 'Select color theme (e.g., vibrant pinks, oranges, greens)', completed: false },
        { id: '3-2', text: 'Hang colorful drapes and fabrics', completed: false },
        { id: '3-3', text: 'Install string lights or lanterns for ambiance', completed: false },
        { id: '3-4', text: 'Arrange fresh flower decorations', completed: false },
      ] },
      { id: '4', text: 'Entertainment planning', completed: false, subtasks: [
        { id: '4-1', text: 'Create a lively music playlist (Bollywood & folk)', completed: false },
        { id: '4-2', text: 'Hire a DJ or dhol players', completed: false },
        { id: '4-3', text: 'Plan and schedule family dance performances', completed: false },
      ] },
      { id: '5', text: 'Finalize food and drink menu', completed: false, subtasks: [
        { id: '5-1', text: 'Plan a menu of easy-to-eat finger foods', completed: false },
        { id: '5-2', text: 'Set up a chaat station or food truck', completed: false },
        { id: '5-3', text: 'Arrange a beverage and cocktail bar', completed: false },
      ] },
      { id: '6', text: 'Ensure ample mehndi supplies', completed: false, subtasks: [
        { id: '6-1', text: 'Purchase high-quality, natural mehndi cones', completed: false },
        { id: '6-2', text: 'Prepare lemon-sugar solution and clove oil for aftercare', completed: false },
      ] },
      { id: '7', text: 'Book photographer/videographer to capture candid moments', completed: false },
      { id: '8', text: 'Prepare and pack guest favors', completed: false, subtasks: [
        { id: '8-1', text: 'Select favors like bangles, bindis, or potli bags', completed: false },
        { id: '8-2', text: 'Package favors beautifully', completed: false },
      ] },
      { id: '9', text: 'Set up a photo booth', completed: false, subtasks: [
        { id: '9-1', text: 'Design and set up a themed backdrop', completed: false },
        { id: '9-2', text: 'Gather fun, relevant props (e.g., signs, sunglasses)', completed: false },
      ] },
    ],
  },
   {
    id: 'evt-wd-sangeet',
    title: 'Wedding - Sangeet',
    category: 'Events',
    type: 'Wedding - Sangeet',
    tasks: [
        { id: '1', text: 'Book entertainment and host', completed: true, subtasks: [
          { id: '1-1', text: 'Finalize DJ or live band', completed: true },
          { id: '1-2', text: 'Book an emcee for the evening', completed: true },
          { id: '1-3', text: 'Confirm playlist and do-not-play list with DJ', completed: false },
        ] },
        { id: '2', text: 'Venue and stage setup', completed: true, subtasks: [
          { id: '2-1', text: 'Set up stage, backdrop, and professional lighting', completed: true },
          { id: '2-2', text: 'Ensure sound system is tested and working', completed: true },
          { id: '2-3', text: 'Check dance floor size and condition', completed: true },
          { id: '2-4', text: 'Set up LED screens for visuals if planned', completed: false },
        ] },
        { id: '3', text: 'Coordinate performances', completed: true, subtasks: [
          { id: '3-1', text: 'Create and share rehearsal schedule', completed: true },
          { id: '3-2', text: 'Appoint a performance coordinator', completed: true },
          { id: '3-3', text: 'Finalize song selection and track order for all performances', completed: true },
          { id: '3-4', text: 'Do a final run-through on the stage', completed: false },
        ] },
        { id: '4', text: 'Finalize dinner and cocktail menu', completed: false, subtasks: [
            { id: '4-1', text: 'Finalize menu with caterer', completed: false },
            { id: '4-2', text: 'Arrange for a cocktail bar and bartender', completed: false },
            { id: '4-3', text: 'Plan for appetizer circulation during performances', completed: false },
        ] },
        { id: '5', text: 'Plan guest seating arrangements and table assignments', completed: false },
        { id: '6', text: 'Brief photographer/videographer on key moments to capture', completed: false },
        { id: '7', text: 'Arrange for a backup generator in case of power failure', completed: false },
        { id: '8', text: 'Prepare a thank-you speech', completed: false },
    ],
  },
  {
    id: 'evt-prod-launch',
    title: 'Product Launch Event',
    category: 'Events',
    type: 'Product Launch',
    tasks: [
      { id: '1', text: 'Secure venue and necessary permits', completed: true },
      { id: '2', text: 'Design and print branding materials', completed: true, subtasks: [
        { id: '2-1', text: 'Design banners and standees with product colors', completed: false },
        { id: '2-2', text: 'Print brochures or info cards', completed: false },
        { id: '2-3', text: 'Order branded swag (pens, notebooks, etc.)', completed: false },
      ] },
      { id: '3', text: 'Prepare product demonstration', completed: false, subtasks: [
        { id: '3-1', text: 'Finalize demo script and key talking points', completed: false },
        { id: '3-2', text: 'Test all hardware and software components thoroughly', completed: false },
        { id: '3-3', text: 'Have a pre-recorded video of the demo as backup', completed: false },
      ] },
      { id: '4', text: 'Arrange catering, including snacks and beverages', completed: false },
      { id: '5', text: 'Manage guest list and track RSVPs online', completed: false },
      { id: '6', text: 'Media and PR', completed: false, subtasks: [
        { id: '6-1', text: 'Draft and schedule press release distribution', completed: false },
        { id: '6-2', text: 'Prepare digital press kits with high-res images', completed: false },
        { id: '6-3', text: 'Schedule pre-event interviews with key spokespeople', completed: false },
        { id: '6-4', text: 'Create a list of target media and influencers', completed: false },
      ] },
      { id: '7', text: 'Hire a professional photographer and videographer', completed: false },
      { id: '8', text: 'Conduct a thorough AV system and microphone check', completed: false },
      { id: '9', text: 'Prepare product samples or trial codes for attendees', completed: false },
      { id: '10', text: 'Plan event agenda, including speaker timings and Q&A session', completed: false },
    ],
  },
  {
    id: 'evt-startup-launch',
    title: 'Startup Launch Party',
    category: 'Events',
    type: 'Startup Launch',
    tasks: [
      { id: '1', text: 'Define launch goals and budget', completed: true },
      { id: '2', text: 'Create a target guest list (investors, press, partners, users)', completed: true },
      { id: '3', text: 'Select and book a unique venue that reflects brand identity', completed: false },
      { id: '4', text: 'Design and send out digital invitations with RSVP tracking', completed: false },
      { id: '5', text: 'Plan a short, engaging presentation or product demo', completed: false },
      { id: '6', text: 'Arrange for catering with trendy food and drink options', completed: false, subtasks: [
        { id: '6-1', text: 'Book a food truck or a popular local caterer', completed: false },
        { id: '6-2', text: 'Create a signature cocktail that matches the brand color', completed: false },
      ] },
      { id: '7', text: 'Set up networking zones or icebreaker activities', completed: false },
      { id: '8', text: 'Prepare branded swag/goodie bags for guests', completed: false },
      { id: '9', text: 'Hire a photographer/videographer to capture the event', completed: false },
      { id: '10', text: 'Set up a social media wall with a unique event hashtag', completed: false },
      { id: '11', text: 'Coordinate with speakers and test AV equipment', completed: false },
      { id: '12', text: 'Follow up with attendees with a thank-you note and press kit', completed: false },
    ],
  },
  // Hospitality
  {
    id: 'hosp-hk-daily',
    title: 'Hotel Daily Housekeeping',
    category: 'Hospitality',
    type: 'Hotel Daily Housekeeping',
    tasks: [
      { id: '1', text: 'Clean and sanitize guest room', completed: true, requiresPhoto: true, subtasks: [
        { id: '1-1', text: 'Make the bed with fresh linens', completed: true },
        { id: '1-2', text: 'Clean bathroom (toilet, shower, sink, mirror)', completed: true },
        { id: '1-3', text: 'Dust all surfaces (tables, lamps, etc.)', completed: true },
        { id: '1-4', text: 'Wipe down high-touch points (switches, handles)', completed: false },
      ] },
      { id: '2', text: 'Restock amenities', completed: true, requiresPhoto: true, subtasks: [
        { id: '2-1', text: 'Replenish towels (bath, hand, face)', completed: true },
        { id: '2-2', text: 'Restock toiletries (shampoo, soap, conditioner)', completed: true },
        { id: '2-3', text: 'Refill tea, coffee, sugar, and water supplies', completed: true },
        { id: '2-4', text: 'Check and restock stationery', completed: false },
      ] },
      { id: '3', text: 'Vacuum carpets and mop hard floors', completed: true },
      { id: '4', text: 'Check and restock minibar, recording any consumption', completed: false },
      { id: '5', text: 'Inspect all room electronics (TV, AC, lights, chargers)', completed: false },
      { id: '6', text: 'Report any maintenance issues or damages immediately', completed: false },
      { id: '7', text: 'Empty all trash bins and replace liners', completed: false },
      { id: '8', text: 'Update room status in the housekeeping management system', completed: false },
      { id: '9', text: 'Check for and collect any guest laundry requests', completed: false },
      { id: '10', text: 'Perform a final room inspection against the checklist', completed: false },
    ],
  },
  {
    id: 'hosp-res-open',
    title: 'Restaurant Daily Opening',
    category: 'Hospitality',
    type: 'Restaurant Daily Opening',
    tasks: [
      { id: '1', text: 'Wipe and set tables & chairs per floor plan', completed: true },
      { id: '2', text: 'Deep clean and sanitize all kitchen surfaces and equipment', completed: true, requiresPhoto: true },
      { id: '3', text: 'Receive and stock raw materials, checking for quality', completed: false },
      { id: '4', text: 'Check temperatures of all refrigerators and freezers', completed: false },
      { id: '5', text: 'Polish and arrange all tableware, glassware, and cutlery', completed: false, subtasks: [
        { id: '5-1', text: 'Check for spots on glassware', completed: false },
        { id: '5-2', text: 'Ensure cutlery is polished and fingerprint-free', completed: false },
        { id: '5-3', text: 'Fold napkins according to restaurant standard', completed: false },
      ] },
      { id: '6', text: 'Switch on all lights, air conditioning, and music systems', completed: false },
      { id: '7', text: 'Conduct daily staff briefing', completed: false, subtasks: [
        { id: '7-1', text: 'Discuss daily specials', completed: false },
        { id: '7-2', text: 'Review reservation list', completed: false },
        { id: '7-3', text: 'Assign staff sections', completed: false },
      ] },
      { id: '8', text: 'Check and clean restrooms, restocking supplies', completed: false },
      { id: '9', a: '9', text: 'Ensure point-of-sale systems are online and functional', completed: false },
      { id: '10', text: 'Review reservation list and plan for large parties', completed: false },
    ],
  },
  {
    id: 'hosp-res-close',
    title: 'Restaurant Daily Closing',
    category: 'Hospitality',
    type: 'Restaurant Daily Closing',
    tasks: [
      { id: '1', text: 'Clean and sanitize all kitchen stations, grills, and surfaces', completed: true, requiresPhoto: true },
      { id: '2', text: 'Switch off all cooking equipment, ovens, and exhaust fans', completed: false },
      { id: '3', text: 'Dispose of all trash and food waste properly', completed: false },
      { id: '4', text: 'Securely lock all food and beverage storage areas', completed: false },
      { id: '5', text: 'Sweep and mop all kitchen and dining area floors', completed: false },
      { id: '6', text: 'Run end-of-day sales reports and reconcile cash drawer', completed: false, subtasks: [
        { id: '6-1', text: 'Print Z-report from POS', completed: false },
        { id: '6-2', text: 'Count cash and match with report', completed: false },
        { id: '6-3', text: 'Secure cash in the safe', completed: false },
      ] },
      { id: '7', text: 'Ensure all staff have completed and signed their closing checklists', completed: false },
      { id: '8', text: 'Turn off dining room lights, music, and climate control', completed: false },
      { id: '9', text: 'Set security alarm and lock all entrance doors', completed: false },
      { id: '10', text: 'Properly store any leftover prepared food with date labels', completed: false },
    ],
  },
  // Training (Example)
  {
    id: 'train-onboard-hotel',
    title: 'New Hotel Staff Onboarding',
    category: 'Training',
    type: 'New Hotel Staff Onboarding',
    tasks: [
      { id: '1', text: 'Company orientation', completed: true, subtasks: [
        { id: '1-1', text: 'Present mission, vision, and values', completed: true },
        { id: '1-2', text: 'Tour of the property', completed: true },
        { id: '1-3', text: 'Introduction to department heads', completed: true },
      ] },
      { id: '2', text: 'Complete mandatory compliance training', completed: true, subtasks: [
        { id: '2-1', text: 'Fire safety and emergency procedure drill', completed: true },
        { id: '2-2', text: 'Workplace health and safety training', completed: false },
      ] },
      { id: '3', text: 'Training module on guest interaction and service standards', completed: false },
      { id: '4', text: 'Hands-on demonstration of room cleaning SOPs', completed: false },
      { id: '5', text: 'Shadow a senior staff member in the assigned role for one full shift', completed: false },
      { id: '6', text: 'Issue uniform and review grooming and presentation standards', completed: false },
      { id: '7', text: 'Complete and review performance on the 30-day evaluation checklist', completed: false },
      { id: '8', text: 'Introduction to hotel software (PMS, POS)', completed: false },
      { id: '9', text: 'Review of HR policies and employee handbook', completed: false },
      { id: '10', text: 'Set up employee ID, email, and system access', completed: false },
    ],
  },
    // Sustainability (Example)
  {
    id: 'sustain-energy-hotel',
    title: 'Hotel Energy Efficiency',
    category: 'Sustainability',
    type: 'Hotel Energy Efficiency',
    tasks: [
      { id: '1', text: 'Audit and ensure lights are switched off in all unused areas', completed: true, requiresPhoto: true },
      { id: '2', text: 'Verify AC thermostats are set to the optimal temperature (e.g., 24°C)', completed: false },
      { id: '3', text: 'Ensure laundry is run only with full, optimized loads', completed: false },
      { id: '4', text: 'Monthly check for replacement of any non-LED bulbs', completed: false },
      { id: '5', text: 'Record and review monthly energy usage from utility bills', completed: false },
      { id: '6', 'text': 'Inspect building envelope for inefficiencies', completed: false, subtasks: [
        { id: '6-1', text: 'Check window and door seals for any air leaks', completed: false },
        { id: '6-2', text: 'Inspect insulation in roof and walls where accessible', completed: false },
      ] },
      { id: '7', text: 'Promote "green" program to guests for reusing towels and linens', completed: false },
      { id: '8', text: 'Schedule regular maintenance for HVAC systems', completed: false },
    ],
  },
];
