
import type { PremiumPack } from "@/lib/premium-packs";

export const facility_management_blueprint: PremiumPack = {
    id: 'facility_management_blueprint',
    title: "Facility Operating System",
    priceINR: 5999,
    priceUSD: 79,
    competitorPriceUSD: 599,
    updatedAt: "2025-02-24",
    paymentId: 'pl_RaWEBHhFLQENxC',
    lemonSqueezyUrl: 'https://moremeets.lemonsqueezy.com/buy/d6d4dd85-3fb9-4c26-8ec3-cb021ddebfdc',
    category: "Corporate & Tech",
    description: "The definitive Sovereign v9.1 technical engine for Hard and Soft FM. Hardening 160 technical control points from MEP to Perimeter Security.",
    heroHeadline: "Stop Catastrophic Facility Failures and Vendor Neglect",
    heroSubheadline: "Track 160+ control points across Hard FM, Soft FM, Groundskeeping, and Compliance—even when you’re not on property.",
    pricingUrgency: "A single major utility failure or one safety breach costs 100x more than this system.",
    consultingAnchor: 10000,
    icon: "building-2",
    badgeText: "V9.1 SOVEREIGN",
    badgeVariant: "accent",
    whoIsItFor: ["COOs", "Heads of Real Estate", "Facility Directors", "Admin VPs", "Property Managers"],
    sampleItems: [
        { text: "<strong>2-Minute Command Pulse</strong>: Technicians and supervisors update MEP and safety status in seconds. Zero-friction reporting.", icon: "timer" },
        { text: "<strong>Hard FM (MEP) Engine</strong>: Zero-fail protocols for HVAC chillers, backup generators, and elevator auto-rescue systems.", icon: "wrench" },
        { text: "<strong>Utility Economics</strong>: Daily KWH and water consumption tracking against baselines to stop unmonitored cost blowouts.", icon: "zap" },
        { text: "<strong>Vendor SLA Command</strong>: Verify 100% of third-party service delivery vs. contract obligations to stop paying for neglect.", icon: "file-check" },
        { text: "<strong>Institutional Memory</strong>: Built-in instructions ensure that even when your best engineer leaves, the standard stays.", icon: "history" },
        { text: "<strong>High-Risk Verification</strong>: Highlighted 'Yellow Targets' show managers exactly what needs sign-off—from LOTO to fire exits.", icon: "target" },
        { text: "<strong>Sovereign Infrastructure</strong>: No recurring SaaS fees. You own your facility data and the control system forever.", icon: "lock" }
    ],
    checklists: [
        {
            title: "Portfolio Governance",
            department: "Executive",
            frequency: "Weekly",
            role: "COO / Owner",
            summary: "Asset health and high-level liability oversight.",
            icon: "crown",
            tasks: [
                { id: "FM-EXE-01", description: "Review major incident status across property group.", priority: "High", riskLevel: "High", consequence: "Escalated liability and asset damage.", proof: "Incident Audit", trainerNotes: "Check 'Root Cause' for all P1 failures." },
                { id: "FM-EXE-02", description: "Verify insurance validity: Public Liability & Machinery Breakdown.", priority: "High", riskLevel: "High", consequence: "Financial ruin during major event.", proof: "Policy File", trainerNotes: "Renew 60 days before expiry." },
                { id: "FM-EXE-03", description: "Audit CAPEX project milestones vs budget.", priority: "Medium", riskLevel: "Medium", consequence: "Cost overruns and delayed upgrades.", proof: "Project Log", trainerNotes: "Check 50% completion photos." },
                { id: "FM-EXE-04", description: "Review 'Empire Mood' and Group shift completion.", priority: "High", riskLevel: "Low", consequence: "Operational drift.", proof: "Console Review", trainerNotes: "Identify bottom 2 properties." },
                { id: "FM-EXE-05", description: "Audit senior management floor presence hours.", priority: "Medium", riskLevel: "Low", consequence: "Management disconnect.", proof: "Roster Log", trainerNotes: "Focus on peak traffic slots." },
                { id: "FM-EXE-06", description: "Verify statutory license status (Fire, Lift, Polluton).", priority: "High", riskLevel: "High", consequence: "Premises sealing.", proof: "License File", trainerNotes: "Display certs at main entry." },
                { id: "FM-EXE-07", description: "Review 'Utility Intensity' trend (KWH per SqFt).", priority: "Low", riskLevel: "Low", consequence: "Energy inefficiency.", proof: "Finance Chart", trainerNotes: "Compare vs previous month." },
                { id: "FM-EXE-08", description: "Audit vendor payment approvals vs SLA penalties.", priority: "Medium", riskLevel: "Low", consequence: "Overpaying for poor service.", proof: "Ledger Note", trainerNotes: "Apply deductions for P1 misses." },
                { id: "FM-EXE-09", description: "Verify Fixed Asset tagging for new MEP equipment.", priority: "Low", riskLevel: "Low", consequence: "Lost institutional assets.", proof: "Asset Log", trainerNotes: "Tag every item > $500." },
                { id: "FM-EXE-10", description: "Check status of unresolved 'Red' safety incidents.", priority: "High", riskLevel: "High", consequence: "Legal liability.", proof: "Incident Log", trainerNotes: "Resolve all < 24h." },
                { id: "FM-EXE-11", description: "Review staff churn in technical departments.", priority: "Low", riskLevel: "Low", consequence: "Loss of institutional knowledge.", proof: "HR Dashboard", trainerNotes: "Analyze exit interview notes." },
                { id: "FM-EXE-12", description: "Verify IT disaster backup cloud sync status.", priority: "High", riskLevel: "High", consequence: "Total loss of BMS data.", proof: "System Log", trainerNotes: "Manual backup test Mondays." },
                { id: "FM-EXE-13", description: "Audit Tenant satisfaction survey scores.", priority: "Medium", riskLevel: "Low", consequence: "Tenant attrition.", proof: "CSAT Report", trainerNotes: "Address bottom 10% complaints." },
                { id: "FM-EXE-14", description: "Verify LOTO policy signature compliance.", priority: "High", riskLevel: "High", consequence: "Fatal industrial accidents.", proof: "Compliance File", trainerNotes: "Audit 10% of new hires." },
                { id: "FM-EXE-15", description: "Check status of Landscaping/Facade AMCs.", priority: "Low", riskLevel: "Low", consequence: "Damaged curb appeal.", proof: "Contract File", trainerNotes: "Check monthly report photos." },
                { id: "FM-EXE-16", description: "Review Board Report PDF archive.", priority: "Low", riskLevel: "Low", consequence: "Loss of history.", proof: "Folder Audit", trainerNotes: "Save snapshot on 1st of month." },
                { id: "FM-EXE-17", description: "Audit petty cash surprise count.", priority: "Medium", riskLevel: "High", consequence: "Internal fraud.", proof: "Audit Note", trainerNotes: "Reconcile vs vouchers." },
                { id: "FM-EXE-18", description: "Verify 100% response to Social Media grievances.", priority: "High", riskLevel: "Low", consequence: "PR damage.", proof: "ORM Dashboard", trainerNotes: "Target < 4h response." },
                { id: "FM-EXE-19", description: "Check availability of spare MEP parts inventory.", priority: "Medium", riskLevel: "Medium", consequence: "Extended downtime.", proof: "Stock Sheet", trainerNotes: "Check critical spares monthly." },
                { id: "FM-EXE-20", description: "Final Weekly Governance sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of oversight.", proof: "Signed Summary", trainerNotes: "Submit to Owners." }
            ]
        },
        {
            title: "Soft FM Command",
            department: "Operations",
            frequency: "Daily",
            role: "General Manager",
            summary: "Hourly hygiene and aesthetic command.",
            icon: "sparkles",
            tasks: [
                { id: "FM-OPS-01", description: "Audit restroom hygiene logs: verify 1-hour frequency.", priority: "High", riskLevel: "Low", consequence: "Immediate occupant dissatisfaction.", proof: "Hourly Sheet", trainerNotes: "Check soap and sanitizers." },
                { id: "FM-OPS-02", description: "Visual Ambiance Check: Music, Temp, Scent in Lobby.", priority: "Medium", riskLevel: "Low", consequence: "Poor first impression.", proof: "Daily Log", trainerNotes: "Target temp: 23°C." },
                { id: "FM-OPS-03", description: "Verify floor buffing and stone-care status.", priority: "Low", riskLevel: "Low", consequence: "Dull facade/image.", proof: "Visual Check", trainerNotes: "Check porch at 8 AM." },
                { id: "FM-OPS-04", description: "Brief HK team on daily VIP arrivals or events.", priority: "High", riskLevel: "Low", consequence: "Service failure.", proof: "Briefing Log", trainerNotes: "Mention high-traffic zones." },
                { id: "FM-OPS-05", description: "Inspect exterior signage illumination.", priority: "Low", riskLevel: "Low", consequence: "Low visibility at night.", proof: "Photo", trainerNotes: "Check at sunset daily." },
                { id: "FM-OPS-06", description: "Audit garbage disposal frequency at main bay.", priority: "Medium", riskLevel: "Medium", consequence: "Pests and odors.", proof: "Log Review", trainerNotes: "Bins must be closed." },
                { id: "FM-OPS-07", description: "Check status of 'Open' tenant complaints.", priority: "High", riskLevel: "High", consequence: "Escalated disputes.", proof: "App/Log Status", trainerNotes: "Target resolve < 4h." },
                { id: "FM-OPS-08", description: "Verify glass cleaning on high-touch surfaces.", priority: "Low", riskLevel: "Low", consequence: "Smudge marks/Image drop.", proof: "Visual Audit", trainerNotes: "Check lobby doors." },
                { id: "FM-OPS-09", description: "Audit 'Wet Floor' signage availability.", priority: "High", riskLevel: "High", consequence: "Slip and fall lawsuits.", proof: "Visual Check", trainerNotes: "Mandatory during mopping." },
                { id: "FM-OPS-10", description: "Check availability of spare cleaning chemicals.", priority: "Medium", riskLevel: "Low", consequence: "Operational halt.", proof: "Stock Note", trainerNotes: "Min 1 week buffer." },
                { id: "FM-OPS-11", description: "Verify pest control bait station placement.", priority: "Medium", riskLevel: "Low", consequence: "Infestation.", proof: "Pest Log", trainerNotes: "Target zero sightings." },
                { id: "FM-OPS-12", description: "Inspect indoor plants for wilting or debris.", priority: "Low", riskLevel: "Low", consequence: "Poor ambiance.", proof: "Visual Audit", trainerNotes: "Water at 7 AM daily." },
                { id: "FM-OPS-13", description: "Check Lobby Wi-Fi portal login speed.", priority: "Medium", riskLevel: "Low", consequence: "Visitor complaints.", proof: "Phone Test", trainerNotes: "Login must be < 10s." },
                { id: "FM-OPS-14", description: "Audit staff grooming and ID visibility.", priority: "Low", riskLevel: "Low", consequence: "Professional image drop.", proof: "Daily Audit", trainerNotes: "Check badges/nails." },
                { id: "FM-OPS-15", description: "Verify porch floodlight status for night safety.", priority: "High", riskLevel: "Medium", consequence: "Security risk.", proof: "Visual Check", trainerNotes: "Replace fused bulbs < 24h." },
                { id: "FM-OPS-16", description: "Check availability of visitor umbrella stock.", priority: "Low", riskLevel: "Low", consequence: "Visitor discomfort.", proof: "Stock Check", trainerNotes: "Check during monsoon." },
                { id: "FM-OPS-17", description: "Audit staircase dust levels.", priority: "Medium", riskLevel: "Low", consequence: "Hidden hygiene decay.", proof: "Walkthrough", trainerNotes: "Check fire-exits weekly." },
                { id: "FM-OPS-18", description: "Verify 'Quiet Zone' policy in library/office.", priority: "Low", riskLevel: "Low", consequence: "Occupant frustration.", proof: "Decibel Check", trainerNotes: "Target < 55dB." },
                { id: "FM-OPS-19", description: "Inspect back-alley waste bins for fire risk.", priority: "High", riskLevel: "High", consequence: "Arson risk.", proof: "Walkthrough", trainerNotes: "Clear cardboard daily." },
                { id: "FM-OPS-20", description: "Final Daily Operations sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of duty control.", proof: "Signed Log", trainerNotes: "Brief GM on overnight security." }
            ]
        },
        {
            title: "Utility Economics",
            department: "Finance",
            frequency: "Daily",
            role: "Finance & Cashier",
            summary: "Energy and utility cost governance.",
            icon: "zap",
            tasks: [
                { id: "FM-FIN-01", description: "Log main KWH meter and compare to baseline.", priority: "Medium", riskLevel: "Low", consequence: "Unmonitored energy spikes.", proof: "Meter Log", trainerNotes: "Check at midnight daily." },
                { id: "FM-FIN-02", description: "Reconcile utility bank settlements vs meter.", priority: "High", riskLevel: "Medium", consequence: "Overcharging errors.", proof: "Match Note", trainerNotes: "Check monthly bill math." },
                { id: "FM-FIN-03", description: "Audit Petty Cash for technical emergencies.", priority: "High", riskLevel: "High", consequence: "Internal theft.", proof: "Audit Log", trainerNotes: "Signature for all vouchers." },
                { id: "FM-FIN-04", description: "Verify 100% AMC payment status.", priority: "High", riskLevel: "High", consequence: "Service contract lapse.", proof: "Payment File", trainerNotes: "Renew 30 days early." },
                { id: "FM-FIN-05", description: "Reconcile water-tank delivery vs invoices.", priority: "Medium", riskLevel: "Medium", consequence: "Paying for missing water.", proof: "Log Match", trainerNotes: "Verify tanker capacity." },
                { id: "FM-FIN-06", description: "Check stationery stock (Vouchers/Invoices).", priority: "Low", riskLevel: "Low", consequence: "Admin halt.", proof: "Supply Note", trainerNotes: "Min 1 month buffer." },
                { id: "FM-FIN-07", description: "Audit 'Discount' approvals for occupants.", priority: "Medium", riskLevel: "Medium", consequence: "Margin erosion.", proof: "POS Report", trainerNotes: "Reason code mandatory." },
                { id: "FM-FIN-08", description: "Verify vendor TDS deductions.", priority: "High", riskLevel: "Medium", consequence: "Tax non-compliance.", proof: "TDS Register", trainerNotes: "Check PAN status monthly." },
                { id: "FM-FIN-09", description: "Match 'Cash-to-Bank' witnessed seal.", priority: "High", riskLevel: "High", consequence: "Internal cash theft.", proof: "Bank Slip", trainerNotes: "Deposit before 11 AM." },
                { id: "FM-FIN-10", description: "Audit staff travel expense claims.", priority: "Low", riskLevel: "Medium", consequence: "Inflated expenses.", proof: "Claim File", trainerNotes: "Match journey logs." },
                { id: "FM-FIN-11", description: "Verify GST input credit on utility bills.", priority: "Medium", riskLevel: "Low", consequence: "Financial inefficiency.", proof: "Ledger Audit", trainerNotes: "Check GSTIN match." },
                { id: "FM-FIN-12", description: "Audit invoice entry TAT (< 24h).", priority: "Medium", riskLevel: "Low", consequence: "Inaccurate real-time stock.", proof: "Entry Log", trainerNotes: "Match physical receiving." },
                { id: "FM-FIN-13", description: "Check availability of bill folders.", priority: "Low", riskLevel: "Low", consequence: "Poor billing image.", proof: "Stock Audit", trainerNotes: "Clean with alcohol wipe." },
                { id: "FM-FIN-14", description: "Review 'Cost per Occupant' trend.", priority: "Low", riskLevel: "Low", consequence: "Margin decline.", proof: "Finance Chart", trainerNotes: "Analyze vs prev year." },
                { id: "FM-FIN-15", description: "Audit fixed-asset tags in MEP plant.", priority: "Low", riskLevel: "Low", consequence: "Lost property.", proof: "Asset Log", trainerNotes: "Chillers must have tags." },
                { id: "FM-FIN-16", description: "Verify medical insurance renewals for staff.", priority: "Medium", riskLevel: "Low", consequence: "Employee distress liability.", proof: "Policy File", trainerNotes: "Renew 30 days pre-term." },
                { id: "FM-FIN-17", description: "Audit 'Free-Parking' quota registry.", priority: "High", riskLevel: "High", consequence: "Revenue leakage.", proof: "Quota File", trainerNotes: "Verify ID cards." },
                { id: "FM-FIN-18", description: "Check availability of tamper seals.", priority: "Low", riskLevel: "Low", consequence: "Compromised security.", proof: "Supply Note", trainerNotes: "Min 500 seals buffer." },
                { id: "FM-FIN-19", description: "Review P1 vendor service TAT for shift.", priority: "High", riskLevel: "Low", consequence: "Loss of focus.", proof: "Job Log", trainerNotes: "Target P1 fix < 30m." },
                { id: "FM-FIN-20", description: "Final daily Finance sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of fiscal control.", proof: "Signed Summary", trainerNotes: "Attach exception reports." }
            ]
        },
        {
            title: "Safety & EHS",
            department: "Safety",
            frequency: "Daily",
            role: "EHS Officer",
            summary: "Property hardening and life-safety command.",
            icon: "shield-check",
            tasks: [
                { id: "FM-SEC-01", description: "Test perimeter electric fence / alarm system.", priority: "High", riskLevel: "High", consequence: "Security breach.", proof: "Test Note", trainerNotes: "Simulate a breach daily." },
                { id: "FM-SEC-02", description: "CCTV Audit: Verify 30-day backup status.", priority: "High", riskLevel: "High", consequence: "Loss of evidence.", proof: "System Screen", trainerNotes: "Check timestamp sync." },
                { id: "FM-SEC-03", description: "Verify fire-exit corridors are clear/unlocked.", priority: "High", riskLevel: "High", consequence: "Fatal entrapment.", proof: "Patrol Log", trainerNotes: "Physically open every door." },
                { id: "FM-SEC-04", description: "Check fire extinguisher pressure (Green).", priority: "High", riskLevel: "High", consequence: "Inability to fight fire.", proof: "Gauge Log", trainerNotes: "Check safety seals daily." },
                { id: "FM-SEC-05", description: "Verify guard sobriety and attendance.", priority: "High", riskLevel: "High", consequence: "Vulnerable perimeter.", proof: "Test Note", trainerNotes: "Conduct at shift change." },
                { id: "FM-SEC-06", description: "Audit visitor ID register: 100% capture.", priority: "High", riskLevel: "High", consequence: "Unauthorized access.", proof: "Registry Audit", trainerNotes: "Retain ID at gate." },
                { id: "FM-SEC-07", description: "Test emergency PA system volume zones.", priority: "High", riskLevel: "Medium", consequence: "Crisis comm failure.", proof: "Sound Test", trainerNotes: "Rotate zones weekly." },
                { id: "FM-SEC-08", description: "Verify 'LOTO' locks on active MEP repairs.", priority: "High", riskLevel: "High", consequence: "Fatal electrocution.", proof: "Visual Audit", trainerNotes: "No lock, No work." },
                { id: "FM-SEC-09", description: "First-aid kit shelf stock check.", priority: "Medium", riskLevel: "Medium", consequence: "Inability to treat injury.", proof: "Stock Audit", trainerNotes: "Check burn-gel expiry." },
                { id: "FM-SEC-10", description: "Chemical store spill containment check.", priority: "High", riskLevel: "Medium", consequence: "Toxic gas exposure.", proof: "Safety Log", trainerNotes: "Separate acids/alkalis." },
                { id: "FM-SEC-11", description: "Verify night-shift external floodlights.", priority: "Medium", riskLevel: "Low", consequence: "Security blind spots.", proof: "Photo", trainerNotes: "Replace fused bulbs < 24h." },
                { id: "FM-SEC-12", description: "Test 'Panic Button' at reception/vault.", priority: "High", riskLevel: "High", consequence: "Robbery response delay.", proof: "Test Log", trainerNotes: "Silent test via monitoring co." },
                { id: "FM-SEC-13", description: "Inspect back-alley waste bins for fire risk.", priority: "High", riskLevel: "High", consequence: "Arson hazard.", proof: "Walkthrough", trainerNotes: "Clear cardboard daily." },
                { id: "FM-SEC-14", description: "Check integrity of roof access padlocks.", priority: "High", riskLevel: "High", consequence: "Fatal fall from height.", proof: "Visual Check", trainerNotes: "Keys to GM box nightly." },
                { id: "FM-SEC-15", description: "Audit security guard patrol hourly logs.", priority: "Low", riskLevel: "Low", consequence: "Discipline drift.", proof: "Log Review", trainerNotes: "Must be hourly entries." },
                { id: "FM-SEC-16", description: "Inspect MEP plant infrared heat points.", priority: "High", riskLevel: "High", consequence: "Electrical fire.", proof: "Panel Log", trainerNotes: "Check for smell/heat." },
                { id: "FM-SEC-17", description: "Emergency Contact List posted clearly.", priority: "Low", riskLevel: "Low", consequence: "Comm delay.", proof: "Photo", trainerNotes: "Include Fire/Police/Owner." },
                { id: "FM-SEC-18", description: "Test lift 'Alarm Bell' battery backup.", priority: "High", riskLevel: "High", consequence: "Trapped occupant panic.", proof: "Start-test Log", trainerNotes: "Test with main power off." },
                { id: "FM-SEC-19", description: "Check availability of safety harnesses.", priority: "High", riskLevel: "High", consequence: "Unsafe work at height.", proof: "Stock Audit", trainerNotes: "Inspect for frayed rope." },
                { id: "FM-SEC-20", description: "Final nightly safety sign-off.", priority: "High", riskLevel: "Low", consequence: "Systemic risk gap.", proof: "Manager Initials", trainerNotes: "Physical perimeter touch." }
            ]
        },
        {
            title: "Technical Certs",
            department: "HR",
            frequency: "Monthly",
            role: "HR Manager",
            summary: "Compliance and safety skill governance.",
            icon: "graduation-cap",
            tasks: [
                { id: "FM-HR-01", description: "Verify LOTO and High-Voltage certs for engineers.", priority: "High", riskLevel: "High", consequence: "Fatal accidents / Unlicensed care.", proof: "Cert Registry", trainerNotes: "No cert, No work." },
                { id: "FM-HR-02", description: "Audit BLS/First-Aid responder roster.", priority: "High", riskLevel: "High", consequence: "Failure to life-support.", proof: "Matrix File", trainerNotes: "Renew 30 days pre-expiry." },
                { id: "FM-HR-03", description: "Briefing grooming audit: check badges/uniforms.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution.", proof: "Attendance Log", trainerNotes: "Check ID cards/clean shirts." },
                { id: "FM-HR-04", description: "Update 'Occupational Safety' training matrix.", priority: "High", riskLevel: "Low", consequence: "Loss of safety culture.", proof: "Matrix Update", trainerNotes: "Target 4h/month per person." },
                { id: "FM-HR-05", description: "Audit attendance trends: latecomers.", priority: "Medium", riskLevel: "Low", consequence: "Operational delays.", proof: "Biometric Log", trainerNotes: "Flag > 3 late entries/week." },
                { id: "FM-HR-06", description: "Staff Health Pulse: verify med certs.", priority: "Medium", riskLevel: "Medium", consequence: "Infection risk.", proof: "Med File", trainerNotes: "Includes canteen staff." },
                { id: "FM-HR-07", description: "Verify NDAs signed by new vendors/contractors.", priority: "High", riskLevel: "High", consequence: "Loss of trade secrets.", proof: "Signed File", trainerNotes: "Store in secure HR vault." },
                { id: "FM-HR-08", description: "Check availability of spare uniforms.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional hires.", proof: "Inventory Check", trainerNotes: "Min 2 sets per role." },
                { id: "FM-HR-09", description: "Review resignation exit interview notes.", priority: "Low", riskLevel: "Low", consequence: "Unaddressed churn causes.", proof: "Exit Notes", trainerNotes: "Analyze 'Admin Friction'." },
                { id: "FM-HR-10", description: "Audit staff break-room hygiene.", priority: "Low", riskLevel: "Low", consequence: "Low morale.", proof: "Cleaning Log", trainerNotes: "Empty bins twice daily." },
                { id: "FM-HR-11", description: "Conduct 'Safety Policy' verbal quiz.", priority: "Medium", riskLevel: "Medium", consequence: "Protocol ignorance.", proof: "Quiz Log", trainerNotes: "Ask random staff daily." },
                { id: "FM-HR-12", description: "Verify 'Sexual Harassment' policy display.", priority: "High", riskLevel: "High", consequence: "Legal liability.", proof: "Photo", trainerNotes: "Display in Staff Room." },
                { id: "FM-HR-13", description: "Check first-aid kits in technical zones.", priority: "High", riskLevel: "Medium", consequence: "Inability to treat burns.", proof: "Stock Audit", trainerNotes: "Check antiseptic expiry." },
                { id: "FM-HR-14", description: "Audit 'Uniform Laundry' cycle time.", priority: "Low", riskLevel: "Low", consequence: "Dirty staff clothes.", proof: "Laundry Log", trainerNotes: "Target < 24h turnaround." },
                { id: "FM-HR-15", description: "Verify 100% sign on 'Safety Policy'.", priority: "High", riskLevel: "Medium", consequence: "No legal defense for breaches.", proof: "Signed Form", trainerNotes: "Include theft policies." },
                { id: "FM-HR-16", description: "Check grooming kit availability in lockers.", priority: "Low", riskLevel: "Low", consequence: "Slipping standards.", proof: "Visual Check", trainerNotes: "Deo/Razors in lockers." },
                { id: "FM-HR-17", description: "Audit 'Overtime' vs Admin budget.", priority: "Medium", riskLevel: "Medium", consequence: "Payroll inflation.", proof: "OT Tracker", trainerNotes: "HOD pre-approval needed." },
                { id: "FM-HR-18", description: "Inspect staff locker hygiene.", priority: "Low", riskLevel: "Low", consequence: "Pest risk in staff zone.", proof: "Cleaning Log", trainerNotes: "Open lockers Sundays." },
                { id: "FM-HR-19", description: "Verify active Certs for Lift Technicians.", priority: "High", riskLevel: "High", consequence: "Legal negligence in accidents.", proof: "Cert Registry", trainerNotes: "Check State Lift Inspector ID." },
                { id: "FM-HR-20", description: "Final monthly HR matrix sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of admin control.", proof: "Signed Matrix", trainerNotes: "Submit to Principal." }
            ]
        },
        {
            title: "Hard FM (MEP)",
            department: "Engineering",
            frequency: "Daily",
            role: "Technical Lead",
            summary: "Technical uptime and backbone protection.",
            icon: "wrench",
            tasks: [
                { id: "FM-ENG-01", description: "Inspect backup generator (DG) and log fuel levels.", priority: "High", riskLevel: "High", consequence: "Total facility blackout.", proof: "Fuel Log", trainerNotes: "Target > 75% fuel tank." },
                { id: "FM-ENG-02", description: "Check Chiller/HVAC compressor heat points.", priority: "High", riskLevel: "Medium", consequence: "Occupant heat discomfort.", proof: "Panel Log", trainerNotes: "Vacuum coils monthly." },
                { id: "FM-ENG-03", description: "Verify RO water TDS parameters (Target < 150).", priority: "High", riskLevel: "High", consequence: "Poor water taste/Health risk.", proof: "TDS Reading", trainerNotes: "Flush filters at > 1 bar diff." },
                { id: "FM-ENG-04", description: "Inspect elevator auto-rescue battery (ARD).", priority: "High", riskLevel: "High", consequence: "Guest trapped in lift.", proof: "Start-test Log", trainerNotes: "Run on batt for 1 cycle." },
                { id: "FM-ENG-05", description: "Log domestic water pump pressure gauges.", priority: "Medium", riskLevel: "Medium", consequence: "Water outage crisis.", proof: "Pressure Log", trainerNotes: "Maintain min 3.0 bar." },
                { id: "FM-ENG-06", description: "Audit server room dedicated AC (Target 20C).", priority: "High", riskLevel: "High", consequence: "Data failure.", proof: "Temp Note", trainerNotes: "Check backup split-unit." },
                { id: "FM-ENG-07", description: "Verify LOTO permit for active repairs.", priority: "High", riskLevel: "High", consequence: "Fatal injury.", proof: "Permit File", trainerNotes: "No lock, No work." },
                { id: "FM-ENG-08", description: "Inspect solar hot water manifold pressure.", priority: "Low", riskLevel: "Low", consequence: "Increased utility costs.", proof: "Gauge Note", trainerNotes: "Clean panels weekly." },
                { id: "FM-ENG-09", description: "Test emergency lighting battery run.", priority: "Medium", riskLevel: "High", consequence: "Darkness during blackout.", proof: "Test Note", trainerNotes: "Run 15 mins monthly." },
                { id: "FM-ENG-10", description: "Check plumbing traps for 'U-bend' dry-out.", priority: "Low", riskLevel: "Low", consequence: "Sewage odors in lobby.", proof: "Visual Check", trainerNotes: "Flush traps weekly." },
                { id: "FM-ENG-11", description: "Audit KWH meter logs hourly.", priority: "Medium", riskLevel: "Low", consequence: "Unmonitored energy spikes.", proof: "Meter Log", trainerNotes: "Alert GM if > 10% diff." },
                { id: "FM-ENG-12", description: "Check AC filter cleaning cycle completion.", priority: "Medium", riskLevel: "Low", consequence: "High energy bills.", proof: "Maint Sheet", trainerNotes: "Wipe lobby vents weekly." },
                { id: "FM-ENG-13", description: "Inspect kitchen gas soap-bubble test.", priority: "High", riskLevel: "High", consequence: "Fire hazard.", proof: "Maint Note", trainerNotes: "Check joints daily." },
                { id: "FM-ENG-14", description: "Verify intercom dial-tone sync.", priority: "Low", riskLevel: "Low", consequence: "Comm failure.", proof: "Dial Test", trainerNotes: "Check security booth lines." },
                { id: "FM-ENG-15", description: "Audit technical room hygiene/dust.", priority: "Low", riskLevel: "Low", consequence: "Equipment fire risk.", proof: "Cleaning Note", trainerNotes: "No boxes allowed in UPS room." },
                { id: "FM-ENG-16", description: "Check RO pre-filter pressure drop.", priority: "Low", riskLevel: "Medium", consequence: "Filter burst.", proof: "Gauge Reading", trainerNotes: "Flush monthly." },
                { id: "FM-ENG-17", description: "Review P1 breakdown TAT for shift.", priority: "High", riskLevel: "Low", consequence: "Loss of focus.", proof: "Job Log", trainerNotes: "Target P1 fix < 30m." },
                { id: "FM-ENG-18", description: "Verify external lighting timer accuracy.", priority: "Low", riskLevel: "Low", consequence: "Security risk.", proof: "Photo", trainerNotes: "Set Sunset-to-Sunrise." },
                { id: "FM-ENG-19", description: "Check staff restroom drainage/hygiene.", priority: "Low", riskLevel: "Low", consequence: "Morale drop.", proof: "Cleaning Note", trainerNotes: "Buff mirrors daily." },
                { id: "FM-ENG-20", description: "Final Technical sign-off for shift.", priority: "High", riskLevel: "Low", consequence: "Loss of dept control.", proof: "Signed Log", trainerNotes: "Brief GM on major fails." }
            ]
        },
        {
            title: "Vendor SLA Governance",
            department: "Admin",
            frequency: "Weekly",
            role: "Customer Experience Lead",
            summary: "Monitors third-party performance parity.",
            icon: "file-check",
            tasks: [
                { id: "FM-VEN-01", description: "Verify vendor attendance logs against contract SLA.", priority: "Medium", riskLevel: "Low", consequence: "Paying for unrendered services.", proof: "SLA Match", trainerNotes: "Deduct from billing for gaps." },
                { id: "FM-VEN-02", description: "Reply to Google Reviews < 24h.", priority: "High", riskLevel: "Medium", consequence: "PR damage.", proof: "Dashboard", trainerNotes: "Address 1-star reviews first." },
                { id: "FM-VEN-03", description: "Social DM appointment reply < 30m.", priority: "Medium", riskLevel: "Low", consequence: "Lost visitor revenue.", proof: "Inbox Clear", trainerNotes: "Confirm via WhatsApp." },
                { id: "FM-VEN-04", description: "Verify Google Maps 'Live Status'.", priority: "High", riskLevel: "Low", consequence: "Visitors arrive to 'Closed' site.", proof: "Mobile Check", trainerNotes: "Update for holidays instantly." },
                { id: "FM-VEN-05", description: "Review 'Discharge Feedback' trends.", priority: "Medium", riskLevel: "Low", consequence: "Service decay.", proof: "Trend Log", trainerNotes: "Highlight top 3 complaints." },
                { id: "FM-VEN-06", description: "Audit 'Feedback QR' placement in lobby.", priority: "Low", riskLevel: "Low", consequence: "Low audit data.", proof: "Visual Check", trainerNotes: "Stickers on chairs." },
                { id: "FM-VEN-07", description: "Verify 'Guest Wi-Fi' code visibility.", priority: "Low", riskLevel: "Low", consequence: "Visitor frustration.", proof: "Photo", trainerNotes: "Display at helpdesk." },
                { id: "FM-VEN-08", description: "Check helpdesk stationery (Pens/Forms).", priority: "Low", riskLevel: "Low", consequence: "Admin friction.", proof: "Supply Audit", trainerNotes: "Check at 8 AM daily." },
                { id: "FM-VEN-09", description: "Verify 100% reply to Social Comments.", priority: "Medium", riskLevel: "Low", consequence: "PR fire ignored.", proof: "Inbox Clear", trainerNotes: "Target < 4h response." },
                { id: "FM-VEN-10", description: "Audit valet car return TAT.", priority: "Medium", riskLevel: "Low", consequence: "Crowded porch.", proof: "Log Match", trainerNotes: "Target < 8 mins." },
                { id: "FM-VEN-11", description: "Verify lobby TV content daypart match.", priority: "Low", riskLevel: "Low", consequence: "Wrong energy.", proof: "Volume Check", trainerNotes: "News/Events only." },
                { id: "FM-VEN-12", description: "Check availability of spare face masks.", priority: "Low", riskLevel: "Low", consequence: "Airborne risk.", proof: "Stock Check", trainerNotes: "Offer to coughing guests." },
                { id: "FM-VEN-13", description: "Verify 'VIP Guest' arrival setup.", priority: "Medium", riskLevel: "Low", consequence: "Trust loss.", proof: "Photo", trainerNotes: "Escalate to GM instantly." },
                { id: "FM-VEN-14", description: "Audit Tenant satisfaction survey scores.", priority: "Medium", riskLevel: "Low", consequence: "Attrition.", proof: "Survey Note", trainerNotes: "Target > 80% positive." },
                { id: "FM-VEN-15", description: "Review resignation exit comments.", priority: "Low", riskLevel: "Low", consequence: "Churn causes.", proof: "Exit Notes", trainerNotes: "Identify manager friction." },
                { id: "FM-VEN-16", description: "Verify 'Safety Policy' display.", priority: "High", riskLevel: "High", consequence: "Liability.", proof: "Photo", trainerNotes: "Display in Staff Room." },
                { id: "FM-VEN-17", description: "Audit staff break-room amenities.", priority: "Low", riskLevel: "Low", consequence: "Low morale.", proof: "Visual Check", trainerNotes: "Ensure water active." },
                { id: "FM-VEN-18", description: "Inspect staff locker hygiene.", priority: "Low", riskLevel: "Low", consequence: "Pest risk.", proof: "Cleaning Log", trainerNotes: "Open lockers Sundays." },
                { id: "FM-VEN-19", description: "Check first-aid kits in non-technical zones.", priority: "Low", riskLevel: "Low", consequence: "Injury liability.", proof: "Stock Audit", trainerNotes: "Check expiry dates." },
                { id: "FM-VEN-20", description: "Final daily Reputation sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of ORM control.", proof: "Signed Dashboard", trainerNotes: "Submit to GM." }
            ]
        },
        {
            title: "Internal Logistics",
            department: "Logistics",
            frequency: "Daily",
            role: "Logistics Lead",
            summary: "Internal distribution and waste command.",
            icon: "package",
            tasks: [
                { id: "FM-LOG-01", description: "Audit high-priority parcel register for 100% handover.", priority: "Medium", riskLevel: "Low", consequence: "Lost institutional assets.", proof: "Log Review", trainerNotes: "Signature required for all items." },
                { id: "FM-LOG-02", description: "Verify loading bay lock integrity.", priority: "High", riskLevel: "High", consequence: "After-hours theft.", proof: "Lock Audit", trainerNotes: "Keys to GM nightly." },
                { id: "FM-LOG-03", description: "Audit staff break-room drainage.", priority: "Low", riskLevel: "Low", consequence: "Unhygienic zone.", proof: "Cleaning Note", trainerNotes: "Buff mirrors daily." },
                { id: "FM-LOG-04", description: "Check availability of spare car/bike keys.", priority: "Low", riskLevel: "Medium", consequence: "Delay crisis.", proof: "Vault Inventory", trainerNotes: "Secure in main safe." },
                { id: "FM-LOG-05", description: "Verify vendor attendance logs.", priority: "Low", riskLevel: "Low", consequence: "Paying for unrendered work.", proof: "Log Review", trainerNotes: "Deduct for late arrivals." },
                { id: "FM-LOG-06", description: "Audit outsourced HK staff ID visibility.", priority: "High", riskLevel: "High", consequence: "Unauthorized person risk.", proof: "Patrol Log", trainerNotes: "Badges must be chest-high." },
                { id: "FM-LOG-07", description: "Inspect back-alley for waste leakage.", priority: "High", riskLevel: "High", consequence: "Fines.", proof: "Walkthrough", trainerNotes: "Check yellow bag seals." },
                { id: "FM-LOG-08", description: "Verify kitchen gas manifold joints soap-test.", priority: "High", riskLevel: "High", consequence: "Explosion.", proof: "Maint Note", trainerNotes: "Check joints daily." },
                { id: "FM-LOG-09", description: "Audit 'Inventory Waste' trend.", priority: "Medium", riskLevel: "Medium", consequence: "Profit leakage.", proof: "Waste Ledger", trainerNotes: "Target waste < 1%." },
                { id: "FM-LOG-10", description: "Check status of 'Fire Exit' clearance.", priority: "High", riskLevel: "High", consequence: "Fatal entrapment.", proof: "Patrol Log", trainerNotes: "Physically open doors." },
                { id: "FM-LOG-11", description: "Verify vendor GST pan match on bills.", priority: "Low", riskLevel: "Low", consequence: "Tax inefficiency.", proof: "Ledger Audit", trainerNotes: "Verify 100% of new vendors." },
                { id: "FM-LOG-12", description: "Audit 'Uniform Laundry' cycle time.", priority: "Low", riskLevel: "Low", consequence: "Dirty clothes.", proof: "Laundry Log", trainerNotes: "Target < 24h turnaround." },
                { id: "FM-LOG-13", description: "Check availability of PPE masks at entry.", priority: "Medium", riskLevel: "Medium", consequence: "Infection.", proof: "Stock Check", trainerNotes: "Provide free to arrivals." },
                { id: "FM-LOG-14", description: "Verify porch floodlight status.", priority: "Low", riskLevel: "Low", consequence: "Security risk.", proof: "Photo", trainerNotes: "Target Sunset-to-Sunrise." },
                { id: "FM-LOG-15", description: "Audit security guard hourly entries.", priority: "Low", riskLevel: "Low", consequence: "Discipline drift.", proof: "Log Review", trainerNotes: "Entries must be hourly." },
                { id: "FM-LOG-16", description: "Verify HIS database cloud sync.", priority: "High", riskLevel: "High", consequence: "Data loss.", proof: "System Log", trainerNotes: "Check sync at 2 AM." },
                { id: "FM-LOG-17", description: "Check first-aid kits in non-clinical zones.", priority: "Low", riskLevel: "Low", consequence: "Liability.", proof: "Stock Audit", trainerNotes: "Check expiry dates." },
                { id: "FM-LOG-18", description: "Verify 100% sign on 'Inventory Waste'.", priority: "Medium", riskLevel: "Medium", consequence: "Leakage.", proof: "Waste Ledger", trainerNotes: "Target < 1% of sales." },
                { id: "FM-LOG-19", description: "Review P1 vendor service TAT.", priority: "Medium", riskLevel: "Low", consequence: "Delayed repairs.", proof: "SLA Match", trainerNotes: "Penalty for > 4h delay." },
                { id: "FM-LOG-20", description: "Final shift Logistics sign-off.", priority: "High", riskLevel: "Low", consequence: "Incomplete handover.", proof: "Signed Summary", trainerNotes: "Brief GM on stockouts." }
            ]
        }
    ]
};

    