
import type { PremiumPack } from "@/lib/premium-packs";

export const franchise_operations_pack: PremiumPack = {
    id: 'franchise_operations_pack',
    title: "Franchise Operating System",
    priceINR: 5999,
    priceUSD: 79,
    competitorPriceUSD: 599,
    updatedAt: "2025-02-24",
    paymentId: 'pl_RaWEBHhFLQENxC',
    lemonSqueezyUrl: 'https://moremeets.lemonsqueezy.com/buy/f4e6b12a-4422-48a0-a198-154332822a27',
    category: "Franchise",
    description: "The definitive Sovereign v9.1 engine for multi-unit groups. Standardizing 152 technical control points from Royalty protection to brand standards.",
    heroHeadline: "Scale Your Brand Without Losing Control",
    heroSubheadline: "Track every outlet, monitor brand standards, and protect your royalty stream—across 152 technical control points.",
    pricingUrgency: "A single failed outlet or one brand-damaging incident costs 100x more than this system.",
    consultingAnchor: 15000,
    icon: "store",
    badgeText: "V9.1 SOVEREIGN",
    badgeVariant: "accent",
    whoIsItFor: ["Franchise Owners", "Heads of Operations", "Development Managers", "Regional Managers"],
    sampleItems: [
        { text: "<strong>Royalty Protection</strong>: Daily sales reconciliation against aggregator and bank records.", icon: "banknote" },
        { text: "<strong>Brand Visual QC</strong>: Signage, uniform, and ambiance audits across the group.", icon: "eye" },
        { text: "<strong>Local Marketing Command</strong>: Activation logs for seasonal promos and ORM.", icon: "megaphone" },
        { text: "<strong>Staff Cert Audit</strong>: Tracking franchisee training levels and grooming parity.", icon: "graduation-cap" },
        { text: "<strong>Supply Chain Integrity</strong>: Auditing vendor receiving to stop unvetted sourcing.", icon: "truck" }
    ],
    checklists: [
        {
            title: "Brand Governance",
            department: "Executive",
            frequency: "Weekly",
            role: "COO / Owner",
            summary: "Group-wide performance and brand protection.",
            icon: "crown",
            tasks: [
                { id: "FR-EXE-01", description: "Audit royalty payout status across all branches.", priority: "High", riskLevel: "Medium", consequence: "Unrealized income leakage.", proof: "Ledger Review", trainerNotes: "Cross-check with bank captures." },
                { id: "FR-EXE-02", description: "Review 'Empire Mood' and Group shift completion.", priority: "High", riskLevel: "Low", consequence: "Operational drift.", proof: "Console Review", trainerNotes: "Identify bottom 2 branches." },
                { id: "FR-EXE-03", description: "Audit mystery audit scores for the week.", priority: "Medium", riskLevel: "Low", consequence: "Brand dilution.", proof: "Audit Report", trainerNotes: "Focus on 1-star failures." },
                { id: "FR-EXE-04", description: "Verify Insurance: Public Liability for all units.", priority: "High", riskLevel: "High", consequence: "Financial ruin during incident.", proof: "Policy File", trainerNotes: "Check expiry 60 days early." },
                { id: "FR-EXE-05", description: "Review P&L utility spikes vs. Group baseline.", priority: "Low", riskLevel: "Low", consequence: "Unchecked overheads.", proof: "Finance Chart", trainerNotes: "Compare vs previous month." },
                { id: "FR-EXE-06", description: "Check status of unresolved 'Red' incidents.", priority: "High", riskLevel: "High", consequence: "Escalated legal liability.", proof: "Incident Log", trainerNotes: "Resolve all P1s < 24h." },
                { id: "FR-EXE-07", description: "Verify License renewal calendar status.", priority: "High", riskLevel: "High", consequence: "Premises sealing.", proof: "License File", trainerNotes: "Check Trade/FSSAI dates." },
                { id: "FR-EXE-08", description: "Audit senior management floor presence hours.", priority: "Medium", riskLevel: "Low", consequence: "Leadership disconnect.", proof: "Roster Log", trainerNotes: "GMs must be on floor Sat peak." },
                { id: "FR-EXE-09", description: "Review 'Revenue per Square Foot' trend.", priority: "Low", riskLevel: "Low", consequence: "Underperforming real estate.", proof: "Sales Report", trainerNotes: "Analyze bottom 10% units." },
                { id: "FR-EXE-10", description: "Verify CAPEX project milestone photos.", priority: "Medium", riskLevel: "Medium", consequence: "Delayed upgrades.", proof: "Project Log", trainerNotes: "Check 50% completion step." },
                { id: "FR-EXE-11", description: "Audit staff payroll accuracy for franchisees.", priority: "High", riskLevel: "Medium", consequence: "Employee legal disputes.", proof: "Payroll Register", trainerNotes: "Check OT calculations." },
                { id: "FR-EXE-12", description: "Review Group CSAT scores on Google/Yelp.", priority: "High", riskLevel: "Low", consequence: "Ranking drop.", proof: "ORM Dashboard", trainerNotes: "Analyze complaint keywords." },
                { id: "FR-EXE-13", description: "Verify 'Fixed Asset' tags on new equipment.", priority: "Low", riskLevel: "Low", consequence: "Lost property.", proof: "Asset Log", trainerNotes: "Tag every item > $500." },
                { id: "FR-EXE-14", description: "Review 'Training Compliance' matrix.", priority: "Medium", riskLevel: "Low", consequence: "Skill stagnation.", proof: "Matrix File", trainerNotes: "Target 4h/person per month." },
                { id: "FR-EXE-15", description: "Audit vendor pricing vs. Market benchmark.", priority: "Medium", riskLevel: "Low", consequence: "Inflated procurement costs.", proof: "Vendor Log", trainerNotes: "Check Top 10 items prices." },
                { id: "FR-EXE-16", description: "Check compliance with local labor laws.", priority: "High", riskLevel: "High", consequence: "Government fines.", proof: "Compliance File", trainerNotes: "Check PF/ESI deposits." },
                { id: "FR-EXE-17", description: "Review status of 'Marketing LSM' spend.", priority: "Low", riskLevel: "Low", consequence: "Wasted budget.", proof: "LSM Tracker", trainerNotes: "Check ROI per campaign." },
                { id: "FR-EXE-18", description: "Audit 'Inventory Variance' Group trend.", priority: "High", riskLevel: "High", consequence: "Massive theft leakage.", proof: "Variance Report", trainerNotes: "Flag > 2% variance." },
                { id: "FR-EXE-19", description: "Final Weekly Governance sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of oversight.", proof: "Signed Summary", trainerNotes: "Submit to Board Mondays." }
            ]
        },
        {
            title: "Site Audit Command",
            department: "Operations",
            frequency: "Daily",
            role: "General Manager",
            summary: "Ensures brand consistency and arrival readiness.",
            icon: "eye",
            tasks: [
                { id: "FR-OPS-01", description: "Verify signage illumination and condition.", priority: "Medium", riskLevel: "Low", consequence: "Brand dilution and poor visibility.", proof: "Photo", trainerNotes: "Check at sunset daily." },
                { id: "FR-OPS-02", description: "Visual Ambiance: Music, Temp, Scent check.", priority: "Medium", riskLevel: "Low", consequence: "Reduced dwell time.", proof: "Daily Log", trainerNotes: "Target exactly 23°C." },
                { id: "FR-OPS-03", description: "Brief staff on daily targets and LSM promos.", priority: "High", riskLevel: "Low", consequence: "Uninformed staff / lost sales.", proof: "Briefing Log", trainerNotes: "Mention upsell item of day." },
                { id: "FR-OPS-04", description: "Conduct random mystery audit walkthrough.", priority: "Medium", riskLevel: "Low", consequence: "Slipping standards.", proof: "Checksheet", trainerNotes: "Run as if you are a guest." },
                { id: "FR-OPS-05", description: "Audit restroom hygiene frequency log.", priority: "High", riskLevel: "Low", consequence: "Negative reviews.", proof: "Hourly Sheet", trainerNotes: "Check soap/sanitizer." },
                { id: "FR-OPS-06", description: "Verify staff grooming and ID visibility.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional image.", proof: "Visual Audit", trainerNotes: "Check name-tags & nails." },
                { id: "FR-OPS-07", description: "Check status of 'Open' guest complaints.", priority: "High", riskLevel: "High", consequence: "Viral reputation damage.", proof: "Feedback Log", trainerNotes: "Resolve all < 4 hours." },
                { id: "FR-OPS-08", description: "Verify availability of spare uniforms.", priority: "Low", riskLevel: "Low", consequence: "Dirty staff appearance.", proof: "Inventory Check", trainerNotes: "Min 2 sets per person." },
                { id: "FR-OPS-09", description: "Audit queue TAT for peak hours.", priority: "Medium", riskLevel: "Low", consequence: "Lost walk-ins.", proof: "System Log", trainerNotes: "Peak: 7 PM - 9 PM." },
                { id: "FR-OPS-10", description: "Verify digital menu item availability.", priority: "High", riskLevel: "Low", consequence: "Guest frustration.", proof: "App Check", trainerNotes: "Sync with kitchen stock." },
                { id: "FR-OPS-11", description: "Check lobby Wi-Fi guest portal login.", priority: "Low", riskLevel: "Low", consequence: "Immediate complaints.", proof: "Phone Test", trainerNotes: "Login must work in < 10s." },
                { id: "FR-OPS-12", description: "Audit trash bin disposal frequency.", priority: "Low", riskLevel: "Medium", consequence: "Odors and pests.", proof: "Cleaning Log", trainerNotes: "Empty when 75% full." },
                { id: "FR-OPS-13", description: "Verify exterior porch floor buffing.", priority: "Low", riskLevel: "Low", consequence: "Poor first impression.", proof: "Walkthrough", trainerNotes: "Buff nightly at 2 AM." },
                { id: "FR-OPS-14", description: "Check lighting in 'Blind Spot' zones.", priority: "Medium", riskLevel: "Medium", consequence: "Security risk.", proof: "Photo", trainerNotes: "Replace fused bulbs < 24h." },
                { id: "FR-OPS-15", description: "Verify staff break-room hygiene.", priority: "Low", riskLevel: "Low", consequence: "Low staff morale.", proof: "Cleaning Note", trainerNotes: "No food in lockers." },
                { id: "FR-OPS-16", description: "Audit 'Upsell' contest results for shift.", priority: "Low", riskLevel: "Low", consequence: "Missed revenue.", proof: "Leaderboard", trainerNotes: "Reward at briefing." },
                { id: "FR-OPS-17", description: "Check availability of promotional flyers.", priority: "Low", riskLevel: "Low", consequence: "Ineffective LSM.", proof: "Stock Audit", trainerNotes: "Min 100 sets at desk." },
                { id: "FR-OPS-18", description: "Verify lobby TV content daypart match.", priority: "Low", riskLevel: "Low", consequence: "Inappropriate energy.", proof: "Visual Check", trainerNotes: "Mute if noise > 60dB." },
                { id: "FR-OPS-19", description: "Final daily Operations sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of duty control.", proof: "Signed Book", trainerNotes: "Oral + Digital briefing." }
            ]
        },
        {
            title: "Royalty & Financials",
            department: "Finance",
            frequency: "Daily",
            role: "Finance & Cashier",
            summary: "Protects the franchise revenue pipeline.",
            icon: "banknote",
            tasks: [
                { id: "FR-FIN-01", description: "Reconcile aggregator gross against POS report.", priority: "High", riskLevel: "High", consequence: "Undetected commission errors.", proof: "Match Note", trainerNotes: "Report > 1% variance." },
                { id: "FR-FIN-02", description: "Blind Stock Count: Top 10 items.", priority: "High", riskLevel: "High", consequence: "High-value inventory theft.", proof: "Stock Sheet", trainerNotes: "Count without system qty." },
                { id: "FR-FIN-03", description: "Audit 'Void' history for shift.", priority: "High", riskLevel: "Medium", consequence: "Bill manipulation leakage.", proof: "POS Audit", trainerNotes: "Voids need GM signature." },
                { id: "FR-FIN-04", description: "Match Cash-to-Bank deposit slip.", priority: "High", riskLevel: "High", consequence: "Internal revenue theft.", proof: "Bank Slip", trainerNotes: "Witnessed seal mandatory." },
                { id: "FR-FIN-05", description: "Verify Cash Float denominations.", priority: "High", riskLevel: "High", consequence: "Operational delays.", proof: "Float Sheet", trainerNotes: "Record denominations." },
                { id: "FR-FIN-06", description: "Check aggregator payouts vs dispatched logs.", priority: "High", riskLevel: "Medium", consequence: "Income loss via unrecorded cancels.", proof: "Payout Reconcile", trainerNotes: "Flag 'Cancelled' orders sent." },
                { id: "FR-FIN-07", description: "Audit 'Discount' code usage pulse.", priority: "Medium", riskLevel: "Medium", consequence: "Margin erosion.", proof: "POS Report", trainerNotes: "Verify reason codes." },
                { id: "FR-FIN-08", description: "Verify invoice entry in < 24h.", priority: "Medium", riskLevel: "Low", consequence: "Inaccurate real-time stock.", proof: "Entry Log", trainerNotes: "Match physical receiving notes." },
                { id: "FR-FIN-09", description: "Audit credit card terminal tamper seals.", priority: "High", riskLevel: "High", consequence: "Skimming legal disaster.", proof: "Visual Audit", trainerNotes: "Check for mismatched screws." },
                { id: "FR-FIN-10", description: "Check stationary stock levels (Bill rolls).", priority: "Low", riskLevel: "Low", consequence: "Billing halt.", proof: "Supply Check", trainerNotes: "Min 1 week buffer stock." },
                { id: "FR-FIN-11", description: "Audit staff travel expense claims.", priority: "Low", riskLevel: "Medium", consequence: "Inflated expenses.", proof: "Claim File", trainerNotes: "Vouchers needed for all." },
                { id: "FR-FIN-12", description: "Verify vendor TDS deductions.", priority: "Medium", riskLevel: "Medium", consequence: "Tax non-compliance.", proof: "TDS Register", trainerNotes: "Check PAN status monthly." },
                { id: "FR-FIN-13", description: "Review 'APC' trend for shift.", priority: "Low", riskLevel: "Low", consequence: "Underperforming upsells.", proof: "Sales Report", trainerNotes: "Compare vs previous week avg." },
                { id: "FR-FIN-14", description: "Check 'Item Variance' for high-risk stock.", priority: "High", riskLevel: "High", consequence: "Systemic portioning fail.", proof: "Variance Report", trainerNotes: "Focus on > 5% variance." },
                { id: "FR-FIN-15", description: "Audit utility meters for EOD.", priority: "Low", riskLevel: "Low", consequence: "Undetected energy spikes.", proof: "Meter Log", trainerNotes: "Check at night shift end." },
                { id: "FR-FIN-16", description: "Verify vendor payment approvals.", priority: "Medium", riskLevel: "Low", consequence: "Paying incorrect rates.", proof: "Approval Note", trainerNotes: "Cross-check market rate list." },
                { id: "FR-FIN-17", description: "Check availability of bill folders.", priority: "Low", riskLevel: "Low", consequence: "Poor billing presentation.", proof: "Stock Note", trainerNotes: "Clean with alcohol wipe." },
                { id: "FR-FIN-18", description: "Audit 'Free-Bed/Seat' quota documentation.", priority: "High", riskLevel: "High", consequence: "Legal penalty/Fines.", proof: "Quota Registry", trainerNotes: "Verify eligibility files." },
                { id: "FR-FIN-19", description: "Final daily Finance sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of fiscal control.", proof: "Signed Summary", trainerNotes: "Attach exception reports." }
            ]
        },
        {
            title: "EHS & Safety Compliance",
            department: "Safety",
            frequency: "Daily",
            role: "EHS Officer",
            summary: "Regulatory and occupational safety command.",
            icon: "hard-hat",
            tasks: [
                { id: "FR-EHS-01", description: "Verify fire extinguisher pressure and expiry.", priority: "High", riskLevel: "High", consequence: "Total liability in case of fire.", proof: "Gauge Log", trainerNotes: "Tag and date every cylinder." },
                { id: "FR-EHS-02", description: "Audit fire-exit corridors for clearance.", priority: "High", riskLevel: "High", consequence: "Fatal entrapment.", proof: "Patrol Log", trainerNotes: "No boxes in fire corridor." },
                { id: "FR-EHS-03", description: "CCTV Audit: Verify 30-day backup status.", priority: "High", riskLevel: "High", consequence: "Loss of evidence.", proof: "System Screen", trainerNotes: "Check timestamp sync." },
                { id: "FR-EHS-04", description: "Verify status of Pest Control bait stations.", priority: "Medium", riskLevel: "Low", consequence: "Infestation in store.", proof: "Pest Log", trainerNotes: "Target zero sightings." },
                { id: "FR-EHS-05", description: "Test fire alarm panel zones.", priority: "High", riskLevel: "High", consequence: "Fatal delay in alert.", proof: "Test Log", trainerNotes: "Rotate zones weekly." },
                { id: "FR-EHS-06", description: "Audit staff entry/exit bag point.", priority: "Medium", riskLevel: "High", consequence: "Inventory theft.", proof: "Security Note", trainerNotes: "No bags in prep zone." },
                { id: "FR-EHS-07", description: "Check perimeter lighting bulbs.", priority: "Low", riskLevel: "Low", consequence: "Night safety risk.", proof: "Visual Check", trainerNotes: "Replace fused bulbs < 24h." },
                { id: "FR-EHS-08", description: "Vault dual-verification access test.", priority: "High", riskLevel: "High", consequence: "Internal theft single-point.", proof: "Access Log", trainerNotes: "Separate keys for GM/Acct." },
                { id: "FR-EHS-09", description: "First-aid kit stock audit.", priority: "Medium", riskLevel: "Medium", consequence: "Inability to treat burns.", proof: "Stock Audit", trainerNotes: "Check burn-gel levels." },
                { id: "FR-EHS-10", description: "Chemical store spill containment.", priority: "High", riskLevel: "Medium", consequence: "Chemical burns.", proof: "Safety Log", trainerNotes: "Separate acids/alkalis." },
                { id: "FR-EHS-11", description: "Verify 'Wet Floor' signage availability.", priority: "Medium", riskLevel: "Medium", consequence: "Slip-and-fall lawsuits.", proof: "Visual Check", trainerNotes: "Mandatory during mopping." },
                { id: "FR-EHS-12", description: "Electrical panel infrared heat test.", priority: "High", riskLevel: "High", consequence: "Electrical fire risk.", proof: "Panel Log", trainerNotes: "Check for smell or heat." },
                { id: "FR-EHS-13", description: "Rear delivery lock integrity check.", priority: "High", riskLevel: "High", consequence: "After-hours burglary.", proof: "Lock Audit", trainerNotes: "Keys to GM nightly." },
                { id: "FR-EHS-14", description: "Emergency Contact List posted.", priority: "Low", riskLevel: "Low", consequence: "Comm delay.", proof: "Photo", trainerNotes: "Include Fire/Police/Owner." },
                { id: "FR-EHS-15", description: "Incident Report 100% completion check.", priority: "Medium", riskLevel: "Low", consequence: "No record for defense.", proof: "Report File", trainerNotes: "Log even small incidents." },
                { id: "FR-EHS-16", description: "Verify kitchen gas soap-bubble test.", priority: "High", riskLevel: "High", consequence: "Catastrophic fire.", proof: "Maint Note", trainerNotes: "Check main joints daily." },
                { id: "FR-EHS-17", description: "Back-alley waste removal (Cardboard).", priority: "High", riskLevel: "Medium", consequence: "Arson risk.", proof: "Walkthrough", trainerNotes: "Flatten boxes daily." },
                { id: "FR-EHS-18", description: "Vendor visitor badge enforcement.", priority: "Low", riskLevel: "Low", consequence: "Unauthorized person risk.", proof: "Patrol Log", trainerNotes: "Badges must be worn." },
                { id: "FR-EHS-19", description: "Final nightly safety sign-off.", priority: "High", riskLevel: "Low", consequence: "Systemic risk gap.", proof: "Manager Initials", trainerNotes: "Physical perimeter touch." }
            ]
        },
        {
            title: "Staff Certification",
            department: "HR",
            frequency: "Monthly",
            role: "HR Manager",
            summary: "Tracks franchisee staff competency and health.",
            icon: "graduation-cap",
            tasks: [
                { id: "FR-HR-01", description: "Update training matrix for current roster.", priority: "High", riskLevel: "Medium", consequence: "Service quality drift.", proof: "Matrix File", trainerNotes: "Verify 'Brand Standard' scores." },
                { id: "FR-HR-02", description: "Verify staff health certs (F&B).", priority: "High", riskLevel: "Medium", consequence: "Regulatory fines.", proof: "Cert File", trainerNotes: "Renew every 6 months." },
                { id: "FR-HR-03", description: "Briefing grooming audit: check badges.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution.", proof: "Attendance Log", trainerNotes: "Check hairnets/clean shirts." },
                { id: "FR-HR-04", description: "Update 'Service Recovery' training matrix.", priority: "High", riskLevel: "Low", consequence: "Loss of unhappy guests.", proof: "Training Log", trainerNotes: "Role-play L.E.A.R.N. protocol." },
                { id: "FR-HR-05", description: "Audit staff attendance trends: latecomers.", priority: "Medium", riskLevel: "Low", consequence: "Operational delays.", proof: "Biometric Log", trainerNotes: "Flag > 3 late entries/week." },
                { id: "FR-HR-06", description: "Verify 'Safety Drill' enrollment.", priority: "High", riskLevel: "High", consequence: "Staff panic in fire.", proof: "Drill Log", trainerNotes: "Surprise every 90 days." },
                { id: "FR-HR-07", description: "Inspect staff locker hygiene.", priority: "Low", riskLevel: "Low", consequence: "Pest risk in staff zone.", proof: "Cleaning Log", trainerNotes: "Open lockers Sundays." },
                { id: "FR-HR-08", description: "Check uniform stock levels.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional hires.", proof: "Inventory Check", trainerNotes: "Min 2 sets per person." },
                { id: "FR-HR-09", description: "Audit 'Upsell' contest results.", priority: "Low", riskLevel: "Low", consequence: "Missed revenue.", proof: "Leaderboard", trainerNotes: "Reward at briefing." },
                { id: "FR-HR-10", description: "Check first-aid responder roster.", priority: "High", riskLevel: "High", consequence: "Medical liability risk.", proof: "Roster Note", trainerNotes: "Min 1 certified/shift." },
                { id: "FR-HR-11", description: "Verify NDAs signed by new hires.", priority: "High", riskLevel: "Medium", consequence: "Loss of trade secrets.", proof: "Signed File", trainerNotes: "Store in secure HR vault." },
                { id: "FR-HR-12", description: "Review resignation exit interview notes.", priority: "Low", riskLevel: "Low", consequence: "Unaddressed churn causes.", proof: "Exit Notes", trainerNotes: "Identify manager friction." },
                { id: "FR-HR-13", description: "Audit 'Overtime' vs GM budget.", priority: "Medium", riskLevel: "Medium", consequence: "Payroll inflation.", proof: "OT Tracker", trainerNotes: "Must be pre-approved." },
                { id: "FR-HR-14", description: "Verify medical insurance coverage.", priority: "Medium", riskLevel: "Low", consequence: "Employee distress/liability.", proof: "Policy File", trainerNotes: "Renew 30 days early." },
                { id: "FR-HR-15", description: "Check grooming kit availability in lockers.", priority: "Low", riskLevel: "Low", consequence: "Slipping standards.", proof: "Visual Check", trainerNotes: "Razors/Deo in lockers." },
                { id: "FR-HR-16", description: "Conduct 'Code Red' verbal quiz.", priority: "High", riskLevel: "High", consequence: "Emergency protocol failure.", proof: "Quiz Log", trainerNotes: "Ask random staff daily." },
                { id: "FR-HR-17", description: "Verify 'Sexual Harassment' policy post.", priority: "High", riskLevel: "High", consequence: "Legal liability/Toxic culture.", proof: "Photo", trainerNotes: "Display in staff room." },
                { id: "FR-HR-18", description: "Audit 'Uniform Laundry' cycle time.", priority: "Low", riskLevel: "Low", consequence: "Dirty clothes.", proof: "Laundry Log", trainerNotes: "Target < 24h turnaround." },
                { id: "FR-HR-19", description: "Final monthly HR matrix sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of admin control.", proof: "Signed Matrix", trainerNotes: "Submit to GM." }
            ]
        },
        {
            title: "IT & POS Integrity",
            department: "Technical",
            frequency: "Weekly",
            role: "Technical Lead",
            summary: "Protects the digital backbone.",
            icon: "laptop",
            tasks: [
                { id: "FR-IT-01", description: "Test POS backup and internet failover.", priority: "High", riskLevel: "High", consequence: "Inability to bill during peak hours.", proof: "Test Note", trainerNotes: "Test with main router off." },
                { id: "FR-IT-02", description: "Guest Wi-Fi Speedtest: Public zones.", priority: "Medium", riskLevel: "Low", consequence: "Negative business reviews.", proof: "Speedtest App", trainerNotes: "Target > 20Mbps." },
                { id: "FR-IT-03", description: "AC Filter cleaning / Lobby temp audit.", priority: "Medium", riskLevel: "Low", consequence: "Guest discomfort/high bills.", proof: "Maint Log", trainerNotes: "Target exactly 23°C." },
                { id: "FR-IT-04", description: "Backup Generator fuel/load test.", priority: "High", riskLevel: "High", consequence: "Total blackout/lost sales.", proof: "Start-test Log", trainerNotes: "Run 10 mins every Sunday." },
                { id: "FR-IT-05", description: "KDS/Digital Menu screen functionality check.", priority: "Medium", riskLevel: "Low", consequence: "Lost kitchen orders.", proof: "Visual Test", trainerNotes: "Reboot routers before weekend." },
                { id: "FR-IT-06", description: "Dining area fused bulb audit.", priority: "Low", riskLevel: "Low", consequence: "Damaged brand ambiance.", proof: "Walkthrough", trainerNotes: "Check accent lights." },
                { id: "FR-IT-07", description: "Plumbing leak / Kitchen drainage check.", priority: "Medium", riskLevel: "Medium", consequence: "Hygiene risk.", proof: "Maint Note", trainerNotes: "Use enzymatic drain cleaner." },
                { id: "FR-IT-08", description: "Aggregator Tablet battery health audit.", priority: "Medium", riskLevel: "Low", consequence: "Store shows 'Closed' falsely.", proof: "App Check", trainerNotes: "Replace frayed cables." },
                { id: "FR-IT-09", description: "Exhaust hood 'Tissue-test' for suction.", priority: "High", riskLevel: "Medium", consequence: "Excess heat/smoke.", proof: "Suction Test", trainerNotes: "Hood must hold paper sheet." },
                { id: "FR-IT-10", description: "Outdoor signage timer check.", priority: "Low", riskLevel: "Low", consequence: "Low walk-in visibility.", proof: "Photo at Night", trainerNotes: "Set sunset-to-midnight." },
                { id: "FR-IT-11", description: "Sound system zone balance audit.", priority: "Low", riskLevel: "Low", consequence: "Unpleasant audio.", proof: "Volume Check", trainerNotes: "Target < 65dB in dining." },
                { id: "FR-IT-12", description: "RO water TDS test (Target < 150).", priority: "High", riskLevel: "High", consequence: "Poor beverage taste.", proof: "TDS Reading", trainerNotes: "Check pre-filter pressure." },
                { id: "FR-IT-13", description: "Fridge coil vacuuming log.", priority: "Medium", riskLevel: "Low", consequence: "Reduced efficiency.", proof: "Visual Audit", trainerNotes: "Do once every 30 days." },
                { id: "FR-IT-14", description: "Intercom dial-test.", priority: "Low", riskLevel: "Low", consequence: "Communication gap.", proof: "Test Call", trainerNotes: "Ensure 100% clear audio." },
                { id: "FR-IT-15", description: "Gas Leak Detector battery check.", priority: "High", riskLevel: "High", consequence: "Undetected gas buildup.", proof: "Alarm Test", trainerNotes: "Replace batteries every 6m." },
                { id: "FR-IT-16", description: "Table base wobbling audit.", priority: "Low", riskLevel: "Low", consequence: "Immediate guest annoyance.", proof: "Visual Audit", trainerNotes: "Check all 4 feet." },
                { id: "FR-IT-17", description: "Server Room AC (Target 20C).", priority: "High", riskLevel: "High", consequence: "PMS/Data fail.", proof: "Temp Reading", trainerNotes: "Check backup split-unit." },
                { id: "FR-IT-18", description: "Review P1 breakdown TAT for shift.", priority: "High", riskLevel: "Low", consequence: "Loss of focus.", proof: "Job Log", trainerNotes: "Target P1 fix in < 30m." },
                { id: "FR-IT-19", description: "Final Technical sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of maintenance control.", proof: "Signed Log", trainerNotes: "Report parts needed to Owner." }
            ]
        },
        {
            title: "Marketing Activation",
            department: "Admin",
            frequency: "Daily",
            role: "Customer Experience Lead",
            summary: "Governs local branch promotions.",
            icon: "megaphone",
            tasks: [
                { id: "FR-MKT-01", description: "Log current promotional materials against schedule.", priority: "Medium", riskLevel: "Low", consequence: "Missed sales opportunities.", proof: "Campaign Log", trainerNotes: "Replace expired posters immediately." },
                { id: "FR-MKT-02", description: "Reply to Google Maps reviews < 24h.", priority: "High", riskLevel: "Medium", consequence: "Ranking drop.", proof: "Digital Dashboard", trainerNotes: "Address 1-star reviews first." },
                { id: "FR-MKT-03", description: "Social Media: Answer all DMs < 30m.", priority: "Medium", riskLevel: "Low", consequence: "Lost booking revenue.", proof: "Inbox Status", trainerNotes: "Confirm via WhatsApp." },
                { id: "FR-MKT-04", description: "Visual audit of tent cards/posters.", priority: "Low", riskLevel: "Low", consequence: "Inconsistent promo messaging.", proof: "Visual Audit", trainerNotes: "Replace torn posters." },
                { id: "FR-MKT-05", description: "Aggregator price sync check (Swiggy/Zomato).", priority: "High", riskLevel: "Medium", consequence: "Customer disputes/Legal fail.", proof: "Price Match", trainerNotes: "Ensure markups are consistent." },
                { id: "FR-MKT-06", description: "Review daily feedback trend for shift.", priority: "Medium", riskLevel: "Low", consequence: "Undetected quality drop.", proof: "Trend Log", trainerNotes: "Highlight recurring complaints." },
                { id: "FR-MKT-07", description: "Loyalty QR code scan test.", priority: "Low", riskLevel: "Low", consequence: "Failure to capture guest data.", proof: "Scan Test", trainerNotes: "Test with personal mobile." },
                { id: "FR-MKT-08", description: "Identify Bday/Anniv bookings for day.", priority: "Medium", riskLevel: "Low", consequence: "Missed delight opportunity.", proof: "Reservation Log", trainerNotes: "Notify GM to greet celebrant." },
                { id: "FR-MKT-09", description: "Aggregator competitor promo audit.", priority: "Low", riskLevel: "Low", consequence: "Inability to adapt.", proof: "Competitor Note", trainerNotes: "Check portals for latest deals." },
                { id: "FR-MKT-10", description: "Music playlist daypart match.", priority: "Low", riskLevel: "Low", consequence: "Wrong energy for ambiance.", proof: "Volume Check", trainerNotes: "High-energy lunch; chill dinner." },
                { id: "FR-MKT-11", description: "Influencer visit prep briefing.", priority: "Medium", riskLevel: "Low", consequence: "Poor PR content.", proof: "PR Calendar", trainerNotes: "Brief GM on preferences." },
                { id: "FR-MKT-12", description: "Email/SMS blast link test.", priority: "Low", riskLevel: "Low", consequence: "Wasted marketing spend.", proof: "Campaign Log", trainerNotes: "Test links before sending all." },
                { id: "FR-MKT-13", description: "Specials photo for Social Media.", priority: "Low", riskLevel: "Low", consequence: "Unappetizing content.", proof: "Camera Roll", trainerNotes: "Use natural light only." },
                { id: "FR-MKT-14", description: "Web booking flow 'Confirmation' test.", priority: "High", riskLevel: "Medium", consequence: "Systemic booking barrier.", proof: "Booking Test", trainerNotes: "Verify email is received." },
                { id: "FR-MKT-15", description: "Uniform logo alignment audit.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution.", proof: "Visual Check", trainerNotes: "Name-tags must be straight." },
                { id: "FR-MKT-16", description: "Local news/Press mention review.", priority: "Low", riskLevel: "Low", consequence: "Missed PR amplification.", proof: "News Check", trainerNotes: "Share positive PR on social." },
                { id: "FR-MKT-17", description: "Holiday decor 100% completion check.", priority: "Low", riskLevel: "Low", consequence: "Lack of seasonal energy.", proof: "Visual Check", trainerNotes: "Complete before opening." },
                { id: "FR-MKT-18", description: "Gift Voucher redemption ID check.", priority: "Medium", riskLevel: "Medium", consequence: "Fraudulent voucher usage.", proof: "Voucher Match", trainerNotes: "Reconcile vs master list." },
                { id: "FR-MKT-19", description: "Final Digital Reputation Sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of ORM governance.", proof: "Signed Dashboard", trainerNotes: "Submit feedback report to GM." }
            ]
        },
        {
            title: "Supply Chain Audits",
            department: "Logistics",
            frequency: "Daily",
            role: "Logistics Lead",
            summary: "Ensures sourcing integrity and first impression command.",
            icon: "truck",
            tasks: [
                { id: "FR-SUP-01", description: "Audit incoming stock against approved vendor list.", priority: "High", riskLevel: "High", consequence: "Compromised product and legal risk.", proof: "Receiving Note", trainerNotes: "Unauthorized vendors = red alert." },
                { id: "FR-SUP-02", description: "Vendor Receiving: Reconcile weight.", priority: "Medium", riskLevel: "Medium", consequence: "Paying for missing stock.", proof: "Scale Note", trainerNotes: "Reject variance > 2%." },
                { id: "FR-SUP-03", description: "Check temp of incoming high-risk perishables.", priority: "High", riskLevel: "High", consequence: "Accepting compromised stock.", proof: "Receiving Log", trainerNotes: "Reject if temp > 7°C." },
                { id: "FR-SUP-04", description: "Audit 'Expiring Stock' (3-day window).", priority: "High", riskLevel: "Medium", consequence: "Inventory waste.", proof: "Expiry Log", trainerNotes: "Move to LSM promo list." },
                { id: "FR-SUP-05", description: "Verify vendor FSSAI for perishables.", priority: "High", riskLevel: "High", consequence: "Legal liability.", proof: "License File", trainerNotes: "Renew repository every 6m." },
                { id: "FR-SUP-06", description: "Inspect back-alley waste bins.", priority: "Medium", riskLevel: "Medium", consequence: "Pest risk/Odors.", proof: "Cleaning Log", trainerNotes: "Bins must be closed." },
                { id: "FR-SUP-07", description: "Reconcile delivery fuel expense claims.", priority: "Medium", riskLevel: "Medium", consequence: "Internal revenue loss.", proof: "Voucher Reconcile", trainerNotes: "Match vs Odometer." },
                { id: "FR-SUP-08", description: "Verify vendor attendance logs.", priority: "Low", riskLevel: "Low", consequence: "Paying for unrendered work.", proof: "Log Review", trainerNotes: "Deduct for late arrivals." },
                { id: "FR-SUP-09", description: "Audit outsourced HK staff ID cards.", priority: "High", riskLevel: "High", consequence: "Unauthorized person risk.", proof: "Patrol Log", trainerNotes: "Badges must be chest-high." },
                { id: "FR-SUP-10", description: "Verify vendor invoice math checks.", priority: "Low", riskLevel: "Low", consequence: "Cumulative loss.", proof: "Ledger Audit", trainerNotes: "Spot-check 5% monthly." },
                { id: "FR-SUP-11", description: "Check loading bay lock integrity.", priority: "High", riskLevel: "High", consequence: "After-hours theft.", proof: "Lock Audit", trainerNotes: "Keys to GM nightly." },
                { id: "FR-SUP-12", description: "Audit staff break-room drainage.", priority: "Low", riskLevel: "Low", consequence: "Unhygienic staff zone.", proof: "Cleaning Note", trainerNotes: "Buff mirrors daily." },
                { id: "FR-SUP-13", description: "Review P1 vendor service TAT.", priority: "Medium", riskLevel: "Low", consequence: "Delayed repairs.", proof: "SLA Match", trainerNotes: "Penalty for > 4h delay." },
                { id: "FR-SUP-14", description: "Check availability of spare car/bike keys.", priority: "Low", riskLevel: "Medium", consequence: "Logistics delay crisis.", proof: "Vault Inventory", trainerNotes: "Secure in main safe." },
                { id: "FR-SUP-15", description: "Storage height check: > 6 inches off floor.", priority: "Medium", riskLevel: "Low", consequence: "Pest nesting risk.", proof: "Visual Check", trainerNotes: "No wooden pallets in prep." },
                { id: "FR-SUP-16", description: "Verify FIFO rotation in dry store.", priority: "High", riskLevel: "High", consequence: "Serve expired product.", proof: "Visual Note", trainerNotes: "Check date labels daily." },
                { id: "FR-SUP-17", description: "Inspect delivery rider rain-gear availability.", priority: "Medium", riskLevel: "Low", consequence: "Halt during monsoon.", proof: "Visual Check", trainerNotes: "Ensure 100% kits." },
                { id: "FR-SUP-18", description: "Audit 'Inventory Waste' group trend.", priority: "Medium", riskLevel: "Medium", consequence: "Profit leakage.", proof: "Waste Ledger", trainerNotes: "Target waste < 1% sales." },
                { id: "FR-SUP-19", description: "Final shift Logistics sign-off.", priority: "High", riskLevel: "Low", consequence: "Incomplete handover.", proof: "Signed Summary", trainerNotes: "Brief GM on stockouts." }
            ]
        }
    ]
};

    