
import type { PremiumPack } from "@/lib/premium-packs";

export const healthcare_and_hospital_operations: PremiumPack = {
    id: 'healthcare_and_hospital_operations',
    title: "Hospital Operating System",
    priceINR: 5999,
    priceUSD: 79,
    paymentId: 'pl_RaWEBHhFLQENxC',
    lemonSqueezyUrl: 'https://moremeets.lemonsqueezy.com/buy/129cb25a-b177-4a6d-a1bf-d8fafc24a09d',
    category: "Healthcare",
    description: "The Sovereign v9.0 clinical engine. Hardening 200 technical control points from WHO Surgical Safety to Mass Casualty protocols.",
    heroHeadline: "Zero-Risk Medical Operations. Audit-Ready.",
    heroSubheadline: "Standardize clinical and operational governance across every department in your facility with a logically-aware data engine.",
    pricingUrgency: "A single clinical error or one NABH/JCI audit failure costs 1000x more than this system.",
    consultingAnchor: 15000,
    icon: "hospital",
    badgeText: "V9.0 SOVEREIGN",
    badgeVariant: "destructive",
    whoIsItFor: ["Medical Directors", "Hospital COOs", "Nursing Superintendents", "Quality Heads", "Admin Directors"],
    sampleItems: [
        { text: "<strong>Clinical Safety (WHO)</strong>: Pre-incision time-outs and dual-verification for high-alert drugs.", icon: "shield-check" },
        { text: "<strong>TPA & Insurance Shield</strong>: 4-hour pre-auth pulse and unbilled consumable reconciliation.", icon: "banknote" },
        { text: "<strong>Emergency & Mass Casualty</strong>: Disaster triage protocols and ambulance fleet vitals.", icon: "ambulance" }
    ],
    checklists: [
        {
            title: "Clinical Governance",
            department: "Clinical",
            frequency: "Weekly",
            role: "COO / Owner",
            summary: "High-level risk and disaster readiness oversight.",
            icon: "crown",
            tasks: [
                { id: "H-EXE-01", description: "Review Sentinel Event Log root causes.", priority: "High", riskLevel: "High", consequence: "Recurring fatal errors.", proof: "Log Audit", trainerNotes: "Check near-miss reporting frequency." },
                { id: "H-EXE-02", description: "Test 'Mass Casualty' siren and command center.", priority: "High", riskLevel: "High", consequence: "Chaos during group accidents.", proof: "Drill Log", trainerNotes: "Verify backup radio comms." },
                { id: "H-EXE-03", description: "Audit Consultant Registration validity.", priority: "High", riskLevel: "High", consequence: "Criminal institutional liability.", proof: "Registry Audit", trainerNotes: "Cross-check State Council portal." },
                { id: "H-EXE-04", description: "Review HAI Infection rates vs benchmarks.", priority: "High", riskLevel: "High", consequence: "Audit failure/High patient stay.", proof: "Infection Log", trainerNotes: "Target HAI < 1% per 1000 days." },
                { id: "H-EXE-05", description: "Verify Indemnity Insurance for Consultants.", priority: "High", riskLevel: "High", consequence: "Uncovered litigation payout.", proof: "Policy File", trainerNotes: "Check expiry 60 days early." },
                { id: "H-EXE-06", description: "Audit Mortality Review Committee minutes.", priority: "High", riskLevel: "High", consequence: "Hidden clinical trends.", proof: "Minutes File", trainerNotes: "Target review in < 15 days of event." },
                { id: "H-EXE-07", description: "Verify 'Code Blue' response TAT scores.", priority: "High", riskLevel: "High", consequence: "Resuscitation failure (Fatal).", proof: "Code Log", trainerNotes: "Target response < 3 minutes." },
                { id: "H-EXE-08", description: "Review Blood Bank cross-match audit.", priority: "High", riskLevel: "High", consequence: "Fatal transfusion reaction.", proof: "Audit Sheet", trainerNotes: "Check dual-sign off logs." },
                { id: "H-EXE-09", description: "Check Clinical Research Ethics approvals.", priority: "Medium", riskLevel: "High", consequence: "Legal research shutdown.", proof: "Ethics File", trainerNotes: "Must have active IRB ID." },
                { id: "H-EXE-10", description: "Audit High-Alert Medication error trend.", priority: "High", riskLevel: "High", consequence: "Fatal patient poisoning.", proof: "Error Log", trainerNotes: "Check double-verification pulse." },
                { id: "H-EXE-11", description: "Verify Medical Records (MRD) completion TAT.", priority: "Medium", riskLevel: "Low", consequence: "NABH audit failure.", proof: "MRD Report", trainerNotes: "Target completion < 24h of discharge." },
                { id: "H-EXE-12", description: "Review Bio-Medical Waste NOC validity.", priority: "High", riskLevel: "High", consequence: "Environmental sealing.", proof: "NOC Certificate", trainerNotes: "Renew 90 days pre-expiry." },
                { id: "H-EXE-13", description: "Audit OT Sterility (Spore test) logs.", priority: "High", riskLevel: "High", consequence: "Post-op sepsis outbreak.", proof: "Spore Report", trainerNotes: "Test every Saturday night." },
                { id: "H-EXE-14", description: "Review Patient Fallout (Transfer out) stats.", priority: "Low", riskLevel: "Medium", consequence: "Loss of institutional trust.", proof: "Transfer Log", trainerNotes: "Analyze clinical gaps weekly." },
                { id: "H-EXE-15", description: "Audit Professional Privilege matrix.", priority: "Medium", riskLevel: "Medium", consequence: "Consultants performing unapproved surgery.", proof: "Matrix File", trainerNotes: "Updated vs latest training." },
                { id: "H-EXE-16", description: "Verify Organ Transplant license status.", priority: "High", riskLevel: "High", consequence: "Criminal legal shutdown.", proof: "License File", trainerNotes: "Display at main reception." },
                { id: "H-EXE-17", description: "Review Radiation Safety (AERB) badges.", priority: "High", riskLevel: "High", consequence: "Staff cancer risk/Lawsuits.", proof: "TLD Report", trainerNotes: "Change badges quarterly." },
                { id: "H-EXE-18", description: "Audit Disaster Backup Server sync.", priority: "High", riskLevel: "High", consequence: "Total loss of medical history.", proof: "System Log", trainerNotes: "Cloud sync test Mondays." },
                { id: "H-EXE-19", description: "Check status of 'Near-Miss' rewards.", priority: "Low", riskLevel: "Low", consequence: "Hidden safety culture.", proof: "HR Note", trainerNotes: "Reward staff for reporting errors." },
                { id: "H-EXE-20", description: "Review monthly 'Revenue leakage' audits.", priority: "Medium", riskLevel: "Medium", consequence: "Financial instability.", proof: "Audit Summary", trainerNotes: "Match billable vs consumable." },
                { id: "H-EXE-21", description: "Verify 'Code Pink' (Abduction) drills.", priority: "High", riskLevel: "High", consequence: "Infant theft disaster.", proof: "Drill File", trainerNotes: "Lockdown test at 2 PM." },
                { id: "H-EXE-22", description: "Audit Consultant Contract AMCs.", priority: "Low", riskLevel: "Low", consequence: "Legal fee disputes.", proof: "Contract File", trainerNotes: "Renew 30 days early." },
                { id: "H-EXE-23", description: "Final weekly Governance sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of clinical oversight.", proof: "Signed Matrix", trainerNotes: "Submit to Board." },
                { id: "H-EXE-24", description: "Review Patient Grievance root causes.", priority: "High", riskLevel: "Low", consequence: "Viral reputation damage.", proof: "Feedback Dashboard", trainerNotes: "Resolve all < 48h." },
                { id: "H-EXE-25", description: "Audit TPA Payout TAT trend.", priority: "Medium", riskLevel: "Low", consequence: "Cash flow crisis.", proof: "Finance Chart", trainerNotes: "Compare vs SLA targets." }
            ]
        },
        {
            title: "ER, ICU & Ward Command",
            department: "Operations",
            frequency: "Daily",
            role: "General Manager",
            summary: "Critical triage and bedside command.",
            icon: "heart-pulse",
            tasks: [
                { id: "H-ER-01", description: "Emergency Triage TAT (Target <5m).", priority: "High", riskLevel: "High", consequence: "Death in waiting area.", proof: "TAT Log", trainerNotes: "Must see MD first-touch." },
                { id: "H-ER-02", description: "Crash Cart: Lock-seal and O2 check.", priority: "High", riskLevel: "High", consequence: "Failed resuscitation.", proof: "Seal Check", trainerNotes: "Replace cylinder < 1000 PSI." },
                { id: "H-ER-03", description: "Bedside Handover: SBAR protocol audit.", priority: "High", riskLevel: "High", consequence: "Critical vitals info loss.", proof: "Handover Log", trainerNotes: "Oral report at patient bed." },
                { id: "H-ER-04", description: "High-Fall Risk: verify side-rails.", priority: "High", riskLevel: "Medium", consequence: "Patient injury negligence.", proof: "Visual Check", trainerNotes: "Mandatory for 65+ age." },
                { id: "H-ER-05", description: "Ambulance vitals: AED/O2 levels.", priority: "High", riskLevel: "High", consequence: "Death during transit.", proof: "Fleet Check", trainerNotes: "Run engine test daily." },
                { id: "H-ER-06", description: "Audit ICU nurse-to-patient ratio.", priority: "High", riskLevel: "High", consequence: "Unmonitored patient decline.", proof: "Roster Log", trainerNotes: "Target 1:1 for ventilated." },
                { id: "H-ER-07", description: "Check Ventilator backup battery charge.", priority: "High", riskLevel: "High", consequence: "Death during power fail.", proof: "System Screen", trainerNotes: "Run on batt for 5 mins." },
                { id: "H-ER-08", description: "Verify MAR sheet 100% completion.", priority: "High", riskLevel: "High", consequence: "Wrong drug/dosage error.", proof: "MAR Audit", trainerNotes: "No blanks allowed." },
                { id: "H-ER-09", description: "Inspect ward IV sites for infection.", priority: "High", riskLevel: "Medium", consequence: "Hospital acquired sepsis.", proof: "Audit Sheet", trainerNotes: "Replace cannulas every 72h." },
                { id: "H-ER-10", description: "Check ER stretcher availability pulse.", priority: "Medium", riskLevel: "Low", consequence: "Blocked ambulance turnaround.", proof: "Visual Check", trainerNotes: "Keep min 2 stretches at bay." },
                { id: "H-ER-11", description: "Verify Code Blue button functionality.", priority: "High", riskLevel: "High", consequence: "No response during arrest.", proof: "Test Log", trainerNotes: "Rotate ward test zones." },
                { id: "H-ER-12", description: "Check infant warmer temp calibration.", priority: "High", riskLevel: "High", consequence: "Hypothermia in NICU.", proof: "Calibration Log", trainerNotes: "Target 36.5C." },
                { id: "H-ER-13", description: "Audit Ward RO water for patients.", priority: "Medium", riskLevel: "Medium", consequence: "Waterborne infection spread.", proof: "TDS Reading", trainerNotes: "Target < 100ppm." },
                { id: "H-ER-14", description: "Verify Suction Unit focal point/jars.", priority: "High", riskLevel: "High", consequence: "Aspiration death (Fatal).", proof: "Visual Check", trainerNotes: "Test vacuum pressure daily." },
                { id: "H-ER-15", description: "Check PPE availability in isolation.", priority: "High", riskLevel: "High", consequence: "Outbreak of viral disease.", proof: "Stock Audit", trainerNotes: "N95 masks min 100 count." },
                { id: "H-ER-16", description: "Verify Dialysis unit water parameters.", priority: "High", riskLevel: "High", consequence: "Patient blood contamination.", proof: "Lab Report", trainerNotes: "Target endo-toxin < 0.25." },
                { id: "H-ER-17", description: "Audit Ward staff grooming briefing.", priority: "Low", riskLevel: "Low", consequence: "Poor brand professionalism.", proof: "Briefing Log", trainerNotes: "Check ID/Nails/Hairnets." },
                { id: "H-ER-18", description: "Check availability of clean bedsheets.", priority: "Medium", riskLevel: "Low", consequence: "Unhygienic patient experience.", proof: "Stock Note", trainerNotes: "Check for graying monthly." },
                { id: "H-ER-19", description: "Verify high-risk protein meal delivery.", priority: "High", riskLevel: "Medium", consequence: "Delayed wound recovery.", proof: "Food Log", trainerNotes: "Match vs MD diet order." },
                { id: "H-ER-20", description: "Audit MRD file handover shift.", priority: "Medium", riskLevel: "Low", consequence: "Missing diagnostic records.", proof: "Handover Log", trainerNotes: "Verify physical file count." },
                { id: "H-ER-21", description: "Check Ward AC/Ventilation humidity.", priority: "Low", riskLevel: "Medium", consequence: "Bacterial mold growth.", proof: "Humidity Log", trainerNotes: "Target 40-60% RH." },
                { id: "H-ER-22", description: "Verify nurse call-bell response time.", priority: "Medium", riskLevel: "Low", consequence: "Patient frustration scores.", proof: "System Log", trainerNotes: "Target < 60 seconds." },
                { id: "H-ER-23", description: "Check availability of morgue trolleys.", priority: "Low", riskLevel: "Low", consequence: "Operational delays.", proof: "Visual Check", trainerNotes: "Keep sanitized 24/7." },
                { id: "H-ER-24", description: "Verify 'Quiet Zone' lobby policy.", priority: "Low", riskLevel: "Low", consequence: "Poor patient rest environment.", proof: "Walkthrough", trainerNotes: "Check decibel levels night." },
                { id: "H-ER-25", description: "Final daily Operations sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of duty control.", proof: "Signed Log", trainerNotes: "Brief GM on arrivals." }
            ]
        },
        {
            title: "TPA & Insurance Shield",
            department: "Finance",
            frequency: "Daily",
            role: "Finance & Cashier",
            summary: "Revenue protection and pre-auth governance.",
            icon: "banknote",
            tasks: [
                { id: "H-TPA-01", description: "TPA Pre-Auth Pulse: Verify status IPs.", priority: "High", riskLevel: "Medium", consequence: "Claim denial after treatment.", proof: "Portal Sync", trainerNotes: "Target approval in < 4h." },
                { id: "H-TPA-02", description: "Unbilled Consumable Reconcile: Ward.", priority: "High", riskLevel: "Medium", consequence: "Silent profit leakage.", proof: "Match Sheet", trainerNotes: "Audit 10% discharge files." },
                { id: "H-TPA-03", description: "Insurance Query Pulse: < 24h resolve.", priority: "Medium", riskLevel: "Low", consequence: "Delayed payment/Cash crunch.", proof: "Query Log", trainerNotes: "Escalate to MD instantly." },
                { id: "H-TPA-04", description: "POS digital settlements vs bank.", priority: "High", riskLevel: "High", consequence: "Cashier-driven theft.", proof: "Settlement Log", trainerNotes: "Report variance > ₹100." },
                { id: "H-TPA-05", description: "Verify elective surgery deposits.", priority: "High", riskLevel: "Low", consequence: "Post-surgery recovery disputes.", proof: "Deposit Log", trainerNotes: "Target 80% estimated cost." },
                { id: "H-TPA-06", description: "Audit 'Free-Bed' quota compliance.", priority: "High", riskLevel: "High", consequence: "Legal penalty/Regulatory fines.", proof: "Quota Register", trainerNotes: "Verify Income certificates." },
                { id: "H-TPA-07", description: "Match pharmacy bills vs nurse return.", priority: "Medium", riskLevel: "Medium", consequence: "Incorrect inventory counts.", proof: "Return Log", trainerNotes: "Credit patient bill instantly." },
                { id: "H-TPA-08", description: "Verify 100% sign on MRD files.", priority: "Medium", riskLevel: "Low", consequence: "Claim rejection via signatures.", proof: "Audit Note", trainerNotes: "Check physician stamps." },
                { id: "H-TPA-09", description: "Audit Corporate Credit vouchers.", priority: "Medium", riskLevel: "Low", consequence: "Unrealized receivables.", proof: "Voucher Match", trainerNotes: "Check employee ID validity." },
                { id: "H-TPA-10", description: "Verify Cash-to-Bank witnessed seal.", priority: "High", riskLevel: "High", consequence: "Internal revenue theft.", proof: "Bank Slip", trainerNotes: "Deposit by 11 AM next day." },
                { id: "H-TPA-11", description: "Audit Voided billing transactions.", priority: "High", riskLevel: "Medium", consequence: "Bill manipulation leakage.", proof: "Void Log", trainerNotes: "Every void needs HOD sign." },
                { id: "H-TPA-12", description: "Check status of TPA desk staffing.", priority: "Low", riskLevel: "Low", consequence: "Admission delays.", proof: "Roster Check", trainerNotes: "Backups for lunch breaks." },
                { id: "H-TPA-13", description: "Verify GST input credit on AMCs.", priority: "Low", riskLevel: "Low", consequence: "Tax inefficiency.", proof: "Ledger Audit", trainerNotes: "Check vendor GSTIN match." },
                { id: "H-TPA-14", description: "Audit staff payroll OT hours.", priority: "Medium", riskLevel: "Medium", consequence: "HR budget blowouts.", proof: "OT Tracker", trainerNotes: "HOD pre-approval needed." },
                { id: "H-TPA-15", description: "Check stationary stock (IPD forms).", priority: "Low", riskLevel: "Low", consequence: "Administrative halt.", proof: "Supply Note", trainerNotes: "Min 1 week buffer stock." },
                { id: "H-TPA-16", description: "Verify medical insurance renewals.", priority: "Medium", riskLevel: "Low", consequence: "Uncovered liability claims.", proof: "Policy File", trainerNotes: "Renew 30 days early." },
                { id: "H-TPA-17", description: "Audit 'Fixed Asset' tags in Ward.", priority: "Low", riskLevel: "Low", consequence: "Lost institutional assets.", proof: "Asset Log", trainerNotes: "Beds must have physical tags." },
                { id: "H-TPA-18", description: "Review daily sales summary trend.", priority: "Low", riskLevel: "Low", consequence: "Underperforming diagnostics.", proof: "Sales Report", trainerNotes: "Compare vs previous week avg." },
                { id: "H-TPA-19", description: "Verify vendor TDS deductions.", priority: "Medium", riskLevel: "Medium", consequence: "Tax non-conformance.", proof: "TDS Register", trainerNotes: "Check pan status monthly." },
                { id: "H-TPA-20", description: "Check availability of bill folders.", priority: "Low", riskLevel: "Low", consequence: "Poor billing presentation.", proof: "Stock Audit", trainerNotes: "Clean with alcohol wipe." },
                { id: "H-TPA-21", description: "Audit 'Discount' code usage pulse.", priority: "High", riskLevel: "Medium", consequence: "Margin erosion.", proof: "POS Report", trainerNotes: "Target < 3% of revenue." },
                { id: "H-TPA-22", description: "Verify 100% KYC for all admissions.", priority: "High", riskLevel: "High", consequence: "Legal liability for fraud.", proof: "ID Audit", trainerNotes: "Must match patient name." },
                { id: "H-TPA-23", description: "Final Shift Finance sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of fiscal control.", proof: "Signed summary", trainerNotes: "Attach exception reports." },
                { id: "H-TPA-24", description: "Audit Cafeteria gross settlements.", priority: "Low", riskLevel: "Low", consequence: "Untracked F&B leakage.", proof: "Log Match", trainerNotes: "Reconcile vs bank capture." },
                { id: "H-TPA-25", description: "Verify IPD advance refund logs.", priority: "Medium", riskLevel: "Low", consequence: "Guest recovery friction.", proof: "Refund Note", trainerNotes: "Return via original mode." }
            ]
        },
        {
            title: "Cleaning, Waste & Safety",
            department: "Safety",
            frequency: "Hourly",
            role: "EHS Officer",
            summary: "Bio-hazard and facility sanitation command.",
            icon: "sparkles",
            tasks: [
                { id: "H-WST-01", description: "Bio-waste: Verify segregation source.", priority: "High", riskLevel: "High", consequence: "Fines and infection spread.", proof: "Visual Audit", trainerNotes: "Check yellow bins daily." },
                { id: "H-WST-02", description: "Sharps: verify bins < 75% full.", priority: "High", riskLevel: "High", consequence: "Needle-stick injuries.", proof: "Visual Check", trainerNotes: "Do not shake bins." },
                { id: "H-WST-03", description: "Restroom Audit: 1-hour frequency.", priority: "High", riskLevel: "Low", consequence: "Negative CX scores.", proof: "Hourly Sheet", trainerNotes: "Check soap/sanitizer." },
                { id: "H-WST-04", description: "Fire Exit Pulse: Corridor clearance.", priority: "High", riskLevel: "High", consequence: "Fatal entrapment.", proof: "Patrol Log", trainerNotes: "Physically open every door." },
                { id: "H-WST-05", description: "Spill Kit Audit: Lab/OT availability.", priority: "High", riskLevel: "High", consequence: "Toxic fluid exposure.", proof: "Stock Check", trainerNotes: "Check goggles/bleach." },
                { id: "H-WST-06", description: "Verify pest-control bait stations.", priority: "Medium", riskLevel: "Low", consequence: "Infestation in sterile zone.", proof: "Pest Log", trainerNotes: "Target zero sightings." },
                { id: "H-WST-07", description: "Inspect OT fumigation logs.", priority: "High", riskLevel: "High", consequence: "Surgical infection outbreak.", proof: "Fumigation Sheet", trainerNotes: "Check daily for high-risk OTs." },
                { id: "H-WST-08", description: "Verify RO membrane backwash.", priority: "Low", riskLevel: "Medium", consequence: "Ineffective patient water.", proof: "System Log", trainerNotes: "Check pressure drop." },
                { id: "H-WST-09", description: "Audit laundry cycle temp (Target 70C).", priority: "High", riskLevel: "High", consequence: "Pathogen survival on linen.", proof: "Temp Reading", trainerNotes: "Check therm-tags daily." },
                { id: "H-WST-10", description: "Check status of solar hot water manifold.", priority: "Low", riskLevel: "Low", consequence: "Increased energy cost.", proof: "Visual Audit", trainerNotes: "Clean panels weekly." },
                { id: "H-WST-11", description: "Verify HVAC AC-filter clean schedule.", priority: "Medium", riskLevel: "Low", consequence: "Poor air quality/High bills.", proof: "Maint Log", trainerNotes: "Check Lobby at 23C." },
                { id: "H-WST-12", description: "Audit staff hand-sanitizer stations.", priority: "High", riskLevel: "Medium", consequence: "Infection transmission.", proof: "Refill Log", trainerNotes: "Check entry/exit points." },
                { id: "H-WST-13", description: "Inspect morgue hygiene and O2 manifold area.", priority: "High", riskLevel: "High", consequence: "Explosion risk/PR disaster.", proof: "Visual Check", trainerNotes: "No flammables near O2." },
                { id: "H-WST-14", description: "Verify emergency lighting battery run.", priority: "Medium", riskLevel: "High", consequence: "Darkness during Code Blue.", proof: "Test Note", trainerNotes: "Run 15 mins monthly." },
                { id: "H-WST-15", description: "Check STP water outlet purity test.", priority: "High", riskLevel: "High", consequence: "Environmental sealing.", proof: "Lab Report", trainerNotes: "Target BOD < 10." },
                { id: "H-WST-16", description: "Audit staff entry ID card visibility.", priority: "Low", riskLevel: "Low", consequence: "Security perimeter drift.", proof: "Patrol Log", trainerNotes: "Badges must be chest-high." },
                { id: "H-WST-17", description: "Verify kitchen exhaust grease level.", priority: "High", riskLevel: "High", consequence: "Kitchen fire risk.", proof: "Visual Audit", trainerNotes: "Clean ducts quarterly." },
                { id: "H-WST-18", description: "Check availability of 'Wet Floor' signs.", priority: "Medium", riskLevel: "Medium", consequence: "Slip-and-fall litigation.", proof: "Stock Note", trainerNotes: "Mandatory for all mopping." },
                { id: "H-WST-19", description: "Verify DG set diesel buffer (min 24h).", priority: "High", riskLevel: "High", consequence: "Total blackout death.", proof: "Fuel Log", trainerNotes: "Keep tank > 75% full." },
                { id: "H-WST-20", description: "Inspect back-alley for bio-waste leakage.", priority: "High", riskLevel: "High", consequence: "Public health hazard/Fines.", proof: "Walkthrough", trainerNotes: "Check yellow bag seals." },
                { id: "H-WST-21", description: "Audit security guard log entries.", priority: "Low", riskLevel: "Low", consequence: "Discipline drift.", proof: "Log Review", trainerNotes: "Entries must be hourly." },
                { id: "H-WST-22", description: "Check first-aid kits in non-clinical zones.", priority: "Low", riskLevel: "Low", consequence: "Staff injury liability.", proof: "Stock Audit", trainerNotes: "Check expiry dates." },
                { id: "H-WST-23", description: "Final nightly safety sign-off.", priority: "High", riskLevel: "Low", consequence: "Systemic risk gap.", proof: "Manager Initials", trainerNotes: "Physical perimeter touch." },
                { id: "H-WST-24", description: "Verify porch floodlight illumination.", priority: "Low", riskLevel: "Low", consequence: "Poor first-touch security.", proof: "Photo", trainerNotes: "Target Sunset-to-Sunrise." },
                { id: "H-WST-25", description: "Check availability of PPE masks at ER entry.", priority: "Medium", riskLevel: "Medium", consequence: "Airborne disease spread.", proof: "Stock Check", trainerNotes: "Provide free to arrivals." }
            ]
        },
        {
            title: "Clinical Training & Certs",
            department: "HR",
            frequency: "Monthly",
            role: "HR Manager",
            summary: "Staff competency and health compliance.",
            icon: "graduation-cap",
            tasks: [
                { id: "H-HR-01", description: "Verify active Nursing Registration IDs.", priority: "High", riskLevel: "High", consequence: "Criminal liability/Unlicensed care.", proof: "Cert Registry", trainerNotes: "No duty without active ID." },
                { id: "H-HR-02", description: "Audit BLS/ACLS roster certification.", priority: "High", riskLevel: "High", consequence: "Failure to life-support.", proof: "Matrix File", trainerNotes: "Renew 30 days pre-expiry." },
                { id: "H-HR-03", description: "Conduct 'Read-Back' verbal order drill.", priority: "High", riskLevel: "High", consequence: "Wrong drug/dose error.", proof: "Quiz Log", trainerNotes: "Test phonetic clarity." },
                { id: "H-HR-04", description: "Staff Health Pulse: verify med certs.", priority: "Medium", riskLevel: "Medium", consequence: "Infection spread to patients.", proof: "Med File", trainerNotes: "Includes stool tests." },
                { id: "H-HR-05", description: "Briefing grooming standards audit.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution.", proof: "Attendance Log", trainerNotes: "Check badges/nails." },
                { id: "H-HR-06", description: "Update 'Patient Safety' training matrix.", priority: "High", riskLevel: "Low", consequence: "Loss of safety culture.", proof: "Matrix File", trainerNotes: "Target 4h/month per person." },
                { id: "H-HR-07", description: "Audit new hire orientation completion.", priority: "Medium", riskLevel: "Low", consequence: "Early turnover/Confusion.", proof: "Folder Audit", trainerNotes: "Check safety module sign-off." },
                { id: "H-HR-08", description: "Verify NDAs signed by Consultants.", priority: "High", riskLevel: "High", consequence: "Loss of trade secrets/Data.", proof: "Signed File", trainerNotes: "Secure in HR vault." },
                { id: "H-HR-09", description: "Check availability of spare uniforms.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional hires.", proof: "Inventory Check", trainerNotes: "Min 2 sets per position." },
                { id: "H-HR-10", description: "Audit 'Overtime' vs budget benchmarks.", priority: "Medium", riskLevel: "Medium", consequence: "Payroll budget blowout.", proof: "OT Tracker", trainerNotes: "GM pre-approval needed." },
                { id: "H-HR-11", description: "Conduct 'Code Blue' verbal quiz.", priority: "High", riskLevel: "High", consequence: "Emergency protocol failure.", proof: "Quiz Log", trainerNotes: "Ask random staff daily." },
                { id: "H-HR-12", description: "Verify 'Sexual Harassment' policy post.", priority: "High", riskLevel: "High", consequence: "Legal liability/Toxic culture.", proof: "Photo", trainerNotes: "Display in staff room." },
                { id: "H-HR-13", description: "Review resignation exit comments.", priority: "Low", riskLevel: "Low", consequence: "Unaddressed churn root causes.", proof: "Exit Notes", trainerNotes: "Identify manager friction." },
                { id: "H-HR-14", description: "Check grooming kit availability.", priority: "Low", riskLevel: "Low", consequence: "Slipping standards.", proof: "Visual Check", trainerNotes: "Razors/Deo in lockers." },
                { id: "H-HR-15", description: "Verify 100% sign on 'Safety Policy'.", priority: "High", riskLevel: "Medium", consequence: "No legal action for breaches.", proof: "Signed Form", trainerNotes: "Include theft policies." },
                { id: "H-HR-16", description: "Audit staff break-room amenities.", priority: "Low", riskLevel: "Low", consequence: "Low morale.", proof: "Visual Check", trainerNotes: "Ensure drinking water active." },
                { id: "H-HR-17", description: "Inspect staff locker hygiene.", priority: "Low", riskLevel: "Low", consequence: "Pest risk in staff zone.", proof: "Cleaning Log", trainerNotes: "Open lockers Sundays." },
                { id: "H-HR-18", description: "Check first-aid responder roster.", priority: "High", riskLevel: "High", consequence: "Medical liability risk.", proof: "Roster Note", trainerNotes: "Min 1 certified/shift." },
                { id: "H-HR-19", description: "Review 'Training Satisfaction' survey.", priority: "Low", riskLevel: "Low", consequence: "Ineffective training spend.", proof: "Survey Note", trainerNotes: "Target > 80% positive." },
                { id: "H-HR-20", description: "Final monthly HR matrix sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of admin control.", proof: "Signed Matrix", trainerNotes: "Submit to GM." },
                { id: "H-HR-21", description: "Check payroll bank info accuracy.", priority: "Low", riskLevel: "Medium", consequence: "Staff pay delays.", proof: "Ledger Audit", trainerNotes: "Verify new account links." },
                { id: "H-HR-22", description: "Audit 'Uniform Laundry' cycle time.", priority: "Low", riskLevel: "Low", consequence: "Staff wearing dirty clothes.", proof: "Laundry Log", trainerNotes: "Target < 24h turnaround." },
                { id: "H-HR-23", description: "Verify active Certs for Engineers.", priority: "High", riskLevel: "High", consequence: "Fatal industrial accidents.", proof: "Cert Registry", trainerNotes: "Check LOTO/High-Volt IDs." },
                { id: "H-HR-24", description: "Conduct infection control refresher.", priority: "High", riskLevel: "High", consequence: "Outbreak of viral disease.", proof: "Training Log", trainerNotes: "Mandatory handwashing quiz." },
                { id: "H-HR-25", description: "Check availability of PPE stock in Ward.", priority: "High", riskLevel: "High", consequence: "Staff infection hazard.", proof: "Stock Sheet", trainerNotes: "Maintain 15-day buffer." }
            ]
        },
        {
            title: "Imaging, MEP & Engineering",
            department: "Technical",
            frequency: "Daily",
            role: "Technical Lead",
            summary: "Scanning and life-support asset governance.",
            icon: "wrench",
            tasks: [
                { id: "H-TEC-01", description: "OT/ICU UPS load-test and battery bank.", priority: "High", riskLevel: "High", consequence: "Patient death during blackout.", proof: "Voltage Log", trainerNotes: "Run 10-min test weekly." },
                { id: "H-TEC-02", description: "O2 Plant: Purity/Pressure log hourly.", priority: "High", riskLevel: "High", consequence: "Total supply failure (Fatal).", proof: "Digital Screen", trainerNotes: "Target purity > 93%." },
                { id: "H-TEC-03", description: "MRI/CT scan area radiation audit.", priority: "High", riskLevel: "High", consequence: "AERB non-compliance/Health risk.", proof: "TLD Report", trainerNotes: "Check lead apron integrity." },
                { id: "H-TEC-04", description: "Check RO water TDS for Dialysis.", priority: "High", riskLevel: "High", consequence: "Patient blood contamination.", proof: "TDS Reading", trainerNotes: "Target < 50 ppm." },
                { id: "H-TEC-05", description: "HIS/PACS server backup and cloud sync.", priority: "High", riskLevel: "High", consequence: "Irrecoverable medical history loss.", proof: "Backup Log", trainerNotes: "Check sync at 2 AM." },
                { id: "H-TEC-06", description: "OT ventilation air-change logs.", priority: "High", riskLevel: "High", consequence: "Surgical infection outbreak.", proof: "System Log", trainerNotes: "Target 20+ changes/hour." },
                { id: "H-TEC-07", description: "Verify vacuum pump pressure (ER/OT).", priority: "High", riskLevel: "High", consequence: "Aspiration death risk.", proof: "Gauge Log", trainerNotes: "Maintain min 400 mmHg." },
                { id: "H-TEC-08", description: "Check status of manifold room cylinders.", priority: "High", riskLevel: "High", consequence: "O2 stockout crisis.", proof: "Stock Sheet", trainerNotes: "Min 48h emergency reserve." },
                { id: "H-TEC-09", description: "Inspect server room split-AC units.", priority: "High", riskLevel: "High", consequence: "HIS server shutdown.", proof: "Temp Note", trainerNotes: "Target constant 20C." },
                { id: "H-TEC-10", description: "Verify AMC tags on MRI/CT machines.", priority: "Medium", riskLevel: "Low", consequence: "Legal service contract lapse.", proof: "Visual Audit", trainerNotes: "Check service due dates." },
                { id: "H-TEC-11", description: "Test emergency PA system volume.", priority: "Medium", riskLevel: "Medium", consequence: "Comm failure during crisis.", proof: "Sound Test", trainerNotes: "Check Stairwell zones." },
                { id: "H-TEC-12", description: "Check boiler temp for patient showers.", priority: "Medium", riskLevel: "Medium", consequence: "Thermal burns or cold shock.", proof: "Temp Log", trainerNotes: "Target 55C at source." },
                { id: "H-TEC-13", description: "Inspect elevator auto-rescue battery.", priority: "High", riskLevel: "High", consequence: "Patient trapped in lift.", proof: "Start-test Log", trainerNotes: "Test with weighted load." },
                { id: "H-TEC-14", description: "Audit LOTO permit for active repairs.", priority: "High", riskLevel: "High", consequence: "Fatal technician injury.", proof: "Permit File", trainerNotes: "No lock, No work." },
                { id: "H-TEC-15", description: "Verify CCTV monitor flicker status.", priority: "Low", riskLevel: "Low", consequence: "Missing visual evidence.", proof: "Visual Check", trainerNotes: "Replace cables if glitching." },
                { id: "H-TEC-16", description: "Check RO pre-filter pressure drop.", priority: "Low", riskLevel: "Medium", consequence: "Dialysis water shutdown.", proof: "Gauge Reading", trainerNotes: "Flush filters at > 1 bar diff." },
                { id: "H-TEC-17", description: "Inspect kitchen gas soap-bubble test.", priority: "High", riskLevel: "High", consequence: "Overnight fire risk.", proof: "Maint Note", trainerNotes: "Check manifold joints daily." },
                { id: "H-TEC-18", description: "Review P1 breakdown TAT for shift.", priority: "High", riskLevel: "Low", consequence: "Loss of engineering focus.", proof: "Job Log", trainerNotes: "Target P1 fix in < 30m." },
                { id: "H-TEC-19", description: "Check staff restroom drainage/hygiene.", priority: "Low", riskLevel: "Low", consequence: "Unhygienic staff zone.", proof: "Cleaning Note", trainerNotes: "Buff mirrors daily." },
                { id: "H-TEC-20", description: "Final Technical sign-off for shift.", priority: "High", riskLevel: "Low", consequence: "Loss of dept control.", proof: "Signed Log", trainerNotes: "Brief GM on major fails." },
                { id: "H-TEC-21", description: "Verify porch floodlight illumination.", priority: "Low", riskLevel: "Low", consequence: "Poor first-touch security.", proof: "Photo", trainerNotes: "Target Sunset-to-Sunrise." },
                { id: "H-TEC-22", description: "Audit security guard log entries.", priority: "Low", riskLevel: "Low", consequence: "Discipline drift.", proof: "Log Review", trainerNotes: "Entries must be hourly." },
                { id: "H-TEC-23", description: "Verify HIS database cloud sync.", priority: "High", riskLevel: "High", consequence: "Total loss of history.", proof: "Cloud Dashboard", trainerNotes: "Manual backup at 3 AM." },
                { id: "H-TEC-24", description: "Check availability of spare car keys.", priority: "Low", riskLevel: "Medium", consequence: "Ambulance delay crisis.", proof: "Vault Inventory", trainerNotes: "Secure in main safe." },
                { id: "H-TEC-25", description: "Inspect MRI coolant (Helium) level.", priority: "High", riskLevel: "High", consequence: "MRI Quench (Extreme cost).", proof: "System Screen", trainerNotes: "Target level > 65%." }
            ]
        },
        {
            title: "Reception, Queue & ORM",
            department: "Admin",
            frequency: "Daily",
            role: "Customer Experience Lead",
            summary: "Reputation and OPD pipeline command.",
            icon: "megaphone",
            tasks: [
                { id: "H-CX-01", description: "OPD Wait-Time Pulse: verify <30m.", priority: "Medium", riskLevel: "Low", consequence: "Patient walk-outs/Review drop.", proof: "Token Report", trainerNotes: "Alert GM if queue > 1h." },
                { id: "H-CX-02", description: "Reply to Google/Practo feedback <24h.", priority: "High", riskLevel: "Medium", consequence: "Reputation damage.", proof: "Dashboard", trainerNotes: "Address 1-star reviews first." },
                { id: "H-CX-03", description: "Doctor Arrival: Verify schedule match.", priority: "High", riskLevel: "Low", consequence: "Massive queue frustration.", proof: "Roster Match", trainerNotes: "Notify patients if MD > 15m late." },
                { id: "H-CX-04", description: "Social Media: Answer all DMs <30m.", priority: "Medium", riskLevel: "Low", consequence: "Lost revenue via unread inquiries.", proof: "Inbox Clear", trainerNotes: "Confirm via WhatsApp." },
                { id: "H-CX-05", description: "Check availability of patient water.", priority: "Low", riskLevel: "Low", consequence: "Poor patient experience scores.", proof: "Visual Check", trainerNotes: "Stock clean cups every 2h." },
                { id: "H-CX-06", description: "Verify lobby magazine/TV status.", priority: "Low", riskLevel: "Low", consequence: "Increased perceived wait time.", proof: "Walkthrough", trainerNotes: "Mute TV if noise > 60dB." },
                { id: "H-CX-07", description: "Audit Receptionist greeting tone.", priority: "Medium", riskLevel: "Low", consequence: "Negative brand first-touch.", proof: "Supervisor Obs", trainerNotes: "Mandatory eye contact + smile." },
                { id: "H-CX-08", description: "Review 'Discharge Feedback' trends.", priority: "Medium", riskLevel: "Low", consequence: "Undetected service decay.", proof: "Trend Log", trainerNotes: "Highlight top 3 complaints daily." },
                { id: "H-CX-09", description: "Verify Helpdesk staffing for rush hr.", priority: "High", riskLevel: "Low", consequence: "Lobby crowding panics.", proof: "Roster Check", trainerNotes: "Peak: 10 AM - 1 PM." },
                { id: "H-CX-10", description: "Check wheelchair availability at gate.", priority: "High", riskLevel: "Medium", consequence: "Patient distress/Liability.", proof: "Visual Audit", trainerNotes: "Min 5 wheelchairs always at porch." },
                { id: "H-CX-11", description: "Verify Google Maps 'Live Status'.", priority: "High", riskLevel: "Low", consequence: "Guests arrive to 'Closed' hospital.", proof: "Mobile Check", trainerNotes: "Update for holidays instantly." },
                { id: "H-CX-12", description: "Audit 'Patient Brochure' stock level.", priority: "Low", riskLevel: "Low", consequence: "Lost conversion for surgeries.", proof: "Supply Check", trainerNotes: "Min 100 sets of top 5 specialties." },
                { id: "H-CX-13", description: "Check in-house pharmacy queue TAT.", priority: "Medium", riskLevel: "Low", consequence: "Post-consultation frustration.", proof: "Audit Sheet", trainerNotes: "Target billing in < 10 mins." },
                { id: "H-CX-14", description: "Verify 'Guest Wi-Fi' portal login.", priority: "Low", riskLevel: "Low", consequence: "Poor patient stay scores.", proof: "Phone Test", trainerNotes: "Login must work in < 10s." },
                { id: "H-CX-15", description: "Audit 'Feedback QR Code' placement.", priority: "Low", riskLevel: "Low", consequence: "Low volume of audit data.", proof: "Visual Check", trainerNotes: "One code per bedside table." },
                { id: "H-CX-16", description: "Check ambiance: scent/temp in OPD.", priority: "Low", riskLevel: "Low", consequence: "Negative micro-impressions.", proof: "Daily Log", trainerNotes: "Keep zone at exactly 23C." },
                { id: "H-CX-17", description: "Review 'Doctor Review' volume trend.", priority: "Low", riskLevel: "Low", consequence: "Falling search authority.", proof: "Monthly Chart", trainerNotes: "Incentivize patient feedback." },
                { id: "H-CX-18", description: "Verify 100% reply to Social Comments.", priority: "Medium", riskLevel: "Low", consequence: "PR fire ignored.", proof: "Inbox Clear", trainerNotes: "Target < 4h response." },
                { id: "H-CX-19", description: "Audit 'Patient Journey' signage visibility.", priority: "Low", riskLevel: "Low", consequence: "Confused patients in corridors.", proof: "Walkthrough", trainerNotes: "Signage must be bilingual." },
                { id: "H-CX-20", description: "Final daily Reputation sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of ORM control.", proof: "Signed Dashboard", trainerNotes: "Submit feedback report to MD." },
                { id: "H-CX-21", description: "Check helpdesk stationary (Pens/Forms).", priority: "Low", riskLevel: "Low", consequence: "Operational friction.", proof: "Supply Audit", trainerNotes: "Check at 8 AM daily." },
                { id: "H-CX-22", description: "Audit valet car return TAT.", priority: "Medium", riskLevel: "Low", consequence: "Crowded porch exit.", proof: "Log Match", trainerNotes: "Target return in < 8 mins." },
                { id: "H-CX-23", description: "Verify lobby TV content daypart match.", priority: "Low", riskLevel: "Low", consequence: "Inappropriate energy.", proof: "Volume Check", trainerNotes: "Health news only." },
                { id: "H-CX-24", description: "Check availability of spare face masks.", priority: "Medium", riskLevel: "Medium", consequence: "Airborne risk.", proof: "Stock Check", trainerNotes: "Offer to coughing patients." },
                { id: "H-CX-25", description: "Verify 'VIP Guest' arrival setup.", priority: "Medium", riskLevel: "Low", consequence: "Loss of institutional trust.", proof: "Photo", trainerNotes: "Escalate to GM instantly." }
            ]
        },
        {
            title: "Pharmacy, Vendors & Canteen",
            department: "Logistics",
            frequency: "Daily",
            role: "Logistics Lead",
            summary: "Profit protection and supplier quality.",
            icon: "truck",
            tasks: [
                { id: "H-LOG-01", description: "Narcotics Vault: Double-count audit.", priority: "High", riskLevel: "High", consequence: "Theft and criminal diversion.", proof: "Dual-Sign Log", trainerNotes: "Conduct at shift end." },
                { id: "H-LOG-02", description: "Canteen HACCP: Patient meal > 65C.", priority: "High", riskLevel: "High", consequence: "Food poisoning in sick patients.", proof: "Food Log", trainerNotes: "Check trolleys pre-dispatch." },
                { id: "H-LOG-03", description: "Vendor Audit: FSSAI certs check.", priority: "High", riskLevel: "High", consequence: "Legal liability for sourcing.", proof: "License File", trainerNotes: "Update repository every 6m." },
                { id: "H-LOG-04", description: "Cold Chain: Pharmacy fridge 2-8C.", priority: "High", riskLevel: "High", consequence: "Ineffective high-cost biologics.", proof: "Temp Log", trainerNotes: "Log at 8 AM and 8 PM." },
                { id: "H-LOG-05", description: "Receiving: weight check bulk meds.", priority: "Medium", riskLevel: "Medium", consequence: "Paying for missing stock.", proof: "Scale Note", trainerNotes: "Check box-seal tampering." },
                { id: "H-LOG-06", description: "Audit 'High-Alert' medication labels.", priority: "High", riskLevel: "High", consequence: "Fatal administration error.", proof: "Visual Audit", trainerNotes: "Must have Red Alert tags." },
                { id: "H-LOG-07", description: "Verify cafeteria cleaning chemicals.", priority: "Medium", riskLevel: "Medium", consequence: "Chemical contamination of food.", proof: "Safety Log", trainerNotes: "Store in separate locked area." },
                { id: "H-LOG-08", description: "Inspect vendor vehicle hygiene/AC.", priority: "Medium", riskLevel: "Low", consequence: "Pathogens entering supply chain.", proof: "Receiving Log", trainerNotes: "Check for pests in crates." },
                { id: "H-LOG-09", description: "Reconcile surgical implant serial IDs.", priority: "High", riskLevel: "High", consequence: "Billed but unused implant fraud.", proof: "System Sync", trainerNotes: "Match bill vs operative note." },
                { id: "H-LOG-10", description: "Check inventory of 'Stat' medication.", priority: "High", riskLevel: "High", consequence: "Delayed treatment during crisis.", proof: "Stock Sheet", trainerNotes: "Min 15-day buffer stock." },
                { id: "H-LOG-11", description: "Audit vendor AMC service quality.", priority: "Medium", riskLevel: "Low", consequence: "Paying for sub-par repairs.", proof: "Job Log", trainerNotes: "Manager sign-off pre-payment." },
                { id: "H-LOG-12", description: "Verify RO water backwash temp.", priority: "Low", riskLevel: "Medium", consequence: "Membrane failure.", proof: "System Reading", trainerNotes: "Log pressure drop hourly." },
                { id: "H-LOG-13", description: "Check availability of tamper seals.", priority: "Low", riskLevel: "Low", consequence: "Compromised drug security.", proof: "Supply Audit", trainerNotes: "Min 1000 seals in stock." },
                { id: "H-LOG-14", description: "Audit 'Expiring Meds' (3-month window).", priority: "High", riskLevel: "Medium", consequence: "Financial inventory loss.", proof: "Expiry Log", trainerNotes: "Return to vendor by 15th." },
                { id: "H-LOG-15", description: "Inspect canteen staff health certs.", priority: "High", riskLevel: "Medium", consequence: "Infection outbreak.", proof: "Med File", trainerNotes: "Includes monthly stool test." },
                { id: "H-LOG-16", description: "Verify Pharmacy CCTV focal point.", priority: "High", riskLevel: "High", consequence: "Loss of evidence for theft.", proof: "System Screen", trainerNotes: "Check timestamp sync." },
                { id: "H-LOG-17", description: "Audit 'Consumable' stockout frequency.", priority: "Medium", riskLevel: "Low", consequence: "Operational friction.", proof: "Matrix Report", trainerNotes: "Flag items with > 2 stockouts." },
                { id: "H-LOG-18", description: "Check gas manifold joint soap-test.", priority: "High", riskLevel: "High", consequence: "Major explosion hazard.", proof: "Maint Note", trainerNotes: "Do not relies on smell alone." },
                { id: "H-LOG-19", description: "Verify vendor GST pan match on bills.", priority: "Low", riskLevel: "Low", consequence: "Tax inefficiency.", proof: "Ledger Audit", trainerNotes: "Verify 100% of new vendors." },
                { id: "H-LOG-20", description: "Inspect morgue hygiene and O2 area.", priority: "High", riskLevel: "High", consequence: "Explosion risk/PR disaster.", proof: "Visual Check", trainerNotes: "No flammables near O2." },
                { id: "H-LOG-21", description: "Audit 'Staff Meal' hygiene standards.", priority: "Low", riskLevel: "Low", consequence: "Low morale/hygiene risks.", proof: "Visual Check", trainerNotes: "Same standard as patients." },
                { id: "H-LOG-22", description: "Verify 'Stat' medicine courier TAT.", priority: "Medium", riskLevel: "Low", consequence: "Delayed recovery.", proof: "Log Book", trainerNotes: "Target < 30 mins delivery." },
                { id: "H-LOG-23", description: "Final Logistics Shift sign-off.", priority: "High", riskLevel: "Low", consequence: "Incomplete handover.", proof: "Signed Summary", trainerNotes: "Brief GM on stockouts." },
                { id: "H-LOG-24", description: "Check status of 'Fire Exit' clearance.", priority: "High", riskLevel: "High", consequence: "Fatal entrapment.", proof: "Patrol Log", trainerNotes: "Physically open every door." },
                { id: "H-LOG-25", description: "Verify 100% sign on 'Inventory Waste'.", priority: "Medium", riskLevel: "Medium", consequence: "Untracked profit leakage.", proof: "Waste Ledger", trainerNotes: "Target waste < 1% sales." }
            ]
        }
    ]
};
