
import type { PremiumPack } from "@/lib/premium-packs";

export const healthcare_and_hospital_operations: PremiumPack = {
    id: 'healthcare_and_hospital_operations',
    title: "Hospital Operating System",
    priceINR: 799,
    priceUSD: 9,
    category: "Healthcare",
    description: "The Sovereign v8.5 clinical engine for hospitals and specialized medical centers. Hardening 200 technical control points from surgical safety to biomedical waste.",
    heroHeadline: "Zero-Risk Medical Operations. Audit-Ready.",
    heroSubheadline: "Standardize clinical and operational governance across every department in your facility with a logically-aware data engine.",
    pricingUrgency: "A single clinical error or one NABH/JCI audit failure costs 1000x more than this system.",
    consultingAnchor: 15000,
    icon: "hospital",
    badgeText: "V8.5 SOVEREIGN",
    badgeVariant: "destructive",
    whoIsItFor: ["Medical Directors", "Hospital COOs", "Nursing Superintendents", "Quality Heads", "Admin Directors"],
    sampleItems: [
        { text: "<strong>Clinical Safety (WHO)</strong>: Pre-incision time-outs and dual-verification for high-alert drugs.", icon: "shield-check" },
        { text: "<strong>Nursing & Ward Command</strong>: Bedside handover audits and crash-cart integrity tracking.", icon: "heart-pulse" },
        { text: "<strong>OPD & Diagnostic Logic</strong>: Queue TAT monitoring and doctor arrival parity checks.", icon: "stethoscope" },
        { text: "<strong>Pharmacy & Narcotics</strong>: Strict access logs and double-blind stock counts for controlled drugs.", icon: "pill" },
        { text: "<strong>Billing & Discharge Shield</strong>: TPA pre-auth tracking and unbilled consumable audits.", icon: "banknote" },
        { text: "<strong>Biomedical Waste (EHS)</strong>: Legal compliance for waste segregation and spillage kit readiness.", icon: "recycle" },
        { text: "<strong>Medical Equipment (BMS)</strong>: OT/ICU UPS load tests and Oxygen Plant pressure monitoring.", icon: "wrench" },
        { text: "<strong>Reputation Shield (ORM)</strong>: 24-hour response mandate for Google and Practo reviews.", icon: "star" }
    ],
    checklists: [
        {
            title: "Clinical Governance",
            department: "Executive",
            frequency: "Weekly",
            role: "COO / Owner",
            summary: "High-level strategic oversight of medical risk, credentialing, and clinical outcomes.",
            icon: "crown",
            tasks: [
                { id: "H-EXE-01", description: "Review Sentinel Event Log for near-miss clinical errors.", priority: "High", riskLevel: "High", consequence: "Fatal patient harm and total loss of hospital license.", proof: "Log Audit", trainerNotes: "Ensure zero open incident files; every entry needs a root cause analysis." },
                { id: "H-EXE-02", description: "Verify valid registration for all consulting and full-time doctors.", priority: "High", riskLevel: "High", consequence: "Massive criminal liability for the institution.", proof: "Credential Registry", trainerNotes: "Cross-check with Medical Council database quarterly." },
                { id: "H-EXE-03", description: "Audit Mortality & Morbidity (M&M) meeting minutes.", priority: "High", riskLevel: "Medium", consequence: "Failure to improve clinical quality from past errors.", proof: "Minutes File", trainerNotes: "Check if action points from last month were closed." },
                { id: "H-EXE-04", description: "Review hospital-acquired infection (HAI) rates across wards.", priority: "High", riskLevel: "High", consequence: "Audit non-conformance and increased patient stay duration.", proof: "Infection Log", trainerNotes: "Target HAI rate < 1%." },
                { id: "H-EXE-05", description: "Verify insurance validity for Professional Indemnity and Fire.", priority: "High", riskLevel: "High", consequence: "Total financial ruin in the event of a lawsuit.", proof: "Policy File", trainerNotes: "Renewal must be initiated 60 days before expiry." },
                { id: "H-EXE-06", description: "Audit doctor arrival parity against OT and OPD schedules.", priority: "High", riskLevel: "Medium", consequence: "Delayed critical procedures and lost patient trust.", proof: "Attendance Log", trainerNotes: "Check for outliers with > 30 min delays." },
                { id: "H-EXE-07", description: "Review monthly 'Clinical Quality KPIs' vs. Benchmarks.", priority: "Medium", riskLevel: "Low", consequence: "Undetected drop in care standards.", proof: "KPI Dashboard", trainerNotes: "Focus on re-admission rates." },
                { id: "H-EXE-08", description: "Verify 100% completion of 'High-Risk Sign-offs' by department heads.", priority: "High", riskLevel: "High", consequence: "Management negligence during critical safety gaps.", proof: "Executive Console", trainerNotes: "Missing signatures trigger an automatic HR alert." },
                { id: "H-EXE-09", description: "Audit 'Emergency Response' (Code Blue) drill performance.", priority: "High", riskLevel: "High", consequence: "Delayed response during a real cardiac arrest.", proof: "Drill Log", trainerNotes: "Response time must be under 3 minutes." },
                { id: "H-EXE-10", description: "Review 'Medical Audit' scores for random patient files.", priority: "Medium", riskLevel: "Medium", consequence: "Incomplete documentation during legal disputes.", proof: "Audit Report", trainerNotes: "Check for legible physician notes and signatures." },
                { id: "H-EXE-11", description: "Check status of 'Radiation Safety' NOC for Radiology dept.", priority: "High", riskLevel: "High", consequence: "Sealing of department by AERB authorities.", proof: "Certificate", trainerNotes: "Verify TLD badge reporting status." },
                { id: "H-EXE-12", description: "Review group-wide biomedical waste disposal costs.", priority: "Low", riskLevel: "Low", consequence: "Unchecked operational cost inflation.", proof: "Finance Ledger", trainerNotes: "Compare cost per bed-day across locations." },
                { id: "H-EXE-13", description: "Verify 'Safe Surgery' checklist compliance in OT.", priority: "High", riskLevel: "High", consequence: "Wrong-site surgery (Fatal Never-Event).", proof: "Surgical Audit", trainerNotes: "Randomly spot-check 5 files per week." },
                { id: "H-EXE-14", description: "Check for any open 'Legal Notice' files.", priority: "High", riskLevel: "High", consequence: "Unmanaged litigation leading to court orders.", proof: "Legal Dashboard", trainerNotes: "Brief external counsel on all new P1 notices." },
                { id: "H-EXE-15", description: "Audit 'TPA/Insurance' rejection trends.", priority: "Medium", riskLevel: "Medium", consequence: "Direct hit to the hospital's net margins.", proof: "Rejection Report", trainerNotes: "Analyze root cause of 'Query' patterns." },
                { id: "H-EXE-16", description: "Verify validity of Blood Bank and Lab licenses.", priority: "High", riskLevel: "High", consequence: "Closure of critical diagnostic units.", proof: "License Repository", trainerNotes: "Initiate renewal 90 days early." },
                { id: "H-EXE-17", description: "Review 'Nursing-to-Patient' ratios across shifts.", priority: "High", riskLevel: "High", consequence: "Increased risk of patient falls and medication errors.", proof: "Roster Log", trainerNotes: "Maintain 1:1 in ICU and 1:6 in Wards." },
                { id: "H-EXE-18", description: "Verify 'Medical Gas' manifold backup levels.", priority: "High", riskLevel: "High", consequence: "Total supply failure (Fatal).", proof: "Manifold Log", trainerNotes: "Physically check secondary cylinder levels." },
                { id: "H-EXE-19", description: "Audit 'Ambulance Vitals' and life-support readiness.", priority: "High", riskLevel: "High", consequence: "Death during transit due to faulty equipment.", proof: "Fleet Check", trainerNotes: "Check O2 levels and Defibrillator battery." },
                { id: "H-EXE-20", description: "Review 'Customer CSAT' trends for Patient Discharge.", priority: "Medium", riskLevel: "Low", consequence: "Poor public perception and ranking drop.", proof: "CSAT Dashboard", trainerNotes: "Analyze 'Billing Delay' comments specifically." },
                { id: "H-EXE-21", description: "Check for open 'Internal Audit' non-conformances (NCs).", priority: "High", riskLevel: "Medium", consequence: "Recurring operational failures.", proof: "NC Tracker", trainerNotes: "All major NCs must be closed in < 15 days." },
                { id: "H-EXE-22", description: "Verify 'UPS & Battery' health for high-stakes scanners.", priority: "High", riskLevel: "Medium", consequence: "Hardware damage worth millions during surge.", proof: "Maintenance Log", trainerNotes: "Check load-testing report." },
                { id: "H-EXE-23", description: "Review 'Antibiotic Stewardship' program data.", priority: "Medium", riskLevel: "Medium", consequence: "Rise of multi-drug resistant organisms.", proof: "Pharmacy Audit", trainerNotes: "Check for 'Restrictive Group' usage approvals." },
                { id: "H-EXE-24", description: "Verify 'Committee Meeting' frequency (Infection, Ethics, Safety).", priority: "Medium", riskLevel: "Low", consequence: "Loss of accreditation (NABH/JCI).", proof: "Minutes Registry", trainerNotes: "Meetings must happen at least quarterly." },
                { id: "H-EXE-25", description: "Final Executive sign-off on the 'Monthly Quality Profile'.", priority: "High", riskLevel: "Low", consequence: "Loss of final administrative oversight.", proof: "Signed Summary", trainerNotes: "Archive the validated PDF version for board review." }
            ]
        },
        {
            title: "Nursing & Ward Command",
            department: "Operations",
            frequency: "Daily",
            role: "General Manager",
            summary: "Manages the patient infrastructure, bedside handover, and emergency drug readiness.",
            icon: "heart-pulse",
            tasks: [
                { id: "H-NUR-01", description: "Bedside Handover: Verify patient vitals and IV site integrity.", priority: "High", riskLevel: "High", consequence: "Loss of critical patient data during shift change.", proof: "Handover Log", trainerNotes: "Confirm MRN match at the bedside with incoming nurse." },
                { id: "H-NUR-02", description: "Crash Cart Integrity: Verify drug seals and AED battery status.", priority: "High", riskLevel: "High", consequence: "Failed resuscitation during cardiac arrest.", proof: "Seal Check Log", trainerNotes: "Check pressure of emergency O2 cylinder." },
                { id: "H-NUR-03", description: "Audit Medication Administration Records (MAR) for 100% completion.", priority: "High", riskLevel: "High", consequence: "Missed doses or double-dosing fatal errors.", proof: "MAR Audit Note", trainerNotes: "Verify signatures against medication times." },
                { id: "H-NUR-04", description: "Check 'High-Fall Risk' bedside signage and side-rails.", priority: "High", riskLevel: "High", consequence: "Patient injury and legal negligence claims.", proof: "Visual Check", trainerNotes: "Side-rails must be UP for all elderly patients." },
                { id: "H-NUR-05", description: "Verify 'Critical Value' reporting speed from Lab to Ward.", priority: "High", riskLevel: "High", consequence: "Delayed treatment for life-threatening lab results.", proof: "Value Log", trainerNotes: "Target reporting time < 15 minutes." },
                { id: "H-NUR-06", description: "Monitor 'Nursing Call Bell' response times.", priority: "Medium", riskLevel: "Medium", consequence: "Patient dissatisfaction and safety risk.", proof: "System Log", trainerNotes: "Target response < 2 minutes." },
                { id: "H-NUR-07", description: "Audit 'Pressure Ulcer' checks for long-stay patients.", priority: "High", riskLevel: "Medium", consequence: "Secondary complications and JCI non-compliance.", proof: "Turn-Chart", trainerNotes: "Check for skin changes every 2 hours." },
                { id: "H-NUR-08", description: "Verify 'Identification Band' presence on 100% of patients.", priority: "High", riskLevel: "High", consequence: "Wrong patient receiving wrong treatment/surgery.", proof: "Walkthrough Note", trainerNotes: "Bands must be legible and secure." },
                { id: "H-NUR-09", description: "Log daily ward-level stock of life-saving consumables.", priority: "Medium", riskLevel: "Low", consequence: "Operational halt during emergency.", proof: "Inventory Sheet", trainerNotes: "Restock when levels drop to 20%." },
                { id: "H-NUR-10", description: "Check 'Vacuum & Suction' functionality at each bedside.", priority: "High", riskLevel: "High", consequence: "Inability to clear airway during choking.", proof: "Test Note", trainerNotes: "Ensure jars are clean and liners are present." },
                { id: "H-NUR-11", description: "Verify 'Infusion Pump' calibration and battery life.", priority: "High", riskLevel: "Medium", consequence: "Inaccurate dosing of critical vasoactive drugs.", proof: "Maintenance Tag", trainerNotes: "Check next due date on the sticker." },
                { id: "H-NUR-12", description: "Monitor 'Bio-waste' bin placement and source-segregation.", priority: "High", riskLevel: "High", consequence: "Fines and needle-stick risk to staff.", proof: "Visual Audit", trainerNotes: "Sharps must go in puncture-proof bins." },
                { id: "H-NUR-13", description: "Check 'Patient Discharge' TAT from doctor's order.", priority: "Medium", riskLevel: "Low", consequence: "Revenue loss and room turnover delay.", proof: "TAT Dashboard", trainerNotes: "Target discharge in < 3 hours." },
                { id: "H-NUR-14", description: "Verify 'Sample Labeling' protocol at the bedside.", priority: "High", riskLevel: "High", consequence: "Wrong diagnosis due to sample mix-up.", proof: "Audit Log", trainerNotes: "Label the sample immediately in front of the patient." },
                { id: "H-NUR-15", description: "Inspect ward refrigerator temperature for patient meds.", priority: "High", riskLevel: "Medium", consequence: "Drug spoilage and ineffectiveness.", proof: "Temp Log", trainerNotes: "Maintain between 2°C and 8°C." },
                { id: "H-NUR-16", description: "Audit 'Restraint Policy' documentation for at-risk patients.", priority: "Medium", riskLevel: "High", consequence: "Legal/Ethical violations.", proof: "Consent Form", trainerNotes: "Requires physician order every 24h." },
                { id: "H-NUR-17", description: "Check 'Nurse Briefing' attendance for shift-notes.", priority: "Low", riskLevel: "Low", consequence: "Communication breakdown.", proof: "Briefing Log", trainerNotes: "Summarize 'High-Risk' patients first." },
                { id: "H-NUR-18", description: "Verify 'Linen Exchange' schedule and cleanliness.", priority: "Low", riskLevel: "Low", consequence: "Poor patient hygiene perception.", proof: "Visual Check", trainerNotes: "No graying or stained linen allowed." },
                { id: "H-NUR-19", description: "Log 'Needle-Stick Injury' instances for the shift.", priority: "High", riskLevel: "High", consequence: "Occupational health risk (HIV/Hep-B).", proof: "Incident Log", trainerNotes: "Follow PEP protocol immediately." },
                { id: "H-NUR-20", description: "Check 'Vitals Monitoring' frequency against orders.", priority: "High", riskLevel: "High", consequence: "Undetected patient deterioration.", proof: "Vitals Chart", trainerNotes: "Check q1h for high-risk; q4h for stable." },
                { id: "H-NUR-21", description: "Verify 'Nurse Station' hygiene and noise control.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional environment.", proof: "Walkthrough", trainerNotes: "Keep station clear of personal items." },
                { id: "H-NUR-22", description: "Audit 'Verbal Order' policy (Should be 'Read Back').", priority: "High", riskLevel: "High", consequence: "Transcription errors leading to wrong meds.", proof: "Order Log", trainerNotes: "Verify nurse read back the order to the MD." },
                { id: "H-NUR-23", description: "Check availability of 'Emergency Spill Kits'.", priority: "Medium", riskLevel: "Medium", consequence: "Disease spread after blood spill.", proof: "Visual Audit", trainerNotes: "Kits must be visible and accessible." },
                { id: "H-NUR-24", description: "Verify 'Patient Diet' matches physician orders.", priority: "Medium", riskLevel: "High", consequence: "Allergic reaction or aspiration (NPO).", proof: "Meal Tray Audit", trainerNotes: "Check bed-tag against tray-tag." },
                { id: "H-NUR-25", description: "Final sign-off on the shift's operational readiness.", priority: "High", riskLevel: "Low", consequence: "Incomplete handover to night manager.", proof: "Signed Ledger", trainerNotes: "Summarize all 'Code Red' or safety issues." }
            ]
        },
        {
            title: "Billing & Insurance Shield",
            department: "Finance",
            frequency: "Daily",
            role: "Finance & Cashier",
            summary: "Protects the hospital revenue pipeline, TPA approvals, and cash integrity.",
            icon: "banknote",
            tasks: [
                { id: "H-BIL-01", description: "TPA Pre-Auth Pulse: Verify approval status for all new IPs.", priority: "High", riskLevel: "Medium", consequence: "Financial loss through claim denial after treatment.", proof: "System Sync", trainerNotes: "Check pre-auth in < 4 hours of admission." },
                { id: "H-BIL-02", description: "Consumable Audit: Reconcile ward usage to final bill.", priority: "High", riskLevel: "Medium", consequence: "Silent profit leakage via unbilled drugs/implants.", proof: "Match Note", trainerNotes: "Audit 5% of discharge files randomly." },
                { id: "H-BIL-03", description: "Reconcile POS digital settlements against bank captures.", priority: "High", riskLevel: "High", consequence: "Untracked revenue loss and cashier fraud.", proof: "Settlement Log", trainerNotes: "Variance > ₹100 requires investigation." },
                { id: "H-BIL-04", description: "Audit 'Refund' and 'Discount' approvals for the day.", priority: "High", riskLevel: "High", consequence: "Unauthorized billing manipulation.", proof: "Approval File", trainerNotes: "Every discount requires MD/COO signature." },
                { id: "H-BIL-05", description: "Verify 'Cash-to-Bank' deposit matches shift totals.", priority: "High", riskLevel: "High", consequence: "Internal cash theft risk.", proof: "Bank Slip", trainerNotes: "Deposit must be done by 11 AM next day." },
                { id: "H-BIL-06", description: "Check 'Outstanding Balance' for all currently admitted patients.", priority: "Medium", riskLevel: "Low", consequence: "Inability to recover funds on discharge.", proof: "Ledger Report", trainerNotes: "Notify patients when deposit drops below 20%." },
                { id: "H-BIL-07", description: "Verify 'Emergency Admission' credit approvals.", priority: "Medium", riskLevel: "Medium", consequence: "Bad debt accumulation.", proof: "Credit Log", trainerNotes: "Check for 'Guarantor' signatures." },
                { id: "H-BIL-08", description: "Audit 'Pharmacy Return' credits against Ward slips.", priority: "Medium", riskLevel: "Low", consequence: "Over-billing or fraudulent credit notes.", proof: "Match Sheet", trainerNotes: "Check batch codes on returns." },
                { id: "H-BIL-09", description: "Check 'Insurance Portal' for open queries/deficiencies.", priority: "High", riskLevel: "Medium", consequence: "Delayed payments and cash-flow crunch.", proof: "Portal Screenshot", trainerNotes: "Resolve all queries in < 24 hours." },
                { id: "H-BIL-10", description: "Verify 'Advance Deposit' levels for scheduled surgeries.", priority: "High", riskLevel: "Low", consequence: "Post-surgery financial disputes.", proof: "System Report", trainerNotes: "Target 100% estimated cost deposit." },
                { id: "H-BIL-11", description: "Check 'TPA Card' validity against patient ID.", priority: "High", riskLevel: "High", consequence: "Fraudulent insurance claims.", proof: "Scan Note", trainerNotes: "Verify against Aadhar/Passport." },
                { id: "H-BIL-12", description: "Audit 'Non-Medical' billing items (Registration, Food).", priority: "Low", riskLevel: "Low", consequence: "Undetected billing gaps.", proof: "Sample Check", trainerNotes: "Ensure registration fee is 100% captured." },
                { id: "H-BIL-13", description: "Verify 'GST Compliance' on all pharmacy/service bills.", priority: "High", riskLevel: "High", consequence: "Tax penalties and legal non-compliance.", proof: "Tax Audit", trainerNotes: "Check HSN codes for new drug entries." },
                { id: "H-BIL-14", description: "Audit 'Voided Bills' history for the shift.", priority: "High", riskLevel: "Medium", consequence: "Revenue skimming fraud.", proof: "Void Log", trainerNotes: "All voids require handwritten manager reason." },
                { id: "H-BIL-15", description: "Check 'Package Billing' accuracy for standard procedures.", priority: "Medium", riskLevel: "Low", consequence: "Over or under-charging for surgeries.", proof: "Package Audit", trainerNotes: "Ensure exclusions are clearly explained." },
                { id: "H-BIL-16", description: "Verify 'Cashier Float' denominations at shift start.", priority: "Low", riskLevel: "Low", consequence: "Operational delays at the counter.", proof: "Float Sheet", trainerNotes: "Maintain min ₹2000 in change." },
                { id: "H-BIL-17", description: "Monitor 'Credit Note' issuance frequency.", priority: "Medium", riskLevel: "Medium", consequence: "Masking billing errors.", proof: "CN Tracker", trainerNotes: "Flag staff with > 5 notes per week." },
                { id: "H-BIL-18", description: "Check 'Pharmacy-to-Billing' API sync health.", priority: "High", riskLevel: "Medium", consequence: "Lost charges for dispensed meds.", proof: "System Test", trainerNotes: "Run a test item entry daily." },
                { id: "H-BIL-19", description: "Audit 'Staff/Doctor' professional discount usage.", priority: "Low", riskLevel: "Low", consequence: "Margin erosion through unauthorized perks.", proof: "Benefit Log", trainerNotes: "Verify ID card for all staff discounts." },
                { id: "H-BIL-20", description: "Check 'Night Billing' handover for IP admissions.", priority: "Medium", riskLevel: "Low", consequence: "Missing admission fees.", proof: "Handover Note", trainerNotes: "Check for 'Interim' bills." },
                { id: "H-BIL-21", description: "Monitor 'Payment Terminal' security seals.", priority: "High", riskLevel: "High", consequence: "Data breach via card skimmers.", proof: "Visual Audit", trainerNotes: "Report any broken holographic seals." },
                { id: "H-BIL-22", description: "Audit 'Third-party Referral' payments (if applicable).", priority: "Medium", riskLevel: "Medium", consequence: "Compliance risk.", proof: "Referral Ledger", trainerNotes: "Must match standard tariff policy." },
                { id: "H-BIL-23", description: "Review 'Average Revenue Per Patient' (ARPOB) trend.", priority: "Low", riskLevel: "Low", consequence: "Unidentified revenue downturns.", proof: "Finance Report", trainerNotes: "Compare to previous week's average." },
                { id: "H-BIL-24", description: "Check 'Final Bill' sign-off by patient/relative.", priority: "High", riskLevel: "Medium", consequence: "Legal disputes over charges.", proof: "Signed Bill", trainerNotes: "Signature mandatory for all IPs." },
                { id: "H-BIL-25", description: "Final closure of the 'Financial Shield' ledger.", priority: "High", riskLevel: "Low", consequence: "Incomplete handover to management.", proof: "Signed Summary", trainerNotes: "Attach all exception reports to the summary." }
            ]
        },
        {
            title: "Bio-Waste & Safety",
            department: "Safety",
            frequency: "Daily",
            role: "EHS Officer",
            summary: "Regulatory compliance for bio-hazardous waste and hospital safety.",
            icon: "recycle",
            tasks: [
                { id: "H-WST-01", description: "Verify color-coded segregation at ward source (Red/Yellow/Blue).", priority: "High", riskLevel: "High", consequence: "Hefty PCB fines and risk of disease transmission.", proof: "Visual Audit", trainerNotes: "Check if non-clinical waste is mixed in yellow bins." },
                { id: "H-WST-02", description: "Audit sharps-container fill levels (Target <75% max).", priority: "High", riskLevel: "High", consequence: "Needle-stick injuries to janitorial and clinical staff.", proof: "Visual Check", trainerNotes: "Do not allow containers to overflow." },
                { id: "H-WST-03", description: "Inspect 'Bio-waste Storage' area lock and signage.", priority: "High", riskLevel: "Medium", consequence: "Unauthorized access or pest infestation.", proof: "Patrol Log", trainerNotes: "Storage area must be clear of the main ward." },
                { id: "H-WST-04", description: "Verify 'Waste Manifest' weight against vendor receipt.", priority: "High", riskLevel: "Medium", consequence: "Legal liability for untracked hazardous waste.", proof: "Manifest File", trainerNotes: "Log the exact pickup time and vehicle ID." },
                { id: "H-WST-05", description: "Test 'Chemical Spill Kit' availability in Oncology/Lab.", priority: "High", riskLevel: "High", consequence: "Fatal exposure after cytotoxic or chemical spills.", proof: "Seal Audit", trainerNotes: "Kits must include bleach and goggles." },
                { id: "H-WST-06", description: "Check status of 'Fire Extinguishers' in the OT zone.", priority: "High", riskLevel: "High", consequence: "Inability to fight electrical fires in ICU/OT.", proof: "Gauge Log", trainerNotes: "Pressure must be in the Green zone." },
                { id: "H-WST-07", description: "Verify all fire-exits are unlocked and clear of trolleys.", priority: "High", riskLevel: "High", consequence: "Fatal stampede or entrapment during fire.", proof: "Patrol Log", trainerNotes: "Wheelchairs must not block fire-doors." },
                { id: "H-WST-08", description: "Audit 'Radiation Shielding' integrity in X-ray rooms.", priority: "High", riskLevel: "High", consequence: "Radiation exposure to staff and public.", proof: "Survey Note", trainerNotes: "Check for cracks in lead-lined glass/doors." },
                { id: "H-WST-09", description: "Test PA system for 'Emergency Codes' clarity.", priority: "Medium", riskLevel: "High", consequence: "Communication failure during Code Blue/Red.", proof: "Sound Test", trainerNotes: "Test from different zones daily." },
                { id: "H-WST-10", description: "Check 'Smoke Detector' heartbeat at the main panel.", priority: "High", riskLevel: "High", consequence: "Delayed fire detection.", proof: "System Screen", trainerNotes: "Ensure zero open zones on panel." },
                { id: "H-WST-11", description: "Verify 'Medical Gas' alarm panel connectivity.", priority: "High", riskLevel: "High", consequence: "Patient asphyxiation due to gas failure.", proof: "Alarm Test", trainerNotes: "Check for 'Low Pressure' light." },
                { id: "H-WST-12", description: "Inspect 'Patient Restrooms' for anti-skid mats.", priority: "Medium", riskLevel: "Medium", consequence: "Elderly patient falls and lawsuits.", proof: "Visual Check", trainerNotes: "Replace worn mats immediately." },
                { id: "H-WST-13", description: "Check availability of 'Personal Protective Equipment' (PPE).", priority: "High", riskLevel: "Medium", consequence: "Preventable clinical infections to staff.", proof: "Stock Audit", trainerNotes: "Ensure min 2 days buffer of N95 masks." },
                { id: "H-WST-14", description: "Verify 'Emergency Lighting' battery-run duration.", priority: "Medium", riskLevel: "High", consequence: "Panic during night-shift power failure.", proof: "Test Note", trainerNotes: "Test for 10 mins under load weekly." },
                { id: "H-WST-15", description: "Audit 'CSSD Sterilization' biological indicator logs.", priority: "High", riskLevel: "High", consequence: "Post-operative infection outbreak.", proof: "Incubation Log", trainerNotes: "Indicator must show 100% bacterial kill." },
                { id: "H-WST-16", description: "Check 'Staff Eye-wash' stations in Lab and Pharmacy.", priority: "High", riskLevel: "High", consequence: "Permanent vision loss after chemical splash.", proof: "Flush Log", trainerNotes: "Flush for 2 minutes every Monday." },
                { id: "H-WST-17", description: "Verify 'Hazardous Material' labeling (GHS standard).", priority: "Medium", riskLevel: "Low", consequence: "Accidental ingestion or wrong handling.", proof: "Storage Audit", trainerNotes: "Labels must be in local language too." },
                { id: "H-WST-18", description: "Audit 'Waste Handler' vaccination records (Hep-B/Tetanus).", priority: "High", riskLevel: "Medium", consequence: "Occupational disease liability.", proof: "Medical File", trainerNotes: "Renew boosters as per schedule." },
                { id: "H-WST-19", description: "Check 'Fire NOC' and 'Lift License' validity.", priority: "High", riskLevel: "High", consequence: "Government sealing of premises.", proof: "License File", trainerNotes: "Renew 60 days before expiry." },
                { id: "H-WST-20", description: "Inspect 'Kitchen Hygiene' if hospital provides food.", priority: "High", riskLevel: "Medium", consequence: "Food poisoning in sick patients.", proof: "Daily Audit", trainerNotes: "Check temp of food trolleys." },
                { id: "H-WST-21", description: "Test 'Code Pink' (Infant Abduction) alarm response.", priority: "High", riskLevel: "High", consequence: "Institutional catastrophe.", proof: "Drill Log", trainerNotes: "Response time must be < 2 minutes." },
                { id: "H-WST-22", description: "Verify 'Electrical Panel' load using IR thermometer.", priority: "High", riskLevel: "High", consequence: "Major electrical fire risk.", proof: "Thermal Log", trainerNotes: "Report any breaker > 60°C." },
                { id: "H-WST-23", description: "Audit 'Oxygen Manifold' room ventilation.", priority: "High", riskLevel: "High", consequence: "Explosion hazard due to gas buildup.", proof: "Visual Check", trainerNotes: "Check for any grease/oil near cylinders." },
                { id: "H-WST-24", description: "Check 'Stairwell' for any storage obstructions.", priority: "High", riskLevel: "High", consequence: "Blocked evacuation.", proof: "Patrol Note", trainerNotes: "Stairs must be 100% clear." },
                { id: "H-WST-25", description: "Final manager walkthrough of safety perimeter.", priority: "High", riskLevel: "Low", consequence: "Gaps in institutional discipline.", proof: "Manager Initials", trainerNotes: "The most critical 10 minutes of the shift." }
            ]
        },
        {
            title: "Clinical Training & Certs",
            department: "HR",
            frequency: "Monthly",
            role: "HR Manager",
            summary: "Governs staff competency, mandatory medical licenses, and infection control training.",
            icon: "graduation-cap",
            tasks: [
                { id: "H-HR-01", description: "Verify 'Nursing Registration' validity for all staff nurses.", priority: "High", riskLevel: "High", consequence: "Criminal liability for unlicensed care.", proof: "Cert File", trainerNotes: "Maintain copies of Nursing Council IDs." },
                { id: "H-HR-02", description: "Audit 'BLS/ACLS' certification status for ICU/ER staff.", priority: "High", riskLevel: "High", consequence: "Inability to perform advanced life support.", proof: "Training Matrix", trainerNotes: "Renew 30 days before expiry." },
                { id: "H-HR-03", description: "Verify 'Medical Certificates' for F&B/Janitorial handlers.", priority: "Medium", riskLevel: "Medium", consequence: "Transmission of infections to patients.", proof: "Med File", trainerNotes: "Includes stool/blood test yearly." },
                { id: "H-HR-04", description: "Audit uniform and grooming at shift briefings.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional brand image.", proof: "Attendance Log", trainerNotes: "Check for clean coats and ID badges." },
                { id: "H-HR-05", description: "Conduct training session on 'Hand Hygiene' (WHO steps).", priority: "High", riskLevel: "High", consequence: "Increased hospital-acquired infections.", proof: "Training Log", trainerNotes: "Ask staff to demonstrate 7-step wash." },
                { id: "H-HR-06", description: "Update 'Skills Matrix' for new medical equipment.", priority: "High", riskLevel: "Medium", consequence: "Equipment damage due to improper use.", proof: "Matrix Update", trainerNotes: "Verify manufacturer training notes." },
                { id: "H-HR-07", description: "Check 'Staff Vaccinations' (Flu/Hep-B) for current roster.", priority: "High", riskLevel: "Medium", consequence: "High staff absenteeism during outbreaks.", proof: "Immuno-Ledger", trainerNotes: "Renew boosters as scheduled." },
                { id: "H-HR-08", description: "Verify 'Confidentiality/HIPAA' agreement signatures.", priority: "High", riskLevel: "High", consequence: "Patient data leak and legal penalties.", proof: "Signed Agreement", trainerNotes: "Required for all clinical and admin staff." },
                { id: "H-HR-09", description: "Review 'Nursing Turnover' data and exit comments.", priority: "Medium", riskLevel: "Low", consequence: "Missing root cause of staff loss.", proof: "Exit Notes", trainerNotes: "Analyze 'Shift Fatigue' comments." },
                { id: "H-HR-10", description: "Audit 'Overtime' hours against safety benchmarks.", priority: "Medium", riskLevel: "High", consequence: "Fatigue-driven medical errors.", proof: "OT Tracker", trainerNotes: "Limit consecutive shifts to 12 hours." },
                { id: "H-HR-11", description: "Check 'Grievance Redressal' log for hospital staff.", priority: "Medium", riskLevel: "Low", consequence: "Toxic workplace risk.", proof: "Resolution File", trainerNotes: "Resolve in < 7 days." },
                { id: "H-HR-12", description: "Verify 'Infection Control' induction for new hires.", priority: "High", riskLevel: "High", consequence: "Immediate risk to patient safety.", proof: "Induction Form", trainerNotes: "No floor duty without induction." },
                { id: "H-HR-13", description: "Audit 'POCSO' training for Pediatric staff.", priority: "High", riskLevel: "High", consequence: "Severe legal and child-safety risk.", proof: "Training Record", trainerNotes: "100% attendance mandatory." },
                { id: "H-HR-14", description: "Check availability of 'Grooming Kits' for clinical staff.", priority: "Low", riskLevel: "Low", consequence: "Slipping grooming standards.", proof: "Visual Check", trainerNotes: "Razors/Deodorants in lockers." },
                { id: "H-HR-15", description: "Verify 'Bio-metric' sync for payroll accuracy.", priority: "Low", riskLevel: "Low", consequence: "Payroll disputes.", proof: "System Log", trainerNotes: "Reconcile shift-adjustments weekly." },
                { id: "H-HR-16", description: "Review 'Upselling Diagnostic' training performance.", priority: "Low", riskLevel: "Low", consequence: "Missed revenue from health checkups.", proof: "Sales Dashboard", trainerNotes: "Focus on preventative care packages." },
                { id: "H-HR-17", description: "Check 'Staff Restroom' hygiene standards.", priority: "Medium", riskLevel: "Low", consequence: "Cross-contamination risk.", proof: "Cleaning Log", trainerNotes: "Same standard as patient rooms." },
                { id: "H-HR-18", description: "Audit 'ID Badge' usage for all 3rd party vendors.", priority: "Medium", riskLevel: "Medium", consequence: "Unauthorized person presence in OT.", proof: "Patrol Log", trainerNotes: "Vendors must wear 'Visitor' tags." },
                { id: "H-HR-19", description: "Verify 'Labor Law' display board compliance.", priority: "Low", riskLevel: "Low", consequence: "Regulatory fines.", proof: "Photo", trainerNotes: "Update minimum wage posters." },
                { id: "H-HR-20", description: "Final weekly HR compliance sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of administrative governance.", proof: "Signed Matrix", trainerNotes: "Submit to COO every Monday morning." },
                { id: "H-HR-21", description: "Check 'Incident Report' training for ward staff.", priority: "High", riskLevel: "Medium", consequence: "Under-reporting of near misses.", proof: "Quiz Log", trainerNotes: "Ask staff to define a 'Sentinel Event'." },
                { id: "H-HR-22", description: "Verify 'Employee ID' database for stale entries.", priority: "Low", riskLevel: "Low", consequence: "Security risk after terminations.", proof: "System Audit", trainerNotes: "Deactivate IDs immediately on exit." },
                { id: "H-HR-23", description: "Audit 'Uniform Stock' for clinical staff.", priority: "Low", riskLevel: "Low", consequence: "New hires looking unprofessional.", proof: "Inventory Check", trainerNotes: "Maintain min 2 sets per person." },
                { id: "H-HR-24", description: "Check 'Committee Membership' for valid representation.", priority: "Medium", riskLevel: "Low", consequence: "NABH audit failure.", proof: "File Audit", trainerNotes: "Must include reps from each department." },
                { id: "H-HR-25", description: "Final Weekly Staff Readiness Pulse.", priority: "High", riskLevel: "Low", consequence: "Operational drift.", proof: "Signed Report", trainerNotes: "Attach all major NCs." }
            ]
        },
        {
            title: "Medical Equipment (BMS)",
            department: "Engineering",
            frequency: "Daily",
            role: "Technical Lead",
            summary: "Protects high-stakes medical infrastructure, UPS backups, and oxygen plants.",
            icon: "wrench",
            tasks: [
                { id: "H-TEC-01", description: "Verify UPS backup status for OT and ICU (Load test).", priority: "High", riskLevel: "High", consequence: "Patient death during blackout due to ventilator failure.", proof: "Voltage Log", trainerNotes: "Test battery load weekly for 10 mins." },
                { id: "H-TEC-02", description: "Inspect 'Oxygen Plant' pressure and purity levels.", priority: "High", riskLevel: "High", consequence: "Total supply failure or delivery of sub-par oxygen.", proof: "Purity Reading", trainerNotes: "Pressure must remain between 4-5 kg/cm2." },
                { id: "H-TEC-03", description: "Check RO water TDS for Dialysis and CSSD units.", priority: "High", riskLevel: "High", consequence: "Patient blood contamination and equipment scaling.", proof: "TDS Reading", trainerNotes: "Target TDS < 50 ppm for dialysis." },
                { id: "H-TEC-04", description: "Inspect 'Air Handling Units' (AHU) pressure in OT.", priority: "High", riskLevel: "High", consequence: "Loss of positive pressure leading to OT infection.", proof: "Magnehelic Gauge", trainerNotes: "Pressure must be Positive (+) to corridors." },
                { id: "H-TEC-05", description: "Check 'Backup Generator' (DG) fuel and battery.", priority: "High", riskLevel: "High", consequence: "Total hospital blackout; guest and patient panic.", proof: "Test Log", trainerNotes: "Maintain min 48 hours of fuel supply." },
                { id: "H-TEC-06", description: "Verify 'Medical Gas Manifold' alarm connectivity.", priority: "High", riskLevel: "High", consequence: "Delayed response to gas leaks or empty cylinders.", proof: "Alarm Test", trainerNotes: "Check for 'Low Cylinder' light daily." },
                { id: "H-TEC-07", description: "Inspect 'Lifts' for manual override and emergency intercom.", priority: "High", riskLevel: "High", consequence: "Patient entrapment during transport.", proof: "Visual Test", trainerNotes: "Test intercom from each car daily." },
                { id: "H-TEC-08", description: "Verify 'Hospital Wi-Fi' speed in high-stakes zones.", priority: "Medium", riskLevel: "Low", consequence: "Inability to access digital patient records.", proof: "Speedtest App", trainerNotes: "Target > 20Mbps in Wards/OT." },
                { id: "H-TEC-09", description: "Check status of 'HMS/HIS' server backups.", priority: "High", riskLevel: "High", consequence: "Irrecoverable loss of patient medical history.", proof: "Backup Log", trainerNotes: "Check sync to off-site cloud." },
                { id: "H-TEC-10", description: "Inspect 'Bio-medical Equipment' AMC tags.", priority: "High", riskLevel: "High", consequence: "Mechanical failure during surgery.", proof: "Date Verification", trainerNotes: "Check next due date on MRI/CT scanners." },
                { id: "H-TEC-11", description: "Verify 'Negative Pressure' in Isolation/COVID Wards.", priority: "High", riskLevel: "High", consequence: "Viral spread to non-infected zones.", proof: "Smoke Test", trainerNotes: "Air must flow INTO the room." },
                { id: "H-TEC-12", description: "Check 'Nurse Call System' central console functionality.", priority: "Medium", riskLevel: "Low", consequence: "Missed patient emergencies.", proof: "Visual Test", trainerNotes: "Reboot router if system lags." },
                { id: "H-TEC-13", description: "Inspect 'Kitchen AC' and ventilation status.", priority: "Low", riskLevel: "Low", consequence: "Heat fatigue for staff and poor hygiene.", proof: "Temp Reading", trainerNotes: "Target < 28°C in prep area." },
                { id: "H-TEC-14", description: "Check 'ETP/STP' plant discharge water clarity.", priority: "High", riskLevel: "Medium", consequence: "Heavy environmental fines and closure.", proof: "Visual Audit", trainerNotes: "Log pH and clarity every shift." },
                { id: "H-TEC-15", description: "Verify 'Telephone Intercom' for all clinical desks.", priority: "Medium", riskLevel: "Low", consequence: "Communication gap during emergency.", proof: "Dial Test", trainerNotes: "Test line clarity." },
                { id: "H-TEC-16", description: "Check 'Solar/Geyser' hot water supply temperature.", priority: "Low", riskLevel: "Low", consequence: "Patient discomfort and complaints.", proof: "Temp Reading", trainerNotes: "Target 55°C at delivery point." },
                { id: "H-TEC-17", description: "Audit 'PMS/HIS' user access log for generic passwords.", priority: "High", riskLevel: "High", consequence: "Unauthorized data modification and hack risk.", proof: "System Audit", trainerNotes: "Enforce password change every 90 days." },
                { id: "H-TEC-18", description: "Inspect 'Fire Pump' diesel and pressure gauges.", priority: "High", riskLevel: "High", consequence: "Failed fire suppression during crisis.", proof: "Gauge Log", trainerNotes: "Run pump for 2 mins every Sunday." },
                { id: "H-TEC-19", description: "Check 'Boiler Room' LOTO and safety protocols.", priority: "High", riskLevel: "High", consequence: "Fatal steam/pressure explosion.", proof: "Visual Audit", trainerNotes: "Verify safety valve lift monthly." },
                { id: "H-TEC-20", description: "Verify 'CCTV Monitor' sync with real-time clock.", priority: "Medium", riskLevel: "Low", consequence: "Inadmissible evidence in court.", proof: "Visual Match", trainerNotes: "Clocks must match server time." },
                { id: "H-TEC-21", description: "Check 'Pharmacy POS' printer and receipt status.", priority: "Low", riskLevel: "Low", consequence: "Billing delays.", proof: "Visual Check", trainerNotes: "Maintain roll inventory." },
                { id: "H-TEC-22", description: "Audit 'Light Bank': replace all fused bulbs in Wards.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional brand image.", proof: "Walkthrough", trainerNotes: "Check bed-head lights specifically." },
                { id: "H-TEC-23", description: "Verify 'Medical Gas' leak status (Soap-bubble test).", priority: "High", riskLevel: "High", consequence: "Gas wastage and explosion hazard.", proof: "Test Note", trainerNotes: "Check manifold connections." },
                { id: "H-TEC-24", description: "Inspect 'Outdoor Lighting' for security zones.", priority: "Medium", riskLevel: "Low", consequence: "Security blind spots at night.", proof: "Visual Check", trainerNotes: "Replace fused bulbs in < 24h." },
                { id: "H-TEC-25", description: "Final Technical sign-off on the facility.", priority: "High", riskLevel: "Low", consequence: "Loss of maintenance governance.", proof: "Signed Log", trainerNotes: "Report major part needs to COO." }
            ]
        },
        {
            title: "Patient Experience & ORM",
            department: "Admin",
            frequency: "Daily",
            role: "Customer Experience Lead",
            summary: "Protects the online brand reputation and governs patient feedback and arrival parity.",
            icon: "star",
            tasks: [
                { id: "H-CX-01", description: "Review Response Pulse: Reply to all Google/Practo reviews <24h.", priority: "High", riskLevel: "Medium", consequence: "Damaged reputation and drop in new patient volume.", proof: "Response Dashboard", trainerNotes: "Address 1-star reviews first with a personalized apology." },
                { id: "H-CX-02", description: "Verify Google Maps 'Live Status' and OPD Opening Hours.", priority: "High", riskLevel: "Low", consequence: "Patients arriving to a 'Closed' OPD; lost revenue.", proof: "Mobile Check", trainerNotes: "Update hours for public holidays instantly." },
                { id: "H-CX-03", description: "Audit 'Social Media DMs' for appointment inquiries.", priority: "Medium", riskLevel: "Low", consequence: "Lost revenue via unread inquiries.", proof: "Inbox Status", trainerNotes: "Target < 30 minute response time." },
                { id: "H-CX-04", description: "Review 'Patient Feedback Forms' for discharge trends.", priority: "High", riskLevel: "Low", consequence: "Undetected drop in care or food quality.", proof: "Trend Log", trainerNotes: "Highlight recurring complaints in GM briefing." },
                { id: "H-CX-05", description: "Verify 'Doctor Arrival' matches appointment start times.", priority: "High", riskLevel: "Low", consequence: "Patient frustration and review drop.", proof: "Roster Match", trainerNotes: "Notify patients if doctor is > 15 min late." },
                { id: "H-CX-06", description: "Check availability of 'Drinking Water' in OPD waiting areas.", priority: "Medium", riskLevel: "Low", consequence: "Poor patient experience scores.", proof: "Visual Audit", trainerNotes: "Stock clean cups every 2 hours." },
                { id: "H-CX-07", description: "Verify 'Helpdesk' staffing during peak OPD slots (9 AM - 1 PM).", priority: "High", riskLevel: "Low", consequence: "Chaos at reception and lost files.", proof: "Roster Check", trainerNotes: "Assign backups for lunch breaks." },
                { id: "H-CX-08", description: "Audit 'Patient Education' posters for outdated content.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional image.", proof: "Visual Walkthrough", trainerNotes: "Replace torn or faded posters." },
                { id: "H-CX-09", description: "Check 'Complaint Box' for physical handwritten notes.", priority: "Medium", riskLevel: "Low", consequence: "Unaddressed patient grievances.", proof: "Pickup Log", trainerNotes: "Collect and log notes daily at 5 PM." },
                { id: "H-CX-10", description: "Verify 'Wheelchair' availability at the main entrance.", priority: "High", riskLevel: "Medium", consequence: "Delayed transport for disabled patients.", proof: "Visual Check", trainerNotes: "Maintain min 2 units at the gate." },
                { id: "H-CX-11", description: "Monitor 'OPD Queue' TAT (Target < 30 mins wait).", priority: "Medium", riskLevel: "Low", consequence: "Patient walk-outs.", proof: "Token Report", trainerNotes: "Alert GM if queue exceeds 1 hour." },
                { id: "H-CX-12", description: "Audit 'Front Office' telephone etiquette (Dial test).", priority: "Medium", riskLevel: "Low", consequence: "Poor first impression for booking inquiries.", proof: "Test Call", trainerNotes: "Check for standard greeting protocol." },
                { id: "H-CX-13", description: "Verify 'Health Checkup' package display visibility.", priority: "Low", riskLevel: "Low", consequence: "Missed preventative care revenue.", proof: "Photo", trainerNotes: "Ensure brochures are at eye-level." },
                { id: "H-CX-14", description: "Check 'Pharmacy Wait-Time' during peak discharge.", priority: "Medium", riskLevel: "Low", consequence: "Patient frustration at end-of-visit.", proof: "Sample Log", trainerNotes: "Target med delivery < 15 mins." },
                { id: "H-CX-15", description: "Audit 'Wait-Area' music and temperature (Target 24°C).", priority: "Low", riskLevel: "Low", consequence: "Patient discomfort.", proof: "Daily Log", trainerNotes: "Avoid loud or high-tempo music." },
                { id: "H-CX-16", description: "Verify 'ID Badge' usage for all front-office staff.", priority: "Low", riskLevel: "Low", consequence: "Difficulty in patient communication.", proof: "Briefing Log", trainerNotes: "Badges must be clearly visible." },
                { id: "H-CX-17", description: "Check 'Website' booking links functionality.", priority: "High", riskLevel: "Medium", consequence: "Systemic barrier to new appointments.", proof: "Booking Test", trainerNotes: "Confirm 'OTP' is received." },
                { id: "H-CX-18", description: "Review 'Practo/ZocDoc' inventory sync.", priority: "High", riskLevel: "Medium", consequence: "Overbooking conflicts.", proof: "System Audit", trainerNotes: "Check slot availability." },
                { id: "H-CX-19", description: "Audit 'Cafeteria' menu for patient-safe options.", priority: "Medium", riskLevel: "Medium", consequence: "Cross-allergy risk for patient relatives.", proof: "Menu Review", trainerNotes: "Check for 'Low Sugar' and 'Vegan' labels." },
                { id: "H-CX-20", description: "Check 'Parking' ease and valet response time.", priority: "Low", riskLevel: "Low", consequence: "Negative first-touch perception.", proof: "Sample Log", trainerNotes: "Valet must return car in < 10 mins." },
                { id: "H-CX-21", description: "Verify 'Visitor Policy' display at Ward entrances.", priority: "Low", riskLevel: "Low", consequence: "Argument with patient relatives.", proof: "Signage Check", trainerNotes: "Must include 'Visiting Hours' clearly." },
                { id: "H-CX-22", description: "Audit 'Appointment Reminders' (SMS/Call) status.", priority: "Medium", riskLevel: "Low", consequence: "High 'No-Show' rates for doctors.", proof: "System Log", trainerNotes: "Reminders must go 24h prior." },
                { id: "H-CX-23", description: "Check 'Discharge Summary' legibility audit.", priority: "High", riskLevel: "High", consequence: "Post-discharge medication errors.", proof: "File Audit", trainerNotes: "Handwritten summaries must be printed." },
                { id: "H-CX-24", description: "Review 'International Patient' concierge status.", priority: "Medium", riskLevel: "Low", consequence: "Service failure for high-margin niche.", proof: "VIP File", trainerNotes: "Check flight/hotel booking logs." },
                { id: "H-CX-25", description: "Final daily CX sign-off on reputation.", priority: "High", riskLevel: "Low", consequence: "Loss of reputation governance.", proof: "Signed Dashboard", trainerNotes: "Submit 'Complaint Status' report to GM." }
            ]
        },
        {
            title: "Pharmacy & Supply Chain",
            department: "Pharmacy",
            frequency: "Daily",
            role: "Logistics Lead",
            summary: "Command module for drug integrity, narcotics control, and medical supply chain.",
            icon: "pill",
            tasks: [
                { id: "H-SUP-01", description: "Narcotics Vault: Independent double-count of all units.", priority: "High", riskLevel: "High", consequence: "Drug diversion and catastrophic criminal theft.", proof: "Dual-Sign Log", trainerNotes: "Witnessed audit mandatory at end of shift." },
                { id: "H-SUP-02", description: "Cold Chain: Log pharmacy fridge temps for biologics.", priority: "High", riskLevel: "High", consequence: "Ineffective vaccine administration worth millions.", proof: "Temp Log", trainerNotes: "Log twice daily: 8 AM and 8 PM." },
                { id: "H-SUP-03", description: "Audit 'High-Alert' medication labeling (LASA meds).", priority: "High", riskLevel: "High", consequence: "Wrong drug administration (Fatal error).", proof: "Visual Audit", trainerNotes: "Use Tall-Man lettering for similar drug names." },
                { id: "H-SUP-04", description: "Verify 'FSSAI/Drug License' of all current suppliers.", priority: "High", riskLevel: "High", consequence: "Legal liability for unvetted/illegal sourcing.", proof: "License Repository", trainerNotes: "Initiate vendor review every 6 months." },
                { id: "H-SUP-05", description: "Check 'Near-Expiry' stock audit (Target >90 days).", priority: "High", riskLevel: "Medium", consequence: "Serving expired product and financial loss.", proof: "Expiry Sweep", trainerNotes: "Flag anything expiring in < 60 days for return." },
                { id: "H-SUP-06", description: "Reconcile 'Implant' stock against surgical KOTs.", priority: "High", riskLevel: "High", consequence: "Theft of high-value stents or orthopedic assets.", proof: "Ledger Match", trainerNotes: "Serial numbers must match the patient bill." },
                { id: "H-SUP-07", description: "Audit 'Emergency Drug' stock levels in Wards.", priority: "High", riskLevel: "High", consequence: "Treatment halt during life-critical event.", proof: "Stock Sheet", trainerNotes: "Check Adrenaline and Atropine counts." },
                { id: "H-SUP-08", description: "Verify 'Medical Gas' manifold backup pressure.", priority: "High", riskLevel: "High", consequence: "Total supply failure (Fatal).", proof: "Manifold Log", trainerNotes: "Maintain min 50% backup cylinder count." },
                { id: "H-SUP-09", description: "Check 'Receiving Temp' for temperature-sensitive drugs.", priority: "High", riskLevel: "High", consequence: "Accepting compromised cold-chain stock.", proof: "Receiving Note", trainerNotes: "Reject if data-logger shows spike > 8°C." },
                { id: "H-SUP-10", description: "Audit 'Pharmacy Dispensing' TAT for OPD patients.", priority: "Medium", riskLevel: "Low", consequence: "Patient frustration and lost sales.", proof: "Queue Report", trainerNotes: "Target prep time < 10 minutes." },
                { id: "H-SUP-11", description: "Verify 'Double-Check' for high-alert drug dispensing.", priority: "High", riskLevel: "High", consequence: "Dispensing errors leading to fatality.", proof: "Dispensing Note", trainerNotes: "Two pharmacists must initial the slip." },
                { id: "H-SUP-12", description: "Check 'Pharmacy Hygiene' and dust-free shelving.", priority: "Medium", riskLevel: "Low", consequence: "Physical contamination of loose medicines.", proof: "Cleaning Log", trainerNotes: "Clean shelves with 70% alcohol weekly." },
                { id: "H-SUP-13", description: "Log 'Antibiotic' consumption trends for MD audit.", priority: "Medium", riskLevel: "Medium", consequence: "Rise of antibiotic resistance.", proof: "System Report", trainerNotes: "Flag usage of 'Reserve Group' drugs." },
                { id: "H-SUP-14", description: "Audit 'Purchase Price' against market rate list.", priority: "Low", riskLevel: "Low", consequence: "Inflated procurement costs.", proof: "Price Audit", trainerNotes: "Check for lower-cost generic alternatives." },
                { id: "H-SUP-15", description: "Verify 'Lead Time' for critical life-saving consumables.", priority: "Medium", riskLevel: "Medium", consequence: "Stockouts of essential items.", proof: "PO Tracker", trainerNotes: "Order when stock hits 15-day buffer." },
                { id: "H-SUP-16", description: "Check 'Narcotic Safe' anchor and lock integrity.", priority: "High", riskLevel: "High", consequence: "Physical theft of controlled substances.", proof: "Visual Check", trainerNotes: "Safe must be bolted to the floor." },
                { id: "H-SUP-17", description: "Monitor 'Stock Return' frequency from Wards.", priority: "Medium", riskLevel: "Low", consequence: "Unchecked inventory movement and theft risk.", proof: "Return Log", trainerNotes: "Flag any Ward with > 10% return rate." },
                { id: "H-SUP-18", description: "Verify 'Staff Access' codes for the pharmacy server.", priority: "High", riskLevel: "Medium", consequence: "Unauthorized billing or stock modification.", proof: "User Log", trainerNotes: "Remove access for terminated staff." },
                { id: "H-SUP-19", description: "Audit 'Oxygen Cylinder' hydrostatic test dates.", priority: "High", riskLevel: "High", consequence: "Cylinder explosion hazard.", proof: "Test Record", trainerNotes: "Check date punched on the neck." },
                { id: "H-SUP-20", description: "Check availability of 'Dispensing Bags' and labels.", priority: "Low", riskLevel: "Low", consequence: "Professional brand dilution.", proof: "Stock Audit", trainerNotes: "Maintain 1-week supply." },
                { id: "H-SUP-21", description: "Verify 'Drug-Drug Interaction' alerts in POS are active.", priority: "High", riskLevel: "High", consequence: "Life-threatening prescribing errors.", proof: "System Test", trainerNotes: "Try entering two interacting meds." },
                { id: "H-SUP-22", description: "Monitor 'Pharmacy Cashier' voided transactions.", priority: "High", riskLevel: "Medium", consequence: "Revenue skimming theft.", proof: "Void Report", trainerNotes: "Verify reason for all cancelled bills." },
                { id: "H-SUP-23", description: "Audit 'Stock Adjustment' ledger for the month.", priority: "Medium", riskLevel: "High", consequence: "Masking stock theft via 'Damage' entries.", proof: "Adjustment Log", trainerNotes: "Check reasons for all bulk adjustments." },
                { id: "H-SUP-24", description: "Check 'Generator/UPS' backup for pharmacy fridges.", priority: "High", riskLevel: "High", consequence: "Overnight cold-chain failure.", proof: "Electrical Test", trainerNotes: "Ensure fridges are on the 'Essential' line." },
                { id: "H-SUP-25", description: "Final daily Pharmacy & Supply Chain sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of governance.", proof: "Signed Dispatch", trainerNotes: "Submit 'Critical Stock' report to GM." }
            ]
        }
    ]
};

    