import type { PremiumPack } from "@/lib/premium-packs";

export const healthcare_and_hospital_operations: PremiumPack = {
    id: 'healthcare_and_hospital_operations',
    title: "Hospital Operations System",
    priceINR: 5999,
    priceUSD: 79,
    paymentId: 'pl_RaWEBHhFLQENxC',
    lemonSqueezyUrl: 'https://moremeets.lemonsqueezy.com/buy/129cb25a-b177-4a6d-a1bf-d8fafc24a09d',
    category: "Healthcare",
    description: "The Sovereign v16.0 clinical governance engine for hospitals. Hardening 200 technical control points across 12 institutional roles to protect patient safety.",
    icon: "hospital",
    badgeText: "V16.0 SOVEREIGN",
    badgeVariant: "destructive",
    whoIsItFor: ["Medical Directors", "Hospital COOs", "Nursing Superintendents", "Quality Heads", "Clinical In-charges"],
    sampleItems: [
        { text: "<strong>WHO Surgical Safety</strong>: Pre-incision time-out seals and site verification.", icon: "shield-check" },
        { text: "<strong>Narcotics Command</strong>: Double-blind vault count logs and diversion monitoring.", icon: "pill" },
        { text: "<strong>Infection Control</strong>: CSSD sterility indicators and ICU hygiene cycles.", icon: "sparkles" }
    ],
    checklists: [
        {
            title: "Executive Governance",
            department: "Clinical",
            frequency: "Daily",
            role: "Medical Director",
            summary: "High-level strategic oversight of clinical risk.",
            icon: "crown",
            tasks: [
                { id: "H-EXE-01", description: "Review Sentinel Event Log; cross-match near-miss clinical errors with department-head escalation signatures.", priority: "High", riskLevel: "High", consequence: "Fatal patient harm and total loss of license.", proof: "Log Audit" },
                { id: "H-EXE-02", description: "Audit physician credentials for 100% validity; verify current DMC/MCI registration for 10 random consultants.", priority: "High", riskLevel: "High", consequence: "Practice by unqualified practitioners.", proof: "Credential Registry" },
                { id: "H-EXE-03", description: "Verify availability of specialized consultants for ICU on-call; match physical roster to digital availability.", priority: "High", riskLevel: "High", consequence: "Clinical halt during patient crisis.", proof: "On-call Roster" },
                { id: "H-EXE-04", description: "Review morbidity and mortality committee minutes; confirm implementation of 100% of corrective actions.", priority: "High", riskLevel: "Medium", consequence: "Lack of clinical accountability.", proof: "Minutes Folder" },
                { id: "H-EXE-05", description: "Audit patient consent forms; witness 10 random IP files for valid authorized signatures pre-surgery.", priority: "High", riskLevel: "High", consequence: "Criminal liability for unauthorized surgery.", proof: "File Audit" },
                { id: "H-EXE-06", description: "Triage medical legal notices; verify resolution status for any open claim older than 48 hours.", priority: "High", riskLevel: "High", consequence: "Unmitigated legal exposure.", proof: "Notice Log" },
                { id: "H-EXE-07", description: "Monitor clinical outcome indicators; analyze mortality and readmission benchmarks vs internal targets.", priority: "High", riskLevel: "High", consequence: "Systemic decline in care quality.", proof: "KPI Dashboard" },
                { id: "H-EXE-08", description: "Review clinical privileging; verify 100% match between surgeon specialty and active surgical list.", priority: "High", riskLevel: "High", consequence: "Malpractice liability.", proof: "Privilege File" },
                { id: "H-EXE-09", description: "Audit doctor attendance parity; match check-in timestamps to today's active IP surgical schedules.", priority: "High", riskLevel: "Medium", consequence: "Delayed life-saving procedures.", proof: "Attendance Log" },
                { id: "H-EXE-10", description: "Conduct weekly briefing with HODs; verify alignment on clinical standard parity across all departments.", priority: "Low", riskLevel: "Low", consequence: "Operational silos.", proof: "Briefing Note" },
                { id: "H-EXE-11", description: "Verify FSSAI compliance for hospital kitchen; inspect active license display and health certifications.", priority: "Medium", riskLevel: "Medium", consequence: "Inpatient foodborne illness risk.", proof: "License Matrix" },
                { id: "H-EXE-12", description: "Review patient rights charter implementation; verify visibility of bilingual posters in all IP corridors.", priority: "Low", riskLevel: "Low", consequence: "Patient attrition and poor sentiment.", proof: "Poster Audit" },
                { id: "H-EXE-13", description: "Collate clinical quality summary; prepare board pack for quarterly institutional risk review.", priority: "Medium", riskLevel: "Low", consequence: "Loss of executive oversight.", proof: "Board Pack" },
                { id: "H-EXE-14", description: "Audit Ethics Committee minutes; verify 100% compliance with clinical trial monitoring protocols.", priority: "Medium", riskLevel: "High", consequence: "Regulatory violations.", proof: "Committee Book" },
                { id: "H-EXE-15", description: "Execute weekly management summary sign-off; witness final dashboard closure for the group.", priority: "High", riskLevel: "Low", consequence: "Loss of duty control.", proof: "Signed Summary" }
            ]
        },
        {
            title: "Quality & Compliance",
            department: "Quality",
            frequency: "Daily",
            role: "Quality Head",
            summary: "Governance for NABH indicators and accreditation readiness.",
            icon: "shield-check",
            tasks: [
                { id: "H-QH-01", description: "NABH Sync: Verify 100% data entry for daily clinical indicators in the master accreditation portal.", priority: "High", riskLevel: "Medium", consequence: "Accreditation lapse.", proof: "Data Portal" },
                { id: "H-QH-02", description: "Audit patient charts; physically inspect 5 random files for 'Initial Assessment' completion within 1 hour.", priority: "High", riskLevel: "Medium", consequence: "Clinical care delay.", proof: "Chart Audit" },
                { id: "H-QH-03", description: "Non-Conformance Registry: Review all open clinical deviations; verify closed-loop resolution in < 24h.", priority: "High", riskLevel: "High", consequence: "Recurring clinical errors.", proof: "NC Tracker" },
                { id: "H-QH-04", description: "Audit gas manifold alarm; trigger low-pressure simulation to verify buzzer sync at Nurse station.", priority: "High", riskLevel: "High", consequence: "Oxygen failure in ICU/OT (Fatal).", proof: "Alarm Log" },
                { id: "H-QH-05", description: "Verify medical equipment AMC; check next service dates for 100% of ventilators and monitors.", priority: "Medium", riskLevel: "Medium", consequence: "Equipment downtime.", proof: "Contract Log" },
                { id: "H-QH-06", description: "Monitor medication error logs; analyze patterns in transcription or dispensing misses for the shift.", priority: "High", riskLevel: "High", consequence: "Unmonitored patient safety risks.", proof: "Error Log" },
                { id: "H-QH-07", description: "Spot-check hand hygiene; conduct random RLU swab test at IP bedside entry points.", priority: "Medium", riskLevel: "High", consequence: "Hospital-acquired infections.", proof: "Observation Note" },
                { id: "H-QH-08", description: "Verify Fall Risk identifiers; physically confirm yellow wristband usage for high-risk patients.", priority: "High", riskLevel: "Medium", consequence: "Patient injury litigation.", proof: "Visual Audit" },
                { id: "H-QH-09", description: "Audit Adverse Drug Reaction system; verify 100% of reported ADRs are uploaded to national registry.", priority: "High", riskLevel: "High", consequence: "Regulatory non-compliance.", proof: "ADR Registry" },
                { id: "H-QH-10", description: "Conduct mock audit of CSSD biological indicators; verify negative growth in 24-hour spore incubation.", priority: "High", riskLevel: "High", consequence: "Systemic sterilization failure.", proof: "Lab Report" },
                { id: "H-QH-11", description: "Review patient grievance TAT; verify resolution for all complaints exceeding 24-hour threshold.", priority: "Medium", riskLevel: "Low", consequence: "Reputational damage.", proof: "Grievance Portal" },
                { id: "H-QH-12", description: "Verify staff competency logs; check ICU nurse certifications for advanced life-support validity.", priority: "High", riskLevel: "High", consequence: "Incompetent care in high-risk zones.", proof: "Skills Matrix" },
                { id: "H-QH-13", description: "Audit 'Vulnerable Patient' identifiers; physically confirm presence of 'At Risk' markers for kids/elderly.", priority: "High", riskLevel: "Medium", consequence: "Child safety breach.", proof: "Registry Audit" },
                { id: "H-QH-14", description: "Check negative pressure rooms; verify air-exchange cycles match clinical isolation standards.", priority: "High", riskLevel: "High", consequence: "Infection outbreak.", proof: "BMS Screen" },
                { id: "H-QH-15", description: "Execute Quality shift sign-off; witness final compliance data backup for the department.", priority: "High", riskLevel: "Low", consequence: "Loss of oversight.", proof: "Signed Sheet" }
            ]
        },
        {
            title: "Nursing Governance",
            department: "Nursing",
            frequency: "Daily",
            role: "Nursing Superintendent",
            summary: "Command for nursing manpower and care standards.",
            icon: "heart-pulse",
            tasks: [
                { id: "H-NS-01", description: "Verify nursing roster parity; match physical bedside attendance to today's active IP census.", priority: "High", riskLevel: "Medium", consequence: "Supervision gaps.", proof: "Attendance Match" },
                { id: "H-NS-02", description: "Audit Code Blue buttons; trigger 3 random signals to verify connectivity to Emergency response team.", priority: "High", riskLevel: "High", consequence: "Fatal resuscitation failure.", proof: "Signal Test" },
                { id: "H-NS-03", description: "Check grooming standards; physically inspect uniforms, ID badges, and hygiene compliance during briefing.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution.", proof: "Briefing Log" },
                { id: "H-NS-04", description: "Verify handover documentation; confirm 100% completion of SBAR forms at shift change.", priority: "High", riskLevel: "High", consequence: "Loss of clinical continuity.", proof: "Handover Sheet" },
                { id: "H-NS-05", description: "Audit medicine vault keys; physically witness handover and sign-off in the custody register.", priority: "High", riskLevel: "High", consequence: "Unauthorized drug access.", proof: "Key Register" },
                { id: "H-NS-06", description: "Monitor call-bell TAT; analyze system logs for any delay exceeding the 2-minute target.", priority: "Medium", riskLevel: "Low", consequence: "Patient frustration.", proof: "System Report" },
                { id: "H-NS-07", description: "Inspect linen par levels; physically count backup sets available for emergency IP admissions.", priority: "Medium", riskLevel: "Low", consequence: "Operational friction.", proof: "Stock Check" },
                { id: "H-NS-08", description: "Audit staff health check registry; verify 100% validity of annual clinical fitness certs.", priority: "High", riskLevel: "Medium", consequence: "Occupational health risk.", proof: "Health File" },
                { id: "H-NS-09", description: "Spot-check patient files; verify discharge summary clarity for 5 random cases pre-billing.", priority: "Medium", riskLevel: "Low", consequence: "Delayed discharge cycle.", proof: "Sample Check" },
                { id: "H-NS-10", description: "Witness 'Shift-Handover Briefing' in high-care units; verify verbal capture of critical alerts.", priority: "High", riskLevel: "High", consequence: "Clinical errors.", proof: "Meeting Note" },
                { id: "H-NS-11", description: "Verify CPR responder availability; match BLS/ACLS certifications against the daily ward roster.", priority: "High", riskLevel: "High", consequence: "Resuscitation failure.", proof: "Roster Audit" },
                { id: "H-NS-12", description: "Audit linen grey-scale; physically reject and tag any stained or frayed IP bedding.", priority: "Low", riskLevel: "Low", consequence: "Poor perception of luxury.", proof: "Visual Audit" },
                { id: "H-NS-13", description: "Monitor dialysis bed readiness; verify completion of disinfection cycle pre-patient intake.", priority: "High", riskLevel: "Medium", consequence: "Cross-infection.", proof: "Ready Log" },
                { id: "H-NS-14", description: "Conduct nurse grievance pulse; document and escalate any equipment or facility barrier reported.", priority: "Low", riskLevel: "Low", consequence: "High staff churn.", proof: "Diary Note" },
                { id: "H-NS-15", description: "Audit laundry TAT; verify 24-hour return of soiled IP linens from vendor.", priority: "Low", riskLevel: "Low", consequence: "Inventory shortage.", proof: "TAT Log" },
                { id: "H-NS-16", description: "Check par levels of patient kits; verify 100% availability of admission toiletries.", priority: "Low", riskLevel: "Low", consequence: "CX failure.", proof: "Stock Sheet" },
                { id: "H-NS-17", description: "Confirm crash cart seal integrity; physically verify serial number matches last lock-down entry.", priority: "High", riskLevel: "High", consequence: "Missing emergency supplies.", proof: "Seal Register" },
                { id: "H-NS-18", description: "Final daily nursing command sign-off; witness shift-end reconciliation of clinical logs.", priority: "High", riskLevel: "Low", consequence: "Governance gap.", proof: "Signed Summary" }
            ]
        },
        {
            title: "Ward & Bedside Execution",
            department: "Nursing",
            frequency: "Hourly",
            role: "Ward Nurse",
            summary: "Daily operational checks at the patient bedside.",
            icon: "clipboard-list",
            tasks: [
                { id: "H-WN-01", description: "Verify patient ID wristband; match MRN against clinical chart before any drug administration.", priority: "High", riskLevel: "High", consequence: "Treatment given to wrong patient (Fatal).", proof: "Visual Audit" },
                { id: "H-WN-02", description: "Check IP bed-rails; physically confirm top and middle rails locked for all fall-risk patients.", priority: "High", riskLevel: "High", consequence: "Patient falls and litigation.", proof: "Walkthrough Log" },
                { id: "H-WN-03", description: "Document handover data; execute SBAR protocol during physical bedside shift exchange.", priority: "High", riskLevel: "High", consequence: "Clinical continuity failure.", proof: "Handover Note" },
                { id: "H-WN-04", description: "Inspect infusion pumps; verify calibration date and power cable integrity.", priority: "Medium", riskLevel: "Medium", consequence: "Dosing errors.", proof: "Visual Check" },
                { id: "H-WN-05", description: "Log bedside monitor connectivity; verify active signal sync at central Nurse station.", priority: "High", riskLevel: "High", consequence: "Unmonitored patient vitals.", proof: "System Screen" },
                { id: "H-WN-06", description: "Verify backup suction and oxygen points; physically trigger test-flow at the headwall.", priority: "High", riskLevel: "High", consequence: "Asphyxiation risk during crisis.", proof: "Manifold Check" },
                { id: "H-WN-07", description: "Sanitize high-touch surfaces; wipe down bed-rails and over-bed tables with approved solution.", priority: "Medium", riskLevel: "High", consequence: "HAI transmission.", proof: "Cleaning Sheet" },
                { id: "H-WN-08", description: "Audit high-alert medication; execute independent dual-sign verification for insulin/heparin.", priority: "High", riskLevel: "High", consequence: "Fatal dosing error.", proof: "Dual-Sign Log" },
                { id: "H-WN-09", description: "Verify table positioning; confirm water-jugs and call-bells are within patient reach.", priority: "Low", riskLevel: "Low", consequence: "Patient discomfort.", proof: "Visual Check" },
                { id: "H-WN-10", description: "Empty and document drains; log volume and color for all active surgical patients.", priority: "High", riskLevel: "Medium", consequence: "Documentation failure.", proof: "Drainage Log" },
                { id: "H-WN-11", description: "Check medicine expiry; physically audit ward-stock for any item with < 30 days shelf life.", priority: "High", riskLevel: "Medium", consequence: "Ineffective treatment.", proof: "Expiry Audit" },
                { id: "H-WN-12", description: "Measure noise levels; verify decibel count in high-care zones is < 45dB.", priority: "Low", riskLevel: "Low", consequence: "Poor recovery environment.", proof: "Meter Reading" },
                { id: "H-WN-13", description: "Verify pressure mattress function; physically confirm inflation for categorized bedsore-risk patients.", priority: "Medium", riskLevel: "Low", consequence: "Patient harm.", proof: "Visual Check" },
                { id: "H-WN-14", description: "Check emergency call buttons; trigger 5 random IP washroom signals to verify reset logic.", priority: "High", riskLevel: "High", consequence: "Undetected fall.", proof: "Signal Test" },
                { id: "H-WN-15", description: "Audit allergy stickers; physically confirm presence of red-alert marker on designated beds.", priority: "High", riskLevel: "High", consequence: "Fatal reaction.", proof: "Visual Check" },
                { id: "H-WN-16", description: "Verify IP file return; check file tracking log post-patient discharge.", priority: "Medium", riskLevel: "Low", consequence: "Lost documentation.", proof: "File Register" },
                { id: "H-WN-17", description: "Audit sanitizer refill; physically check dispensers at every patient room entry point.", priority: "High", riskLevel: "High", consequence: "Infection risk.", proof: "Stock Check" },
                { id: "H-WN-18", description: "Final ward handover sign-off; witness transfer of clinical custody initials.", priority: "High", riskLevel: "Low", consequence: "Governance gap.", proof: "Signed Sheet" }
            ]
        },
        {
            title: "Surgical Suite (OT)",
            department: "Surgery",
            frequency: "Per Show",
            role: "OT In-charge",
            summary: "Zero-fail protocols for surgical safety and sterility.",
            icon: "shield-check",
            tasks: [
                { id: "H-OT-01", description: "Execute WHO 'Time Out'; witness surgeon, anesthetist, and nurse verbal confirmation of site and patient.", priority: "High", riskLevel: "High", consequence: "Wrong-site surgery (Fatal never-event).", proof: "Surgical Checklist" },
                { id: "H-OT-02", description: "Verify sterility indicators; check internal chemical indicator change for every instrument set.", priority: "High", riskLevel: "High", consequence: "Post-operative septicemia.", proof: "Indicator Tape" },
                { id: "H-OT-03", description: "Log medical gas manifold pressure; manifold gauge must read between 4-5 kg/cm2.", priority: "High", riskLevel: "High", consequence: "Intra-operative hypoxia risk.", proof: "Gauge Log" },
                { id: "H-OT-04", description: "Audit CSSD biological indicators; verify negative growth in 24-hour spore incubation test.", priority: "High", riskLevel: "High", consequence: "Systemic sterilization failure.", proof: "Lab Report" },
                { id: "H-OT-05", description: "Check OT positive pressure; verify manometer reading matches sterile zone targets.", priority: "Medium", riskLevel: "Medium", consequence: "Contaminated air-flow.", proof: "Gauge Check" },
                { id: "H-OT-06", description: "Physical count: Match needles, sponges, and blades post-op with independent witness.", priority: "High", riskLevel: "High", consequence: "Retained foreign body in patient.", proof: "Count Sheet" },
                { id: "H-OT-07", description: "Verify fumigation status; confirm deep-clean completion certificate pre-OT opening.", priority: "High", riskLevel: "Medium", consequence: "Microbial buildup.", proof: "Fumigation Log" },
                { id: "H-OT-08", description: "Inspect UPS backup runtime; verify surgical lights operate for >10 mins on battery load.", priority: "High", riskLevel: "High", consequence: "Surgical halt during power flip.", proof: "Load Test" },
                { id: "H-OT-09", description: "Verify scrub-sink soap; physically confirm dispenser full and water temp at 40°C.", priority: "Low", riskLevel: "Low", consequence: "Ineffective hand-hygiene.", proof: "Temp Log" },
                { id: "H-OT-10", description: "Log surgical staff PPE; verify 100% compliance with double-masking and hairnet seals.", priority: "High", riskLevel: "High", consequence: "Patient contamination.", proof: "Daily Audit" },
                { id: "H-OT-11", description: "Check OT door sensors; verify auto-seal logic for sliding sterile doors.", priority: "Medium", riskLevel: "Low", consequence: "Breach of sterile zone.", proof: "Visual Check" },
                { id: "H-OT-12", description: "Audit anesthesia self-test; verify digital log of machine calibration pre-first case.", priority: "High", riskLevel: "High", consequence: "Mechanical failure during sedation.", proof: "Machine Log" },
                { id: "H-OT-13", description: "Verify recovery bed availability; match PACU status with active surgical pipeline.", priority: "Medium", riskLevel: "Medium", consequence: "Post-op gridlock.", proof: "Status App" },
                { id: "H-OT-14", description: "Check surgical gown par-levels; physically count sterile stock available for today's list.", priority: "Low", riskLevel: "Low", consequence: "Delayed show start.", proof: "Stock Sheet" },
                { id: "H-OT-15", description: "Inspect cautery grounding; physically check patient return electrode cables for fraying.", priority: "High", riskLevel: "High", consequence: "Electrical burns.", proof: "Safety Tag" },
                { id: "H-OT-16", description: "Verify biopsy sample retrieval; witness transfer of labeled specimen to pathology log.", priority: "High", riskLevel: "High", consequence: "Loss of patient sample.", proof: "Handover Log" },
                { id: "H-OT-17", description: "Conduct spot-check of suction unit; verify vacuum levels match clinical thresholds.", priority: "High", riskLevel: "High", consequence: "Airway obstruction risk.", proof: "Test Note" },
                { id: "H-OT-18", description: "Monitor OT temperature; target 18-21°C range to inhibit bacterial growth.", priority: "Medium", riskLevel: "Low", consequence: "Staff fatigue / Pathogen risk.", proof: "BMS Screen" },
                { id: "H-OT-19", description: "Log scavenger system function; verify waste gas extraction to prevent staff exposure.", priority: "High", riskLevel: "Medium", consequence: "Staff health hazard.", proof: "Flow Meter" },
                { id: "H-OT-20", description: "Final OT closure seal; physically verify medical gas valves off and locked at EOD.", priority: "High", riskLevel: "Low", consequence: "Explosion hazard.", proof: "Signed Summary" }
            ]
        },
        {
            title: "Pharmacy & Narcotics",
            department: "Pharmacy",
            frequency: "Daily",
            role: "Pharmacy Lead",
            summary: "Governance for controlled substances and medication integrity.",
            icon: "pill",
            tasks: [
                { id: "H-PL-01", description: "Narcotics Vault: Independent double-blind count of all Schedule X units with witness signature.", priority: "High", riskLevel: "High", consequence: "Internal theft and criminal liability.", proof: "Vault Register" },
                { id: "H-PL-02", description: "Cold Chain: Log medical fridge temp; verify range 2°C to 8°C twice per shift.", priority: "High", riskLevel: "High", consequence: "Ineffective vaccine administration.", proof: "Temp Log" },
                { id: "H-PL-03", description: "LASA Audit: Physically verify segregation of look-alike/sound-alike drugs on racks.", priority: "High", riskLevel: "High", consequence: "Medication mismatch.", proof: "Visual Check" },
                { id: "H-PL-04", description: "Remove pharmaceuticals; take down any stock with < 60 days to expiry for return-to-vendor.", priority: "High", riskLevel: "Medium", consequence: "Dispensing ineffective meds.", proof: "Expiry Log" },
                { id: "H-PL-05", description: "Challenge prescription errors; document 3 random illegible orders for doctor clarification.", priority: "Medium", riskLevel: "Low", consequence: "Dosing errors.", proof: "Query Log" },
                { id: "H-PL-06", description: "Verify digital inventory sync; match 10 random SKUs physical vs system count.", priority: "Medium", riskLevel: "Low", consequence: "Unmonitored stock-outs.", proof: "System Report" },
                { id: "H-PL-07", description: "Audit schedule-H sales; match 100% of dispensed bills against valid prescriptions.", priority: "High", riskLevel: "High", consequence: "Legal closure of pharmacy.", proof: "Bill Match" },
                { id: "H-PL-08", description: "Inspect storage humidity; verify hygrometer reading is < 60% for chemical stability.", priority: "Medium", riskLevel: "Medium", consequence: "Powder decay.", proof: "Hygrometer Reading" },
                { id: "H-PL-09", description: "Check crash-cart kit par-levels; physically count cardiac-drug stock for replacements.", priority: "High", riskLevel: "High", consequence: "Empty cart during emergency.", proof: "Stock Sheet" },
                { id: "H-PL-10", description: "Conduct spot-check for unauthorized staff entry into the restricted drug vault.", priority: "High", riskLevel: "High", consequence: "Narcotic diversion.", proof: "Access Log" },
                { id: "H-PL-11", description: "Verify RTV log; match returned recalled batches against vendor credit notes.", priority: "High", riskLevel: "High", consequence: "Dispensing dangerous product.", proof: "Recall File" },
                { id: "H-PL-12", description: "Audit billing discounts; verify valid staff/scheme ID for any manual price correction.", priority: "Medium", riskLevel: "Low", consequence: "Revenue leakage.", proof: "Audit Report" },
                { id: "H-PL-13", description: "Verify night-chemist credentials; physically check valid registration for shift-staff.", priority: "High", riskLevel: "High", consequence: "Practice by unregistered person.", proof: "Briefing Log" },
                { id: "H-PL-14", description: "Check par levels of pediatric drugs; verify availability of specialized infant suspensions.", priority: "Medium", riskLevel: "Low", consequence: "Operational delay.", proof: "Visual Check" },
                { id: "H-PL-15", description: "Inspect labeling accuracy; verify 100% of repackaged patient doses have clear barcode/expiry.", priority: "High", riskLevel: "High", consequence: "Wrong ingestion.", proof: "Label Audit" },
                { id: "H-PL-16", description: "Confirm final EOD vault seal; physically witness high-security lock-down.", priority: "High", riskLevel: "High", consequence: "Theft.", proof: "Seal Note" },
                { id: "H-PL-17", description: "Final shift handover initials; witness transfer of narcotics custody signature.", priority: "High", riskLevel: "Low", consequence: "Governance gap.", proof: "Signed Sheet" }
            ]
        },
        {
            title: "Biomedical Waste (EHS)",
            department: "Safety",
            frequency: "Daily",
            role: "EHS Officer",
            summary: "Regulatory compliance for bio-hazards and worker safety.",
            icon: "recycle",
            tasks: [
                { id: "H-EHS-01", description: "Verify color-coded waste segregation; physically inspect red, yellow, and blue bins at ward source.", priority: "High", riskLevel: "High", consequence: "Massive fines and cross-infection.", proof: "Visual Audit" },
                { id: "H-EHS-02", description: "Audit sharps-container fill; physically seal and replace any container exceeding 75% fill mark.", priority: "High", riskLevel: "High", consequence: "Needle-stick injury risk.", proof: "Visual Check" },
                { id: "H-EHS-03", description: "Log yellow-bag weight; match weight handover to CBMWTF vendor against ward logs.", priority: "High", riskLevel: "Medium", consequence: "Inaccurate reporting.", proof: "Weight Slip" },
                { id: "H-EHS-04", description: "Inspect spillage kits; verify par-levels of absorbent sand and pads per floor.", priority: "High", riskLevel: "High", consequence: "Toxic gas exposure.", proof: "Inventory Check" },
                { id: "H-EHS-05", description: "Verify radiation badges; confirm 100% of OT staff are wearing active dosimetry markers.", priority: "High", riskLevel: "High", consequence: "Legal claims.", proof: "Badge Registry" },
                { id: "H-EHS-06", description: "Audit thick-cut gloves; physically verify stock for 100% of cleaning teams.", priority: "High", riskLevel: "High", consequence: "Puncture injuries.", proof: "Stock Audit" },
                { id: "H-EHS-07", description: "Check fire-exit paths; verify zero obstructions in basement and technical zones.", priority: "High", riskLevel: "High", consequence: "Fatal entrapment.", proof: "Patrol Log" },
                { id: "H-EHS-08", description: "Verify LOTO on incinerator panel; physically check padlocks are applied during maintenance.", priority: "High", riskLevel: "High", consequence: "Industrial accident.", proof: "Permit Registry" },
                { id: "H-EHS-09", description: "Log effluent vitals; measure pH and TDS from the main hospital STP outlet.", priority: "Medium", riskLevel: "Medium", consequence: "Untreated discharge fines.", proof: "Vitals Book" },
                { id: "H-EHS-10", description: "Inspect safety signage; verify high-visibility hazard markers in radiology zones.", priority: "Low", riskLevel: "Low", consequence: "Slipping culture.", proof: "Photo" },
                { id: "H-EHS-11", description: "Verify spill training status; confirm 100% of shift-staff have completed quarterly mock response.", priority: "High", riskLevel: "Medium", consequence: "Chemical leak chaos.", proof: "Training Log" },
                { id: "H-EHS-12", description: "Audit waste bay hygiene; verify hourly cleaning cycle to prevent pest attraction.", priority: "Low", riskLevel: "Low", consequence: "Infestation.", proof: "Hourly Sheet" },
                { id: "H-EHS-13", description: "Check PEP kits; verify availability of post-exposure drugs in ER fridge.", priority: "High", riskLevel: "High", consequence: "Untreated infections.", proof: "Kit Registry" },
                { id: "H-EHS-14", description: "Inspect lead-apron integrity; perform annual crack test for 100% of radiology shielding.", priority: "High", riskLevel: "High", consequence: "Radiation leak.", proof: "Test Cert" },
                { id: "H-EHS-15", description: "Monitor potable water; log TDS purity at 10 random IP drinking points.", priority: "High", riskLevel: "High", consequence: "Inpatient epidemic.", proof: "TDS Reading" },
                { id: "H-EHS-16", description: "Execute EHS summary; witness final safety compliance initials for the campus.", priority: "High", riskLevel: "Low", consequence: "Governance gap.", proof: "Signed Summary" },
                { id: "H-EHS-17", description: "Final daily safety sign-off; witness shift-end security seal of hazard stores.", priority: "High", riskLevel: "Low", consequence: "Theft.", proof: "Signed Sheet" }
            ]
        },
        {
            title: "OPD & Diagnostics",
            department: "OPD",
            frequency: "Daily",
            role: "OPD Manager",
            summary: "Governs the patient pipeline and arrival parity.",
            icon: "stethoscope",
            tasks: [
                { id: "H-OPD-01", description: "Verify doctor arrival time; match check-in timestamp to scheduled appointment slots.", priority: "High", riskLevel: "Low", consequence: "Patient frustration.", proof: "Attendance Log" },
                { id: "H-OPD-02", description: "Monitor diagnostic report TAT; cross-match sample collection time vs digital report release.", priority: "Medium", riskLevel: "Medium", consequence: "Delayed diagnosis.", proof: "TAT Dashboard" },
                { id: "H-OPD-03", description: "Audit patient registration; verify 100% ID document scanning for new registrations.", priority: "High", riskLevel: "Low", consequence: "Demographic errors.", proof: "Registry Audit" },
                { id: "H-OPD-04", description: "Inspect collection kits; verify sterility seals and expiry for all lab vials.", priority: "High", riskLevel: "High", consequence: "Contaminated results.", proof: "Visual Check" },
                { id: "H-OPD-05", description: "Verify report delivery sync; match lab-to-ward courier log against receipt entries.", priority: "Medium", riskLevel: "Low", consequence: "Clinical lag.", proof: "System Sync" },
                { id: "H-OPD-06", description: "Check par levels of stationery; physically count patient files and registration forms.", priority: "Low", riskLevel: "Low", consequence: "Admin friction.", proof: "Stock Sheet" },
                { id: "H-OPD-07", description: "Audit wait-times; verify queue display sync for screening zones.", priority: "Medium", riskLevel: "Low", consequence: "Crowd chaos.", proof: "Queue Log" },
                { id: "H-OPD-08", description: "Inspect MRI/CT suites; verify zero unauthorized entry while magnet is active.", priority: "High", riskLevel: "High", consequence: "Fatal asset damage.", proof: "Access Log" },
                { id: "H-OPD-09", description: "Verify restroom hygiene; physically inspect OPD public washrooms every 60 mins.", priority: "Low", riskLevel: "Low", consequence: "Poor brand image.", proof: "Hourly Sheet" },
                { id: "H-OPD-10", description: "Test ER dial-tone; verify direct intercom line between OPD helpdesk and Trauma bay.", priority: "High", riskLevel: "Medium", consequence: "Comm failure.", proof: "Sound Test" },
                { id: "H-OPD-11", description: "Verify queue screen function; physically confirm patient token display is online.", priority: "Low", riskLevel: "Low", consequence: "Service friction.", proof: "Visual Check" },
                { id: "H-OPD-12", description: "Audit lab billing; match 5 random diagnostic slips against POS entries.", priority: "Medium", riskLevel: "Low", consequence: "Revenue leakage.", proof: "Bill Match" },
                { id: "H-OPD-13", description: "Check reagent par-levels; physically count critical blood-count kits.", priority: "High", riskLevel: "Medium", consequence: "Diagnostic halt.", proof: "Stock Check" },
                { id: "H-OPD-14", description: "Verify helpdesk grooming; inspect staff badges and uniform cleanliness.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution.", proof: "Briefing Log" },
                { id: "H-OPD-15", description: "Inspect specimen bags; verify 100% of bio-transport containers are double-sealed.", priority: "High", riskLevel: "Medium", consequence: "Leakage risk.", proof: "Visual Audit" },
                { id: "H-OPD-16", description: "Final OPD desk closure; witness cash-float reconciliation at shift end.", priority: "High", riskLevel: "Low", consequence: "Shortage.", proof: "Signed Log" },
                { id: "H-OPD-17", description: "Final daily operational sign-off; witness handover of open diagnostic cases.", priority: "High", riskLevel: "Low", consequence: "Governance gap.", proof: "Signed Sheet" }
            ]
        },
        {
            title: "Engineering & Medical Gas",
            department: "Engineering",
            frequency: "Daily",
            role: "Chief Engineer",
            summary: "Infrastructure uptime and life-support continuity.",
            icon: "wrench",
            tasks: [
                { id: "H-CE-01", description: "Inspect DG fuel level; dip-stick reading must match flow-meter baseline +/- 1%.", priority: "High", riskLevel: "High", consequence: "Blackout and clinical halt.", proof: "Meter Log" },
                { id: "H-CE-02", description: "Log medical gas manifold pressure; manifold gauge must read between 4-5 kg/cm2.", priority: "High", riskLevel: "High", consequence: "Intra-operative hypoxia risk (Fatal).", proof: "Manifold Log" },
                { id: "H-CE-03", description: "Test lift intercoms; physically trigger help button to verify link to Security desk.", priority: "High", riskLevel: "High", consequence: "Trapped visitors.", proof: "Sound Test" },
                { id: "H-CE-04", description: "Monitor RO purity; log TDS at dialysis entry point; target < 50 ppm.", priority: "High", riskLevel: "High", consequence: "Patient poisoning.", proof: "TDS Reading" },
                { id: "H-CE-05", description: "Audit UPS load; physically verify runtime of server-room batteries on simulated failover.", priority: "High", riskLevel: "High", consequence: "Data loss.", proof: "Load Test" },
                { id: "H-CE-06", description: "Check HVAC chiller discharge; verify target set-point 7°C +/- 1 in the BMS.", priority: "Medium", riskLevel: "Medium", consequence: "Patient discomfort.", proof: "BMS Screen" },
                { id: "H-CE-07", description: "Perform IR panel scan; inspect ward breaker banks for hotspots exceeding 60°C.", priority: "High", riskLevel: "High", consequence: "Electrical fire.", proof: "Scan Log" },
                { id: "H-CE-08", description: "Verify fire-pump mode; confirm 100% of pumps are in 'AUTO' position.", priority: "High", riskLevel: "High", consequence: "Zero suppression pressure.", proof: "Gauge Log" },
                { id: "H-CE-09", description: "Check gas cylinder par-levels; physically count reserve manifold banks.", priority: "High", riskLevel: "High", consequence: "Death during line failure.", proof: "Stock Check" },
                { id: "H-CE-10", description: "Log daily KWH yield; match solar/grid usage vs institution baseline.", priority: "Low", riskLevel: "Low", consequence: "Energy waste.", proof: "Meter Reading" },
                { id: "H-CE-11", description: "Verify OT suction motors; test vacuum pull pre-morning list.", priority: "High", riskLevel: "High", consequence: "Surgical safety failure.", proof: "Visual Check" },
                { id: "H-CE-12", description: "Inspect facade integrity; check for moisture seepage in clinical sterile zones.", priority: "Low", riskLevel: "Low", consequence: "Asset decay.", proof: "Walkthrough" },
                { id: "H-CE-13", description: "Audit plumbing logs; verify resolution of leaks in diagnostic wing < 4h.", priority: "Medium", riskLevel: "Low", consequence: "Equipment damage.", proof: "Log Book" },
                { id: "H-CE-14", description: "Verify AHU cleaning; physically inspect 5 filter pads for dust load.", priority: "Low", riskLevel: "Low", consequence: "Poor air quality.", proof: "Cleaning Card" },
                { id: "H-CE-15", description: "Monitor hot water; log boiler temp for IP supply (Target 55°C).", priority: "Medium", riskLevel: "Low", consequence: "Inpatient complaints.", proof: "Temp Log" },
                { id: "H-CE-16", description: "Check pump auto-logic; verify tank high-level sensor cutoff.", priority: "Medium", riskLevel: "Medium", consequence: "Flooding.", proof: "Gauge Check" },
                { id: "H-CE-17", description: "Execute triage alert; document all P1 equipment faults for morning briefing.", priority: "High", riskLevel: "Low", consequence: "Unmonitored decay.", proof: "Alert Note" },
                { id: "H-CE-18", description: "Final nightly sign-off; witness seal of engineering vault keys.", priority: "High", riskLevel: "Low", consequence: "Theft.", proof: "Signed Sheet" }
            ]
        },
        {
            title: "Hospital Security",
            department: "Security",
            frequency: "Daily",
            role: "Security Chief",
            summary: "Hardens the perimeter and manages high-risk access.",
            icon: "shield",
            tasks: [
                { id: "H-SC-01", description: "CCTV Audit: Confirm high-res coverage of narcotics vault entry with 30-day storage sync.", priority: "High", riskLevel: "High", consequence: "Untraceable internal theft.", proof: "Monitor Audit" },
                { id: "H-SC-02", description: "Visitor ID Capture: Audit gate log for 100% scanning of original government-issued photo IDs.", priority: "High", riskLevel: "High", consequence: "Unauthorized intruder access.", proof: "Registry Audit" },
                { id: "H-SC-03", description: "Random sobriety check: Execute breathalyzer test for 2 AM rotation guards.", priority: "High", riskLevel: "High", consequence: "Vulnerable perimeter.", proof: "Test Note" },
                { id: "H-SC-04", description: "Patrol ER entrance; physically verify zero obstructions for ambulance intake.", priority: "High", riskLevel: "High", consequence: "Fatal delay in trauma care.", proof: "Walkthrough" },
                { id: "H-SC-05", description: "Audit key cabinet; verify custody logs for 100% of OT and Pharmacy access.", priority: "High", riskLevel: "High", consequence: "Unauthorized vault entry.", proof: "Inventory Check" },
                { id: "H-SC-06", description: "Test panic buttons; trigger 5 random floor alarms to verify sync at main booth.", priority: "High", riskLevel: "High", consequence: "Comm failure during crisis.", proof: "Signal Test" },
                { id: "H-SC-07", description: "Verify perimeter lighting; inspect alleyways for dead bulbs after 6 PM.", priority: "Medium", riskLevel: "Medium", consequence: "Theft blind spots.", proof: "Visual Check" },
                { id: "H-SC-08", description: "Monitor morgue access; verify log match vs door-access timestamps.", priority: "High", riskLevel: "High", consequence: "Legal liability.", proof: "Access Book" },
                { id: "H-SC-09", description: "Staff bag-checks: Conduct 5 random searches for departing night-shift support staff.", priority: "Medium", riskLevel: "Medium", consequence: "Internal shrinkage.", proof: "Registry Note" },
                { id: "H-SC-10", description: "Verify Air Ambulance readiness; inspect landing zone for debris or unauthorized vehicles.", priority: "High", riskLevel: "High", consequence: "Trauma transport liability.", proof: "Cert File" },
                { id: "H-SC-11", description: "Audit security stationery; verify par-levels of visitor and attendant badges.", priority: "Low", riskLevel: "Low", consequence: "Admin friction.", proof: "Stock Check" },
                { id: "H-SC-12", description: "Inspect restricted zones; verify high-visibility 'No Entry' markers are intact.", priority: "Low", riskLevel: "Low", consequence: "Visitor trespassing.", proof: "Visual Audit" },
                { id: "H-SC-13", description: "Conduct toolbox talk; brief night guards on suspicious behavior indicators.", priority: "Low", riskLevel: "Low", consequence: "Slipping alertness.", proof: "Briefing Log" },
                { id: "H-SC-14", description: "Check metal detectors; verify sensitivity of 100% entrance archways.", priority: "High", riskLevel: "High", consequence: "Weapon entry risk.", proof: "Test Log" },
                { id: "H-SC-15", description: "Final perimeter seal; witness EOD lockdown of administrative wings.", priority: "High", riskLevel: "Low", consequence: "Unsecured property.", proof: "Signed Summary" }
            ]
        },
        {
            title: "Billing & Revenue",
            department: "Finance",
            frequency: "Daily",
            role: "Billing Manager",
            summary: "Protects the financial pipeline and discharge cycle.",
            icon: "banknote",
            tasks: [
                { id: "H-BM-01", description: "TPA Pre-Auth Pulse: Confirm approval status for all active IP cases; flag pending > 4 hours.", priority: "High", riskLevel: "Medium", consequence: "Unrecoverable financial loss.", proof: "System Sync" },
                { id: "H-BM-02", description: "Consumable Audit: Match ward stock usage logs vs final system bill for 3 random IP cases.", priority: "Medium", riskLevel: "Low", consequence: "Silent profit leakage.", proof: "Bill Audit" },
                { id: "H-BM-03", description: "Verify refund authorization; match 5 random corrections to valid manager signatures.", priority: "High", riskLevel: "Medium", consequence: "Internal fraud.", proof: "Sample Check" },
                { id: "H-BM-04", description: "Monitor discharge TAT; analyze time from 'Medically Fit' to physical exit (Target < 2h).", priority: "Medium", riskLevel: "Low", consequence: "Bed gridlock.", proof: "Cycle Report" },
                { id: "H-BM-05", description: "Reconcile cash collections; match physical vault drop to daily POS report.", priority: "High", riskLevel: "High", consequence: "Revenue theft.", proof: "Bank Slip" },
                { id: "H-BM-06", description: "Audit empanelment validity; verify expiry dates for top 5 insurance partners.", priority: "High", riskLevel: "Medium", consequence: "Payment halts.", proof: "License Matrix" },
                { id: "H-BM-07", description: "Check stationery par; physically count bill rolls and claim forms.", priority: "Low", riskLevel: "Low", consequence: "Discharge delays.", proof: "Stock Check" },
                { id: "H-BM-08", description: "Verify cashier float; physically witness blind-count at shift start.", priority: "High", riskLevel: "Medium", consequence: "Untraceable shortages.", proof: "Cash Log" },
                { id: "H-BM-09", description: "Audit access logs; verify zero unauthorized POS bill deletions.", priority: "High", riskLevel: "High", consequence: "Billing fraud.", proof: "IT Audit" },
                { id: "H-BM-10", description: "Execute daily summary; witness final finance reconciliation for the unit.", priority: "Medium", riskLevel: "Low", consequence: "Oversight loss.", proof: "Signed Sheet" },
                { id: "H-BM-11", description: "Audit aged debtors; flag TPA payments exceeding 45-day threshold.", priority: "Low", riskLevel: "Low", consequence: "Capital pressure.", proof: "Aging Report" },
                { id: "H-BM-12", description: "Verify tariff display; confirm lobby boards match current billing rates.", priority: "High", riskLevel: "Medium", consequence: "Consumer penalties.", proof: "Photo" },
                { id: "H-BM-13", description: "Spot-check package accuracy; verify inclusion list matches patient invoice.", priority: "Medium", riskLevel: "Low", consequence: "Billing disputes.", proof: "Audit Note" },
                { id: "H-BM-14", description: "Check settlement status; verify 100% batch closure on card machines.", priority: "High", riskLevel: "Low", consequence: "Revenue delay.", proof: "Printout" },
                { id: "H-BM-15", description: "Witness vault drop; physically seal shift collection for bank transit.", priority: "High", riskLevel: "High", consequence: "Internal theft.", proof: "Signed Log" }
            ]
        },
        {
            title: "HR & Vetting",
            department: "HR",
            frequency: "Monthly",
            role: "HR Manager",
            summary: "Staff health, legal compliance, and institutional vetting.",
            icon: "user-plus",
            tasks: [
                { id: "H-HR-01", description: "Staff Vaccination Registry: Verify 100% compliance of clinical staff with current immuno-calendar.", priority: "High", riskLevel: "High", consequence: "Legal non-compliance and health risk.", proof: "Immuno File" },
                { id: "H-HR-02", description: "Credentialing Audit: Verify current DMC/MCI registration for 10 random visiting consultants.", priority: "High", riskLevel: "High", consequence: "Practice by unqualified persons.", proof: "Audit Sheet" },
                { id: "H-HR-03", description: "POSH Policy Display: Physically confirm committee visibility in 100% of staff rooms.", priority: "High", riskLevel: "High", consequence: "Severe legal liability.", proof: "Visual Check" },
                { id: "H-HR-04", description: "Audit biometric logs; match payslip OT claims against physical check-in data.", priority: "Medium", riskLevel: "Low", consequence: "Payroll fraud.", proof: "Match Note" },
                { id: "H-HR-05", description: "Verify health certificates; confirm FSSAI-compliant certs for 100% of pantry staff.", priority: "High", riskLevel: "Medium", consequence: "Cross-infection.", proof: "Cert Registry" },
                { id: "H-HR-06", description: "Check labor posters; verify availability of mandatory statutory notices in locker zones.", priority: "Low", riskLevel: "Low", consequence: "Regulatory fines.", proof: "Photo" },
                { id: "H-HR-07", description: "Audit grievance log; verify 100% of unresolved nursing issues are escalated to NS.", priority: "Medium", riskLevel: "Low", consequence: "High institutional churn.", proof: "Grievance Book" },
                { id: "H-HR-08", description: "Verify ID badge expiry; check database for 100% of clinical staff cards.", priority: "Low", riskLevel: "Low", consequence: "Security risk.", proof: "Database Sync" },
                { id: "H-HR-09", description: "Audit contract-worker ESI/PF; verify monthly challan proofs for outsourced guards.", priority: "High", riskLevel: "High", consequence: "Legal liability.", proof: "Challan File" },
                { id: "H-HR-10", description: "Conduct training spot-check; verify 'Safe-Inject' certification for 5 random nurses.", priority: "High", riskLevel: "High", consequence: "HAI outbreak risk.", proof: "Training Matrix" },
                { id: "H-HR-11", description: "Verify locker hygiene; physically inspect change-rooms for unwashed uniforms.", priority: "Low", riskLevel: "Low", consequence: "Odor drift.", proof: "Walkthrough" },
                { id: "H-HR-12", description: "Check uniform par-levels; physically count backup stock for new hires.", priority: "Low", riskLevel: "Low", consequence: "Poor presentation.", proof: "Stock Sheet" },
                { id: "H-HR-13", description: "Audit indemnity insurance; verify validity for 100% of surgical consultants.", priority: "High", riskLevel: "High", consequence: "Legal cost exposure.", proof: "Policy Registry" },
                { id: "H-HR-14", description: "Verify guard onboarding; confirm background check for outsourced security.", priority: "High", riskLevel: "Medium", consequence: "Vetting failure.", proof: "Signed Checklist" },
                { id: "H-HR-15", description: "Final monthly compliance sign-off; witness governance closure for HR.", priority: "Medium", riskLevel: "Low", consequence: "Oversight gap.", proof: "Signed Sheet" }
            ]
        }
    ]
};
