
import type { PremiumPack } from "@/lib/premium-packs";

export const hotels_and_resorts: PremiumPack = {
    id: 'hotels_and_resorts',
    title: "Hotel Operating System",
    priceINR: 5999,
    priceUSD: 79,
    competitorPriceUSD: 599,
    updatedAt: "2025-02-24",
    paymentId: 'pl_RaWEBHhFLQENxC',
    lemonSqueezyUrl: 'https://moremeets.lemonsqueezy.com/buy/2f377557-d41f-4571-83d3-a52e24ac27dd',
    category: "Hospitality",
    description: "The definitive Sovereign v11.1 engine for luxury hotels and resorts. Standardizing 180+ technical control points across Front Office, Housekeeping, Engineering, and Events.",
    heroHeadline: "Eliminate Guest Safety Gaps and Viral Reputation Damage",
    heroSubheadline: "Track 180+ technical control points across 8 distinct roles—even when you’re not on property.",
    pricingUrgency: "One safety incident or a single negative viral review costs 100x more than this entire system.",
    consultingAnchor: 15000,
    icon: "building",
    badgeText: "V11.1 SOVEREIGN",
    badgeVariant: "accent",
    bestseller: true,
    whoIsItFor: ["General Managers", "Hotel Owners", "Heads of Housekeeping", "Banqueting Directors", "Security & Valet Managers"],
    sampleItems: [
        { text: "<strong>Front Office Integrity</strong>: Zero-fail guest ID compliance and C-Form registration sync.", icon: "concierge-bell" },
        { text: "<strong>Housekeeping Command</strong>: Hourly public area audits and deep-clean room inspection scores.", icon: "bed" },
        { text: "<strong>Digital Command & ORM</strong>: Rate parity audits and 24h review response pulse to protect rankings.", icon: "globe" },
        { text: "<strong>MEP & Technical Safety</strong>: Daily generator load tests and water quality TDS monitoring.", icon: "wrench" }
    ],
    checklists: [
        {
            title: "Governance & Audit",
            department: "Executive",
            frequency: "Weekly",
            role: "Owner / Managing Director",
            summary: "High-level strategic oversight of property risk and money.",
            icon: "crown",
            tasks: [
                { id: "HR-EXE-01", description: "Review 'Empire Mood' scores and total money made today.", priority: "High", riskLevel: "Low", consequence: "Operational drift and loss of team focus.", proof: "Dashboard Review" },
                { id: "HR-EXE-02", description: "Match the night audit report against actual bank money received.", priority: "High", riskLevel: "High", consequence: "Internal theft and revenue leakage.", proof: "Audit Sheet" },
                { id: "HR-EXE-03", description: "Check if the Public Liability insurance is still valid.", priority: "High", riskLevel: "High", consequence: "Financial ruin during a guest accident.", proof: "Policy File" },
                { id: "HR-EXE-04", description: "Audit commission bills from MMT/Airbnb to avoid overpaying.", priority: "High", riskLevel: "Medium", consequence: "Paying for 'No-Show' guests who never arrived.", proof: "Ledger Match" },
                { id: "HR-EXE-05", description: "Review where the mystery auditors found faults this week.", priority: "Medium", riskLevel: "Low", consequence: "Lowering of hotel standards.", proof: "Audit Report" },
                { id: "HR-EXE-06", description: "Check that the Fire License (NOC) is displayed and in-date.", priority: "High", riskLevel: "High", consequence: "Government sealing of the hotel.", proof: "NOC Certificate" },
                { id: "HR-EXE-07", description: "Review electricity and water bills for any strange spikes.", priority: "Low", riskLevel: "Low", consequence: "Wasted money on utilities.", proof: "P&L Note" },
                { id: "HR-EXE-08", description: "Check that senior managers were on the floor during peak Saturday hours.", priority: "Medium", riskLevel: "Low", consequence: "Management disconnect when guests need them most.", proof: "Roster Log" },
                { id: "HR-EXE-09", description: "Check if any guest is threatening a legal case.", priority: "High", riskLevel: "High", consequence: "Unmanaged lawsuits and court costs.", proof: "Legal Dashboard" },
                { id: "HR-EXE-10", description: "Look at photos of any ongoing repair or building work.", priority: "Medium", riskLevel: "Medium", consequence: "Budget overruns and unmonitored delays.", proof: "Project Log" },
                { id: "HR-EXE-11", description: "Audit staff payroll to make sure everyone was paid correctly.", priority: "High", riskLevel: "Medium", consequence: "Employee disputes and strikes.", proof: "Payroll Register" },
                { id: "HR-EXE-12", description: "Check the hotel's ranking on Google and TripAdvisor.", priority: "High", riskLevel: "Low", consequence: "Fewer bookings if the score drops.", proof: "CSAT Report" },
                { id: "HR-EXE-13", description: "Perform a physical count of all Master Keys.", priority: "High", riskLevel: "High", consequence: "Security risk if a master key is missing.", proof: "Audit Log" },
                { id: "HR-EXE-14", description: "Check how much was spent on new linen this month.", priority: "Low", riskLevel: "Low", consequence: "Overspending on bedsheets.", proof: "Stock Report" },
                { id: "HR-EXE-15", description: "Compare vendor prices with other suppliers to ensure we aren't overpaying.", priority: "Medium", riskLevel: "Low", consequence: "Inflated procurement costs.", proof: "Vendor Log" },
                { id: "HR-EXE-16", description: "Check if PF and ESI payments for staff are up to date.", priority: "High", riskLevel: "High", consequence: "Government fines and legal risk.", proof: "Compliance File" },
                { id: "HR-EXE-17", description: "Review how many hours of training each staff member received.", priority: "Medium", riskLevel: "Low", consequence: "Staff skills getting rusty.", proof: "Matrix File" },
                { id: "HR-EXE-18", description: "Check if the General Manager gave too many free discounts.", priority: "High", riskLevel: "Medium", consequence: "Direct loss of room profit.", proof: "POS Void Log" },
                { id: "HR-EXE-19", description: "Verify that the generator was serviced on time.", priority: "High", riskLevel: "High", consequence: "Blackout during a full house.", proof: "Service Record" },
                { id: "HR-EXE-20", description: "Final Weekly Strategic sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of board-level oversight.", proof: "Signed Summary" }
            ]
        },
        {
            title: "Front Office & Arrival",
            department: "Front Desk",
            frequency: "Daily",
            role: "General Manager",
            summary: "Legal compliance, guest arrival readiness, and billing integrity.",
            icon: "concierge-bell",
            tasks: [
                { id: "HR-FO-01", description: "Check guest IDs and send info to police (C-Form).", priority: "High", riskLevel: "High", consequence: "Criminal liability and loss of hotel license.", proof: "Compliance Log", trainerNotes: "Scan original IDs only." },
                { id: "HR-FO-02", description: "Check if MMT/Airbnb bookings match what is in our system.", priority: "High", riskLevel: "Medium", consequence: "Double-booking and angry guests.", proof: "PMS Match" },
                { id: "HR-FO-03", description: "Send 'Welcome' messages to all Airbnb arrivals for today.", priority: "Medium", riskLevel: "Low", consequence: "Poor communication scores.", proof: "App Inbox" },
                { id: "HR-FO-04", description: "Count the room keys and make sure none are missing.", priority: "High", riskLevel: "High", consequence: "Security risk for guest rooms.", proof: "Key Audit" },
                { id: "HR-FO-05", description: "Check if any guest has reached their credit limit.", priority: "Medium", riskLevel: "Medium", consequence: "Guests leaving without paying for extras.", proof: "POS Report" },
                { id: "HR-FO-06", description: "Review and approve 'Late Checkout' requests.", priority: "Low", riskLevel: "Low", consequence: "Housekeeping delays for the next guest.", proof: "Log Book" },
                { id: "HR-FO-07", description: "Check if VIP welcome fruit or gifts are ready in the room.", priority: "Medium", riskLevel: "Low", consequence: "VIP guests feeling ignored.", proof: "Photo" },
                { id: "HR-FO-08", description: "Make sure 'Walk-in' guests are quoted the correct rate.", priority: "Medium", riskLevel: "Medium", consequence: "Selling rooms for too cheap.", proof: "Rate Log" },
                { id: "HR-FO-09", description: "Check if the bell-desk trolleys are clean and working.", priority: "Low", riskLevel: "Low", consequence: "Bad first impression.", proof: "Visual Check" },
                { id: "HR-FO-10", description: "Check the flight pickup list for any changes or delays.", priority: "High", riskLevel: "Low", consequence: "Guests waiting at the airport.", proof: "Tracking Log" },
                { id: "HR-FO-11", description: "Audit staff grooming: check uniforms and ID badges.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional brand image.", proof: "Daily Brief" },
                { id: "HR-FO-12", description: "Test the lobby Wi-Fi: login must work in 10 seconds.", priority: "Medium", riskLevel: "Low", consequence: "Immediate guest complaints.", proof: "Phone Test" },
                { id: "HR-FO-13", description: "Update the currency exchange board with today's rates.", priority: "High", riskLevel: "Medium", consequence: "Financial loss or legal fines.", proof: "Rate Note" },
                { id: "HR-FO-14", description: "Check 'Lost & Found': make sure all items are tagged.", priority: "Medium", riskLevel: "Medium", consequence: "Theft claims against the hotel.", proof: "Safe Entry" },
                { id: "HR-FO-15", description: "Check if repeat guests have their favorite drinks in the room.", priority: "Medium", riskLevel: "Low", consequence: "Loss of loyal guests.", proof: "Guest History" },
                { id: "HR-FO-16", description: "Check if the morning newspapers were delivered to rooms.", priority: "Low", riskLevel: "Low", consequence: "Broken luxury standard.", proof: "Door Audit" },
                { id: "HR-FO-17", description: "Audit the concierge: check if tour vendors are vetted.", priority: "Medium", riskLevel: "High", consequence: "Guest injury liability during tours.", proof: "Vendor License" },
                { id: "HR-FO-18", description: "Check stationary at the desk (pens, forms, cards).", priority: "Low", riskLevel: "Low", consequence: "Service delays.", proof: "Supply Audit" },
                { id: "HR-FO-19", description: "Verify the cash bag is sealed before the shift ends.", priority: "High", riskLevel: "High", consequence: "Internal cash theft.", proof: "Cash Bag" },
                { id: "HR-FO-20", description: "Final Daily Front Office sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of duty control.", proof: "Signed Log" }
            ]
        },
        {
            title: "Housekeeping & Rooms",
            department: "Housekeeping",
            frequency: "Daily",
            role: "Head of Housekeeping",
            summary: "Manages the invisible infrastructure of cleanliness and comfort.",
            icon: "bed",
            tasks: [
                { id: "HR-HK-01", description: "Check that all rooms are clean before the 2 PM check-in.", priority: "High", riskLevel: "High", consequence: "Guests waiting in the lobby; angry reviews.", proof: "Inspection Sign-off" },
                { id: "HR-HK-02", description: "Audit 5 random rooms: check under the bed and top of AC.", priority: "High", riskLevel: "High", consequence: "Slipping standards and dust issues.", proof: "Audit Scorecard" },
                { id: "HR-HK-03", description: "Check sheets and towels for any stains or graying.", priority: "High", riskLevel: "Medium", consequence: "Poor quality image.", proof: "Linen Log" },
                { id: "HR-HK-04", description: "Check bathrooms: no hair, no mold, and dry floors.", priority: "High", riskLevel: "High", consequence: "Dirty room complaints.", proof: "Visual Audit" },
                { id: "HR-HK-05", description: "Check for any signs of bugs (bed bugs or roaches).", priority: "High", riskLevel: "High", consequence: "Health department closure.", proof: "Pest Audit" },
                { id: "HR-HK-06", description: "Check if the mini-bar is restocked and billed correctly.", priority: "Medium", riskLevel: "Medium", consequence: "Unpaid guest consumption.", proof: "Consumption Log" },
                { id: "HR-HK-07", description: "Check common area toilets every hour for tissue and smell.", priority: "High", riskLevel: "Low", consequence: "Immediate guest disgust.", proof: "Hourly Sheet" },
                { id: "HR-HK-08", description: "Check if the lobby floor is buffed and shining.", priority: "Low", riskLevel: "Low", consequence: "Dull hotel image.", proof: "Visual Check" },
                { id: "HR-HK-09", description: "Clean all high-touch surfaces (elevator buttons, handles).", priority: "Medium", riskLevel: "Medium", consequence: "Spread of germs.", proof: "Sanitization Log" },
                { id: "HR-HK-10", description: "Check the status of 'Out of Order' rooms for repairs.", priority: "Medium", riskLevel: "Low", consequence: "Lost room revenue.", proof: "Maint Sync" },
                { id: "HR-HK-11", description: "Audit the laundry room: check chemical levels.", priority: "Low", riskLevel: "Low", consequence: "Laundry operations halt.", proof: "Stock Check" },
                { id: "HR-HK-12", description: "Inspect staff locker rooms for food or dirt.", priority: "Low", riskLevel: "Low", consequence: "Pest risk in staff areas.", proof: "Cleaning Note" },
                { id: "HR-HK-13", description: "Check if 'Turn-down' service is ready for 6 PM.", priority: "Medium", riskLevel: "Low", consequence: "Missed luxury standard.", proof: "Roster Match" },
                { id: "HR-HK-14", description: "Log any broken furniture or fused bulbs found in rooms.", priority: "Medium", riskLevel: "Low", consequence: "Maintenance backlog.", proof: "Issue Log" },
                { id: "HR-HK-15", description: "Check shampoo/soap stock in the main store.", priority: "Low", riskLevel: "Low", consequence: "Running out of amenities.", proof: "Inventory Note" },
                { id: "HR-HK-16", description: "Verify all trash bins were emptied at the back bay.", priority: "Low", riskLevel: "High", consequence: "Odors and pests.", proof: "Walkthrough" },
                { id: "HR-HK-17", description: "Check the cleaning of the staff cafeteria.", priority: "Low", riskLevel: "Low", consequence: "Low staff morale.", proof: "Visual Audit" },
                { id: "HR-HK-18", description: "Audit the 'Deep Clean' schedule for the week.", priority: "Medium", riskLevel: "Low", consequence: "Long-term grime buildup.", proof: "Deep Clean Log" },
                { id: "HR-HK-19", description: "Final shift Housekeeping sign-off.", priority: "High", riskLevel: "Low", consequence: "Incomplete handover.", proof: "Signed Summary" },
                { id: "HR-HK-20", description: "Check availability of spare pillows and blankets.", priority: "Low", riskLevel: "Low", consequence: "Guest discomfort at night.", proof: "Stock Note" }
            ]
        },
        {
            title: "Dining & Room Service",
            department: "F&B",
            frequency: "Daily",
            role: "F&B Manager",
            summary: "Command for the restaurant, bar, and room service.",
            icon: "utensils",
            tasks: [
                { id: "HR-FNB-01", description: "Test the room service phone: answer in 3 rings.", priority: "High", riskLevel: "Medium", consequence: "Lost orders and hungry guests.", proof: "Dial Log" },
                { id: "HR-FNB-02", description: "Check that all plates and glasses are chip-free.", priority: "Medium", riskLevel: "Low", consequence: "Bad luxury image.", proof: "Visual Audit" },
                { id: "HR-FNB-03", description: "Walk the corridors to remove dirty room service trays.", priority: "Medium", riskLevel: "Low", consequence: "Smelly hallways and poor brand image.", proof: "Patrol Log" },
                { id: "HR-FNB-04", description: "Count the bar bottles and match against sales.", priority: "High", riskLevel: "High", consequence: "Internal theft of expensive liquor.", proof: "POS Match" },
                { id: "HR-FNB-05", description: "Check bar license: original paper must be visible.", priority: "High", riskLevel: "High", consequence: "Police raid and bar closure.", proof: "Visual Check" },
                { id: "HR-FNB-06", description: "Check fridge temps: must be between 1°C and 4°C.", priority: "High", riskLevel: "High", consequence: "Food poisoning outbreak.", proof: "Temp Log" },
                { id: "HR-FNB-07", description: "Check the ice machine for any dirt or slime.", priority: "High", riskLevel: "High", consequence: "Sick guests from dirty ice.", proof: "Cleaning Log" },
                { id: "HR-FNB-08", description: "Verify all allergens are marked on the menu.", priority: "High", riskLevel: "High", consequence: "Fatal allergic reactions.", proof: "Menu Audit" },
                { id: "HR-FNB-09", description: "Check if the buffet is set up by 7:30 AM.", priority: "Medium", riskLevel: "Low", consequence: "Morning guest frustration.", proof: "Visual Sign-off" },
                { id: "HR-FNB-10", description: "Audit the bar fridge: check for expired juices.", priority: "Medium", riskLevel: "Low", consequence: "Bad drink taste and complaints.", proof: "Stock Check" },
                { id: "HR-FNB-11", description: "Check table alignment in the main restaurant.", priority: "Low", riskLevel: "Low", consequence: "Messy brand look.", proof: "Walkthrough" },
                { id: "HR-FNB-12", description: "Check lighting in the dining hall: no fused bulbs.", priority: "Medium", riskLevel: "Low", consequence: "Dull dinner ambiance.", proof: "Photo" },
                { id: "HR-FNB-13", description: "Reconcile aggregator (Zomato) orders for the shift.", priority: "High", riskLevel: "Medium", consequence: "Missing money from app sales.", proof: "Match Note" },
                { id: "HR-FNB-14", description: "Check staff grooming: clean nails and no hand wounds.", priority: "High", riskLevel: "Medium", consequence: "Contaminated food.", proof: "Briefing Log" },
                { id: "HR-FNB-15", description: "Check availability of bill folders.", priority: "Low", riskLevel: "Low", consequence: "Poor billing image.", proof: "Stock Note" },
                { id: "HR-FNB-16", description: "Inspect the bar floor drain for odors.", priority: "Medium", riskLevel: "Low", consequence: "Negative guest reviews about smell.", proof: "Visual Check" },
                { id: "HR-FNB-17", description: "Review the daily waste log from the kitchen.", priority: "Medium", riskLevel: "Low", consequence: "Hidden profit loss.", proof: "Waste Sheet" },
                { id: "HR-FNB-18", description: "Verify Gas Manifold joint safety: soap bubble test.", priority: "High", riskLevel: "High", consequence: "Fire hazard.", proof: "Maint Note" },
                { id: "HR-FNB-19", description: "Final manager sign-off on bar closure.", priority: "High", riskLevel: "High", consequence: "Liquor theft risk overnight.", proof: "Signed Summary" },
                { id: "HR-FNB-20", description: "Check first-aid burn gel in the kitchen.", priority: "Low", riskLevel: "Medium", consequence: "Inability to treat staff injuries.", proof: "Stock Audit" }
            ]
        },
        {
            title: "Events & Weddings",
            department: "Banquets",
            frequency: "Per Event",
            role: "Events Manager",
            summary: "Zero-fail framework for conference halls and weddings.",
            icon: "calendar-heart",
            tasks: [
                { id: "HR-EVT-01", description: "Test projectors, mics, and Wi-Fi 4 hours before the event.", priority: "High", riskLevel: "High", consequence: "Major event failure.", proof: "Tech Report" },
                { id: "HR-EVT-02", description: "Check for loose cables or trip hazards in the hall.", priority: "High", riskLevel: "High", consequence: "Guest injury and liability.", proof: "Walkthrough" },
                { id: "HR-EVT-03", description: "Mop the dance floor dry before the first dance.", priority: "High", riskLevel: "Medium", consequence: "Slipping accident during key moment.", proof: "Visual Sign-off" },
                { id: "HR-EVT-04", description: "Check hall temp: keep at exactly 23°C.", priority: "Medium", riskLevel: "Low", consequence: "Guests leaving early.", proof: "Temp Note" },
                { id: "HR-EVT-05", description: "Verify all buffet warmers are on and over 65°C.", priority: "High", riskLevel: "High", consequence: "Cold food and health risk.", proof: "Food Log" },
                { id: "HR-EVT-06", description: "Audit hall bathroom cleaning frequency.", priority: "High", riskLevel: "Low", consequence: "Negative guest reviews.", proof: "Hourly Sheet" },
                { id: "HR-EVT-07", description: "Check availability of fire exits: must be clear.", priority: "High", riskLevel: "High", consequence: "Fatal trap during emergency.", proof: "Patrol Log" },
                { id: "HR-EVT-08", description: "Check if the VIP arrival greeting is ready.", priority: "Medium", riskLevel: "Low", consequence: "VIP dissatisfaction.", proof: "Photo" },
                { id: "HR-EVT-09", description: "Check lighting in the parking zone for event guests.", priority: "Medium", riskLevel: "Medium", consequence: "Security risk.", proof: "Photo" },
                { id: "HR-EVT-10", description: "Final event closure and billing sign-off.", priority: "High", riskLevel: "Low", consequence: "Unpaid bills.", proof: "Signed summary" }
            ]
        },
        {
            title: "Perimeter & Life Safety",
            department: "Security",
            frequency: "Daily",
            role: "Security Chief",
            summary: "Command for the arrival infrastructure and asset protection.",
            icon: "shield-check",
            tasks: [
                { id: "HR-SEC-01", description: "Count all valet keys and match against the log.", priority: "High", riskLevel: "High", consequence: "Theft or unauthorized car use.", proof: "Dual-Sign Log" },
                { id: "HR-SEC-02", description: "Check pool vitals: pH and Chlorine every 4 hours.", priority: "High", riskLevel: "High", consequence: "Infections and health closure.", proof: "Temp Log" },
                { id: "HR-SEC-03", description: "Verify CCTV is recording and covers all exits.", priority: "High", riskLevel: "High", consequence: "No evidence for insurance if theft occurs.", proof: "System Check" },
                { id: "HR-SEC-04", description: "Check for any holes in the perimeter fence.", priority: "High", riskLevel: "Medium", consequence: "Security breach.", proof: "Patrol Log" },
                { id: "HR-SEC-05", description: "Check fire extinguisher pressure (must be in Green).", priority: "High", riskLevel: "High", consequence: "Inability to fight a fire.", proof: "Gauge Log" },
                { id: "HR-SEC-06", description: "Check if the lifeguard is on duty and alert.", priority: "High", riskLevel: "High", consequence: "Fatal drowning liability.", proof: "Visual Sign-off" },
                { id: "HR-SEC-07", description: "Test the panic buttons at the front desk.", priority: "High", riskLevel: "High", consequence: "Robbery response failure.", proof: "Test Note" },
                { id: "HR-SEC-08", description: "Check for 'Wet Floor' signs whenever there is a spill.", priority: "High", riskLevel: "High", consequence: "Slip and fall litigation.", proof: "Stock Check" },
                { id: "HR-SEC-09", description: "Verify security guard sobriety during shift change.", priority: "High", riskLevel: "High", consequence: "Vulnerable hotel perimeter.", proof: "Test Note" },
                { id: "HR-SEC-10", description: "Audit guest 'Day Pass' badges for the pool.", priority: "Medium", riskLevel: "Low", consequence: "Unauthorized person access.", proof: "Badge Log" },
                { id: "HR-SEC-11", description: "Inspect back-alley waste bins for fire risk.", priority: "High", riskLevel: "High", consequence: "Arson hazard.", proof: "Walkthrough" },
                { id: "HR-SEC-12", description: "Check first-aid kits in the gym and pool area.", priority: "Medium", riskLevel: "Medium", consequence: "Inability to treat guests.", proof: "Stock Audit" },
                { id: "HR-SEC-13", description: "Verify no flammables are stored near the O2 manifold.", priority: "High", riskLevel: "High", consequence: "Explosion risk.", proof: "Visual Check" },
                { id: "HR-SEC-14", description: "Check exterior lighting bulbs after sunset.", priority: "Medium", riskLevel: "Low", consequence: "Theft/Safety risk.", proof: "Walkthrough" },
                { id: "HR-SEC-15", description: "Check safe integrity in Room 101.", priority: "Medium", riskLevel: "Low", consequence: "Guest belongings theft.", proof: "Visual Check" },
                { id: "HR-SEC-16", description: "Audit security guard patrol hourly entries.", priority: "Medium", riskLevel: "Low", consequence: "Discipline drift.", proof: "Log Review" },
                { id: "HR-SEC-17", description: "Test lift 'Alarm Bell' battery backup.", priority: "High", riskLevel: "High", consequence: "Trapped guest panic.", proof: "Start-test Log" },
                { id: "HR-SEC-18", description: "Emergency PA system volume zone test.", priority: "High", riskLevel: "Medium", consequence: "Crisis communication failure.", proof: "Sound Test" },
                { id: "HR-SEC-19", description: "Final nightly safety sign-off.", priority: "High", riskLevel: "Low", consequence: "Systemic risk gap.", proof: "Manager Initials" },
                { id: "HR-SEC-20", description: "Check for pre-existing car dents on valet arrival.", priority: "High", riskLevel: "High", consequence: "False insurance claims.", proof: "Photo/Checksheet" }
            ]
        },
        {
            title: "Engineering & MEP",
            department: "Engineering",
            frequency: "Daily",
            role: "Chief Engineer",
            summary: "Hardens the property infrastructure against breakdowns.",
            icon: "wrench",
            tasks: [
                { id: "HR-ENG-01", description: "Check if motors are too hot or making loud noises.", priority: "High", riskLevel: "Medium", consequence: "Machine breakdown and guest discomfort.", proof: "BMS Reading" },
                { id: "HR-ENG-02", description: "Check the generator fuel and battery.", priority: "High", riskLevel: "High", consequence: "Total blackout panics.", proof: "Test Log" },
                { id: "HR-ENG-03", description: "Check shower water temp: must be 55°C.", priority: "High", riskLevel: "High", consequence: "Ice-cold showers.", proof: "Temp Log" },
                { id: "HR-ENG-04", description: "Test one zone of smoke detectors every week.", priority: "High", riskLevel: "High", consequence: "Fatal delay in fire alert.", proof: "Alarm Test Log" },
                { id: "HR-ENG-05", description: "Clean AC filters in the main lobby.", priority: "Medium", riskLevel: "Low", consequence: "Bad air quality.", proof: "Maint Sheet" },
                { id: "HR-ENG-06", description: "Test the lift 'Auto-Rescue' battery.", priority: "High", riskLevel: "High", consequence: "Guest trapped in lift.", proof: "Start-test Log" },
                { id: "HR-ENG-07", description: "Check the server room AC (must be 20°C).", priority: "High", riskLevel: "High", consequence: "System crash and data loss.", proof: "Temp Reading" },
                { id: "HR-ENG-08", description: "Check for water leaks in the public bathrooms.", priority: "Low", riskLevel: "Low", consequence: "Water waste and bad image.", proof: "Visual Check" },
                { id: "HR-ENG-09", description: "Test all lobby phones for a dial tone.", priority: "Low", riskLevel: "Low", consequence: "Communication gap.", proof: "Dial Test" },
                { id: "HR-ENG-10", description: "Verify LOTO (Lock-Out) tags on active repairs.", priority: "High", riskLevel: "High", consequence: "Fatal technician injury.", proof: "Permit File" }
            ]
        },
        {
            title: "VIP & Digital Reputation",
            department: "Marketing",
            frequency: "Daily",
            role: "Guest Relations Manager",
            summary: "Protects the online reputation and top revenue-generating guests.",
            icon: "star",
            tasks: [
                { id: "HR-VIP-01", description: "Reply to all Google/TripAdvisor reviews within 24 hours.", priority: "High", riskLevel: "Medium", consequence: "Lower ranking and fewer bookings.", proof: "Review Dashboard" },
                { id: "HR-VIP-02", description: "Check if our room prices match on MMT and Airbnb.", priority: "High", riskLevel: "High", consequence: "Fines and lost direct revenue.", proof: "Parity Check" },
                { id: "HR-VIP-03", description: "Answer all Instagram/WhatsApp messages within 30 mins.", priority: "Medium", riskLevel: "Low", consequence: "Lost booking leads.", proof: "Inbox Clear" },
                { id: "HR-VIP-04", description: "Greet every VIP arrival personally.", priority: "High", riskLevel: "Medium", consequence: "Loss of loyal high-spending guests.", proof: "VIP List" },
                { id: "HR-VIP-05", description: "Update Google Maps hours for any holiday change.", priority: "High", riskLevel: "Low", consequence: "Guests arrive to a closed hotel.", proof: "Mobile Check" },
                { id: "HR-VIP-06", description: "Check for any special birthday setups in rooms.", priority: "Medium", riskLevel: "Low", consequence: "Missed guest delight.", proof: "Photo" },
                { id: "HR-VIP-07", description: "Handle any guest complaints within 15 mins.", priority: "High", riskLevel: "High", consequence: "PR fire ignored.", proof: "Incident Log" },
                { id: "HR-VIP-08", description: "Test the loyalty QR code on room tables.", priority: "Low", riskLevel: "Low", consequence: "Failure to capture guest data.", proof: "Scan Test" },
                { id: "HR-VIP-09", description: "Review competitor room rates for today.", priority: "Low", riskLevel: "Low", consequence: "Missing out on local demand.", proof: "Comp Log" },
                { id: "HR-VIP-10", description: "Final Reputation sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of ORM control.", proof: "Signed Dashboard" }
            ]
        }
    ]
};
