
import type { PremiumPack } from "@/lib/premium-packs";

export const hotels_and_resorts: PremiumPack = {
    id: 'hotels_and_resorts',
    title: "Hotel Operating System (Sovereign v4.3)",
    priceINR: 5999,
    priceUSD: 79,
    competitorPriceUSD: 599,
    updatedAt: "2025-02-24",
    paymentId: 'pl_RaWEBHhFLQENxC',
    lemonSqueezyUrl: 'https://moremeets.lemonsqueezy.com/buy/2f377557-d41f-4571-83d3-a52e24ac27dd',
    category: "Hospitality",
    description: "No monthly subscriptions. No SaaS dependency. One-time investment for a lifetime of control. Sovereign v4.3 is the professional plug for your operational leaks.",
    heroHeadline: "Eliminate Guest Safety Gaps and Viral Reputation Damage",
    heroSubheadline: "Track 150+ technical control points across Front Office, Housekeeping, and Engineering—stay in control even when you’re not on property.",
    pricingUrgency: "One safety incident or a single negative viral review costs 100x more than this entire system.",
    consultingAnchor: 5000,
    icon: "building",
    badgeText: "V4.3 SOVEREIGN",
    badgeVariant: "accent",
    bestseller: true,
    whoIsItFor: ["General Managers", "Hotel Owners", "Heads of Housekeeping", "Chief Engineers", "Security Directors"],
    sampleItems: [
        { text: "<strong>2-Minute Daily Pulse</strong>: Your team updates housekeeping and safety status in seconds. 100% staff adoption.", icon: "timer" },
        { text: "<strong>OTA Reputation Shield</strong>: Track failures that lead to negative guest reviews before they are posted.", icon: "star" },
        { text: "<strong>High-Risk Verification</strong>: Highlighted 'Yellow Targets' show managers exactly what needs sign-off—from fire safety to pool hygiene.", icon: "shield-check" },
        { text: "<strong>Empire Mood Engine</strong>: Drive team behavior with live recognition and healthy competition between shifts.", icon: "trophy" },
        { text: "<strong>Institutional Memory</strong>: Built-in instructions ensure that even with high turnover, your standards remain constant.", icon: "history" },
        { text: "<strong>Revenue Protection</strong>: Stop the profit bleed caused by inconsistent billing and maintenance downtime.", icon: "banknote" },
        { text: "<strong>Multi-Property Switchboard</strong>: Manage multiple properties or blocks from one master file. Toggle facilities ON/OFF.", icon: "layout-grid" }
    ],
    checklists: [
        {
            title: "Front Office & Reservations",
            department: "Front Desk",
            frequency: "Daily",
            role: "Front Office Manager",
            summary: "Ensures legal compliance, guest arrival readiness, and billing integrity.",
            icon: "concierge-bell",
            tasks: [
                { id: "HR-FO-01", description: "Verify all arrivals against booking system (PMS vs. Channel Manager).", priority: "High", riskLevel: "High", consequence: "Overbooking conflict and forced guest relocation/denial.", proof: "System Reconcile Note", trainerNotes: "Cross-check all OTAs (Expedia, Booking.com) before shift start." },
                { id: "HR-FO-02", description: "Ensure check-in desk is staffed during peak arrival hours (12 PM - 3 PM).", priority: "High", riskLevel: "Medium", consequence: "Long wait times leading to immediate negative first impressions.", proof: "Roster Audit", trainerNotes: "Lobby presence is non-negotiable during these hours." },
                { id: "HR-FO-03", description: "Validate guest ID compliance and police registration (C-Form/KYC).", priority: "High", riskLevel: "High", consequence: "Severe legal violations and potential business closure.", proof: "Compliance Log", trainerNotes: "Strictly follow local KYC norms for every guest." },
                { id: "HR-FO-04", description: "Track and log unresolved guest complaints from the previous shift.", priority: "High", riskLevel: "High", consequence: "Escalated complaints turning into viral 1-star reviews.", proof: "Open Issue Log", trainerNotes: "Maintain a live log for immediate management intervention." },
                { id: "HR-FO-05", description: "Confirm all scheduled wake-up calls are logged and verified.", priority: "Medium", riskLevel: "Medium", consequence: "Guests missing flights or meetings; high dissatisfaction.", proof: "Call Log", trainerNotes: "Double-check manual entries against system logs." },
                { id: "HR-FO-06", description: "Monitor early/late check-in requests and sync with Housekeeping.", priority: "Medium", riskLevel: "Low", consequence: "Room allocation conflicts and delayed check-ins.", proof: "HK Sync Log", trainerNotes: "Use the internal radio for real-time status updates." },
                { id: "HR-FO-07", description: "Verify billing accuracy and folio items before checkout.", priority: "High", riskLevel: "Medium", consequence: "Revenue leakage and disputes during checkout.", proof: "Folio Audit", trainerNotes: "Cross-check POS entries from F&B and Spa." },
                { id: "HR-FO-08", description: "Check status of payment settlements and credit card pre-auths.", priority: "High", riskLevel: "High", consequence: "Direct financial loss and untraceable cash gaps.", proof: "Finance Reconciliation", trainerNotes: "Verify POS settlements match PMS records." },
                { id: "HR-FO-09", description: "Track and process all no-show bookings according to policy.", priority: "Medium", riskLevel: "Low", consequence: "Lost revenue due to uncharged cancellations.", proof: "No-Show Report", trainerNotes: "Apply the 24-hour charge policy strictly." },
                { id: "HR-FO-10", description: "Audit lobby and entrance cleanliness and ambiance.", priority: "Medium", riskLevel: "Low", consequence: "Sub-par first impression for incoming VIPs.", proof: "Visual Check", trainerNotes: "Check music volume and scent machine levels." },
                { id: "HR-FO-11", description: "Confirm all reservation modifications are updated in the system.", priority: "Medium", riskLevel: "Medium", consequence: "Guest conflict over incorrect dates or room types.", proof: "Modification Log" },
                { id: "HR-FO-12", description: "Monitor readiness for group bookings and event arrivals.", priority: "High", riskLevel: "Medium", consequence: "Operational chaos during mass check-ins.", proof: "Group Plan" },
                { id: "HR-FO-13", description: "Verify key card functionality and battery status of locks.", priority: "Medium", riskLevel: "Low", consequence: "Guest locked out of room after a long day.", proof: "Random Test Log" },
                { id: "HR-FO-14", description: "Check concierge and bell desk readiness for baggage handling.", priority: "Low", riskLevel: "Low", consequence: "Service gaps during luggage delivery.", proof: "Shift Briefing" },
                { id: "HR-FO-15", description: "Confirm guest transport bookings with external vendors.", priority: "Medium", riskLevel: "Medium", consequence: "Guest missing transport; brand reputation damage.", proof: "Vendor Call Log" }
            ]
        },
        {
            title: "Housekeeping & Room Integrity",
            department: "Housekeeping",
            frequency: "Daily",
            role: "Head of Housekeeping",
            summary: "Manages the invisible infrastructure of cleanliness and comfort.",
            icon: "bed",
            tasks: [
                { id: "HR-HK-01", description: "Verify all rooms are cleaned and inspected before check-in time.", priority: "High", riskLevel: "High", consequence: "Guest arriving to an unmade room; immediate refund risk.", proof: "Inspection Sign-off", trainerNotes: "Arrival rooms must be prioritized over stay-overs." },
                { id: "HR-HK-02", description: "Conduct random supervisor audits of 10% of occupied rooms.", priority: "High", riskLevel: "High", consequence: "Slipping standards leading to hygiene complaints.", proof: "Audit Scorecard", trainerNotes: "Use the 'White Glove' test on hidden surfaces." },
                { id: "HR-HK-03", description: "Check linen quality: scan for stains, tears, or graying.", priority: "High", riskLevel: "Medium", consequence: "Damage to premium brand perception.", proof: "Linen Log", trainerNotes: "Discard any linen that doesn't meet the 'Super White' standard." },
                { id: "HR-HK-04", description: "Verify all guest amenities (toiletries, water) are fully stocked.", priority: "Medium", riskLevel: "Low", consequence: "Guest inconvenience and low detail-rating.", proof: "Stock Checklist" },
                { id: "HR-HK-05", description: "Audit bathroom hygiene: check for hair, mold, and scale.", priority: "High", riskLevel: "High", consequence: "The #1 driver of negative 1-star reviews.", proof: "Deep Clean Log" },
                { id: "HR-HK-06", description: "Monitor room turnaround time (TAT) for checkout rooms.", priority: "Medium", riskLevel: "Low", consequence: "Operational delays during high-occupancy days.", proof: "TAT Tracker" },
                { id: "HR-HK-07", description: "Ensure minibar restocking and seal verification.", priority: "Medium", riskLevel: "Low", consequence: "Revenue loss and inventory discrepancies.", proof: "Restock Sheet" },
                { id: "HR-HK-08", description: "Track and log all Lost & Found items with photos.", priority: "High", riskLevel: "High", consequence: "Theft accusations and loss of guest trust.", proof: "Digital L&F Log", trainerNotes: "Bag and tag items immediately with room number and date." },
                { id: "HR-HK-09", description: "Sanitize housekeeping carts and equipment daily.", priority: "Low", riskLevel: "Low", consequence: "Cross-contamination between room blocks.", proof: "Cleaning Schedule" },
                { id: "HR-HK-10", description: "Verify laundry turnaround and external vendor SLA.", priority: "Medium", riskLevel: "Medium", consequence: "Running out of fresh linen during peak occupancy.", proof: "Laundry Log" },
                { id: "HR-HK-11", description: "Inspect corridor cleanliness and light fixture status.", priority: "Medium", riskLevel: "Low", consequence: "Poor corridor ambiance affecting guest mood.", proof: "Walkthrough" },
                { id: "HR-HK-12", description: "Inspect for signs of pests (bed bugs, roaches) in crevices.", priority: "High", riskLevel: "High", consequence: "Total brand destruction and health closure.", proof: "Pest Audit", trainerNotes: "Report any signs to the GM immediately." },
                { id: "HR-HK-13", description: "Deep clean rotation: perform 2 rooms per floor today.", priority: "Medium", riskLevel: "Medium", consequence: "Long-term hygiene degradation.", proof: "Rotation Log" },
                { id: "HR-HK-14", description: "Audit mattress condition and rotation status.", priority: "Medium", riskLevel: "Low", consequence: "Guest back pain and sleep-quality complaints.", proof: "Monthly Log" },
                { id: "HR-HK-15", description: "Curtain and upholstery steam cleaning check.", priority: "Low", riskLevel: "Low", consequence: "Dust buildup and allergen issues.", proof: "Cleaning Schedule" },
                { id: "HR-HK-16", description: "Verify staff attendance and shift handover notes.", priority: "Medium", riskLevel: "Medium", consequence: "Understaffing leading to service failure.", proof: "Attendance Log" },
                { id: "HR-HK-17", description: "Ensure room fragrance matches brand standards.", priority: "Low", riskLevel: "Low", consequence: "Inconsistent sensory experience.", proof: "Olfactory Check" },
                { id: "HR-HK-18", description: "Verify dilution levels of cleaning chemicals.", priority: "Medium", riskLevel: "Medium", consequence: "Chemical burns or ineffective cleaning.", proof: "Dosing Log" },
                { id: "HR-HK-19", description: "Inspect public area washrooms hourly.", priority: "High", riskLevel: "Medium", consequence: "High-visibility hygiene failure.", proof: "Hourly Log" },
                { id: "HR-HK-20", description: "Track repeat cleaning issues per staff member.", priority: "High", riskLevel: "Medium", consequence: "Systemic operational decay.", proof: "Coaching Log" }
            ]
        },
        {
            title: "Engineering & Life Safety",
            department: "Engineering",
            frequency: "Daily",
            role: "Chief Engineer",
            summary: "Hardens the property infrastructure against breakdowns and safety events.",
            icon: "wrench",
            tasks: [
                { id: "HR-ENG-01", description: "Check HVAC chiller/units and monitor lobby temp.", priority: "High", riskLevel: "Medium", consequence: "Guest discomfort in common areas.", proof: "BMS Reading" },
                { id: "HR-ENG-02", description: "Inspect backup generator (DG) and fuel levels.", priority: "High", riskLevel: "High", consequence: "Total blackout during power failure.", proof: "Test Log", trainerNotes: "Run DG for 10 minutes under no-load daily." },
                { id: "HR-ENG-03", description: "Verify hot water supply temperature at the boiler.", priority: "High", riskLevel: "High", consequence: "Ice-cold showers; high guest anger.", proof: "Temp Log" },
                { id: "HR-ENG-04", description: "Log and prioritize daily maintenance requests from PMS.", priority: "Medium", riskLevel: "Low", consequence: "Broken amenities remaining in rooms.", proof: "Work Order Log" },
                { id: "HR-ENG-05", description: "Safety check of all elevators: leveling and sensors.", priority: "High", riskLevel: "High", consequence: "Entrapment or serious mechanical injury.", proof: "Daily Log", trainerNotes: "Ensure emergency phone is functional." },
                { id: "HR-ENG-06", description: "Inspect for plumbing leaks in utility shafts.", priority: "Medium", riskLevel: "Medium", consequence: "Structural water damage and mold.", proof: "Shaft Log" },
                { id: "HR-ENG-07", description: "Audit common area lighting: replace fused bulbs.", priority: "Low", riskLevel: "Low", consequence: "Poor ambiance and safety dark-spots.", proof: "Visual Check" },
                { id: "HR-ENG-08", description: "Test fire alarm panel and smoke detector samples.", priority: "High", riskLevel: "High", consequence: "Fatal delay during real fire incident.", proof: "Alarm Test Log" },
                { id: "HR-ENG-09", description: "Monitor daily energy and water consumption units.", priority: "Medium", riskLevel: "Low", consequence: "Unnoticed utility leakage and higher costs.", proof: "Meter Reading" },
                { id: "HR-ENG-10", description: "Inspect kitchen equipment (Ovens, Cold Storage).", priority: "High", riskLevel: "Medium", consequence: "F&B service disruption.", proof: "Kitchen PM Log" },
                { id: "HR-ENG-11", description: "Verify water pressure at the highest floor rooms.", priority: "Medium", riskLevel: "Low", consequence: "Guest complaints about shower flow.", proof: "Pressure Gauge" },
                { id: "HR-ENG-12", description: "Inspect parking barriers and security gate systems.", priority: "Low", riskLevel: "Low", consequence: "Traffic congestion at entrance.", proof: "Functional Test" },
                { id: "HR-ENG-13", description: "Verify fuel stock for boiler and generators.", priority: "High", riskLevel: "High", consequence: "Infrastructure shutdown.", proof: "Stock Record" },
                { id: "HR-ENG-14", description: "Check elevator emergency alarm and intercom.", priority: "High", riskLevel: "High", consequence: "Safety violation.", proof: "Weekly Log" },
                { id: "HR-ENG-15", description: "Review weekly preventive maintenance (PM) schedule.", priority: "Medium", riskLevel: "Medium", consequence: "Unexpected equipment breakdown.", proof: "PM Master" }
            ]
        },
        {
            title: "VIP & Guest Experience",
            department: "Guest Relations",
            frequency: "Daily",
            role: "Guest Relations Manager",
            summary: "Protects the top 20% of revenue-generating guests.",
            icon: "star",
            tasks: [
                { id: "HR-VIP-01", description: "Identify all VIP arrivals and Repeat Guests for today.", priority: "High", riskLevel: "Medium", consequence: "Generic treatment of premium guests; loss of loyalty.", proof: "VIP Arrival List" },
                { id: "HR-VIP-02", description: "Verify special room setups (Honeymoon, Birthday, Flowers).", priority: "High", riskLevel: "Medium", consequence: "Failure to deliver promised celebrations.", proof: "Photo of Setup" },
                { id: "HR-VIP-03", description: "Assign a dedicated Guest Manager for all Category A VIPs.", priority: "Medium", riskLevel: "Low", consequence: "Service gaps during stay.", proof: "Assignment Log" },
                { id: "HR-VIP-04", description: "Track and confirm all special dietary/pillow requests.", priority: "High", riskLevel: "Medium", consequence: "Guest discomfort and feeling ignored.", proof: "Request Log" },
                { id: "HR-VIP-05", description: "Check availability of welcome gestures/amenities.", priority: "Medium", riskLevel: "Low", consequence: "Inconsistent arrival experience.", proof: "Stock Audit" },
                { id: "HR-VIP-06", description: "Conduct courtesy calls to rooms checked in yesterday.", priority: "High", riskLevel: "Medium", consequence: "Missed chance to fix issues before checkout.", proof: "Call Log" },
                { id: "HR-VIP-07", description: "Handle and log all guest escalations immediately.", priority: "High", riskLevel: "High", consequence: "Escalated conflict leading to legal/PR risk.", proof: "Incident Log" },
                { id: "HR-VIP-08", description: "Analyze repeat guest preferences for personalization.", priority: "Medium", riskLevel: "Low", consequence: "Missed opportunity for high-LTV engagement.", proof: "Preference Profile" },
                { id: "HR-VIP-09", description: "Maintain the 'Guest Recognition' staff briefing notes.", priority: "Medium", riskLevel: "Low", consequence: "Staff not recognizing regulars.", proof: "Briefing Sheet" },
                { id: "HR-VIP-10", description: "Personalized farewell check for departing VIPs.", priority: "Medium", riskLevel: "Low", consequence: "Generic departure experience.", proof: "Departure Log" }
            ]
        }
    ]
};
