
import type { PremiumPack } from "@/lib/premium-packs";

export const hotels_and_resorts: PremiumPack = {
    id: 'hotels_and_resorts',
    title: "Hotel Operating System",
    priceINR: 5999,
    priceUSD: 79,
    competitorPriceUSD: 599,
    updatedAt: "2025-02-24",
    paymentId: 'pl_RaWEBHhFLQENxC',
    lemonSqueezyUrl: 'https://moremeets.lemonsqueezy.com/buy/2f377557-d41f-4571-83d3-a52e24ac27dd',
    category: "Hospitality",
    description: "The definitive Sovereign v9.0 engine for luxury hotels and resorts. Standardizing 184 technical control points across Front Office, Housekeeping, Engineering, and Events.",
    heroHeadline: "Eliminate Guest Safety Gaps and Viral Reputation Damage",
    heroSubheadline: "Track 184 technical control points across Front Office, Housekeeping, Engineering, Events, and ORM—even when you’re not on property.",
    pricingUrgency: "One safety incident or a single negative viral review costs 100x more than this entire system.",
    consultingAnchor: 15000,
    icon: "building",
    badgeText: "V9.0 SOVEREIGN",
    badgeVariant: "accent",
    bestseller: true,
    whoIsItFor: ["General Managers", "Hotel Owners", "Heads of Housekeeping", "Banqueting Directors", "Security & Valet Managers"],
    sampleItems: [
        { text: "<strong>Front Office Integrity</strong>: Zero-fail guest ID compliance and PMS-to-Police registration sync.", icon: "concierge-bell" },
        { text: "<strong>Housekeeping Command</strong>: Hourly public area audits and deep-clean room inspection scores.", icon: "bed" },
        { text: "<strong>Digital Command & ORM</strong>: Rate parity audits across MMT/Goibibo and 24h review response pulse.", icon: "globe" }
    ],
    checklists: [
        {
            title: "Governance & Audit",
            department: "Executive",
            frequency: "Weekly",
            role: "COO / Owner",
            summary: "High-level strategic oversight of property risk.",
            icon: "crown",
            tasks: [
                { id: "HR-EXE-01", description: "Review 'Empire Mood' and ADR performance.", priority: "High", riskLevel: "Low", consequence: "Operational drift.", proof: "Dashboard Review", trainerNotes: "Check ADR vs RevPAR weekly." },
                { id: "HR-EXE-02", description: "Audit Night Audit report vs bank captures.", priority: "High", riskLevel: "High", consequence: "Revenue theft.", proof: "Audit Sheet", trainerNotes: "Reconcile terminals at 3 AM." },
                { id: "HR-EXE-03", description: "Verify insurance validity (Public Liability).", priority: "High", riskLevel: "High", consequence: "Financial ruin during incident.", proof: "Policy File", trainerNotes: "Check 60 days before expiry." },
                { id: "HR-EXE-04", description: "Audit MMT/Airbnb commission invoices.", priority: "High", riskLevel: "Medium", consequence: "Overpaying commissions.", proof: "Ledger Match", trainerNotes: "Flag 'No-Shows' by 5th." },
                { id: "HR-EXE-05", description: "Review mystery audit fail trends.", priority: "Medium", riskLevel: "Low", consequence: "Slipping standards.", proof: "Audit Report", trainerNotes: "Brief HODs on failures." },
                { id: "HR-EXE-06", description: "Verify Fire NOC and AMC status.", priority: "High", riskLevel: "High", consequence: "Legal closure.", proof: "NOC Certificate", trainerNotes: "Update repository quarterly." },
                { id: "HR-EXE-07", description: "Review P&L utility spikes.", priority: "Low", riskLevel: "Low", consequence: "Unchecked overheads.", proof: "P&L Note", trainerNotes: "Compare vs previous month." },
                { id: "HR-EXE-08", description: "Audit senior roster floor presence.", priority: "Medium", riskLevel: "Low", consequence: "Management disconnect.", proof: "Roster Log", trainerNotes: "Check peak Saturday slots." },
                { id: "HR-EXE-09", description: "Check status of open guest legal claims.", priority: "High", riskLevel: "High", consequence: "Escalated litigation.", proof: "Legal Dashboard", trainerNotes: "Consult counsel weekly." },
                { id: "HR-EXE-10", description: "Verify CAPEX project progress photos.", priority: "Medium", riskLevel: "Medium", consequence: "Delayed upgrades.", proof: "Project Log", trainerNotes: "Check milestone 25/50/75%." },
                { id: "HR-EXE-11", description: "Audit staff payroll accuracy.", priority: "High", riskLevel: "Medium", consequence: "Internal legal disputes.", proof: "Payroll Register", trainerNotes: "Check OT calculations." },
                { id: "HR-EXE-12", description: "Review Group CSAT scores.", priority: "High", riskLevel: "Low", consequence: "Drop in OTA ranking.", proof: "CSAT Report", trainerNotes: "Identify bottom 2 properties." },
                { id: "HR-EXE-13", description: "Verify 'Key Control' master audit.", priority: "High", riskLevel: "High", consequence: "Security perimeter fail.", proof: "Audit Log", trainerNotes: "Physical master key count." },
                { id: "HR-EXE-14", description: "Review linen stock replacement spend.", priority: "Low", riskLevel: "Low", consequence: "Overspending on assets.", proof: "Stock Report", trainerNotes: "Discard grey linen quarterly." },
                { id: "HR-EXE-15", description: "Audit vendor pricing vs market rate.", priority: "Medium", riskLevel: "Low", consequence: "Inflated procurement costs.", proof: "Vendor Log", trainerNotes: "Check Top 10 items prices." },
                { id: "HR-EXE-16", description: "Check compliance with local labor laws.", priority: "High", riskLevel: "High", consequence: "Government fines.", proof: "Compliance File", trainerNotes: "Check PF/ESI deposits." },
                { id: "HR-EXE-17", description: "Review 'Training Hours' per staff.", priority: "Medium", riskLevel: "Low", consequence: "Skill stagnation.", proof: "Matrix File", trainerNotes: "Target 4h/month per person." },
                { id: "HR-EXE-18", description: "Audit 'Discount' usage by GM.", priority: "High", riskLevel: "Medium", consequence: "Margin erosion.", proof: "POS Void Log", trainerNotes: "Max 2% of room revenue." },
                { id: "HR-EXE-19", description: "Check generator maintenance history.", priority: "High", riskLevel: "High", consequence: "Blackout disaster.", proof: "Service Record", trainerNotes: "Service every 250 hours." },
                { id: "HR-EXE-20", description: "Verify board report PDF archive.", priority: "Low", riskLevel: "Low", consequence: "Loss of history.", proof: "System Folder", trainerNotes: "Save monthly snapshots." },
                { id: "HR-EXE-21", description: "Audit petty cash sorpresa count.", priority: "Medium", riskLevel: "High", consequence: "Minor theft leakage.", proof: "Audit Note", trainerNotes: "Signature required for all." },
                { id: "HR-EXE-22", description: "Review ORM 'Resolution Speed'.", priority: "High", riskLevel: "Low", consequence: "Negative viral trends.", proof: "Digital Dashboard", trainerNotes: "Target < 2h for Red reviews." },
                { id: "HR-EXE-23", description: "Final Weekly Governance Sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of oversight.", proof: "Signed Summary", trainerNotes: "Submit to Owner Mondays." }
            ]
        },
        {
            title: "Front Office & Reservations",
            department: "Front Desk",
            frequency: "Daily",
            role: "General Manager",
            summary: "Legal compliance and arrival readiness.",
            icon: "concierge-bell",
            tasks: [
                { id: "HR-FO-01", description: "Validate guest ID compliance (C-Form).", priority: "High", riskLevel: "High", consequence: "Criminal liability/License loss.", proof: "Compliance Log", trainerNotes: "Scan original IDs only." },
                { id: "HR-FO-02", description: "Verify MMT/Goibibo booking vouchers.", priority: "High", riskLevel: "Medium", consequence: "Guest disputes/delays.", proof: "PMS Match", trainerNotes: "Cross-check voucher ID." },
                { id: "HR-FO-03", description: "Airbnb pre-arrival 'Welcome' send.", priority: "Medium", riskLevel: "Low", consequence: "Poor comm scores.", proof: "App Inbox", trainerNotes: "Include parking details." },
                { id: "HR-FO-04", description: "Verify 100% C-Form police sync.", priority: "High", riskLevel: "High", consequence: "Legal shutdown.", proof: "FRP Portal", trainerNotes: "Must sync in < 24h." },
                { id: "HR-FO-05", description: "Reconcile room keys against PMS.", priority: "High", riskLevel: "High", consequence: "Security risk/Lost assets.", proof: "Key Audit", trainerNotes: "Inventory keys every shift." },
                { id: "HR-FO-06", description: "Audit guest 'Credit Limit' warnings.", priority: "Medium", riskLevel: "Medium", consequence: "Unrecoverable bills.", proof: "POS Report", trainerNotes: "Take deposit for extras." },
                { id: "HR-FO-07", description: "Review 'Late Checkout' approvals.", priority: "Low", riskLevel: "Low", consequence: "Cleaning delays.", proof: "Log Book", trainerNotes: "Communicate to HK instantly." },
                { id: "HR-FO-08", description: "Verify VIP arrival welcome fruit.", priority: "Medium", riskLevel: "Low", consequence: "VIP dissatisfaction.", proof: "Photo", trainerNotes: "Check fruit freshness." },
                { id: "HR-FO-09", description: "Audit 'Walk-in' rates vs Parity.", priority: "Medium", riskLevel: "Medium", consequence: "Under-selling rooms.", proof: "Rate Log", trainerNotes: "Always offer Rack first." },
                { id: "HR-FO-10", description: "Check bell-desk trolley condition.", priority: "Low", riskLevel: "Low", consequence: "Poor brand first-touch.", proof: "Visual Check", trainerNotes: "Polish brass weekly." },
                { id: "HR-FO-11", description: "Verify flight pickup list accuracy.", priority: "High", riskLevel: "Low", consequence: "Guest waiting at airport.", proof: "Tracking Log", trainerNotes: "Call driver 1h before." },
                { id: "HR-FO-12", description: "Audit FO staff grooming/sovereignty.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution.", proof: "Daily Brief", trainerNotes: "Check badges/hair." },
                { id: "HR-FO-13", description: "Check lobby Wi-Fi guest portal.", priority: "Medium", riskLevel: "Low", consequence: "Immediate guest complaints.", proof: "Phone Test", trainerNotes: "Login must work in < 10s." },
                { id: "HR-FO-14", description: "Verify currency exchange rates.", priority: "High", riskLevel: "Medium", consequence: "Financial loss/Legal risk.", proof: "RBI Rate Note", trainerNotes: "Update board by 10 AM." },
                { id: "HR-FO-15", description: "Audit 'Lost & Found' log entry.", priority: "Medium", riskLevel: "Medium", consequence: "Legal theft claims.", proof: "Safe Entry", trainerNotes: "Tag every item with Room #." },
                { id: "HR-FO-16", description: "Review 'Repeat Guest' special pref.", priority: "Medium", riskLevel: "Low", consequence: "Loss of loyalty scores.", proof: "Guest History", trainerNotes: "Pre-stock fav beverage." },
                { id: "HR-FO-17", description: "Verify morning newspaper delivery.", priority: "Low", riskLevel: "Low", consequence: "Broken luxury ritual.", proof: "Door Audit", trainerNotes: "Target delivery by 7 AM." },
                { id: "HR-FO-18", description: "Audit 'Concierge Desk' tour vendors.", priority: "Medium", riskLevel: "High", consequence: "Guest injury liability.", proof: "Vendor License", trainerNotes: "Only use pre-vetted tours." },
                { id: "HR-FO-19", description: "Check desk station stationary stock.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional delays.", proof: "Supply Audit", trainerNotes: "Min 50 registration cards." },
                { id: "HR-FO-20", description: "Verify FO cashier closure shift.", priority: "High", riskLevel: "High", consequence: "Internal revenue theft.", proof: "Cash Bag", trainerNotes: "GM witnessed seal." },
                { id: "HR-FO-21", description: "Conduct night audit rollover.", priority: "High", riskLevel: "Low", consequence: "Systemic data corruption.", proof: "System Log", trainerNotes: "Run at 2:30 AM exactly." },
                { id: "HR-FO-22", description: "Check elevator guest flooring/hygiene.", priority: "Low", riskLevel: "Low", consequence: "Negative micro-impressions.", proof: "Cleaning Log", trainerNotes: "Buff mirrors hourly." },
                { id: "HR-FO-23", description: "Final shift handover FO sign-off.", priority: "High", riskLevel: "Low", consequence: "Critical info loss.", proof: "Signed Book", trainerNotes: "Oral + Digital briefing." }
            ]
        },
        {
            title: "Finance & Billing Shield",
            department: "Finance",
            frequency: "Daily",
            role: "Finance & Cashier",
            summary: "Billing integrity and asset governance.",
            icon: "banknote",
            tasks: [
                { id: "HR-FIN-01", description: "Blind Count: Clean linen vs invoice.", priority: "High", riskLevel: "Medium", consequence: "Silent asset theft.", proof: "Stock Sheet", trainerNotes: "Audit 5% bundles randomly." },
                { id: "HR-FIN-02", description: "Verify Petty Cash vs approvals.", priority: "Medium", riskLevel: "High", consequence: "Internal fraud.", proof: "Voucher Audit", trainerNotes: "Signature required for all." },
                { id: "HR-FIN-03", description: "Match digital POS vs bank capture.", priority: "High", riskLevel: "High", consequence: "Cashier theft.", proof: "Match Note", trainerNotes: "Investigate variance > ₹100." },
                { id: "HR-FIN-04", description: "Audit 'Voided' room service bills.", priority: "High", riskLevel: "High", consequence: "Inventory theft.", proof: "Void Report", trainerNotes: "Every void needs reason code." },
                { id: "HR-FIN-05", description: "Verify advance deposits for Banquets.", priority: "High", riskLevel: "Low", consequence: "Post-event recovery loss.", proof: "Ledger Note", trainerNotes: "80% payment 7 days pre-evt." },
                { id: "HR-FIN-06", description: "Reconcile minibar restock vs sales.", priority: "Medium", riskLevel: "Medium", consequence: "Uncharged guest consumption.", proof: "Minibar Log", trainerNotes: "Verify expiry dates monthly." },
                { id: "HR-FIN-07", description: "Check stationary inventory (Letterhead).", priority: "Low", riskLevel: "Low", consequence: "Operational halt.", proof: "Supply Check", trainerNotes: "Min 1 month buffer stock." },
                { id: "HR-FIN-08", description: "Audit staff cafeteria coupons.", priority: "Low", riskLevel: "Low", consequence: "Unchecked food spend.", proof: "Coupon Log", trainerNotes: "Reconcile vs HR headcount." },
                { id: "HR-FIN-09", description: "Verify credit card machine tamper seal.", priority: "High", riskLevel: "High", consequence: "Skimming legal disaster.", proof: "Visual Audit", trainerNotes: "Look for mismatched screws." },
                { id: "HR-FIN-10", description: "Check bar bottle opening vs POS.", priority: "High", riskLevel: "High", consequence: "Liquor profit leakage.", proof: "Bottle Count", trainerNotes: "Blind count high-value malts." },
                { id: "HR-FIN-11", description: "Audit 'Complimentary' room nights.", priority: "High", riskLevel: "Medium", consequence: "Director revenue loss.", proof: "Comp Log", trainerNotes: "Must have MD sign-off." },
                { id: "HR-FIN-12", description: "Verify vendor TDS deductions.", priority: "Medium", riskLevel: "Medium", consequence: "Tax compliance non-conformance.", proof: "TDS Report", trainerNotes: "Check vendor PAN validity." },
                { id: "HR-FIN-13", description: "Match breakfast headcount vs POS.", priority: "Medium", riskLevel: "Medium", consequence: "Untracked buffet leakage.", proof: "Headcount Sheet", trainerNotes: "Check vs occupied room count." },
                { id: "HR-FIN-14", description: "Audit laundry chemical inventory.", priority: "Medium", riskLevel: "Low", consequence: "Inflated chemical costs.", proof: "Chem Log", trainerNotes: "Verify dilution ratios." },
                { id: "HR-FIN-15", description: "Verify GST input credit on bills.", priority: "High", riskLevel: "Medium", consequence: "Financial inefficiency.", proof: "Tax Audit", trainerNotes: "Match GSTIN on supplier bills." },
                { id: "HR-FIN-16", description: "Review 'Average Room Rate' trend.", priority: "Low", riskLevel: "Low", consequence: "Underperforming revenue team.", proof: "Rev Report", trainerNotes: "Compare vs market competitive set." },
                { id: "HR-FIN-17", description: "Audit asset tags on IT hardware.", priority: "Low", riskLevel: "Low", consequence: "Inability to track lost items.", proof: "Asset Register", trainerNotes: "Laptops must have physical tags." },
                { id: "HR-FIN-18", description: "Verify bank deposit slip vs shift.", priority: "High", riskLevel: "High", consequence: "Internal cash theft.", proof: "Bank Slip", trainerNotes: "Deposit witnessed by GM." },
                { id: "HR-FIN-19", description: "Check availability of bill folders.", priority: "Low", riskLevel: "Low", consequence: "Poor billing presentation.", proof: "Stock Note", trainerNotes: "Clean folders with alcohol wipe." },
                { id: "HR-FIN-20", description: "Audit 'No-Show' fee collection.", priority: "Medium", riskLevel: "Low", consequence: "Lost fee income.", proof: "OTA Portal", trainerNotes: "Charge credit card instantly." },
                { id: "HR-FIN-21", description: "Review monthly electricity/sales ratio.", priority: "Low", riskLevel: "Low", consequence: "Wasteful energy spend.", proof: "Trend Chart", trainerNotes: "Target < 10% of gross." },
                { id: "HR-FIN-22", description: "Audit staff travel expense claims.", priority: "Low", riskLevel: "Medium", consequence: "Inflated HR expenses.", proof: "Claim File", trainerNotes: "Vouchers needed for all cabs." },
                { id: "HR-FIN-23", description: "Final daily Finance sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of fiscal control.", proof: "Signed Summary", trainerNotes: "Submit EOD to MD." }
            ]
        },
        {
            title: "Security, Pool & CCTV",
            department: "Security",
            frequency: "Daily",
            role: "EHS Officer",
            summary: "Property safety and leisure zone command.",
            icon: "shield-check",
            tasks: [
                { id: "HR-SEC-01", description: "Valet Key Vault: Reconcile keys.", priority: "High", riskLevel: "High", consequence: "Theft/unauthorized car use.", proof: "Dual-Sign Log", trainerNotes: "Keys stay in locked box." },
                { id: "HR-SEC-02", description: "Pool Vitals: pH/Chlorine every 4h.", priority: "High", riskLevel: "High", consequence: "Health shutdown/Infections.", proof: "Temp Log", trainerNotes: "Target pH 7.2 - 7.6." },
                { id: "HR-SEC-03", description: "CCTV: Verify 30-day backup status.", priority: "High", riskLevel: "High", consequence: "Loss of evidence.", proof: "System Screen", trainerNotes: "Check timestamp sync." },
                { id: "HR-SEC-04", description: "Perimeter fence patrol: Holes/Gaps.", priority: "High", riskLevel: "Medium", consequence: "Security breach.", proof: "Patrol Log", trainerNotes: "Check back-alley entrance." },
                { id: "HR-SEC-05", description: "Audit visitor 'Day Pass' badges.", priority: "Medium", riskLevel: "Low", consequence: "Unauthorized person access.", proof: "Badge Log", trainerNotes: "ID required for all day-users." },
                { id: "HR-SEC-06", description: "Fire Extinguisher pressure check.", priority: "High", riskLevel: "High", consequence: "Inability to fight fire.", proof: "Gauge Log", trainerNotes: "Check safety seals daily." },
                { id: "HR-SEC-07", description: "Lifeguard sobriety/Presence check.", priority: "High", riskLevel: "High", consequence: "Fatal drowning liability.", proof: "Visual Sign-off", trainerNotes: "No phones at pool deck." },
                { id: "HR-SEC-08", description: "Gym cable/Bolt mechanical audit.", priority: "High", riskLevel: "High", consequence: "Serious guest injury.", proof: "Inspection Log", trainerNotes: "Test treadmill E-stop." },
                { id: "HR-SEC-09", description: "Nightly external lighting check.", priority: "Medium", riskLevel: "Low", consequence: "Increased theft/safety risk.", proof: "Walkthrough", trainerNotes: "Replace fused bulbs < 24h." },
                { id: "HR-SEC-10", description: "Audit loading bay security camera.", priority: "High", riskLevel: "High", consequence: "Untracked stock theft.", proof: "Monitor Check", trainerNotes: "View must capture faces." },
                { id: "HR-SEC-11", description: "Emergency exit 'Push-bar' test.", priority: "High", riskLevel: "High", consequence: "Fatal entrapment in fire.", proof: "Patrol Log", trainerNotes: "Open and close door 100%." },
                { id: "HR-SEC-12", description: "Verify first-aid kit shelf stock.", priority: "Medium", riskLevel: "Medium", consequence: "Inability to treat guests.", proof: "Stock Audit", trainerNotes: "Check expiry dates." },
                { id: "HR-SEC-13", description: "Test 'Panic Button' at FO/Cashier.", priority: "High", riskLevel: "High", consequence: "Robbery response failure.", proof: "Test Note", trainerNotes: "Silent test via monitoring co." },
                { id: "HR-SEC-14", description: "Check integrity of safe in Room 101.", priority: "Medium", riskLevel: "Low", consequence: "Guest belongings theft claims.", proof: "Visual Check", trainerNotes: "Check battery status weekly." },
                { id: "HR-SEC-15", description: "Audit staff entry 'ID Card' scan.", priority: "Medium", riskLevel: "Low", consequence: "Unauthorized entry.", proof: "System Report", trainerNotes: "No ID, No entry." },
                { id: "HR-SEC-16", description: "Check chemical store 'LOTO' locks.", priority: "High", riskLevel: "Medium", consequence: "Toxic gas exposure.", proof: "Visual Audit", trainerNotes: "Separate acids/alkalis." },
                { id: "HR-SEC-17", description: "Verify 'No Smoking' zone compliance.", priority: "Low", riskLevel: "Low", consequence: "Fire hazard/Guest discomfort.", proof: "Walkthrough", trainerNotes: "Check stairwells for butts." },
                { id: "HR-SEC-18", description: "Inspect valet car handover sheets.", priority: "High", riskLevel: "Medium", consequence: "Fake damage claims.", proof: "Sheet Audit", trainerNotes: "Mark all dents pre-valet." },
                { id: "HR-SEC-19", description: "Verify security radio battery stock.", priority: "Low", riskLevel: "Low", consequence: "Comm failure during crisis.", proof: "Supply Note", trainerNotes: "Target min 5 spare batteries." },
                { id: "HR-SEC-20", description: "Test floodlights at porch entrance.", priority: "Low", riskLevel: "Low", consequence: "Poor first-touch security.", proof: "Photo", trainerNotes: "Check lux levels weekly." },
                { id: "HR-SEC-21", description: "Audit security guard log entries.", priority: "Medium", riskLevel: "Low", consequence: "Discipline drift.", proof: "Log Review", trainerNotes: "Entries must be hourly." },
                { id: "HR-SEC-22", description: "Check DVR room temperature (Target 20C).", priority: "Medium", riskLevel: "Medium", consequence: "Disk failure/loss of record.", proof: "Temp Note", trainerNotes: "Keep dedicated AC ON 24/7." },
                { id: "HR-SEC-23", description: "Final nightly safety sign-off.", priority: "High", riskLevel: "Low", consequence: "Systemic risk gap.", proof: "Manager Initials", trainerNotes: "Physical perimeter touch." }
            ]
        },
        {
            title: "Training & Grooming",
            department: "HR",
            frequency: "Monthly",
            role: "HR Manager",
            summary: "Staff health and service standard governance.",
            icon: "graduation-cap",
            tasks: [
                { id: "HR-HR-01", description: "Verify staff health certs (F&B).", priority: "High", riskLevel: "Medium", consequence: "Infection risk/Legal fines.", proof: "Cert File", trainerNotes: "Renew every 6 months." },
                { id: "HR-HR-02", description: "Briefing grooming audit: badges.", priority: "Low", riskLevel: "Low", consequence: "Luxury brand dilution.", proof: "Log Book", trainerNotes: "Check name-tags/hairnets." },
                { id: "HR-HR-03", description: "Update 'Service Recovery' training.", priority: "High", riskLevel: "Low", consequence: "Loss of unhappy guests.", proof: "Matrix File", trainerNotes: "Role-play L.E.A.R.N. protocol." },
                { id: "HR-HR-04", description: "Audit staff attendance trends.", priority: "Medium", riskLevel: "Low", consequence: "Operational delays.", proof: "Biometric Log", trainerNotes: "Flag > 3 late entries/week." },
                { id: "HR-HR-05", description: "Verify 'Safety Drill' enrollment.", priority: "High", riskLevel: "High", consequence: "Staff panic in fire.", proof: "Drill Log", trainerNotes: "Surprise every 90 days." },
                { id: "HR-HR-06", description: "Inspect staff locker hygiene.", priority: "Low", riskLevel: "Low", consequence: "Pest risk in staff zone.", proof: "Cleaning Log", trainerNotes: "Open lockers Sundays." },
                { id: "HR-HR-07", description: "Check uniform stock levels.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional hires.", proof: "Inventory Check", trainerNotes: "Min 2 sets per person." },
                { id: "HR-HR-08", description: "Audit 'Upsell' contest results.", priority: "Low", riskLevel: "Low", consequence: "Missed revenue.", proof: "Leaderboard", trainerNotes: "Reward at briefing." },
                { id: "HR-HR-09", description: "Check first-aid responder roster.", priority: "High", riskLevel: "High", consequence: "Medical liability risk.", proof: "Roster Note", trainerNotes: "Min 1 certified/shift." },
                { id: "HR-HR-10", description: "Verify NDAs signed by new hires.", priority: "High", riskLevel: "Medium", consequence: "Loss of trade secrets.", proof: "Signed File", trainerNotes: "Store in secure HR vault." },
                { id: "HR-HR-11", description: "Review resignation exit comments.", priority: "Low", riskLevel: "Low", consequence: "Unaddressed churn root causes.", proof: "Exit Notes", trainerNotes: "Identify manager friction." },
                { id: "HR-HR-12", description: "Audit 'Overtime' vs GM budget.", priority: "Medium", riskLevel: "Medium", consequence: "Payroll inflation.", proof: "OT Tracker", trainerNotes: "Must be pre-approved." },
                { id: "HR-HR-13", description: "Verify medical insurance coverage.", priority: "Medium", riskLevel: "Low", consequence: "Employee distress/liability.", proof: "Policy File", trainerNotes: "Renew 30 days early." },
                { id: "HR-HR-14", description: "Check grooming kit availability.", priority: "Low", riskLevel: "Low", consequence: "Slipping standards.", proof: "Visual Check", trainerNotes: "Razors/Deo in lockers." },
                { id: "HR-HR-15", description: "Conduct 'Code Red' verbal quiz.", priority: "High", riskLevel: "High", consequence: "Emergency protocol failure.", proof: "Quiz Log", trainerNotes: "Ask random staff daily." },
                { id: "HR-HR-16", description: "Verify 'Sexual Harassment' policy post.", priority: "High", riskLevel: "High", consequence: "Legal liability/Toxic culture.", proof: "Photo", trainerNotes: "Display in staff room." },
                { id: "HR-HR-17", description: "Audit 'Uniform Laundry' cycle time.", priority: "Low", riskLevel: "Low", consequence: "Staff wearing dirty clothes.", proof: "Laundry Log", trainerNotes: "Target < 24h turnaround." },
                { id: "HR-HR-18", description: "Review 'Training Satisfaction' survey.", priority: "Low", riskLevel: "Low", consequence: "Ineffective training spend.", proof: "Survey Note", trainerNotes: "Target > 80% positive." },
                { id: "HR-HR-19", description: "Verify active Certs for Engineers.", priority: "High", riskLevel: "High", consequence: "Fatal industrial accidents.", proof: "Cert Registry", trainerNotes: "Check LOTO/High-Volt IDs." },
                { id: "HR-HR-20", description: "Final monthly HR matrix sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of admin control.", proof: "Signed Matrix", trainerNotes: "Submit to GM." },
                { id: "HR-HR-21", description: "Check payroll bank info accuracy.", priority: "Low", riskLevel: "Medium", consequence: "Staff pay delays.", proof: "Ledger Audit", trainerNotes: "Verify new account links." },
                { id: "HR-HR-22", description: "Audit staff break-room amenities.", priority: "Low", riskLevel: "Low", consequence: "Low morale.", proof: "Visual Check", trainerNotes: "Ensure drinking water active." },
                { id: "HR-HR-23", description: "Verify 'Staff ID' visibility rules.", priority: "Low", riskLevel: "Low", consequence: "Security perimeter drift.", proof: "Walkthrough", trainerNotes: "IDs must be visible." }
            ]
        },
        {
            title: "Engineering & Life Safety",
            department: "Engineering",
            frequency: "Daily",
            role: "Technical Lead",
            summary: "Property infrastructure and backbone protection.",
            icon: "wrench",
            tasks: [
                { id: "HR-ENG-01", description: "Guest Wi-Fi Speedtest: Public zones.", priority: "Medium", riskLevel: "Low", consequence: "Negative business reviews.", proof: "Speedtest App", trainerNotes: "Check Lobby/Business Ctr." },
                { id: "HR-ENG-02", description: "Inspect generator fuel/battery levels.", priority: "High", riskLevel: "High", consequence: "Total blackout panics.", proof: "Test Log", trainerNotes: "Min 48h fuel supply." },
                { id: "HR-ENG-03", description: "Boiler temp check: 55C at source.", priority: "High", riskLevel: "High", consequence: "Ice-cold showers/Disgust.", proof: "Temp Log", trainerNotes: "Target delivery 55C." },
                { id: "HR-ENG-04", description: "Test fire smoke detector samples.", priority: "High", riskLevel: "High", consequence: "Fatal delay in fire alert.", proof: "Alarm Log", trainerNotes: "Rotate test zones weekly." },
                { id: "HR-ENG-05", description: "Chiller/AC filter cleaning log.", priority: "Medium", riskLevel: "Low", consequence: "Guest discomfort/high bills.", proof: "Maint Sheet", trainerNotes: "Check lobby at 23C." },
                { id: "HR-ENG-06", description: "Elevator UPS/Battery bank test.", priority: "High", riskLevel: "High", consequence: "Guest trapped in lift.", proof: "Start-test Log", trainerNotes: "Run lift 1 cycle on batt." },
                { id: "HR-ENG-07", description: "Plumbing: audit lobby faucet leaks.", priority: "Low", riskLevel: "Low", consequence: "Water waste/Image damage.", proof: "Visual Check", trainerNotes: "Change washers instantly." },
                { id: "HR-ENG-08", description: "Check lobby phone dial-tone sync.", priority: "Low", riskLevel: "Low", consequence: "Comm failure for guests.", proof: "Dial Test", trainerNotes: "Check intercom lines daily." },
                { id: "HR-ENG-09", description: "Kitchen fridge core motor heat check.", priority: "High", riskLevel: "Medium", consequence: "Compressor burnout risk.", proof: "Panel Log", trainerNotes: "Vacuum coils monthly." },
                { id: "HR-ENG-10", description: "Garden irrigation timer accuracy.", priority: "Low", riskLevel: "Low", consequence: "Dead Curbside appeal.", proof: "Visual Check", trainerNotes: "Set for 6 AM / 6 PM." },
                { id: "HR-ENG-11", description: "Verify STP/ETP water parameter log.", priority: "High", riskLevel: "High", consequence: "Environmental fines/Odors.", proof: "PCB Log", trainerNotes: "Maintain pH 6.5-8.5." },
                { id: "HR-ENG-12", description: "Check exterior signage illumination.", priority: "Low", riskLevel: "Low", consequence: "Low visibility/image drop.", proof: "Photo at Night", trainerNotes: "Set for Sunset-to-Sunrise." },
                { id: "HR-ENG-13", description: "Inspect kitchen exhaust suction.", priority: "High", riskLevel: "Medium", consequence: "Grease buildup fire risk.", proof: "Tissue Test", trainerNotes: "Clean hood filters weekly." },
                { id: "HR-ENG-14", description: "Test emergency lighting battery.", priority: "Medium", riskLevel: "High", consequence: "Total darkness panics.", proof: "Test Note", trainerNotes: "Run 15 mins monthly." },
                { id: "HR-ENG-15", description: "Check laundry machine boiler seal.", priority: "High", riskLevel: "High", consequence: "Industrial steam explosion.", proof: "Visual Audit", trainerNotes: "Check pressure relief valve." },
                { id: "HR-ENG-16", description: "Audit server room AC (Target 20C).", priority: "High", riskLevel: "High", consequence: "Loss of PMS/Data fail.", proof: "Temp Reading", trainerNotes: "Check backup split-unit." },
                { id: "HR-ENG-17", description: "Verify CCTV monitor flicker status.", priority: "Low", riskLevel: "Low", consequence: "Missing visual evidence.", proof: "Visual Check", trainerNotes: "Replace cables if glitching." },
                { id: "HR-ENG-18", description: "Check RO water TDS (Target <100).", priority: "High", riskLevel: "High", consequence: "Waterborne illness panics.", proof: "TDS Meter", trainerNotes: "Change filters at 150ppm." },
                { id: "HR-ENG-19", description: "Inspect kitchen gas soap-test.", priority: "High", riskLevel: "High", consequence: "Overnight fire risk.", proof: "Maint Note", trainerNotes: "Daily test on main joints." },
                { id: "HR-ENG-20", description: "Review P1 breakdown TAT for shift.", priority: "High", riskLevel: "Low", consequence: "Loss of engineering focus.", proof: "Job Log", trainerNotes: "Target P1 fix in < 30m." },
                { id: "HR-ENG-21", description: "Check outdoor furniture paint/rust.", priority: "Low", riskLevel: "Low", consequence: "Poor curbside appeal.", proof: "Visual Audit", trainerNotes: "Buff rust spots immediately." },
                { id: "HR-ENG-22", description: "Verify LOTO permit compliance.", priority: "High", riskLevel: "High", consequence: "Technician injury (Fatal).", proof: "Permit File", trainerNotes: "No lock, No work." },
                { id: "HR-ENG-23", description: "Final Technical sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of dept control.", proof: "Signed Log", trainerNotes: "Brief GM on major fails." }
            ]
        },
        {
            title: "Digital Command & ORM",
            department: "Admin",
            frequency: "Daily",
            role: "Customer Experience Lead",
            summary: "Online reputation and portal governance.",
            icon: "globe",
            tasks: [
                { id: "HR-DIG-01", description: "Rate Parity Audit: MMT vs Direct.", priority: "High", riskLevel: "High", consequence: "OTA deprioritization.", proof: "Parity Check", trainerNotes: "Keep within 1% variance." },
                { id: "HR-DIG-02", description: "MMT/Airbnb Review Response <24h.", priority: "High", riskLevel: "Medium", consequence: "Ranking drop on portals.", proof: "Dashboard", trainerNotes: "Personalize every reply." },
                { id: "HR-DIG-03", description: "Social DM appointment reply <30m.", priority: "Medium", riskLevel: "Low", consequence: "Lost booking revenue.", proof: "Inbox Clear", trainerNotes: "Confirm via WhatsApp." },
                { id: "HR-DIG-04", description: "Verify 'Live Availability' on OTAs.", priority: "High", riskLevel: "High", consequence: "Overbooking penalties.", proof: "Channel Sync", trainerNotes: "Manual check last 5 rooms." },
                { id: "HR-DIG-05", description: "Google My Business 'Status' check.", priority: "High", riskLevel: "Low", consequence: "Guests arrive to 'Closed' hotel.", proof: "Mobile Check", trainerNotes: "Update hours for holidays." },
                { id: "HR-DIG-06", description: "Monitor website 'Book Now' load time.", priority: "Medium", riskLevel: "Low", consequence: "Lost direct revenue.", proof: "Speed Test", trainerNotes: "Target < 3s load." },
                { id: "HR-DIG-07", description: "Check TripAdvisor ranking trend.", priority: "Low", riskLevel: "Low", consequence: "Drop in search visibility.", proof: "Weekly Note", trainerNotes: "Target Top 5 in sector." },
                { id: "HR-DIG-08", description: "Verify Instagram 'Bio' link active.", priority: "Low", riskLevel: "Low", consequence: "Broken marketing funnel.", proof: "Scan Test", trainerNotes: "Test with personal mobile." },
                { id: "HR-DIG-09", description: "Audit 'Influencer' stay itinerary.", priority: "Medium", riskLevel: "Low", consequence: "Poor PR content.", proof: "PR Calendar", trainerNotes: "Brief FO on arrivals." },
                { id: "HR-DIG-10", description: "Check CRM birthday blast list.", priority: "Medium", riskLevel: "Low", consequence: "Missed guest delight.", proof: "CRM Report", trainerNotes: "Blast sent 7 days pre-date." },
                { id: "HR-DIG-11", description: "Verify 'Promo Code' validity.", priority: "High", riskLevel: "Medium", consequence: "Customer booking frustration.", proof: "Test Booking", trainerNotes: "Check 'Seasonal' codes." },
                { id: "HR-DIG-12", description: "Review competitor rate trend.", priority: "Low", riskLevel: "Low", consequence: "Inability to adapt to market.", proof: "Comp Set Log", trainerNotes: "Check Airbnb pricing daily." },
                { id: "HR-DIG-13", description: "Audit property photos on portals.", priority: "Low", riskLevel: "Low", consequence: "Outdated brand image.", proof: "Visual Audit", trainerNotes: "Update seasonal shots." },
                { id: "HR-DIG-14", description: "Check 'Email Signature' branding.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional comms.", proof: "Inbox Check", trainerNotes: "Enforce brand template." },
                { id: "HR-DIG-15", description: "Verify newsletter 'Unsubscribe' link.", priority: "High", riskLevel: "Medium", consequence: "Legal privacy violations.", proof: "Test Email", trainerNotes: "Target GDPR compliance." },
                { id: "HR-DIG-16", description: "Review 'Abandon Cart' stats.", priority: "Low", riskLevel: "Low", consequence: "Unrealized sales leakage.", proof: "Web Report", trainerNotes: "Trigger recovery email < 1h." },
                { id: "HR-DIG-17", description: "Audit 'SEO Keywords' ranking.", priority: "Low", riskLevel: "Low", consequence: "Lost organic traffic.", proof: "SEO Log", trainerNotes: "Focus on 'Hotel in [Zone]'." },
                { id: "HR-DIG-18", description: "Verify SSL certificate expiry date.", priority: "High", riskLevel: "High", consequence: "Site warning/Total traffic loss.", proof: "System Dashboard", trainerNotes: "Renew 30 days early." },
                { id: "HR-DIG-19", description: "Check portal mapping for new rooms.", priority: "Medium", riskLevel: "High", consequence: "Inventory drift.", proof: "Mapping Table", trainerNotes: "Test with test-booking." },
                { id: "HR-DIG-20", description: "Audit 'Pay-at-Hotel' vs Voucher.", priority: "High", riskLevel: "Medium", consequence: "Billing confusion.", proof: "POS Report", trainerNotes: "Flag MMT 'Prepaid' vouchers." },
                { id: "HR-DIG-21", description: "Review social media 'Sentiment'.", priority: "Low", riskLevel: "Low", consequence: "Undetected PR fire.", proof: "Sentiment Log", trainerNotes: "Check tags daily." },
                { id: "HR-DIG-22", description: "Check 'Live Chat' agent response.", priority: "Low", riskLevel: "Low", consequence: "Lost website leads.", proof: "Chat Log", trainerNotes: "Target < 1 min response." },
                { id: "HR-DIG-23", description: "Final daily Digital Command sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of ORM control.", proof: "Signed Dashboard", trainerNotes: "Submit to GM." }
            ]
        },
        {
            title: "Vendors & Fleet Logistics",
            department: "Logistics",
            frequency: "Daily",
            role: "Logistics Lead",
            summary: "Supply integrity and first impression command.",
            icon: "truck",
            tasks: [
                { id: "HR-LOG-01", description: "Driver Sobriety Audit: Breathalyzer.", priority: "High", riskLevel: "High", consequence: "Fatal crash/Legal disaster.", proof: "Test Note", trainerNotes: "Conduct pre-airport trip." },
                { id: "HR-LOG-02", description: "Vendor Receiving: Reconcile weight.", priority: "Medium", riskLevel: "Medium", consequence: "Paying for missing stock.", proof: "Scale Note", trainerNotes: "Reject variance > 2%." },
                { id: "HR-LOG-03", description: "Garden presentation: Debris removal.", priority: "Low", riskLevel: "Low", consequence: "Poor curb appeal.", proof: "Visual Check", trainerNotes: "Check porch planters." },
                { id: "HR-LOG-04", description: "Fleet AC/Wi-Fi heartbeat test.", priority: "Medium", riskLevel: "Low", consequence: "Luxury transfer failure.", proof: "Visual Audit", trainerNotes: "Stock chilled water daily." },
                { id: "HR-LOG-05", description: "Verify vendor FSSAI for perishables.", priority: "High", riskLevel: "High", consequence: "Legal liability for unvetted.", proof: "License File", trainerNotes: "Renew repository every 6m." },
                { id: "HR-LOG-06", description: "Check valet driver uniform/ID.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution at arrival.", proof: "Roster Log", trainerNotes: "Must wear white gloves." },
                { id: "HR-LOG-07", description: "Inspect back-alley waste bins.", priority: "Medium", riskLevel: "Medium", consequence: "Pest risk/Odors.", proof: "Cleaning Log", trainerNotes: "Bins must be closed." },
                { id: "HR-LOG-08", description: "Verify luggage tag stock levels.", priority: "Low", riskLevel: "Low", consequence: "Operational delays.", proof: "Supply Check", trainerNotes: "Min 500 tags buffer." },
                { id: "HR-LOG-09", description: "Reconcile valet fuel expense claims.", priority: "Medium", riskLevel: "Medium", consequence: "Internal revenue loss.", proof: "Voucher Reconcile", trainerNotes: "Match vs Odometer." },
                { id: "HR-LOG-10", description: "Verify vendor attendance logs.", priority: "Low", riskLevel: "Low", consequence: "Paying for unrendered work.", proof: "Log Review", trainerNotes: "Deduct for late arrivals." },
                { id: "HR-LOG-11", description: "Check porch floor buffing status.", priority: "Low", riskLevel: "Low", consequence: "Dull luxury entry.", proof: "Visual Check", trainerNotes: "Buff nightly at 2 AM." },
                { id: "HR-LOG-12", description: "Audit staff shuttle route speed.", priority: "Medium", riskLevel: "High", consequence: "Accident risk.", proof: "GPS Report", trainerNotes: "Target < 40km/h." },
                { id: "HR-LOG-13", description: "Verify 'Guest Gift' stock levels.", priority: "Low", riskLevel: "Low", consequence: "VIP service failure.", proof: "Inventory Note", trainerNotes: "Target 10 sets buffer." },
                { id: "HR-LOG-14", description: "Check water irrigation pressure.", priority: "Low", riskLevel: "Low", consequence: "Dead lawn patches.", proof: "Visual Check", trainerNotes: "Check at sunset." },
                { id: "HR-LOG-15", description: "Audit outsourced HK staff ID.", priority: "High", riskLevel: "High", consequence: "Unauthorized person risk.", proof: "Patrol Log", trainerNotes: "Badges must be chest-high." },
                { id: "HR-LOG-16", description: "Verify vendor invoice math checks.", priority: "Low", riskLevel: "Low", consequence: "Cumulative financial loss.", proof: "Ledger Audit", trainerNotes: "Spot-check 5% monthly." },
                { id: "HR-LOG-17", description: "Check car tire-tread depth audit.", priority: "High", riskLevel: "High", consequence: "Safety accident liability.", proof: "Fleet Sheet", trainerNotes: "Replace if < 2mm." },
                { id: "HR-LOG-18", description: "Verify loading bay lock integrity.", priority: "High", riskLevel: "High", consequence: "After-hours theft.", proof: "Lock Audit", trainerNotes: "Keys to GM nightly." },
                { id: "HR-LOG-19", description: "Check staff restroom drainage.", priority: "Low", riskLevel: "Low", consequence: "Unhygienic staff zone.", proof: "Cleaning Note", trainerNotes: "Buff mirrors daily." },
                { id: "HR-LOG-20", description: "Review P1 vendor service TAT.", priority: "Medium", riskLevel: "Low", consequence: "Delayed repairs.", proof: "SLA Match", trainerNotes: "Penalty for > 4h delay." },
                { id: "HR-LOG-21", description: "Verify porch music box sync.", priority: "Low", riskLevel: "Low", consequence: "Silent arrival ambiance.", proof: "Volume Check", trainerNotes: "Chilled jazz default." },
                { id: "HR-LOG-22", description: "Check availability of spare car keys.", priority: "Low", riskLevel: "Medium", consequence: "Guest delay crisis.", proof: "Vault Inventory", trainerNotes: "Secure in main safe." },
                { id: "HR-LOG-23", description: "Final shift Logistics sign-off.", priority: "High", riskLevel: "Low", consequence: "Incomplete handover.", proof: "Signed Summary", trainerNotes: "Brief GM on arrivals." }
            ]
        }
    ]
};
