
import type { PremiumPack } from "@/lib/premium-packs";

export const restaurants: PremiumPack = {
    id: 'restaurants',
    title: "Restaurant Operations Control System (ROCS)",
    category: "Hospitality",
    description: "The definitive governance framework for 5-star restaurant reliability. Includes 240+ technical SOPs, Multi-Branch Switchboard, and ROI tracking.",
    heroHeadline: "RESTAURANT OPERATIONAL CONSOLE v4.3",
    heroSubheadline: "The Sovereign Standard for COOs and Owners who take zero-risk governance and P&L protection seriously. Stop managing manually.",
    pricingUrgency: "One health department closure or a single 'never event' costs 100x more than this entire system.",
    consultingAnchor: 5000,
    priceINR: 5999,
    priceUSD: 79,
    competitorPriceUSD: 599,
    updatedAt: "2025-02-24",
    paymentId: 'pl_RaWEBHhFLQENxC',
    lemonSqueezyUrl: 'https://moremeets.lemonsqueezy.com/buy/f4e6b12a-4422-48a0-a198-154332822a27',
    icon: "utensils-crossed",
    badgeText: "V4.3 SOVEREIGN",
    badgeVariant: "accent",
    bestseller: true,
    whoIsItFor: ["Restaurant Owners", "Group COOs", "Multi-Unit Managers", "Executive Chefs"],
    sampleItems: [
        { text: "<strong>Live Executive Intelligence</strong>: See which branch, team, and staff are performing in seconds with the 'Empire Mood' banner.", icon: "zap" },
        { text: "<strong>2-Minute Reporting</strong>: Staff find their specific role tasks using integrated filters, ensuring 100% adoption without the paperwork fatigue.", icon: "timer" },
        { text: "<strong>Multi-Branch Switchboard</strong>: Toggle Bar, Garden, Valet, and Pool modules ON/OFF to fit every unique outlet in your group.", icon: "layout-grid" },
        { text: "<strong>Institutional Memory</strong>: Convert tribal knowledge into permanent infrastructure. New hires execute like veterans from Day 1.", icon: "history" },
        { text: "<strong>Manager Target Verification</strong>: Highlighted 'Yellow Cells' show leadership exactly where to sign off on high-risk control points.", icon: "shield-check" },
        { text: "<strong>Loss Recovery Engine</strong>: Track operational incidents and quantify their financial impact to protect your bottom-line margins.", icon: "banknote" }
    ],
    checklists: [
        {
            title: "Kitchen Opening",
            department: "Kitchen",
            frequency: "Daily",
            role: "Head Chef",
            summary: "Critical food safety and readiness protocols.",
            icon: "sunrise",
            tasks: Array.from({ length: 20 }, (_, i) => ({
                id: `KO-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Log temperatures of all walk-in chillers and freezers.",
                    "Inspect dry storage for signs of rodents or pests.",
                    "Verify sanitization of all surfaces using 200ppm strips.",
                    "Calibrate all food probes using ice-point method.",
                    "Audit staff health and grooming (nails, wounds, hair).",
                    "Check inventory of all high-risk perishable items.",
                    "Verify functionality of all kitchen exhaust systems.",
                    "Prepare sanitized sanitizer buckets for all workstations.",
                    "Organize raw prep area according to color-coding rules.",
                    "Test all dishwasher chemical levels.",
                    "Check availability of blue detectable band-aids.",
                    "Verify pest control bait station placement.",
                    "Check water filter pressure for ice machine.",
                    "Inspect grease trap for capacity/odors.",
                    "Check oven gaskets for heat leaks.",
                    "Verify raw protein date labeling.",
                    "Audit knife magnet for count integrity.",
                    "Inspect ceiling for leaks/mold.",
                    "Verify staff handwashing station temp (Min 38°C).",
                    "Check vegetable wash chemical ppm."
                ][i],
                priority: i < 5 ? "High" : "Medium",
                riskLevel: i < 5 ? "High" : "Medium",
                consequence: "Pathogen transmission, food waste, or regulatory closure.",
                proof: "Digital Log / Photo",
                trainerNotes: "Standard clinical procedure. Do not skip."
            }))
        },
        {
            title: "Kitchen Closing",
            department: "Kitchen",
            frequency: "Daily",
            role: "Sous Chef",
            summary: "End-of-shift safety and sanitation shutdown.",
            icon: "sunset",
            tasks: Array.from({ length: 20 }, (_, i) => ({
                id: `KC-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Perform mandatory main gas valve shutdown.",
                    "Empty and deep-clean all deep fryers.",
                    "Label and date-stamp all prepped items (FIFO).",
                    "Clean and sanitize all walk-in floor drains.",
                    "Organize and secure chemical storage locker.",
                    "Empty all trash bins and sanitize interiors.",
                    "Check all pilot lights are extinguished.",
                    "Sanitize meat slicer and disassemble.",
                    "Secure all knife magnets and sharpen.",
                    "Final walk-in door seal verification.",
                    "Discard all open dairy past expiry.",
                    "Turn off all hood lights and fans.",
                    "Wipe down all door handles with 70% alcohol.",
                    "Mop floors with degreaser.",
                    "Secure all prep fridge lids.",
                    "Check dishwasher for food debris.",
                    "Verify all staff have clocked out.",
                    "Empty and dry bain-marie wells.",
                    "Lock dry store and wine cellar.",
                    "Review morning prep list for next day."
                ][i],
                priority: "High",
                riskLevel: "High",
                consequence: "Fire risk, overnight spoilage, or hygiene failure.",
                proof: "Physical Log",
                trainerNotes: "Critical for overnight facility safety."
            }))
        },
        {
            title: "Bar Opening",
            department: "Bar",
            frequency: "Daily",
            role: "Bar Manager",
            summary: "Beverage service readiness and revenue protection.",
            icon: "glass-water",
            tasks: Array.from({ length: 20 }, (_, i) => ({
                id: `BO-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Ice machine deep flush and visual hygiene check.",
                    "Reconcile spirit inventory against previous closing.",
                    "Date-code all fresh fruit garnishes.",
                    "Check draft beer line pressure (12-14 PSI).",
                    "Sanitize all jiggers and speed pours.",
                    "Verify coffee machine group head pressure.",
                    "Check inventory of tonic/soda mixers.",
                    "Inspect glassware for chips or cracks.",
                    "Verify functionality of bar POS printer.",
                    "Check wine chiller temp (Red: 14°C, White: 7°C).",
                    "Sanitize bar counter and stools.",
                    "Test cocktail station refrigeration.",
                    "Verify availability of tamper-proof seals.",
                    "Check floor mat placement at bar wells.",
                    "Brief team on 'Drink of the Month' specs.",
                    "Verify cocktail menu availability.",
                    "Clean beer drip trays.",
                    "Check speed rail order and cleanliness.",
                    "Verify bar towel stock.",
                    "Test blender functionality."
                ][i],
                priority: "Medium",
                riskLevel: "Medium",
                consequence: "Inventory theft, poor quality, or customer complaint.",
                proof: "Visual Audit",
                trainerNotes: "Focus on stock integrity and glass safety."
            }))
        },
        {
            title: "Bar Closing",
            department: "Bar",
            frequency: "Daily",
            role: "Head Bartender",
            summary: "Revenue and stock security shutdown.",
            icon: "lock",
            tasks: Array.from({ length: 20 }, (_, i) => ({
                id: `BC-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Perform blind-count of high-value malts.",
                    "Deep-clean and sanitize all bar wells and drains.",
                    "Lock spirit cages and secure key in safe.",
                    "Disconnect beer line couplers (if per SOP).",
                    "Wash and dry all shaker tins and tools.",
                    "Empty all bar waste and sanitize bins.",
                    "Check under-counter fridge door seals.",
                    "Verify all open wines are vacuum sealed.",
                    "Clean coffee machine backflush.",
                    "Reconcile POS cash vs reports.",
                    "Lock bar entrance and secure gate.",
                    "Clean soda gun holsters.",
                    "Record total wastage for shift.",
                    "Turn off bar music and dimmers.",
                    "Hand over keys to Duty Manager.",
                    "Sanitize speed pourers.",
                    "Check draft handles are locked.",
                    "Verify garnish discard log.",
                    "Clean back bar shelves.",
                    "Log POS server sync status."
                ][i],
                priority: "High",
                riskLevel: "High",
                consequence: "Theft, pest attraction, or revenue leakage.",
                proof: "Stock Sheet / Z-Report",
                trainerNotes: "Zero tolerance for cash or spirit variance."
            }))
        },
        {
            title: "Dining Room Service",
            department: "Service",
            frequency: "Daily",
            role: "Floor Manager",
            summary: "Brand standards and guest comfort audits.",
            icon: "layout",
            tasks: Array.from({ length: 20 }, (_, i) => ({
                id: `FOH-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Table Wobble & Cleanliness Walkthrough.",
                    "Restroom 10-Point Audit (Paper, Scent, Water).",
                    "Verify Menu & Table Talker pricing accuracy.",
                    "Check ambient lighting/Dimmer presets.",
                    "Test Playlist & Volume Levels.",
                    "Inspect host stand for guest wait-list readiness.",
                    "Verify server uniform/grooming (Nails, Hair).",
                    "Check functionality of credit card machines.",
                    "Inspect high-chairs for safety/cleanliness.",
                    "Verify water TDS levels for guest service.",
                    "Audit server product knowledge (Specials).",
                    "Check for any burnt-out light bulbs.",
                    "Verify AC temperature (Goal: 22-24°C).",
                    "Inspect upholstery for stains/damage.",
                    "Check salt/pepper shaker levels and cleanliness.",
                    "Audit cutlery for water spots/smudges.",
                    "Verify fire extinguisher accessibility in FOH.",
                    "Check emergency exit signage illumination.",
                    "Monitor speed of service (Target: 15m Apps).",
                    "Confirm manager password for voids is secure."
                ][i],
                priority: "Medium",
                riskLevel: "Medium",
                consequence: "Guest dissatisfaction, legal disputes, or brand damage.",
                proof: "Walkthrough Log",
                trainerNotes: "Standards must match the 5-star benchmark."
            }))
        },
        {
            title: "EHS & Safety Audit",
            department: "Compliance",
            frequency: "Weekly",
            role: "General Manager",
            summary: "Life-safety and legal liability mitigation.",
            icon: "hard-hat",
            tasks: Array.from({ length: 20 }, (_, i) => ({
                id: `EHS-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Fire Exit Clearance & Panic Bar Test.",
                    "First Aid & AED Battery/Stock Audit.",
                    "Electrical Panel Hotspot/Odor Audit.",
                    "Floor Slip-Resistance & Mat Audit.",
                    "Emergency Lighting Backup Test.",
                    "Kitchen Fire Suppression (Ansul) Audit.",
                    "CO2 Gas Storage & Leak Audit (Bar).",
                    "Stairwell Treads & Handrail Audit.",
                    "Hazardous Chemical (MSDS) Registry.",
                    "Electrical Cable Management Audit (Office).",
                    "Kitchen Ventilation Belt/Motor Health.",
                    "Pest Exclusion (Gaps/Holes) Audit.",
                    "Staff Lifting Technique Observation.",
                    "Roof Drain/Gutter Clearance Check.",
                    "CCTV Camera Angle & Cleaning Audit.",
                    "Waste Compactor/Area Hygiene Check.",
                    "Staff Canteen/Locker Safety Walk.",
                    "Backup Generator Fuel & Oil Level.",
                    "Kitchen Sinks Drain Speed Check.",
                    "Manager Safety SOP Knowledge Test."
                ][i],
                priority: "High",
                riskLevel: "High",
                consequence: "Fatal injury, structural fire, or massive litigation.",
                proof: "Safety Log / Vendor Certificate",
                trainerNotes: "Mandatory weekly walkthrough for liability protection."
            }))
        },
        {
            title: "Statutory & Licensing",
            department: "Executive",
            frequency: "Monthly",
            role: "Owner/COO",
            summary: "License renewal and legal governance.",
            icon: "landmark",
            tasks: Array.from({ length: 20 }, (_, i) => ({
                id: `STAT-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "FSSAI & Health License Expiry Review.",
                    "Alcohol Excise Register Reconciliation.",
                    "Weights & Measures (Scales) Calibration Audit.",
                    "Financial P&L Review vs Budget.",
                    "Labour Law / PF Compliance Audit.",
                    "Fire NOC Renewal Status Check.",
                    "Pest Control Contract & Service Log Audit.",
                    "Lift License & Safety Certificate.",
                    "GST Filing Confirmation (Previous Month).",
                    "Property Tax / Lease Payment Review.",
                    "Music License (PPL/IPRS) Confirmation.",
                    "Signage/Hoarding License Audit.",
                    "Water Quality Lab Report (Annual).",
                    "Staff Medical Fitness Records Audit.",
                    "Insurance Policy Expiry Check.",
                    "Trade License Validity Check.",
                    "Sign-board License Proof.",
                    "Environmental (Pollution) NOC.",
                    "Legal Metrology Audit (Packaging).",
                    "Employee Background Check Registry."
                ][i],
                priority: "High",
                riskLevel: "High",
                consequence: "Operational closure, arrest, or financial ruin.",
                proof: "Document Audit / Receipt",
                trainerNotes: "Renewals must trigger 60 days in advance."
            }))
        },
        {
            title: "Home Delivery Control",
            department: "Logistics",
            frequency: "Daily",
            role: "Dispatch Coordinator",
            summary: "Off-site brand and safety management.",
            icon: "truck",
            tasks: Array.from({ length: 20 }, (_, i) => ({
                id: `DEL-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Thermal Bag Hygiene & Odor Audit.",
                    "Verify Tamper-Evident Seal Inventory.",
                    "Driver Grooming & Vehicle Cleanliness Check.",
                    "Order ID Handoff Procedure (3-Point Match).",
                    "Packaging Heat-Retention Integrity Check.",
                    "Audit dispatch area surface sanitation.",
                    "Check availability of driver sanitizers.",
                    "Verify route-optimization efficiency.",
                    "Track 3PL driver wait times.",
                    "Inspect delivery vehicle branding/signage.",
                    "Review guest feedback on delivery packing.",
                    "Verify cold-chain items stay chilled in bag.",
                    "Check driver safety gear (Gloves/Boots).",
                    "Audit takeaway cutlery inclusion rate.",
                    "Reconcile aggregator tabs vs POS daily.",
                    "Verify dispatch area lighting.",
                    "Check bike maintenance logs.",
                    "Audit driver hydration station.",
                    "Verify dispatch printer roll stock.",
                    "Monitor peak hour dispatch lag."
                ][i],
                priority: "Medium",
                riskLevel: "Medium",
                consequence: "Customer churn, food poisoning, or revenue loss.",
                proof: "Dispatch Log",
                trainerNotes: "Delivery is the brand in the guest's home."
            }))
        },
        {
            title: "Takeaway & Pickup",
            department: "Service",
            frequency: "Daily",
            role: "Hostess",
            summary: "Counter service speed and accuracy.",
            icon: "shopping-bag",
            tasks: Array.from({ length: 20 }, (_, i) => ({
                id: `PICK-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Counter Sanitization & Napkin/Cutlery Stock.",
                    "Order Accuracy Double-Check at Counter.",
                    "Pickup Lane Clearance Walkthrough.",
                    "Check availability of pre-printed bills.",
                    "Verify packaging lid-tightness.",
                    "Audit guest wait area cleanliness.",
                    "Check loyalty point enrolment procedure.",
                    "Test counter POS card tap functionality.",
                    "Verify condiment stock (Ketchup/Salt).",
                    "Manager check of high-value takeaway orders.",
                    "Verify takeaway bag handles.",
                    "Check for correct menu placement.",
                    "Verify order display screen sync.",
                    "Clean POS screens.",
                    "Check stock of business cards.",
                    "Audit pickup turnaround time.",
                    "Verify counter staff grooming.",
                    "Check telephone responsiveness.",
                    "Verify availability of QR menus.",
                    "Reconcile daily takeaway revenue."
                ][i],
                priority: "High",
                riskLevel: "High",
                consequence: "Service chaos, inaccurate orders, or theft.",
                proof: "Visual Check / POS Report",
                trainerNotes: " Handoff is the critical moment of trust."
            }))
        },
        {
            title: "Valet Parking Security",
            department: "Security",
            frequency: "Daily",
            role: "Security Manager",
            summary: "Vehicle security and liability management.",
            icon: "car",
            tasks: Array.from({ length: 10 }, (_, i) => ({
                id: `VAL-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Log existing vehicle damage at intake.",
                    "Key Safe 2-Person Verification.",
                    "CCTV Blindspot & Night-Lighting Check.",
                    "Verify driver license validity.",
                    "Check valet parking area surface safety.",
                    "Audit key retrieval time (Target: < 5m).",
                    "Inspect valet uniform & flashlight stock.",
                    "Verify insurance validity for valet parking.",
                    "Check parking permit area compliance.",
                    "Perform key safe inventory count."
                ][i],
                priority: "High",
                riskLevel: "High",
                consequence: "Vehicle theft, damage claims, or driver liability.",
                proof: "Damage Card / Key Log",
                trainerNotes: "Valet is the first and last guest touchpoint."
            }))
        },
        {
            title: "Garden & Outdoor",
            department: "Facilities",
            frequency: "Weekly",
            role: "Facility Manager",
            summary: "Outdoor ambiance and pest control.",
            icon: "sprout",
            tasks: Array.from({ length: 10 }, (_, i) => ({
                id: `GAR-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Outdoor Pest Boundary Treatment Log.",
                    "Weatherproofing & Umbrella Anchor Audit.",
                    "Stone/Pathway Trip hazard Walkthrough.",
                    "Outdoor Lighting & Dimmer Functional Test.",
                    "Plant Health & Irrigation Audit.",
                    "Check for beehives/wasp nests.",
                    "Verify outdoor AC/Misting system pressure.",
                    "Inspect outdoor furniture for rust/splinters.",
                    "Clean outdoor debris and dust.",
                    "Audit outdoor music volume levels."
                ][i],
                priority: "Medium",
                riskLevel: "Medium",
                consequence: "Infestation, guest injury, or atmosphere failure.",
                proof: "Vendor Log / Walkthrough",
                trainerNotes: "Nature is chaotic; the system must be rigid."
            }))
        },
        {
            title: "Staff Quarters",
            department: "HR",
            frequency: "Daily",
            role: "HR Supervisor",
            summary: "Internal welfare and back-of-house hygiene.",
            icon: "home",
            tasks: Array.from({ length: 10 }, (_, i) => ({
                id: `SQ-${(i + 1).toString().padStart(2, '0')}`,
                description: [
                    "Staff Locker & Changing Room Deep Clean.",
                    "Uniform Laundry Sanitization Check.",
                    "Staff Drinking Water Filter Audit.",
                    "Inspect staff toilets for hygiene.",
                    "Verify staff meal hygiene & temp.",
                    "Check fire alarm in staff quarters.",
                    "Inspect beds for bugs/pests.",
                    "Verify adequate lighting in hallways.",
                    "Audit personal item storage policy.",
                    "Manager 1-on-1 Welfare Check."
                ][i],
                priority: "Medium",
                riskLevel: "Medium",
                consequence: "Staff sickness, low morale, or internal fire.",
                proof: "Walkthrough / TDS Log",
                trainerNotes: "The team's environment reflects the guest's environment."
            }))
        }
    ]
};
