
import type { PremiumPack } from "@/lib/premium-packs";

export const school_operations_pack: PremiumPack = {
    id: 'school_operations_pack',
    title: "School Operating System",
    priceINR: 5999,
    priceUSD: 79,
    category: "Education",
    description: "The Sovereign v9.1 technical engine for K-12 and Academies. Hardening 152 control points from School Bus safety to Science Lab security.",
    heroHeadline: "Zero-Risk Campus Operations. Audit-Ready.",
    heroSubheadline: "Standardize safety, transport, social reputation, and academic governance across your entire campus with a logically-aware data engine.",
    pricingUrgency: "In education, a single safety 'never event' is an institutional catastrophe. This system is the safeguard.",
    consultingAnchor: 10000,
    icon: "school",
    badgeText: "V9.1 SOVEREIGN",
    badgeVariant: "destructive",
    whoIsItFor: ["School Principals", "Trustees", "Heads of Administration", "Transport Managers", "Registrars"],
    sampleItems: [
        { text: "<strong>Transport (Bus) Command</strong>: Mandatory 'Empty Bus Walkthrough' and driver sobriety checks.", icon: "bus" },
        { text: "<strong>Social Media & ORM</strong>: 24h response pulse for reviews and parent inquiry tracking.", icon: "megaphone" },
        { text: "<strong>Expedition & Trip Safety</strong>: Risk assessments and permission audits for off-campus tours.", icon: "map" },
        { text: "<strong>Campus Security & CCTV</strong>: 30-day backup verification and visitor ID lockdown protocols.", icon: "shield-check" }
    ],
    checklists: [
        {
            title: "Board & Trustee Governance",
            department: "Executive",
            frequency: "Weekly",
            role: "COO / Owner",
            summary: "Campus-wide strategic risk and liability oversight.",
            icon: "crown",
            tasks: [
                { id: "SC-EXE-01", description: "Review Transport Incident alerts and GPS speed violations.", priority: "High", riskLevel: "High", consequence: "Institutional negligence liability.", proof: "Alert Log", trainerNotes: "Check for any bus reaching > 45km/h." },
                { id: "SC-EXE-02", description: "Audit POCSO compliance and staff background check validity.", priority: "High", riskLevel: "High", consequence: "Severe legal and moral catastrophe.", proof: "Matrix Audit", trainerNotes: "Verify police verification for new hires." },
                { id: "SC-EXE-03", description: "Verify Insurance: Public Liability & Student Accident policy.", priority: "High", riskLevel: "High", consequence: "Uncovered medical litigation.", proof: "Policy File", trainerNotes: "Check expiry 60 days pre-term." },
                { id: "SC-EXE-04", description: "Review 'Sentinel Event' Log: near-miss accidents.", priority: "High", riskLevel: "High", consequence: "Recurring safety failure.", proof: "Log Review", trainerNotes: "Ensure every slip has a root cause." },
                { id: "SC-EXE-05", description: "Audit Board Meeting minutes for safety approvals.", priority: "Medium", riskLevel: "Low", consequence: "Administrative drift.", proof: "Minutes File", trainerNotes: "Check sign-off on CAPEX for security." },
                { id: "SC-EXE-06", description: "Review monthly 'Fee Collection' vs Budget gap.", priority: "High", riskLevel: "Medium", consequence: "Operational cash crunch.", proof: "Finance Chart", trainerNotes: "Escalate > 10% variance." },
                { id: "SC-EXE-07", description: "Verify Fire NOC and Structural Stability certificates.", priority: "High", riskLevel: "High", consequence: "Premises sealing by authorities.", proof: "NOC Certificate", trainerNotes: "Display at main reception." },
                { id: "SC-EXE-08", description: "Review 'Staff Churn' trends in Academic departments.", priority: "Low", riskLevel: "Low", consequence: "Curriculum discontinuity.", proof: "HR Dashboard", trainerNotes: "Analyze exit interview reasons." },
                { id: "SC-EXE-09", description: "Audit 'Institutional Memory' backup status.", priority: "Medium", riskLevel: "Low", consequence: "Loss of academic records.", proof: "Server Log", trainerNotes: "Check cloud sync every Monday." },
                { id: "SC-EXE-10", description: "Check status of CCTV in 'Blind Spot' zones.", priority: "High", riskLevel: "Medium", consequence: "Unmonitored student zones.", proof: "Monitor Check", trainerNotes: "Focus on back stairs/lockers." },
                { id: "SC-EXE-11", description: "Review 'Expedition Safety' protocols for upcoming trips.", priority: "High", riskLevel: "High", consequence: "Unmanaged off-site risks.", proof: "Trip Risk File", trainerNotes: "Verify teacher-student ratios." },
                { id: "SC-EXE-12", description: "Audit vendor pricing for Canteen/Uniforms.", priority: "Medium", riskLevel: "Low", consequence: "Inflated procurement costs.", proof: "Vendor Log", trainerNotes: "Check Top 10 items prices." },
                { id: "SC-EXE-13", description: "Verify 'Emergency PA' system coverage.", priority: "High", riskLevel: "High", consequence: "Communication failure during crisis.", proof: "Test Note", trainerNotes: "Test from Playground zone." },
                { id: "SC-EXE-14", description: "Review status of 'Scholarship' quota audits.", priority: "Low", riskLevel: "Medium", consequence: "Regulatory non-conformance.", proof: "Quota File", trainerNotes: "Verify eligibility documents." },
                { id: "SC-EXE-15", description: "Audit fixed assets in Computer Labs.", priority: "Low", riskLevel: "Low", consequence: "Lost institutional property.", proof: "Asset Log", trainerNotes: "PCs must have physical tags." },
                { id: "SC-EXE-16", description: "Check compliance with local building bylaws.", priority: "High", riskLevel: "High", consequence: "Legal sealing of wings.", proof: "Compliance File", trainerNotes: "Review floor usage quarterly." },
                { id: "SC-EXE-17", description: "Review 'Curriculum Progress' vs Calendar.", priority: "Low", riskLevel: "Low", consequence: "Delayed exam readiness.", proof: "Academic Log", trainerNotes: "Highlight > 2 week lags." },
                { id: "SC-EXE-18", description: "Audit 'Theft/Incident' trends in Hostels.", priority: "High", riskLevel: "Medium", consequence: "Student safety perception drop.", proof: "Incident Log", trainerNotes: "Check lock integrity weekly." },
                { id: "SC-EXE-19", description: "Final weekly Governance sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of administrative control.", proof: "Signed Summary", trainerNotes: "Submit to Board of Trustees." }
            ]
        },
        {
            title: "Campus Command & Counselling",
            department: "Operations",
            frequency: "Daily",
            role: "General Manager",
            summary: "Student flow, counselling governance, and trip logistics.",
            icon: "school",
            tasks: [
                { id: "SC-OPS-01", description: "Teacher Arrival: Verify 100% parity by 8:15 AM.", priority: "High", riskLevel: "Low", consequence: "Unsupervised classrooms.", proof: "Attendance Log", trainerNotes: "Assign stand-by teachers instantly." },
                { id: "SC-OPS-02", description: "Assembly Hall: Verify sound, mics, and lighting.", priority: "Medium", riskLevel: "Low", consequence: "Chaos during morning prayers.", proof: "Visual Check", trainerNotes: "Check PA system feedback levels." },
                { id: "SC-OPS-03", description: "Student Counsellor: Verify session log completion.", priority: "High", riskLevel: "High", consequence: "Unaddressed behavioral risks.", proof: "Confidential Log", trainerNotes: "Check counts only (Privacy applies)." },
                { id: "SC-OPS-04", description: "Medical Emergency: Verify infirmary nurse presence.", priority: "High", riskLevel: "High", consequence: "Failure to life-support.", proof: "Roster Check", trainerNotes: "Nurse must be at desk by 8 AM." },
                { id: "SC-OPS-05", description: "Classroom Audit: Check for furniture damage/splinters.", priority: "Medium", riskLevel: "Medium", consequence: "Student injury negligence.", proof: "Visual Audit", trainerNotes: "Focus on desk-edge integrity." },
                { id: "SC-OPS-06", description: "Teachers Room: Audit hygiene and behavior standards.", priority: "Low", riskLevel: "Low", consequence: "Brand professionalism drop.", proof: "Cleaning Note", trainerNotes: "Check for unwashed mugs/papers." },
                { id: "SC-OPS-07", description: "Field Trip Readiness: Audit permission slips for Grade X.", priority: "High", riskLevel: "High", consequence: "Legal liability for unauthorized trip.", proof: "Slip Registry", trainerNotes: "No slip, No trip. Manual check." },
                { id: "SC-OPS-08", description: "School Bell: Sync with master time-server.", priority: "Low", riskLevel: "Low", consequence: "Campus scheduling chaos.", proof: "Visual Check", trainerNotes: "Drift must be < 10 seconds." },
                { id: "SC-OPS-09", description: "Lost & Found: Log all arrivals and tag with Date.", priority: "Medium", riskLevel: "Low", consequence: "Parent disputes over assets.", proof: "L&F Ledger", trainerNotes: "Secure in main admin vault." },
                { id: "SC-OPS-10", description: "Corridor Patrol: Check for unauthorized student groups.", priority: "Medium", riskLevel: "Medium", consequence: "Bullying opportunities.", proof: "Patrol Note", trainerNotes: "Check back-alleys during recess." },
                { id: "SC-OPS-11", description: "Library: Verify 'Silence Zone' and book return pulse.", priority: "Low", riskLevel: "Low", consequence: "Academic environment decay.", proof: "Observation", trainerNotes: "Check decibel levels." },
                { id: "SC-OPS-12", description: "Student Handover: Verify late-pickup list.", priority: "High", riskLevel: "High", consequence: "Kidnapping/Security breach.", proof: "Handover Log", trainerNotes: "ID match mandatory for late pickup." },
                { id: "SC-OPS-13", description: "Verify 'Medical Emergency' phone is charging.", priority: "High", riskLevel: "High", consequence: "No comms during trauma.", proof: "Visual Check", trainerNotes: "Keep dedicated mobile at Reception." },
                { id: "SC-OPS-14", description: "Inspect Hall floors for slick spots pre-recess.", priority: "High", riskLevel: "High", consequence: "Slip and fall litigation.", proof: "Mop Log", trainerNotes: "Use 'Wet Floor' signs 100%." },
                { id: "SC-OPS-15", description: "Counselling: Log 'Red Flag' alerts to Principal.", priority: "High", riskLevel: "High", consequence: "Fatal self-harm or violence risk.", proof: "Alert Note", trainerNotes: "Escalate behavioral shifts instantly." },
                { id: "SC-OPS-16", description: "Check status of 'Teacher Substitutes' roster.", priority: "High", riskLevel: "Low", consequence: "Academic vacuum.", proof: "Roster Sheet", trainerNotes: "Update by 8:30 AM daily." },
                { id: "SC-OPS-17", description: "Audit Teachers Room noise levels during class.", priority: "Low", riskLevel: "Low", consequence: "Distraction to adjacent rooms.", proof: "Observation", trainerNotes: "Keep doors closed during period." },
                { id: "SC-OPS-18", description: "Verify 'Exam Paper' vault seal status.", priority: "High", riskLevel: "High", consequence: "Academic integrity catastrophe.", proof: "Seal Log", trainerNotes: "Principal + GM sign-off." },
                { id: "SC-OPS-19", description: "Final Daily Campus sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of duty control.", proof: "Signed Log", trainerNotes: "Brief GM on overnight security." }
            ]
        },
        {
            title: "Fee & Finance Shield",
            department: "Finance",
            frequency: "Daily",
            role: "Finance & Cashier",
            summary: "Revenue protection and statutory financial audits.",
            icon: "banknote",
            tasks: [
                { id: "SC-FIN-01", description: "Fee Portal Sync: Reconcile digital vs Bank.", priority: "High", riskLevel: "High", consequence: "Revenue leakage/Unbilled seats.", proof: "Reconcile Sheet", trainerNotes: "Flag variance > ₹100." },
                { id: "SC-FIN-02", description: "Cashier Float: Verify opening/closing cash.", priority: "High", riskLevel: "High", consequence: "Internal theft/Fraud.", proof: "Cash Bag", trainerNotes: "Witnessed seal mandatory." },
                { id: "SC-FIN-03", description: "Petty Cash: Surprise audit vs vouchers.", priority: "Medium", riskLevel: "High", consequence: "Small-scale embezzlement.", proof: "Audit Note", trainerNotes: "No sign, No payout." },
                { id: "SC-FIN-04", description: "Vendor Audit: Check Uniform/Book rates.", priority: "Medium", riskLevel: "Low", consequence: "Parent perception of overcharging.", proof: "Rate List", trainerNotes: "Compare vs market baseline." },
                { id: "SC-FIN-05", description: "Verify Salary bank-links for new staff.", priority: "Low", riskLevel: "Medium", consequence: "Payroll delays/Morale drop.", proof: "System Log", trainerNotes: "Validate IFSC codes." },
                { id: "SC-FIN-06", description: "Audit 'Lost & Found' asset register.", priority: "Low", riskLevel: "Low", consequence: "Untracked asset loss.", proof: "Inventory Note", trainerNotes: "Liquisate unclaimed > 90 days." },
                { id: "SC-FIN-07", description: "Check stationary stock (Answer sheets).", priority: "High", riskLevel: "Medium", consequence: "Exam operational halt.", proof: "Stock Sheet", trainerNotes: "Min 1 month buffer stock." },
                { id: "SC-FIN-08", description: "Verify statutory PF/ESI deposits.", priority: "High", riskLevel: "High", consequence: "Legal penalty/Criminal risk.", proof: "Challan Log", trainerNotes: "Submit by 15th monthly." },
                { id: "SC-FIN-09", description: "Audit 'Late Fee' calculation accuracy.", priority: "Medium", riskLevel: "Low", consequence: "Parent disputes/Refund requests.", proof: "Sample Check", trainerNotes: "Audit 5 random accounts." },
                { id: "SC-FIN-10", description: "Verify Cash-to-Bank deposit slip.", priority: "High", riskLevel: "High", consequence: "Transit theft risk.", proof: "Bank Slip", trainerNotes: "Deposit before 11 AM next day." },
                { id: "SC-FIN-11", description: "Audit 'Free-Seat' quota documentation.", priority: "High", riskLevel: "High", consequence: "Regulatory cancellation of license.", proof: "Quota Registry", trainerNotes: "Verify income certificates." },
                { id: "SC-FIN-12", description: "Check status of 'Electricity' bill payment.", priority: "Medium", riskLevel: "High", consequence: "Campus power disconnection.", proof: "Payment Receipt", trainerNotes: "Pay 5 days pre-deadline." },
                { id: "SC-FIN-13", description: "Audit transport 'Diesel' vouchers.", priority: "Medium", riskLevel: "Medium", consequence: "Fuel theft leakage.", proof: "Match Note", trainerNotes: "Cross-check with odometer." },
                { id: "SC-FIN-14", description: "Verify 'Library' fine collection total.", priority: "Low", riskLevel: "Low", consequence: "Untracked micro-leakage.", proof: "Fine Register", trainerNotes: "Reconcile vs system report." },
                { id: "SC-FIN-15", description: "Check availability of 'Bill Books'.", priority: "Low", riskLevel: "Low", consequence: "Administrative friction.", proof: "Stock Audit", trainerNotes: "Order at < 5 books buffer." },
                { id: "SC-FIN-16", description: "Audit staff travel expense claims.", priority: "Low", riskLevel: "Medium", consequence: "Inflated admin expenses.", proof: "Voucher File", trainerNotes: "Verify journey logs." },
                { id: "SC-FIN-17", description: "Verify vendor TDS deductions.", priority: "Medium", riskLevel: "Medium", consequence: "Tax non-conformance.", proof: "TDS Register", trainerNotes: "Check PAN status monthly." },
                { id: "SC-FIN-18", description: "Review 'Revenue per Student' trend.", priority: "Low", riskLevel: "Low", consequence: "Undetected margin erosion.", proof: "Finance Chart", trainerNotes: "Analyze vs previous year." },
                { id: "SC-FIN-19", description: "Final daily Finance sign-off.", priority: "High", riskLevel: "Low", consequence: "Incomplete handover.", proof: "Signed Summary", trainerNotes: "Attach exception reports." }
            ]
        },
        {
            title: "Perimeter & Life Safety",
            department: "Safety",
            frequency: "Daily",
            role: "EHS Officer",
            summary: "Infrastructure hardening, Playground safety, and CCTV command.",
            icon: "hard-hat",
            tasks: [
                { id: "SC-SEC-01", description: "CCTV Audit: Verify 30-day backup sync.", priority: "High", riskLevel: "High", consequence: "Loss of evidence for bullying/theft.", proof: "System Screen", trainerNotes: "Check timestamp accuracy." },
                { id: "SC-SEC-02", description: "Playground: Inspect for loose bolts/rust.", priority: "High", riskLevel: "High", consequence: "Catastrophic child injury.", proof: "Safety Log", trainerNotes: "Check slides and swings base." },
                { id: "SC-SEC-03", description: "Perimeter: check for holes in fence/gates.", priority: "High", riskLevel: "High", consequence: "Intruder entry/Child runaway.", proof: "Patrol Note", trainerNotes: "Check back-alley behind Labs." },
                { id: "SC-SEC-04", description: "Fire Exit: verify corridors are clear.", priority: "High", riskLevel: "High", consequence: "Fatal entrapment.", proof: "Walkthrough", trainerNotes: "No boxes allowed in stairwells." },
                { id: "SC-SEC-05", description: "Visitor ID: Audit register for 100% ID capture.", priority: "High", riskLevel: "High", consequence: "Unauthorized person access.", proof: "Registry Audit", trainerNotes: "Retain ID at main gate." },
                { id: "SC-SEC-06", description: "Emergency PA: Test playground speaker zone.", priority: "High", riskLevel: "Medium", consequence: "Crisis comm failure.", proof: "Sound Test", trainerNotes: "Test at 8 AM sharp." },
                { id: "SC-SEC-07", description: "Check fire extinguisher pressure (Green).", priority: "High", riskLevel: "High", consequence: "Inability to fight fire.", proof: "Gauge Log", trainerNotes: "Service every 180 days." },
                { id: "SC-SEC-08", description: "Verify security guard sobriety check.", priority: "High", riskLevel: "High", consequence: "Vulnerable campus perimeter.", proof: "Test Note", trainerNotes: "Conduct during shift change." },
                { id: "SC-SEC-09", description: "Test 'Panic Button' at main reception.", priority: "High", riskLevel: "High", consequence: "Robbery/Security delay.", proof: "Test Log", trainerNotes: "Silent test with monitoring co." },
                { id: "SC-SEC-10", description: "Check status of 'Wet Floor' signs in Halls.", priority: "Medium", riskLevel: "Medium", consequence: "Slip and fall litigation.", proof: "Visual Check", trainerNotes: "Mandatory for all mopping." },
                { id: "SC-SEC-11", description: "Audit night-shift external floodlights.", priority: "Medium", riskLevel: "Low", consequence: "Security blind spots at night.", proof: "Photo", trainerNotes: "Replace fused bulbs < 24h." },
                { id: "SC-SEC-12", description: "Verify 'LOTO' locks on electrical panels.", priority: "High", riskLevel: "High", consequence: "Fatal technician electrocution.", proof: "Visual Audit", trainerNotes: "No open panels allowed." },
                { id: "SC-SEC-13", description: "Inspect back-alley waste bins for fire risk.", priority: "High", riskLevel: "Medium", consequence: "Arson/External fire risk.", proof: "Walkthrough", trainerNotes: "Clear cardboard daily." },
                { id: "SC-SEC-14", description: "Check first-aid kits in Sports zones.", priority: "High", riskLevel: "Medium", consequence: "Inability to treat pitch injuries.", proof: "Stock Audit", trainerNotes: "Check antiseptic expiry." },
                { id: "SC-SEC-15", description: "Verify 'No Entry' signage on roof access.", priority: "High", riskLevel: "High", consequence: "Fatal fall from height risk.", proof: "Photo", trainerNotes: "Keep doors locked 24/7." },
                { id: "SC-SEC-16", description: "Audit staff entry badge visibility.", priority: "Low", riskLevel: "Low", consequence: "Unidentified staff risk.", proof: "Visual Check", trainerNotes: "Badges must be chest-high." },
                { id: "SC-SEC-17", description: "Verify water-tank cover integrity/locks.", priority: "High", riskLevel: "High", consequence: "Fatal drowning/Water poisoning.", proof: "Visual Audit", trainerNotes: "Monthly padlock check." },
                { id: "SC-SEC-18", description: "Test emergency lighting battery backup.", priority: "Medium", riskLevel: "High", consequence: "Darkness during blackout panic.", proof: "Test Note", trainerNotes: "Run 15 mins monthly." },
                { id: "SC-SEC-19", description: "Final nightly safety sign-off.", priority: "High", riskLevel: "Low", consequence: "Systemic risk gap.", proof: "Manager Initials", trainerNotes: "Physical perimeter touch." }
            ]
        },
        {
            title: "POCSO & Personnel Certs",
            department: "HR",
            frequency: "Monthly",
            role: "HR Manager",
            summary: "Legal competency, Child protection training, and Staff health.",
            icon: "graduation-cap",
            tasks: [
                { id: "SC-HR-01", description: "Verify 100% POCSO training attendance.", priority: "High", riskLevel: "High", consequence: "Severe legal & moral liability.", proof: "Training Log", trainerNotes: "Mandatory for all employees." },
                { id: "SC-HR-02", description: "Audit Teacher Certification validity.", priority: "High", riskLevel: "High", consequence: "Regulatory de-affiliation risk.", proof: "Cert Registry", trainerNotes: "Check B.Ed/Cert expiry dates." },
                { id: "SC-HR-03", description: "Staff Health Pulse: verify med certs.", priority: "Medium", riskLevel: "Medium", consequence: "Infection risk to students.", proof: "Med File", trainerNotes: "Includes canteen staff tests." },
                { id: "SC-HR-04", description: "Teacher Room Behavior Audit: Grooming.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution.", proof: "Briefing Log", trainerNotes: "Check ID cards/Formal dress." },
                { id: "SC-HR-05", description: "Update 'Child Protection' matrix for new hires.", priority: "High", riskLevel: "High", consequence: "Unvetted staff exposure.", proof: "Matrix Update", trainerNotes: "Target < 7 days from DOJ." },
                { id: "SC-HR-06", description: "Audit attendance trends: latecomers.", priority: "Medium", riskLevel: "Low", consequence: "Classroom delay frustration.", proof: "Biometric Log", trainerNotes: "Flag > 3 late entries/week." },
                { id: "SC-HR-07", description: "Verify NDAs signed by visiting coaches.", priority: "High", riskLevel: "Medium", consequence: "Student data privacy risk.", proof: "Signed File", trainerNotes: "Store in secure HR vault." },
                { id: "SC-HR-08", description: "Check availability of spare uniforms.", priority: "Low", riskLevel: "Low", consequence: "Unprofessional hires.", proof: "Inventory Check", trainerNotes: "Min 2 sets per role." },
                { id: "SC-HR-09", description: "Review resignation exit interview notes.", priority: "Low", riskLevel: "Low", consequence: "Unaddressed churn root causes.", proof: "Exit Notes", trainerNotes: "Analyze 'Admin Friction'." },
                { id: "SC-HR-10", description: "Audit staff break-room hygiene.", priority: "Low", riskLevel: "Low", consequence: "Pest risk in admin zone.", proof: "Cleaning Log", trainerNotes: "Empty bins twice daily." },
                { id: "SC-HR-11", description: "Conduct 'Safety Policy' verbal quiz.", priority: "Medium", riskLevel: "Medium", consequence: "Protocol ignorance.", proof: "Quiz Log", trainerNotes: "Ask random staff daily." },
                { id: "SC-HR-12", description: "Verify 'Sexual Harassment' policy display.", priority: "High", riskLevel: "High", consequence: "Legal liability/Toxic culture.", proof: "Photo", trainerNotes: "Display in Staff Room." },
                { id: "SC-HR-13", description: "Check first-aid responder roster.", priority: "High", riskLevel: "High", consequence: "Medical negligence risk.", proof: "Roster Note", trainerNotes: "Min 1 certified per floor." },
                { id: "SC-HR-14", description: "Review 'Teacher Motivation' survey results.", priority: "Low", riskLevel: "Low", consequence: "Ineffective training spend.", proof: "Survey Note", trainerNotes: "Target > 80% positive." },
                { id: "SC-HR-15", description: "Audit 'Uniform Laundry' cycle time.", priority: "Low", riskLevel: "Low", consequence: "Staff wearing dirty clothes.", proof: "Laundry Log", trainerNotes: "Target < 24h turnaround." },
                { id: "SC-HR-16", description: "Verify 100% sign on 'Safety Policy'.", priority: "High", riskLevel: "Medium", consequence: "No legal action for breaches.", proof: "Signed Form", trainerNotes: "Include theft policies." },
                { id: "SC-HR-17", description: "Check grooming kit availability in lockers.", priority: "Low", riskLevel: "Low", consequence: "Slipping standards.", proof: "Visual Check", trainerNotes: "Deo/Razors in lockers." },
                { id: "SC-HR-18", description: "Audit 'Overtime' vs Admin budget.", priority: "Medium", riskLevel: "Medium", consequence: "Payroll budget blowout.", proof: "OT Tracker", trainerNotes: "HOD pre-approval needed." },
                { id: "SC-HR-19", description: "Final monthly HR matrix sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of admin control.", proof: "Signed Matrix", trainerNotes: "Submit to Principal." }
            ]
        },
        {
            title: "Lab, Tech & Auditorium",
            department: "Technical",
            frequency: "Weekly",
            role: "Technical Lead",
            summary: "Science Lab safety, IT uptime, and Hall AV governance.",
            icon: "wrench",
            tasks: [
                { id: "SC-TEC-01", description: "Science Lab: Soap-test all gas joints.", priority: "High", riskLevel: "High", consequence: "Campus explosion (Fatal).", proof: "Pressure Log", trainerNotes: "Log pressure drop hourly." },
                { id: "SC-TEC-02", description: "IT Lab: Verify 'Educational Filters' active.", priority: "High", riskLevel: "High", consequence: "Access to inappropriate content.", proof: "Firewall Log", trainerNotes: "Test 10 random URLs." },
                { id: "SC-TEC-03", description: "Auditorium: Test mics and PA loop sync.", priority: "Medium", riskLevel: "Low", consequence: "Event disruption/Chaos.", proof: "Sound Test", trainerNotes: "Check feedback at 100% gain." },
                { id: "SC-TEC-04", description: "Science Lab: Audit chemical segregation.", priority: "High", riskLevel: "High", consequence: "Toxic gas or fire reaction.", proof: "Storage Audit", trainerNotes: "Keep Acids in locked cupboard." },
                { id: "SC-TEC-05", description: "Server Room: Check dedicated AC (Target 20C).", priority: "High", riskLevel: "High", consequence: "Network crash/Data loss.", proof: "Temp Note", trainerNotes: "Clean filters every Sunday." },
                { id: "SC-TEC-06", description: "Generator: Inspect fuel and battery levels.", priority: "High", riskLevel: "High", consequence: "Total blackout during exams.", proof: "Test Log", trainerNotes: "Min 48h fuel supply." },
                { id: "SC-TEC-07", description: "UPS Bank: Test 10-min load for Computer Lab.", priority: "High", riskLevel: "Medium", consequence: "PC damage and data corruption.", proof: "Voltage Log", trainerNotes: "Test with 50% load." },
                { id: "SC-TEC-08", description: "Smartboard: Verify firmware/OS update sync.", priority: "Low", riskLevel: "Low", consequence: "Interruption to teaching.", proof: "System Log", trainerNotes: "Update at 3 AM Mondays." },
                { id: "SC-TEC-09", description: "Verify 'LOTO' permit for active Lab repairs.", priority: "High", riskLevel: "High", consequence: "Fatal technician injury.", proof: "Permit File", trainerNotes: "No lock, No work." },
                { id: "SC-TEC-10", description: "Check auditorium smoke exhaust fans.", priority: "High", riskLevel: "High", consequence: "Suffocation in event of fire.", proof: "Test Note", trainerNotes: "Run 5 mins monthly." },
                { id: "SC-TEC-11", description: "Inspect Science Lab shower functionality.", priority: "High", riskLevel: "High", consequence: "Fatal chemical burns.", proof: "Water Log", trainerNotes: "Flush for 1 min monthly." },
                { id: "SC-TEC-12", description: "Audit Computer Lab keyboard hygiene.", priority: "Low", riskLevel: "Medium", consequence: "Spread of germs among students.", proof: "Cleaning Log", trainerNotes: "Wipe with alcohol daily." },
                { id: "SC-TEC-13", description: "Check Science Lab eye-wash station stock.", priority: "High", riskLevel: "High", consequence: "Permanent vision loss risk.", proof: "Stock Audit", trainerNotes: "Keep sterile water stocked." },
                { id: "SC-TEC-14", description: "Inspect Auditorium seat mechanicals/bolts.", priority: "Medium", riskLevel: "Medium", consequence: "Student injury negligence.", proof: "Visual Audit", trainerNotes: "Check for wobbling rows." },
                { id: "SC-TEC-15", description: "Verify Science Lab 'LOTO' locks on burners.", priority: "High", riskLevel: "High", consequence: "Unauthorized gas usage risk.", proof: "Visual Check", trainerNotes: "Master valve locked after 4 PM." },
                { id: "SC-TEC-16", description: "Check Wi-Fi bandwidth for high-stakes exams.", priority: "High", riskLevel: "Low", consequence: "Systemic academic delay.", proof: "Speedtest App", trainerNotes: "Target > 50Mbps per lab." },
                { id: "SC-TEC-17", description: "Review P1 breakdown TAT for Lab tech.", priority: "High", riskLevel: "Low", consequence: "Loss of academic focus.", proof: "Job Log", trainerNotes: "Target P1 fix in < 30m." },
                { id: "SC-TEC-18", description: "Verify external lighting timer accuracy.", priority: "Low", riskLevel: "Low", consequence: "Security risk at night.", proof: "Photo", trainerNotes: "Set Sunset-to-Sunrise." },
                { id: "SC-TEC-19", description: "Final Technical sign-off for shift.", priority: "High", riskLevel: "Low", consequence: "Loss of dept control.", proof: "Signed Log", trainerNotes: "Brief GM on major fails." }
            ]
        },
        {
            title: "Admission, Reception & ORM",
            department: "Admin",
            frequency: "Daily",
            role: "Customer Experience Lead",
            summary: "Admission pipeline, Social Media ORM, and first-touch governance.",
            icon: "megaphone",
            tasks: [
                { id: "SC-CX-01", description: "Parent Social Inquiry TAT: Resolve < 2 hours.", priority: "High", riskLevel: "Low", consequence: "Lost admissions revenue via unread DMs.", proof: "Inbox Clear", trainerNotes: "Confirm via WhatsApp/Call instantly." },
                { id: "SC-CX-02", description: "Google/Search: Reply to all reviews < 24h.", priority: "High", riskLevel: "Medium", consequence: "Viral reputation damage.", proof: "Dashboard", trainerNotes: "Address 1-star reviews first." },
                { id: "SC-CX-03", description: "Instagram/FB: Post 'Safe Event' footage according to privacy rules.", priority: "Medium", riskLevel: "Low", consequence: "Institutional invisibility.", proof: "Post Link", trainerNotes: "Verify student face-blur policy." },
                { id: "SC-CX-04", description: "Reception: Audit tone and greeting smile.", priority: "Medium", riskLevel: "Low", consequence: "Negative brand first-touch.", proof: "Supervisor Obs", trainerNotes: "Mandatory eye contact." },
                { id: "SC-CX-05", description: "Parent Portal: verify login speed.", priority: "Low", riskLevel: "Low", consequence: "Mass parent frustration.", proof: "App Test", trainerNotes: "Login must work in < 10s." },
                { id: "SC-CX-06", description: "Google Maps: update hours for holidays.", priority: "High", riskLevel: "Low", consequence: "Parents arrive to 'Closed' campus.", proof: "Mobile Check", trainerNotes: "Update instantly for breaks." },
                { id: "SC-CX-07", description: "Check availability of parent water/tea.", priority: "Low", riskLevel: "Low", consequence: "Negative first impression.", proof: "Visual Check", trainerNotes: "Stock clean cups every 2h." },
                { id: "SC-CX-08", description: "Audit 'Feedback QR' placement in lobby.", priority: "Low", riskLevel: "Low", consequence: "Low volume of audit data.", proof: "Visual Check", trainerNotes: "Check stickers on chairs." },
                { id: "SC-CX-09", description: "Verify 'Guest Wi-Fi' code visibility.", priority: "Low", riskLevel: "Low", consequence: "Parent frustration scores.", proof: "Photo", trainerNotes: "Display at helpdesk only." },
                { id: "SC-CX-10", description: "Monitor 'Admission Center' ambiance/scent.", priority: "Low", riskLevel: "Low", consequence: "Negative micro-impressions.", proof: "Daily Log", trainerNotes: "Keep zone at exactly 23C." },
                { id: "SC-CX-11", description: "Social Media: Answer all YouTube comments < 24h.", priority: "Medium", riskLevel: "Low", consequence: "Negative sentiment buildup.", proof: "Comment Audit", trainerNotes: "Delete offensive spam instantly." },
                { id: "SC-CX-12", description: "Audit Admission form 'Medical Info' section.", priority: "High", riskLevel: "High", consequence: "Undocumented allergy risk.", proof: "Audit Sheet", trainerNotes: "Cross-check vs Student Matrix." },
                { id: "SC-CX-13", description: "Check status of 'Uniform Order' TAT.", priority: "Medium", riskLevel: "Low", consequence: "Parent delivery disputes.", proof: "Vendor Log", trainerNotes: "Target < 7 days delivery." },
                { id: "SC-CX-14", description: "Verify 100% reply to Social Comments.", priority: "Medium", riskLevel: "Low", consequence: "PR fire ignored.", proof: "Inbox Clear", trainerNotes: "Target < 4h response." },
                { id: "SC-CX-15", description: "Audit 'Campus Signage' bilingual clarity.", priority: "Low", riskLevel: "Low", consequence: "Confused visitors in corridors.", proof: "Walkthrough", trainerNotes: "Signs must be Bilingual." },
                { id: "SC-CX-16", description: "Review 'Influencer/Tour' itinerary.", priority: "Low", riskLevel: "Low", consequence: "Poor branding content.", proof: "Event Calendar", trainerNotes: "Brief Principal on arrivals." },
                { id: "SC-CX-17", description: "Verify 'Newsletter' link functionality.", priority: "Low", riskLevel: "Low", consequence: "Communication breakdown.", proof: "Test Email", trainerNotes: "Check mobile rendering." },
                { id: "SC-CX-18", description: "Check helpdesk stationary (Pens/Forms).", priority: "Low", riskLevel: "Low", consequence: "Operational friction.", proof: "Supply Audit", trainerNotes: "Check at 8 AM daily." },
                { id: "SC-CX-19", description: "Final daily Reputation sign-off.", priority: "High", riskLevel: "Low", consequence: "Loss of ORM control.", proof: "Signed Dashboard", trainerNotes: "Submit feedback report to Principal." }
            ]
        },
        {
            title: "Transport, Canteen & Hygiene",
            department: "Logistics",
            frequency: "Daily",
            role: "Logistics Lead",
            summary: "Zero-fail School Bus, HACCP Canteen, and Janitorial command.",
            icon: "truck",
            tasks: [
                { id: "SC-LOG-01", description: "Empty Bus Walkthrough: verify end-of-trip.", priority: "High", riskLevel: "High", consequence: "Child left behind (Fatal never-event).", proof: "Physical Sign-off", trainerNotes: "Touch the back seat physically." },
                { id: "SC-LOG-02", description: "Driver Sobriety: breathalyzer test result.", priority: "High", riskLevel: "High", consequence: "Fatal crash/Legal disaster.", proof: "Test Note", trainerNotes: "Conduct before morning trip." },
                { id: "SC-LOG-03", description: "Canteen HACCP: verify meal temp > 65C.", priority: "High", riskLevel: "High", consequence: "Foodborne illness outbreak.", proof: "Temp Log", trainerNotes: "Check hot-bins pre-recess." },
                { id: "SC-LOG-04", description: "Washroom Hygiene: Audit 1-hour frequency.", priority: "High", riskLevel: "Low", consequence: "Major driver of parent complaints.", proof: "Hourly Sheet", trainerNotes: "Check soap/sanitizer." },
                { id: "SC-LOG-05", description: "Vendor Receiving: Reconcile weight.", priority: "Medium", riskLevel: "Medium", consequence: "Paying for missing stock.", proof: "Scale Note", trainerNotes: "Reject variance > 2%." },
                { id: "SC-LOG-06", description: "Canteen: Verify FSSAI for all perishables.", priority: "High", riskLevel: "High", consequence: "Legal liability for unvetted sourcing.", proof: "License File", trainerNotes: "Renew repository every 6m." },
                { id: "SC-LOG-07", description: "Washroom: Check for drainage blockages.", priority: "Medium", riskLevel: "Medium", consequence: "Campus flood/Hygiene risk.", proof: "Visual Audit", trainerNotes: "Use enzymatic cleaner weekly." },
                { id: "SC-LOG-08", description: "Bus Fleet: Verify AC/GPS heartbeat test.", priority: "Medium", riskLevel: "Low", consequence: "Inability to track students.", proof: "System Dashboard", trainerNotes: "Check SIM cards data balance." },
                { id: "SC-LOG-09", description: "Canteen: Audit staff hairnets/handwashing.", priority: "High", riskLevel: "High", consequence: "Physical contamination of student food.", proof: "Briefing Log", trainerNotes: "Check nails/wounds daily." },
                { id: "SC-LOG-10", description: "Check availability of 'Empty Bus' stickers.", priority: "High", riskLevel: "Low", consequence: "Process bypass by drivers.", proof: "Supply Note", trainerNotes: "Sticker must be applied to back glass." },
                { id: "SC-LOG-11", description: "Inspect back-alley waste bins for pests.", priority: "Medium", riskLevel: "Medium", consequence: "Infestation in academic zone.", proof: "Cleaning Log", trainerNotes: "Bins must be closed." },
                { id: "SC-LOG-12", description: "Verify RO water backwash temp.", priority: "Low", riskLevel: "Medium", consequence: "Waterborne disease spread.", proof: "System Log", trainerNotes: "Log pressure drop hourly." },
                { id: "SC-LOG-13", description: "Audit bus-driver uniform and ID.", priority: "Low", riskLevel: "Low", consequence: "Brand dilution.", proof: "Attendance Log", trainerNotes: "Check for clean shirts." },
                { id: "SC-LOG-14", description: "Reconcile canteen sales vs cash-bag.", priority: "High", riskLevel: "High", consequence: "Internal revenue theft.", proof: "Match Note", trainerNotes: "Investigate variance > ₹50." },
                { id: "SC-LOG-15", description: "Check availability of spare car/bus keys.", priority: "Low", riskLevel: "Medium", consequence: "Emergency delay crisis.", proof: "Vault Inventory", trainerNotes: "Secure in main safe." },
                { id: "SC-LOG-16", description: "Verify vendor attendance logs.", priority: "Low", riskLevel: "Low", consequence: "Paying for unrendered work.", proof: "Log Review", trainerNotes: "Deduct for late arrivals." },
                { id: "SC-LOG-17", description: "Audit staff break-room drainage.", priority: "Low", riskLevel: "Low", consequence: "Unhygienic staff zone.", proof: "Cleaning Note", trainerNotes: "Buff mirrors daily." },
                { id: "SC-LOG-18", description: "Review P1 vendor service TAT.", priority: "Medium", riskLevel: "Low", consequence: "Delayed repairs.", proof: "SLA Match", trainerNotes: "Penalty for > 4h delay." },
                { id: "SC-LOG-19", description: "Final shift Logistics sign-off.", priority: "High", riskLevel: "Low", consequence: "Incomplete handover.", proof: "Signed Summary", trainerNotes: "Brief GM on arrivals." }
            ]
        }
    ]
};
